Repository woocommerce/woocommerce-blocks, pull requests merged in 2018-12, with the labels that each got.

#190 Update test snapshots after markup changes in 182
  assets/js/components/search-list-control/test/__snapshots__/index.js.snap
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#189 Category Selection: Add the first category to deeply nested items
  assets/js/components/product-category-control/index.js
Labels: [Status] Ready to Merge

#191 Category Selection: Prevent scrollbar on bottom of category selection screen
  assets/js/components/search-list-control/style.scss
Labels: [Status] Ready to Merge

#192 Category Selection: Always show "selected" section
  assets/css/product-category-block.scss
  assets/js/components/search-list-control/index.js
  assets/js/components/search-list-control/style.scss
  assets/js/components/search-list-control/test/__snapshots__/index.js.snap
Labels: Blocks, [Status] Ready to Merge

#198 Add `woocommerce` as a supported keyword for the block
  assets/js/product-category-block.js
Labels: Blocks, [Status] Ready to Merge

#197 Category Selection: Add loading & no results states
  assets/js/components/product-category-control/index.js
  assets/js/components/search-list-control/index.js
  assets/js/components/search-list-control/style.scss
  assets/js/components/search-list-control/test/__snapshots__/index.js.snap
  package-lock.json
  package.json
Labels: Blocks, [Status] Ready to Merge

#199 Update textdomain to plugin slug
  .babelrc
  .gitignore
  assets/js/components/product-category-control/index.js
  assets/js/components/product-preview/index.js
  assets/js/components/search-list-control/index.js
  assets/js/product-category-block.js
  languages/woo-gutenberg-products-block.php
  package-lock.json
  package.json
  woocommerce-gutenberg-products-block.php
Labels: [Status] Ready to Merge

#210 Add styles for better reusable block preview
  assets/css/product-category-block.scss
  assets/css/products-block.scss
  assets/js/product-category-block.js
Labels: Blocks, [Status] Needs Design Review, [Status] Ready to Merge

#211 Bump version to 1.3.0-dev
  woocommerce-gutenberg-products-block.php
Labels: Build, [Status] Ready to Merge

#214 Layout: Remove “center” alignment option
  assets/js/product-category-block.js
Labels: Blocks, [Status] Ready to Merge

#215 Fix PHP CodeSniffer issues
  phpcs.xml
  tests/api/products-extra.php
  tests/bootstrap.php
  woocommerce-gutenberg-products-block.php
Labels: Build, [Status] Ready to Merge

#220 Build: Compile all blocks into one file
  assets/js/index.js
  assets/js/product-category-block.js
  webpack.config.js
  woocommerce-gutenberg-products-block.php
Labels: Build, [Status] Ready to Merge

#234 correct link in readme.md
  README.md
Labels: Documentation, [Status] Ready to Merge

#223 Product preview: Update "Add to cart" button to inherit theme's button styles
  assets/css/product-category-block.scss
  assets/js/components/product-preview/index.js
  assets/js/components/product-preview/style.scss
  assets/js/components/product-preview/test/__snapshots__/index.js.snap
  postcss.config.js
Labels: Blocks, [Status] Needs Design Review, [Status] Ready to Merge

#221 Block: Add new "Best Selling Products" block
  assets/css/product-category-block.scss
  assets/js/index.js
  assets/js/product-best-sellers.js
  assets/js/product-category-block.js
  assets/js/utils/get-query.js
  assets/js/utils/get-shortcode.js
  assets/js/utils/shared-attributes.js
  assets/js/utils/test/get-query.js
  webpack.config.js
  woocommerce-gutenberg-products-block.php
Labels: Blocks, [Status] Ready to Merge

#236 Add PHPCS to travis CI tests
  .travis.yml
  composer.json
Labels: Build, [Status] Ready to Merge

#235 Fix incorrectly escaped HTML in build notice
  woocommerce-gutenberg-products-block.php
Labels: [Status] Ready to Merge, [Type] Bug

#238 Move product order control into a shared component
  assets/js/components/product-orderby-control/index.js
  assets/js/product-category-block.js
Labels: Components, [Status] Ready to Merge

#249 New Block: Add "Top Rated Products" block
  assets/js/index.js
  assets/js/product-top-rated.js
  assets/js/utils/get-query.js
  assets/js/utils/get-shortcode.js
  woocommerce-gutenberg-products-block.php
Labels: Blocks, [Status] Needs Review

#254 fix individual product block (legacy)
  assets/js/legacy/views/specific-select.jsx
Labels: Legacy Block, [Status] Ready to Merge, [Type] Bug

#251 Category Selection: Add support for category operator
  assets/css/abstracts/_breakpoints.scss
  assets/css/product-category-block.scss
  assets/js/components/product-category-control/index.js
  assets/js/components/product-category-control/style.scss
  assets/js/product-best-sellers.js
  assets/js/product-category-block.js
  assets/js/product-on-sale.js
  assets/js/utils/get-query.js
  assets/js/utils/get-shortcode.js
  assets/js/utils/shared-attributes.js
  includes/class-wgpb-products-controller.php
Labels: Components, [Status] Ready to Merge

#257 Move icon components from SearchList to a app-wide file
  assets/js/components/icons/index.js
  assets/js/components/product-category-control/index.js
  assets/js/components/search-list-control/icons.js
  assets/js/components/search-list-control/index.js
Labels: Components, [Status] Ready to Merge

#255 New Block: Add "Newest Products" Block
  assets/js/index.js
  assets/js/legacy/products-block.jsx
  assets/js/product-new.js
  assets/js/utils/get-query.js
  assets/js/utils/get-shortcode.js
  woocommerce-gutenberg-products-block.php
Labels: Blocks, [Status] Ready to Merge

#263 API: Inject attribute group name & slug into API response
  includes/class-wgpb-product-attribute-terms-controller.php
Labels: REST API, [Status] Ready to Merge

#258 Add new SearchListItem component
  assets/js/components/product-category-control/index.js
  assets/js/components/product-category-control/style.scss
  assets/js/components/search-list-control/index.js
  assets/js/components/search-list-control/item.js
  assets/js/components/search-list-control/style.scss
  assets/js/components/search-list-control/test/__snapshots__/index.js.snap
Labels: Components, [Status] Ready to Merge

#264 Fix multiple API calls returning out of order, causing set rows to be incorrect
  assets/js/product-best-sellers.js
  assets/js/product-category-block.js
  assets/js/product-new.js
  assets/js/product-on-sale.js
  assets/js/product-top-rated.js
Labels: Blocks, [Status] Ready to Merge

#265 Update SearchListControl hierarchical items style
  assets/css/abstracts/_mixins.scss
  assets/js/components/search-list-control/style.scss
Labels: Components, [Status] Ready to Merge

#273 Fix the spacing around the “edit mode” of Products by Category
  assets/js/product-category-block.js
Labels: Blocks, [Status] Ready to Merge

#272 Fix "products by all categories" not finding products in parent-categories
  includes/class-wgpb-products-controller.php
  tests/api/products-categories.php
  woocommerce-gutenberg-products-block.php
Labels: REST API, [Status] Ready to Merge, [Tests] Includes Tests

#279 Visually hide the “any”/“all” categories selector when less than 2 categories are selected
  assets/js/components/product-category-control/index.js
  assets/js/components/product-category-control/style.scss
Labels: Components, [Status] Ready to Merge
