Repository woocommerce/woocommerce-blocks, pull requests merged in 2018-11, with the labels that each got.

#121 Add all dependencies used in the product block to the script registration
  woocommerce-gutenberg-products-block.php
Labels: [Status] Ready to Merge

#122 Update build process
  .babelrc
  .gitignore
  Gruntfile.js
  README.md
  assets/css/gutenberg-products-block-rtl.css
  assets/css/gutenberg-products-block.css
  assets/css/products-block.scss
  assets/js/products-block.js
  assets/js/products-block.jsx
  package-lock.json
  package.json
  postcss.config.js
  webpack.config.js
  woocommerce-gutenberg-products-block.php
Labels: Build, [Status] Ready to Merge

#123 Add eslint to find and fix code style issues
  .eslintignore
  .eslintrc.js
  assets/js/products-block.jsx
  assets/js/views/attribute-select.jsx
  assets/js/views/category-select.jsx
  assets/js/views/specific-select.jsx
  package-lock.json
  package.json
  webpack.config.js
Labels: Build, [Status] Ready to Merge

#126 Add stylelint to find and fix css code style issues
  .stylelintrc.json
  assets/css/products-block.scss
  package-lock.json
  package.json
Labels: Build, [Status] Ready to Merge

#128 Add .editorconfig file for editor integration
  .editorconfig
  webpack.config.js
Labels: Build, [Status] Ready to Merge

#130 Set up Jest for JS testing
  .eslintrc.js
  assets/js/products-block.jsx
  assets/js/test/__snapshots__/product-preview.js.snap
  assets/js/test/product-preview.js
  package-lock.json
  package.json
  tests/js/jest.config.json
  tests/js/setup-globals.js
Labels: Build, [Status] Ready to Merge

#135 Move legacy block to “legacy” folder
  assets/js/legacy/products-block.jsx
  assets/js/legacy/views/attribute-select.jsx
  assets/js/legacy/views/category-select.jsx
  assets/js/legacy/views/specific-select.jsx
  assets/js/test/product-preview.js
  webpack.config.js
Labels: [Status] Needs Review

#136 Add a basic product category block
  assets/css/product-category-block.scss
  assets/js/components/product-preview/index.js
  assets/js/components/product-preview/style.scss
  assets/js/components/product-preview/test/__snapshots__/index.js.snap
  assets/js/components/product-preview/test/index.js
  assets/js/product-category-block.js
  assets/js/utils/get-query.js
  assets/js/utils/get-shortcode.js
  assets/js/utils/shared-attributes.js
  assets/js/utils/test/get-query.js
  includes/class-wgpb-products-controller.php
  package-lock.json
  package.json
  webpack.config.js
  woocommerce-gutenberg-products-block.php
Labels: Blocks, [Status] Ready to Merge

#141 Update “tested up to” versions for WC and WP
  readme.txt
  woocommerce-gutenberg-products-block.php
Labels: [Status] Ready to Merge

#144 Add the "edit mode" toggle to the product category block
  assets/css/abstracts/_breakpoints.scss
  assets/css/abstracts/_colors.scss
  assets/css/abstracts/_mixins.scss
  assets/css/product-category-block.scss
  assets/js/product-category-block.js
  webpack.config.js
Labels: Blocks, [Status] Ready to Merge

#150 Check that the translation function exists before using it
  woocommerce-gutenberg-products-block.php
Labels: [Status] Ready to Merge

#146 Load only published products in the preview
  assets/js/legacy/products-block.jsx
  assets/js/legacy/views/specific-select.jsx
  assets/js/utils/get-query.js
  assets/js/utils/test/get-query.js
Labels: [Status] Ready to Merge

#156 Adds continuous integration testing with travis
  .nvmrc
  .travis.yml
  assets/css/abstracts/_breakpoints.scss
  assets/css/abstracts/_mixins.scss
  assets/css/product-category-block.scss
  package-lock.json
  package.json
  phpunit.xml.dist
  tests/api/products-extra.php
  tests/bin/install-wp-tests.sh
  tests/bin/phpunit.sh
  tests/bootstrap.php
  woocommerce-gutenberg-products-block.php
Labels: Build, [Status] Ready to Merge

#158 Update jsx-a11y label rule to only require ID, not ID+nesting
  .eslintrc.js
Labels: Build, [Status] Ready to Merge

#159 Update script dependencies, add all packages used in blocks
  webpack.config.js
  woocommerce-gutenberg-products-block.php
Labels: [Status] Ready to Merge

#163 WooCommerce sniffs
  composer.json
  composer.lock
  phpcs.xml
Labels: [Status] Ready to Merge

#164 PHP pre-commit hook
  package-lock.json
  package.json
Labels: [Status] Ready to Merge

#173 Fix React warning for array items needed unique key props
  assets/js/legacy/products-block.jsx
Labels: [Status] Ready to Merge, [Type] Bug

#175 Show the Layout settings as open by default
  assets/js/product-category-block.js
Labels: Blocks, [Status] Ready to Merge

#177 Adjust category list max-height
  assets/js/components/search-list-control/style.scss
Labels: [Status] Ready to Merge

#176 Update eslint config to ignore legacy block
  .eslintignore
  .eslintrc.js
Labels: Build, [Status] Ready to Merge

#162 New custom endpoints
  assets/js/components/product-category-control/index.js
  assets/js/legacy/products-block.jsx
  assets/js/legacy/views/attribute-select.jsx
  assets/js/legacy/views/category-select.jsx
  assets/js/legacy/views/specific-select.jsx
  assets/js/product-category-block.js
  includes/class-wgpb-product-attribute-terms-controller.php
  includes/class-wgpb-product-attributes-controller.php
  includes/class-wgpb-product-categories-controller.php
  includes/class-wgpb-products-controller.php
  package-lock.json
  tests/api/products-extra.php
  woocommerce-gutenberg-products-block.php
Labels: REST API, [Status] Ready to Merge

#174 Add tests for SearchListControl
  assets/js/components/search-list-control/index.js
  assets/js/components/search-list-control/test/__snapshots__/index.js.snap
  assets/js/components/search-list-control/test/index.js
  tests/js/setup-globals.js
Labels: [Tests] Includes Tests

#179 Category Selection: Add hierarchy support for nested categories
  assets/css/abstracts/_mixins.scss
  assets/js/components/product-category-control/index.js
  assets/js/components/product-category-control/style.scss
  assets/js/components/search-list-control/hierarchy.js
  assets/js/components/search-list-control/index.js
  assets/js/components/search-list-control/test/__snapshots__/index.js.snap
  assets/js/components/search-list-control/test/hierarchy.js
  assets/js/components/search-list-control/test/index.js
Labels: Blocks, [Status] Ready to Merge, [Tests] Includes Tests
