Repository woocommerce/woocommerce-blocks, pull requests merged in 2019-10, with the labels that each got.

#1004 Update docblock for `remove_core_blocks`
  src/Domain/Bootstrap.php
Labels: skip-changelog, status: ready to merge

#987 Update Products on Sale and Products Tag icons
  assets/js/blocks/product-on-sale/index.js
  assets/js/blocks/product-tag/block.js
  assets/js/blocks/product-tag/index.js
  assets/js/components/icons/index.js
  assets/js/components/icons/product-on-sale.js
  assets/js/components/icons/product-tag.js
Labels: status: ready to merge, type: enhancement

#1003 Use renderFrontend util in All Products block
  assets/js/blocks/products/all-products/frontend.js
  assets/js/utils/render-frontend.js
Labels: skip-changelog, status: ready to merge

#997 Implement querystrings for the All Products block
  assets/js/base/components/product-grid/container.js
  assets/js/base/hocs/test/with-window.js
  assets/js/base/hocs/with-window.js
  assets/js/blocks/products/all-products/block.js
  assets/js/blocks/products/all-products/frontend.js
  assets/js/utils/render-frontend.js
Labels: skip-changelog, status: ready to merge

#994 Create withProducts HOC for All Products block
  assets/js/base/components/order-select/index.js
  assets/js/base/components/pagination/index.js
  assets/js/base/components/pagination/style.scss
  assets/js/base/components/product-grid-item/index.js
  assets/js/base/components/product-grid-item/product-button/index.js
  assets/js/base/components/product-grid-item/product-image/index.js
  assets/js/base/components/product-grid-item/product-link/index.js
  assets/js/base/components/product-grid-item/product-price/index.js
  assets/js/base/components/product-grid-item/product-rating/index.js
  assets/js/base/components/product-grid-item/product-sale-badge/index.js
  assets/js/base/components/product-grid-item/product-title/index.js
  assets/js/base/components/product-grid/container.js
  assets/js/base/components/product-grid/index.js
  assets/js/base/components/product-grid/style.scss
  assets/js/base/components/product-order-select/index.js
  assets/js/base/components/product-order-select/style.scss
  assets/js/base/hocs/test/with-products.js
  assets/js/base/hocs/test/with-window.js
  assets/js/base/hocs/utils.js
  assets/js/base/hocs/with-products.js
  assets/js/base/hocs/with-window.js
  assets/js/blocks/products/all-products/block.js
  assets/js/blocks/products/all-products/frontend.js
  assets/js/blocks/products/all-products/index.js
  assets/js/blocks/products/all-products/sample-data.json
  assets/js/blocks/products/edit.js
  assets/js/blocks/products/utils.js
  assets/js/settings/blocks/constants.js
  assets/js/utils/render-frontend.js
Labels: grid-blocks, skip-changelog, status: ready to merge

#1013 Create CODEOWNERS file
  .gitattributes
  CODEOWNERS
  bin/build-plugin-zip.sh
  bin/wordpress-deploy.sh
Labels: skip-changelog, status: ready to merge

#1017 Fix: Load back-compat wcSettings global for old `@woocommerce/settings` package
  src/Domain/Bootstrap.php
Labels: status: ready to merge, type: blocker, type: bug

#1018 Introduce legacy build system and new aliases
  .editorconfig
  CONTRIBUTING.md
  assets/js/base/components/load-more-button/index.js
  assets/js/base/components/order-select/index.js
  assets/js/base/components/pagination/index.js
  assets/js/base/components/product-order-select/index.js
  assets/js/base/components/review-list-item/index.js
  assets/js/base/components/review-list/index.js
  assets/js/base/components/review-order-select/index.js
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-category/index.js
  assets/js/blocks/featured-product/block.js
  assets/js/blocks/handpicked-products/block.js
  assets/js/blocks/handpicked-products/index.js
  assets/js/blocks/product-best-sellers/block.js
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-categories/edit.js
  assets/js/blocks/product-categories/index.js
  assets/js/blocks/product-category/block.js
  assets/js/blocks/product-new/block.js
  assets/js/blocks/product-new/index.js
  assets/js/blocks/product-on-sale/block.js
  assets/js/blocks/product-on-sale/index.js
  assets/js/blocks/product-search/index.js
  assets/js/blocks/product-tag/block.js
  assets/js/blocks/product-tag/index.js
  assets/js/blocks/product-top-rated/block.js
  assets/js/blocks/products-by-attribute/block.js
  assets/js/blocks/reviews/all-reviews/edit.js
  assets/js/blocks/reviews/all-reviews/index.js
  assets/js/blocks/reviews/all-reviews/no-reviews-placeholder.js
  assets/js/blocks/reviews/edit-utils.js
  assets/js/blocks/reviews/editor-block.js
  assets/js/blocks/reviews/frontend-block.js
  assets/js/blocks/reviews/reviews-by-category/edit.js
  assets/js/blocks/reviews/reviews-by-category/index.js
  assets/js/blocks/reviews/reviews-by-category/no-reviews-placeholder.js
  assets/js/blocks/reviews/reviews-by-product/edit.js
  assets/js/blocks/reviews/reviews-by-product/index.js
  assets/js/blocks/reviews/reviews-by-product/no-reviews-placeholder.js
  assets/js/components/product-attribute-control/index.js
  assets/js/components/product-category-control/index.js
  assets/js/components/product-control/index.js
  assets/js/components/products-control/index.js
  assets/js/hocs/with-attributes.js
  assets/js/hocs/with-categories.js
  assets/js/hocs/with-category.js
  assets/js/hocs/with-product-variations.js
  assets/js/hocs/with-product.js
  assets/js/hocs/with-searched-products.js
  assets/js/legacy/README.md
  bin/fallback-module-directory-webpack-plugin.js
  bin/webpack-helpers.js
  package-lock.json
  tests/js/jest.config.json
  webpack.config.js
Labels: status: ready to merge, type: enhancement

#1012 Rename properties and components from 'order' to 'sort'
  assets/js/base/components/product-grid/container.js
  assets/js/base/components/product-grid/index.js
  assets/js/base/components/product-order-select/style.scss
  assets/js/base/components/product-sort-select/index.js
  assets/js/base/components/product-sort-select/style.scss
  assets/js/base/components/review-order-select/style.scss
  assets/js/base/components/review-sort-select/index.js
  assets/js/base/components/review-sort-select/style.scss
  assets/js/base/components/sort-select/index.js
  assets/js/base/components/sort-select/style.scss
  assets/js/base/hocs/test/with-products.js
  assets/js/base/hocs/test/with-reviews.js
  assets/js/base/hocs/with-products.js
  assets/js/blocks/reviews/editor-block.js
  assets/js/blocks/reviews/editor-container-block.js
  assets/js/blocks/reviews/frontend-block.js
  assets/js/blocks/reviews/frontend-container-block.js
  assets/js/blocks/reviews/utils.js
Labels: skip-changelog, status: ready to merge

#1016 Remove unnecessary stylint-disable-line
  assets/js/base/components/product-grid-item/product-rating/index.js
Labels: skip-changelog, status: ready to merge

#1021 Fix ProductAttributeControl not reacting to clicks
  assets/js/components/product-attribute-control/index.js
Labels: skip-changelog, status: ready to merge, type: bug

#1022 Create withBrowserLocation and withBrowserHistory HOC
  assets/js/base/components/product-grid/container.js
  assets/js/base/components/product-grid/index.js
  assets/js/base/hocs/test/with-browser-history.js
  assets/js/base/hocs/test/with-browser-location.js
  assets/js/base/hocs/test/with-browser-window-prop.js
  assets/js/base/hocs/with-browser-history.js
  assets/js/base/hocs/with-browser-location.js
  assets/js/base/hocs/with-browser-window-prop.js
  assets/js/base/hocs/with-window.js
Labels: skip-changelog, status: ready to merge

#1011 Scroll to top when switching pages in All Products block
  assets/js/base/components/pagination/index.js
  assets/js/base/components/pagination/style.scss
  assets/js/base/components/product-grid/index.js
  assets/js/base/hocs/with-scroll-to-top/index.js
  assets/js/base/hocs/with-scroll-to-top/style.scss
  assets/js/base/hocs/with-scroll-to-top/test/index.js
Labels: skip-changelog, status: ready to merge

#1006 Refactor permission checks for authors
  src/RestApi/Controllers/Products.php
Labels: cherry-pick 🍒, status: ready to merge, type: bug

#1015 Avoid first and last pages being included in pagination 'pagesToDisplay'
  assets/js/base/components/pagination/index.js
  assets/js/base/components/pagination/test/index.js
  assets/js/base/components/pagination/utils.js
Labels: skip-changelog, status: ready to merge

#1041 Pagination: disable first/last page if they are active
  assets/js/base/components/pagination/index.js
Labels: skip-changelog, status: ready to merge

#1040 Create withQueryStringValues HOC and use it in ProductGrid component
  assets/js/base/components/product-grid/container.js
  assets/js/base/components/product-grid/index.js
  assets/js/base/hocs/test/with-browser-history.js
  assets/js/base/hocs/test/with-browser-location.js
  assets/js/base/hocs/test/with-browser-window-prop.js
  assets/js/base/hocs/test/with-query-string-values.js
  assets/js/base/hocs/with-browser-history.js
  assets/js/base/hocs/with-browser-location.js
  assets/js/base/hocs/with-browser-window-prop.js
  assets/js/base/hocs/with-query-string-values.js
  assets/js/blocks/products/all-products/frontend.js
Labels: skip-changelog, status: ready to merge

#1033 Expose wp_version on settings api and provide a js version compare function
  assets/js/settings/shared/index.js
  assets/js/settings/shared/test/compare-with-wp-version.js
  package-lock.json
  package.json
  src/Assets/AssetDataRegistry.php
Labels: status: ready to merge, type: enhancement

#1045 Update NPM package docs after deprecation
  CONTRIBUTING.md
Labels: status: ready to merge

#1052 Add filter to control whether product grid results should be cacheable
  src/BlockTypes/AbstractProductGrid.php
Labels: extensibility, grid-blocks, status: ready to merge

#1024 Use Server Side Rendering for Product Category List block
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-categories/edit.js
  assets/js/blocks/product-categories/frontend.js
  assets/js/blocks/product-categories/get-categories.js
  assets/js/blocks/product-categories/hierarchy.js
  assets/js/blocks/product-categories/index.js
  assets/js/settings/blocks/constants.js
  bin/webpack-helpers.js
  src/Assets.php
  src/BlockTypes/ProductCategories.php
Labels: status: ready to merge, type: performance, type: refactor

#717 Add empty content messages
  assets/js/blocks/product-category/block.js
  src/BlockTypes/AbstractProductGrid.php
Labels: WP 5.3

#1046 Introduce a Cart API on top of the REST API
  src/RestApi.php
  src/RestApi/Controllers/Products.php
  src/RestApi/StoreApi/Controllers/Cart.php
  src/RestApi/StoreApi/Controllers/CartItems.php
  src/RestApi/StoreApi/README.md
  src/RestApi/StoreApi/Schemas/AbstractSchema.php
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  src/RestApi/StoreApi/Schemas/CartSchema.php
  src/RestApi/StoreApi/Utilities/CartController.php
  src/RestApi/Utilities/ProductImages.php
  tests/php/RestApi/StoreApi/Controllers/Cart.php
  tests/php/RestApi/StoreApi/Controllers/CartItems.php
Labels: rest-api, skip-changelog, status: ready to merge

#1058 Refresh package-lock.json due to node lts version bump
  .travis.yml
  package-lock.json
Labels: status: ready to merge, type: bug, type: build

#1059 Add previews for Reviews blocks
  assets/js/base/hocs/test/with-reviews.js
  assets/js/base/hocs/with-reviews.js
  assets/js/blocks/reviews/all-reviews/index.js
  assets/js/blocks/reviews/attributes.js
  assets/js/blocks/reviews/example.js
  assets/js/blocks/reviews/reviews-by-category/index.js
  assets/js/blocks/reviews/reviews-by-product/index.js
  assets/js/previews/reviews.js
Labels: status: ready to merge

#1008 Add wp.data store for schema and lists.
  assets/js/data/README.md
  assets/js/data/collections/README.md
  assets/js/data/collections/action-types.js
  assets/js/data/collections/actions.js
  assets/js/data/collections/constants.js
  assets/js/data/collections/index.js
  assets/js/data/collections/reducers.js
  assets/js/data/collections/resolvers.js
  assets/js/data/collections/selectors.js
  assets/js/data/collections/test/reducers.js
  assets/js/data/collections/test/resolvers.js
  assets/js/data/collections/test/selectors.js
  assets/js/data/constants.js
  assets/js/data/index.js
  assets/js/data/query-state/README.md
  assets/js/data/query-state/action-types.js
  assets/js/data/query-state/actions.js
  assets/js/data/query-state/constants.js
  assets/js/data/query-state/index.js
  assets/js/data/query-state/reducers.js
  assets/js/data/query-state/selectors.js
  assets/js/data/query-state/test/reducers.js
  assets/js/data/query-state/test/selectors.js
  assets/js/data/query-state/utils.js
  assets/js/data/schema/README.md
  assets/js/data/schema/action-types.js
  assets/js/data/schema/actions.js
  assets/js/data/schema/constants.js
  assets/js/data/schema/index.js
  assets/js/data/schema/reducers.js
  assets/js/data/schema/resolvers.js
  assets/js/data/schema/selectors.js
  assets/js/data/schema/test/reducers.js
  assets/js/data/schema/test/resolvers.js
  assets/js/data/schema/test/selectors.js
  assets/js/data/schema/test/utils.js
  assets/js/data/schema/utils.js
  assets/js/data/utils/has-in-state.js
  assets/js/data/utils/index.js
  assets/js/data/utils/update-state.js
  bin/webpack-helpers.js
  package-lock.json
  package.json
  src/Assets.php
  tests/js/jest.config.json
  webpack.config.js
Labels: status: ready to merge, type: feature request

#1065 Missing homeUrl variable due to white space breaks the product search block.
  assets/js/settings/blocks/constants.js
Labels: cherry-pick 🍒, status: ready to merge

#1073 Modify collections store to add headers to the store state.
  assets/js/data/collections/README.md
  assets/js/data/collections/actions.js
  assets/js/data/collections/constants.js
  assets/js/data/collections/controls.js
  assets/js/data/collections/index.js
  assets/js/data/collections/reducers.js
  assets/js/data/collections/resolvers.js
  assets/js/data/collections/selectors.js
  assets/js/data/collections/test/reducers.js
  assets/js/data/collections/test/resolvers.js
  assets/js/data/collections/test/selectors.js
Labels: status: ready to merge, type: enhancement

#1066 Add responsive product grid styles
  assets/css/editor.scss
  assets/css/style.scss
Labels: status: ready to merge

#1034 Add WP 5.3 preview for Feature Product Block
  assets/js/blocks/featured-product/block.js
  assets/js/blocks/featured-product/example.js
  assets/js/blocks/featured-product/index.js
  assets/js/hocs/with-product.js
  assets/js/previews/products.js
  assets/js/settings/blocks/constants.js
Labels: status: ready to merge, type: feature request

#1047 Prepare All Products block to accept extension inner blocks
  assets/js/atomic/utils/index.js
  assets/js/base/components/product-list-item/index.js
  assets/js/base/components/product-list-item/utils.js
  assets/js/base/context/inner-block-parent-name-context.js
  assets/js/blocks-registry/get-registered-inner-blocks.js
  assets/js/blocks-registry/index.js
  assets/js/blocks-registry/register-inner-block.js
  assets/js/blocks-registry/registered-blocks-init.js
  assets/js/blocks-registry/test/index.js
  assets/js/blocks/products/all-products/block.js
  assets/js/blocks/products/all-products/edit.js
  assets/js/blocks/products/attributes.js
  assets/js/blocks/products/base-utils.js
  assets/js/settings/shared/set-setting.js
  bin/webpack-helpers.js
  src/Assets.php
  webpack.config.js
Labels: extensibility, grid-blocks, skip-changelog, status: ready to merge

#1055 REST API - Store API - Product filtering data, products endpoint, and cart refinements
  src/RestApi.php
  src/RestApi/StoreApi/Controllers/Cart.php
  src/RestApi/StoreApi/Controllers/CartItems.php
  src/RestApi/StoreApi/Controllers/ProductCollectionData.php
  src/RestApi/StoreApi/Controllers/Products.php
  src/RestApi/StoreApi/README.md
  src/RestApi/StoreApi/Schemas/AbstractSchema.php
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  src/RestApi/StoreApi/Schemas/CartSchema.php
  src/RestApi/StoreApi/Schemas/ProductSchema.php
  src/RestApi/StoreApi/Utilities/CartController.php
  src/RestApi/StoreApi/Utilities/Pagination.php
  src/RestApi/StoreApi/Utilities/ProductFiltering.php
  src/RestApi/StoreApi/Utilities/ProductQuery.php
  tests/php/RestApi/StoreApi/Controllers/Cart.php
  tests/php/RestApi/StoreApi/Controllers/CartItems.php
  tests/php/RestApi/StoreApi/Controllers/ProductCollectionData.php
  tests/php/RestApi/StoreApi/Controllers/Products.php
Labels: rest-api, status: ready to merge

#1088 Fix incorrect definition of loadProduct in withProduct. (fixes #1087)
  assets/js/hocs/with-product.js
Labels: status: ready to merge, type: bug

#1090 Add php5.3 restriction for All Products block
  bin/webpack-helpers.js
  src/Assets.php
  src/Library.php
  webpack.config.js
Labels: status: ready to merge, type: enhancement

#1093 Fix product categories block refreshing more than expected.
  assets/js/blocks/product-categories/block.js
Labels: WP 5.3, status: ready to merge, type: bug

#1067 Implement new data stores with All Products block
  assets/js/base/components/product-list/index.js
  assets/js/base/hooks/index.js
  assets/js/base/hooks/test/use-query-state.js
  assets/js/base/hooks/test/use-shallow-equal.js
  assets/js/base/hooks/test/use-store-products.js
  assets/js/base/hooks/use-query-state.js
  assets/js/base/hooks/use-shallow-equal.js
  assets/js/base/hooks/use-store-products.js
  assets/js/data/collections/controls.js
  assets/js/data/collections/resolvers.js
  assets/js/data/collections/selectors.js
  assets/js/data/collections/test/resolvers.js
  assets/js/data/collections/test/selectors.js
  bin/webpack-helpers.js
Labels: WP 5.3, type: enhancement

#1086 BlocksWpQuery wrapper for WP_Query
  src/BlockTypes/AbstractProductGrid.php
  src/Utils/BlocksWpQuery.php
Labels: skip-changelog, status: ready to merge

#1099 Add useCollection and useCollectionHeader hooks (closes: #1096)
  assets/js/base/hooks/test/use-collection.js
  assets/js/base/hooks/test/use-store-products.js
  assets/js/base/hooks/use-collection-header.js
  assets/js/base/hooks/use-collection.js
  assets/js/base/hooks/use-store-products.js
Labels: status: ready to merge, type: feature request

#1103 Fix bugs in useCollection hook
  assets/js/base/hooks/index.js
  assets/js/base/hooks/use-collection.js
Labels: status: ready to merge, type: bug
