Repository woocommerce/woocommerce-blocks, pull requests merged in 2019-09, with the labels that each got.

#933 Fix misleading comment in src/Assets.php
  src/Assets.php
Labels: skip-changelog, status: ready to merge

#937 Exclude bundlesize and composer files from being deployed ZIP
  .gitattributes
  bin/github-deploy.sh
Labels: status: ready to merge, type: build

#926 Create Pagination and ProductOrderSelect components
  assets/js/base/components/label/index.js
  assets/js/base/components/label/test/__snapshots__/index.js.snap
  assets/js/base/components/pagination/index.js
  assets/js/base/components/pagination/style.scss
  assets/js/base/components/pagination/test/index.js
  assets/js/base/components/pagination/utils.js
  assets/js/base/components/product-order-select/index.js
Labels: skip-changelog, status: ready to merge

#938 RTL fixes
  assets/js/blocks/product-categories/style.scss
  assets/js/blocks/product-search/style.scss
  package.json
  src/Assets.php
  webpack.config.js
Labels: status: ready to merge, type: bug

#944 Update Product Search Icon
  assets/js/blocks/product-search/index.js
  assets/js/components/icons/index.js
  assets/js/components/icons/product-search.js
Labels: status: ready to merge, type: enhancement

#949 Remove colors from icons displayed in the shortcuts inserter
  assets/js/blocks/product-search/index.js
  assets/js/blocks/reviews/all-reviews/index.js
  assets/js/blocks/reviews/reviews-by-category/index.js
  assets/js/blocks/reviews/reviews-by-product/index.js
  assets/js/components/icons/all-reviews.js
  assets/js/components/icons/product-search.js
  assets/js/components/icons/reviews-by-category.js
  assets/js/components/icons/reviews-by-product.js
Labels: status: ready to merge

#948 Add version string replacement script for deploy
  CONTRIBUTING.md
  bin/github-deploy.sh
  bin/version-changes.sh
Labels: status: ready to merge, type: build, type: enhancement

#951 Fix increment bug in withComponentId
  .prettierrc
  assets/js/base/hocs/test/with-component-id.js
  assets/js/base/hocs/with-component-id.js
Labels: status: ready to merge, type: bug, type: performance

#952 Fix review block icons not having foreground color
  assets/js/blocks/reviews/reviews-by-category/index.js
  assets/js/blocks/reviews/reviews-by-product/index.js
Labels: skip-changelog, status: ready to merge, type: bug

#953 Reformat files with new tabwidth
  assets/js/base/components/label/index.js
  assets/js/base/components/load-more-button/index.js
  assets/js/base/components/pagination/index.js
  assets/js/base/components/product-order-select/index.js
  assets/js/base/components/read-more/index.js
  assets/js/base/components/read-more/utils.js
  assets/js/base/components/review-list-item/index.js
  assets/js/base/components/review-list/index.js
  assets/js/base/components/review-order-select/index.js
  assets/js/base/hocs/test/with-reviews.js
  assets/js/base/hocs/with-reviews.js
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-product/block.js
  assets/js/blocks/handpicked-products/block.js
  assets/js/blocks/handpicked-products/index.js
  assets/js/blocks/product-best-sellers/block.js
  assets/js/blocks/product-best-sellers/index.js
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-categories/edit.js
  assets/js/blocks/product-categories/frontend.js
  assets/js/blocks/product-categories/hierarchy.js
  assets/js/blocks/product-category/block.js
  assets/js/blocks/product-category/index.js
  assets/js/blocks/product-new/block.js
  assets/js/blocks/product-new/index.js
  assets/js/blocks/product-on-sale/block.js
  assets/js/blocks/product-search/block.js
  assets/js/blocks/product-search/index.js
  assets/js/blocks/product-tag/block.js
  assets/js/blocks/product-top-rated/block.js
  assets/js/blocks/products-by-attribute/block.js
  assets/js/blocks/reviews/all-reviews/edit.js
  assets/js/blocks/reviews/edit-utils.js
  assets/js/blocks/reviews/reviews-by-category/edit.js
  assets/js/blocks/reviews/reviews-by-category/no-reviews-placeholder.js
  assets/js/blocks/reviews/reviews-by-product/edit.js
  assets/js/blocks/reviews/reviews-by-product/no-reviews-placeholder.js
  assets/js/blocks/reviews/save.js
  assets/js/blocks/reviews/utils.js
  assets/js/components/api-error-placeholder/index.js
  assets/js/components/grid-content-control/index.js
  assets/js/components/grid-layout-control/index.js
  assets/js/components/product-attribute-control/index.js
  assets/js/components/product-category-control/index.js
  assets/js/components/product-control/index.js
  assets/js/components/product-orderby-control/index.js
  assets/js/components/product-tag-control/index.js
  assets/js/components/toggle-button-control/index.js
  assets/js/hocs/test/with-attributes.js
  assets/js/hocs/test/with-categories.js
  assets/js/hocs/test/with-category.js
  assets/js/hocs/test/with-product.js
  assets/js/hocs/test/with-searched-products.js
  assets/js/hocs/with-attributes.js
  assets/js/hocs/with-category.js
  assets/js/hocs/with-product.js
  assets/js/hocs/with-searched-products.js
  bin/changelog.js
  bin/generate-translation-json.js
  webpack.config.js
Labels: skip-changelog, status: ready to merge

#955 Rename ApiErrorPlaceholder to ErrorPlaceholder
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-product/block.js
  assets/js/blocks/reviews/editor-block.js
  assets/js/blocks/reviews/reviews-by-product/no-reviews-placeholder.js
  assets/js/components/error-placeholder/error-message.js
  assets/js/components/error-placeholder/index.js
  assets/js/components/error-placeholder/style.scss
  assets/js/components/product-attribute-control/index.js
  assets/js/components/product-category-control/index.js
  assets/js/components/products-control/index.js
Labels: components, status: ready to merge

#950 Fix product categories list displaying [Object] instead of count
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-categories/style.scss
Labels: status: ready to merge, type: bug

#954 Create renderFrontend utils function
  assets/js/blocks/product-categories/frontend.js
  assets/js/blocks/reviews/frontend.js
  assets/js/utils/render-frontend.js
Labels: status: ready to merge, type: refactor

#981 Revert "Update dependency automattic/jetpack-autoloader to v1.3.1"
  composer.json
  composer.lock
Labels: type: bug, type: build

#978 Fix product grids overflowing in some themes
  assets/css/style.scss
Labels: cherry-pick 🍒, grid-blocks, status: ready to merge, type: bug

#964 Make it possible to select variations in Featured Product block again
  assets/js/components/product-control/index.js
Labels: cherry-pick 🍒, status: ready to merge, type: bug

#956 Implement PHP DI container and refactor. Also implements new Asset data interface for extendable settings passed to js.
  .eslintrc.js
  assets/js/settings/blocks/constants.js
  assets/js/settings/blocks/index.js
  assets/js/settings/shared/currency.js
  assets/js/settings/shared/default-constants.js
  assets/js/settings/shared/get-setting.js
  assets/js/settings/shared/index.js
  assets/js/settings/shared/set-setting.js
  assets/js/settings/shared/settings-init.js
  assets/js/settings/shared/test/get-setting.js
  assets/js/settings/shared/test/set-setting.js
  src/Assets.php
  src/Assets/Api.php
  src/Assets/AssetDataRegistry.php
  src/Assets/BackCompatAssetDataRegistry.php
  src/Domain/Bootstrap.php
  src/Domain/Package.php
  src/Package.php
  src/Registry/AbstractDependencyType.php
  src/Registry/Container.php
  src/Registry/FactoryType.php
  src/Registry/SharedType.php
  tests/js/setup-globals.js
  tests/php/Assets/AssetDataRegistry.php
  tests/php/Bootstrap/MainFile.php
  tests/php/Domain/Package.php
  tests/php/Registry/Container.php
  tests/php/mocks/AssetDataRegistry.php
  tests/php/mocks/MockTestDependency.php
  webpack.config.js
  woocommerce-gutenberg-products-block.php
Labels: status: ready to merge, type: enhancement, type: refactor

#985 Fix webpack requestToExternal
  webpack.config.js
Labels: skip-changelog, status: ready to merge

#986 Delete interpolate-components dependency and update package-lock.json
  package-lock.json
  package.json
  renovate.json
Labels: skip-changelog, status: ready to merge

#974 Update ProductControl to use HOCs
  assets/js/blocks/featured-product/block.js
  assets/js/components/product-control/index.js
  assets/js/components/products-control/index.js
  assets/js/components/utils/index.js
  assets/js/hocs/index.js
  assets/js/hocs/test/with-product-variations.js
  assets/js/hocs/test/with-searched-products.js
  assets/js/hocs/test/with-transform-single-select-to-multiple-select.js
  assets/js/hocs/with-product-variations.js
  assets/js/hocs/with-searched-products.js
  assets/js/hocs/with-transform-single-select-to-multiple-select.js
Labels: skip-changelog, status: ready to merge, type: refactor

#1000 Followup: Ensure version check for back-compat AssetDataRegistry is correct
  src/Domain/Bootstrap.php
Labels: skip-changelog, status: ready to merge, type: enhancement

#999 Remove unnecessary logic (setSetting)
  assets/js/settings/shared/set-setting.js
Labels: skip-changelog, status: ready to merge, type: bug
