Repository woocommerce/woocommerce-blocks, pull requests merged in 2019-12, with the labels that each got.

#1276 Replace 'isPreview' with 'isEditor' when it refers to the editor
  assets/js/blocks/active-filters/block.js
  assets/js/blocks/active-filters/edit.js
  assets/js/blocks/price-filter/block.js
  assets/js/blocks/price-filter/edit.js
  assets/js/blocks/product-search/block.js
  assets/js/blocks/product-search/index.js
Labels: skip-changelog, status: ready to merge, type: refactor

#1287 Remove with-query-string-values hoc implementation
  assets/js/base/components/product-list/container.js
  assets/js/base/hocs/test/with-query-string-values.js
  assets/js/base/hocs/with-query-string-values.js
Labels: skip-changelog, status: ready to merge

#1291 Fix the PHP Notice in Featured Category Block when the category Id is invalid
  src/BlockTypes/FeaturedCategory.php
Labels: status: ready to merge

#1292 Restore back-compat loading of assets registry switch which ensures wcSettings is only loaded when necessary
  package-lock.json
  package.json
  src/Assets/AssetDataRegistry.php
  src/Domain/Bootstrap.php
  tests/php/Assets/AssetDataRegistry.php
  tests/php/mocks/AssetDataRegistry.php
Labels: status: ready to merge, type: enhancement

#1255 Add dropdown display style to Attribute Filter block
  assets/js/base/components/checkbox-list/index.js
  assets/js/base/components/dropdown-selector/index.js
  assets/js/base/components/dropdown-selector/input-wrapper.js
  assets/js/base/components/dropdown-selector/input.js
  assets/js/base/components/dropdown-selector/menu.js
  assets/js/base/components/dropdown-selector/selected-chip.js
  assets/js/base/components/dropdown-selector/style.scss
  assets/js/base/components/label/index.js
  assets/js/base/components/price-slider/style.scss
  assets/js/blocks/active-filters/style.scss
  assets/js/blocks/attribute-filter/block.js
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/attribute-filter/frontend.js
  assets/js/blocks/attribute-filter/index.js
  assets/js/blocks/attribute-filter/style.scss
  package-lock.json
  package.json
Labels: status: ready to merge, type: enhancement

#1306 Skeleton shopping cart block
  assets/js/blocks/cart-checkout/cart/block.js
  assets/js/blocks/cart-checkout/cart/example.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/index.js
  bin/webpack-helpers.js
  src/Assets.php
  src/BlockTypes/Cart.php
  src/Library.php
  webpack.config.js
Labels: skip-changelog, status: ready to merge

#1308 Skeleton Checkout block
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/example.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/blocks/cart-checkout/checkout/index.js
  assets/js/blocks/cart-checkout/checkout/style.scss
  bin/webpack-helpers.js
  src/Assets.php
  src/BlockTypes/Checkout.php
  src/Library.php
  webpack.config.js
Labels: new block, status: ready to merge

#1310 Change bundle size limit to 400 in Travis tests
  bundlesize.config.json
Labels: skip-changelog, status: ready to merge

#1309 Add 'AND' display format to Attribute filter dropdown
  assets/js/base/components/dropdown-selector/index.js
  assets/js/base/components/dropdown-selector/input.js
  assets/js/base/components/dropdown-selector/selected-chip.js
  assets/js/base/components/dropdown-selector/selected-value.js
  assets/js/base/components/dropdown-selector/style.scss
  assets/js/blocks/attribute-filter/block.js
  assets/js/blocks/attribute-filter/style.scss
Labels: skip-changelog, status: ready to merge, type: enhancement

#1319 Add `low_stock_remaining` field to product API
  src/RestApi/StoreApi/Schemas/ProductSchema.php
Labels: rest-api, skip-changelog, status: ready to merge

#1330 Minor code style fixes in All Products block
  assets/js/blocks/products/all-products/edit.js
  assets/js/blocks/products/base-utils.js
  assets/js/blocks/products/edit.js
Labels: skip-changelog, status: ready to merge, type: refactor

#1327 allow merchant to toggle cart empty/full modes in block editor
  assets/js/blocks/cart-checkout/cart/block.js
  assets/js/blocks/cart-checkout/cart/components/empty-cart.js
  assets/js/blocks/cart-checkout/cart/components/full-cart.js
  assets/js/blocks/cart-checkout/cart/index.js
  assets/js/components/text-toolbar-button/README.md
  assets/js/components/text-toolbar-button/index.js
  assets/js/components/text-toolbar-button/style.scss
Labels: skip-changelog, status: ready to merge

#1329 Introduce Checkout Form skeleton and Checkout Form Step Component
  assets/css/abstracts/_colors.scss
  assets/js/base/components/checkout/form-step/index.js
  assets/js/base/components/checkout/form-step/style.scss
  assets/js/base/components/checkout/form/index.js
  assets/js/base/components/checkout/form/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/editor.scss
  assets/js/blocks/cart-checkout/checkout/index.js
Labels: components, status: ready to merge

#1339 Avoid filtering Attribute Filter options when query type is OR
  assets/js/blocks/attribute-filter/block.js
Labels: status: ready to merge

#1332 Add 'Go' button to Attribute Filter
  assets/js/base/components/label/index.js
  assets/js/base/components/price-slider/index.js
  assets/js/base/components/price-slider/style.scss
  assets/js/base/components/submit-button/index.js
  assets/js/base/components/submit-button/style.scss
  assets/js/blocks/attribute-filter/block.js
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/attribute-filter/frontend.js
  assets/js/blocks/attribute-filter/index.js
  assets/js/blocks/attribute-filter/label.js
  assets/js/blocks/attribute-filter/preview.js
  assets/js/blocks/attribute-filter/style.scss
  assets/js/blocks/price-filter/edit.js
Labels: status: ready to merge, type: enhancement

#1335 Fix package init for WooCommerce 3.9
  src/Domain/Package.php
  src/Package.php
  tests/php/Domain/Package.php
  woocommerce-gutenberg-products-block.php
Labels: skip-changelog, status: ready to merge

#1343 Improve cart and checkout block namespacing
  bin/webpack-helpers.js
  src/Assets.php
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
  webpack.config.js
Labels: skip-changelog, status: ready to merge, type: bug

#1353 Fix broken cart & checkout blocks due to inconsistent block names between server side and client side registration
  bin/webpack-helpers.js
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
  webpack.config.js
Labels: status: ready to merge, type: bug

#1355 Update changelog with 2.5.3 release
  readme.txt
Labels: documentation, status: ready to merge

#1344 Store API: Add shipping rate api
  src/RestApi.php
  src/RestApi/Controllers/Cart.php
  src/RestApi/Controllers/Products.php
  src/RestApi/StoreApi/Controllers/Cart.php
  src/RestApi/StoreApi/Controllers/CartItems.php
  src/RestApi/StoreApi/Controllers/CartShippingRates.php
  src/RestApi/StoreApi/Controllers/ProductAttributeTerms.php
  src/RestApi/StoreApi/Controllers/ProductAttributes.php
  src/RestApi/StoreApi/Controllers/ProductCollectionData.php
  src/RestApi/StoreApi/Controllers/Products.php
  src/RestApi/StoreApi/README.md
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  src/RestApi/StoreApi/Schemas/CartShippingRateSchema.php
  src/RestApi/StoreApi/Schemas/ProductSchema.php
  src/RestApi/StoreApi/Utilities/CartController.php
  tests/php/RestApi/StoreApi/Controllers/CartShippingRates.php
Labels: rest-api, status: ready to merge

#1350 Add Empty Cart View with inner blocks
  assets/js/blocks/cart-checkout/cart/components/empty-cart.js
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/cart/empty-cart/icon-data-uri.js
  assets/js/blocks/cart-checkout/cart/empty-cart/index.js
  assets/js/blocks/cart-checkout/cart/empty-cart/style.scss
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/index.js
  assets/js/blocks/cart-checkout/cart/style.scss
  assets/js/settings/blocks/constants.js
  src/Assets.php
Labels: skip-changelog, status: ready to merge

#1352 Added instructions for handling release branches
  CONTRIBUTING.md
Labels: status: ready to merge

#1357 Fix asset namespacing for cart and checkout blocks - round three!
  src/Assets.php
  src/Assets/Api.php
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
Labels: status: ready to merge, type: bug

#1363 Fix increase in some bundle sizes
  package.json
Labels: status: ready to merge, type: bug, type: performance

#1364 Install bundlecop and configure in package.json size-check script
  assets/js/blocks/reviews/all-reviews/index.js
  package-lock.json
  package.json
Labels: skip-changelog, type: build, type: performance

#1365 Try bundlewatch
  bundlesize.config.json
  package-lock.json
  package.json
Labels: skip-changelog, type: build, type: performance

#1325 add pricing discount info to cart line items api
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  src/RestApi/StoreApi/Schemas/CartSchema.php
  tests/php/RestApi/StoreApi/Controllers/Cart.php
  tests/php/RestApi/StoreApi/Controllers/CartItems.php
Labels: rest-api, status: ready to merge

#1368 Load ErrorPlaceholder CSS only in the editor
  assets/js/components/error-placeholder/editor.scss
  assets/js/components/error-placeholder/index.js
Labels: skip-changelog, status: ready to merge

#1369 Rename SubmitButton to FilterSubmitButton
  assets/js/base/components/filter-submit-button/index.js
  assets/js/base/components/filter-submit-button/style.scss
  assets/js/base/components/price-slider/index.js
  assets/js/blocks/attribute-filter/block.js
Labels: skip-changelog, status: ready to merge

#1366 Add Cart block checkout button
  assets/js/base/components/button/index.js
  assets/js/base/components/button/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/checkout-button/american-express-logo.js
  assets/js/blocks/cart-checkout/cart/full-cart/checkout-button/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/checkout-button/payment-logos.js
  assets/js/blocks/cart-checkout/cart/full-cart/checkout-button/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/cart/index.js
  assets/js/settings/blocks/constants.js
  src/Assets.php
Labels: skip-changelog, status: ready to merge

#1367 Add money formatting to API responses
  src/RestApi/StoreApi/Schemas/AbstractSchema.php
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  src/RestApi/StoreApi/Schemas/CartSchema.php
  tests/php/RestApi/StoreApi/Controllers/Cart.php
  tests/php/RestApi/StoreApi/Controllers/CartItems.php
Labels: status: ready to merge

#1374 Use wc_review_ratings_enabled() API function to check if review ratings are enabled
  assets/js/base/components/review-list/index.js
  assets/js/blocks/reviews/edit-utils.js
  assets/js/blocks/reviews/editor-block.js
  assets/js/blocks/reviews/frontend-block.js
  assets/js/blocks/reviews/utils.js
  assets/js/settings/blocks/constants.js
  src/Assets.php
Labels: status: ready to merge

#1379 Normalize set minPrice and maxPrice values by step
  assets/js/base/components/price-slider/index.js
Labels: components, status: ready to merge, type: bug

#1382 Fix messaging when there are no attributes
  assets/js/blocks/attribute-filter/edit.js
Labels: status: ready to merge, type: bug

#1383 Only allow one instance of the All Products block per page/post.
  assets/js/blocks/active-filters/index.js
  assets/js/blocks/price-filter/index.js
  assets/js/blocks/products/all-products/index.js
Labels: status: ready to merge, type: bug

#1385 All Products Block: Fix default sort order changes not updating block in editor.
  assets/js/base/components/product-list/container.js
Labels: status: ready to merge, type: bug

#1390 Always filter attribute filters based on price filter
  assets/js/blocks/attribute-filter/block.js
Labels: status: ready to merge, type: bug

#1384 Only allow one cart or checkout block per page.
  assets/js/blocks/cart-checkout/cart/index.js
  assets/js/blocks/cart-checkout/checkout/index.js
Labels: status: ready to merge, type: enhancement

#1389 Reformat files
  assets/js/base/hocs/test/with-products.js
  assets/js/components/icons/external.js
  assets/js/components/icons/money.js
  assets/js/components/text-toolbar-button/index.js
  assets/js/data/schema/selectors.js
  assets/js/hocs/test/with-categories.js
  assets/js/hocs/test/with-product-variations.js
Labels: status: ready to merge

#1391 Fix Attribute Fiter count misalignment
  assets/js/blocks/attribute-filter/style.scss
Labels: skip-changelog, status: ready to merge, type: bug

#1356 Add Feedback Prompt in Cart & Checkout blocks sidebar
  assets/js/base/context/product-layout-context.js
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/hocs/index.js
  assets/js/hocs/with-feedback-prompt/feedback-prompt.js
  assets/js/hocs/with-feedback-prompt/index.js
  assets/js/hocs/with-feedback-prompt/style.scss
Labels: skip-changelog, status: ready to merge

#1386 Price filter: preserve previous constraints while loading
  assets/js/base/components/price-slider/index.js
  assets/js/base/utils/price.js
  assets/js/base/utils/test/price.js
  assets/js/blocks/price-filter/block.js
  assets/js/blocks/price-filter/test/use-price-constraints.js
  assets/js/blocks/price-filter/use-price-constraints.js
  tests/js/jest.config.json
Labels: status: ready to merge, type: bug

#1351 Add Checkout Form components
  assets/css/abstracts/_colors.scss
  assets/js/base/components/checkout/no-shipping/index.js
  assets/js/base/components/checkout/no-shipping/style.scss
  assets/js/base/components/input-row/index.js
  assets/js/base/components/input-row/style.scss
  assets/js/base/components/radio-control/index.js
  assets/js/base/components/radio-control/style.scss
  assets/js/base/components/text-input/index.js
  assets/js/base/components/text-input/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: components, status: ready to merge, type: feature request

#1395 Update several blocks so they don't support HTML editing
  assets/js/blocks/active-filters/index.js
  assets/js/blocks/attribute-filter/index.js
  assets/js/blocks/price-filter/index.js
  assets/js/blocks/product-categories/index.js
  assets/js/blocks/reviews/all-reviews/index.js
  assets/js/blocks/reviews/reviews-by-category/index.js
  assets/js/blocks/reviews/reviews-by-product/index.js
Labels: status: ready to merge

#1397 Fix incorrect property name for price format
  assets/js/base/utils/price.js
  assets/js/blocks/price-filter/block.js
Labels: status: ready to merge, type: bug

#1402 Fix broken atomic blocks in the All Products Block
  package.json
Labels: status: ready to merge, type: blocker, type: bug

#1399 Remove extra colon in active filter block
  assets/js/blocks/active-filters/block.js
Labels: status: ready to merge

#1404 update changelog to 2.5.5
  readme.txt
Labels: documentation, skip-changelog, status: ready to merge

#1403 Update Contributors.md for releasing a new minor version
  CONTRIBUTING.md
Labels: documentation, status: ready to merge

#1412 Translator string feedback
  assets/js/blocks/active-filters/edit.js
  assets/js/blocks/active-filters/utils.js
Labels: status: ready to merge

#1415 fix translation quantities
  assets/js/atomic/components/product/button/index.js
  assets/js/base/components/checkbox-list/index.js
  assets/js/base/components/checkout/form-step/index.js
Labels: status: ready to merge, type: bug

#1378 Store API: Add cart coupon endpoints
  src/RestApi.php
  src/RestApi/StoreApi/Controllers/CartCoupons.php
  src/RestApi/StoreApi/README.md
  src/RestApi/StoreApi/Schemas/CartCouponSchema.php
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  src/RestApi/StoreApi/Schemas/CartSchema.php
  src/RestApi/StoreApi/Utilities/CartController.php
  tests/php/RestApi/StoreApi/Controllers/CartCoupons.php
Labels: rest-api, skip-changelog, status: ready to merge

#1420 Update filter blocks descriptions to explain they only work with the All Products block
  assets/js/blocks/active-filters/index.js
  assets/js/blocks/attribute-filter/index.js
  assets/js/blocks/price-filter/index.js
  readme.txt
Labels: skip-changelog, status: ready to merge

#1419 Fix Price Filter constraints by rounding up and down
  assets/js/blocks/price-filter/constants.js
  assets/js/blocks/price-filter/test/use-price-constraints.js
  assets/js/blocks/price-filter/use-price-constraints.js
Labels: status: ready to merge, type: bug

#1401 Add type to checkout input fields
  assets/js/base/components/text-input/index.js
  assets/js/base/components/text-input/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: skip-changelog, status: ready to merge

#1421 Fix double 'yet yet'
  assets/js/blocks/attribute-filter/edit.js
Labels: skip-changelog, status: ready to merge

#1417 Store API: Add customer endpoints
  src/RestApi.php
  src/RestApi/StoreApi/Controllers/Customer.php
  src/RestApi/StoreApi/README.md
  src/RestApi/StoreApi/Schemas/CustomerSchema.php
  tests/php/RestApi/StoreApi/Controllers/Customer.php
Labels: rest-api, status: ready to merge

#1450 Remove minor unit from price filter
  assets/js/blocks/price-filter/test/use-price-constraints.js
  assets/js/blocks/price-filter/use-price-constraints.js
Labels: status: ready to merge, type: bug

#1445 Remove style-loader
  bin/webpack-helpers.js
  package-lock.json
  package.json
Labels: skip-changelog, status: ready to merge
