Repository woocommerce/woocommerce-blocks, pull requests merged in 2019-06, with the labels that each got.

#610 Remove the styles build target in webpack
  assets/js/index.js
  webpack.config.js
Labels: Build, [Status] Ready to Merge

#605 Introduce transient caching to grid block queries
  assets/php/class-wgpb-block-grid-base.php
  assets/php/class-wgpb-block-product-best-sellers.php
  assets/php/class-wgpb-block-product-new.php
  assets/php/class-wgpb-block-product-top-rated.php
Labels: [Status] Ready to Merge

#609 Update all dynamic blocks
  assets/js/blocks/handpicked-products/block.js
  assets/js/blocks/product-best-sellers/block.js
  assets/js/blocks/product-category/block.js
  assets/js/blocks/product-new/block.js
  assets/js/blocks/product-on-sale/block.js
  assets/js/blocks/product-top-rated/block.js
  assets/js/blocks/products-by-attribute/block.js
  assets/php/class-wgpb-block-featured-product.php
  assets/php/class-wgpb-block-grid-base.php
  assets/php/class-wgpb-block-handpicked-products.php
  assets/php/class-wgpb-block-library.php
  assets/php/class-wgpb-block-product-best-sellers.php
  assets/php/class-wgpb-block-product-category.php
  assets/php/class-wgpb-block-product-new.php
  assets/php/class-wgpb-block-product-on-sale.php
  assets/php/class-wgpb-block-product-top-rated.php
  assets/php/class-wgpb-block-products-by-attribute.php
Labels: Grid Blocks, [Status] Ready to Merge

#625 Add `menu_order` as a valid orderby value
  assets/php/class-wgpb-block-library.php
Labels: Grid Blocks, [Status] Ready to Merge

#626 Try webpack dependency extraction plugin
  assets/php/class-wgpb-block-library.php
  package-lock.json
  package.json
  webpack.config.js
Labels: Build, [Status] Ready to Merge

#613 Add/block product categories
  .eslintrc.js
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-categories/edit.js
  assets/js/blocks/product-categories/editor.scss
  assets/js/blocks/product-categories/frontend.js
  assets/js/blocks/product-categories/hierarchy.js
  assets/js/blocks/product-categories/index.js
  assets/js/components/icons/folder.js
  assets/js/components/icons/index.js
  assets/js/utils/deprecations.js
  assets/php/class-wgpb-block-library.php
  webpack.config.js
Labels: New Block, [Status] Ready to Merge

#637 Product Categories List: Add the links into the rendered block
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-categories/edit.js
  assets/php/class-wgpb-block-library.php
Labels: [Status] Ready to Merge

#646 Dependencies: Roll back husky update to 2.4.1
  package-lock.json
  package.json
  renovate.json
Labels: [Status] Ready to Merge, [Type] Bug

#647 Product Categories List: Update dropdown view
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-categories/edit.js
  assets/js/blocks/product-categories/frontend.js
  assets/js/blocks/product-categories/index.js
  assets/js/blocks/product-categories/style.scss
  assets/php/class-wgpb-block-library.php
Labels: Accessibility, [Status] Needs Design Review, [Status] Needs Review

#650 Product Categories List: add a placeholder on save
  assets/js/blocks/product-categories/frontend.js
  assets/js/blocks/product-categories/index.js
  assets/js/blocks/product-categories/style.scss
Labels: [Status] Ready to Merge

#651 Release version 2.2.0
  assets/css/style.scss
  package-lock.json
  package.json
  readme.txt
  woocommerce-gutenberg-products-block.php
Labels: [Status] Ready to Merge

#652 Bump version to 2.3.0-dev
  package-lock.json
  package.json
  readme.txt
  woocommerce-gutenberg-products-block.php
Labels: [Status] Ready to Merge

#628 Include blocks api in feature plugin
  assets/js/blocks/featured-product/block.js
  assets/js/components/product-attribute-control/index.js
  assets/js/components/product-category-control/index.js
  assets/js/components/utils/index.js
  assets/php/class-wgpb-block-library.php
  composer.json
  composer.lock
  package-lock.json
  phpcs.xml
  readme.txt
  src/RestApi.php
  src/RestApi/Controllers/ProductAttributeTerms.php
  src/RestApi/Controllers/ProductAttributes.php
  src/RestApi/Controllers/ProductCategories.php
  src/RestApi/Controllers/Products.php
  src/Utilities/SingletonTrait.php
  tests/bin/install-wp-tests.sh
  tests/php/RestApi/Controllers/ProductAttributeTerms.php
  tests/php/RestApi/Controllers/ProductAttributes.php
  tests/php/RestApi/Controllers/ProductCategories.php
  tests/php/RestApi/Controllers/Products.php
  woocommerce-gutenberg-products-block.php
Labels: [Tests] Includes Tests
