Repository woocommerce/woocommerce-blocks, pull requests merged in 2019-07, with the labels that each got.

#661 Allow additional CSS classes to SSR blocks
  assets/php/class-wgpb-block-grid-base.php
  assets/php/class-wgpb-block-library.php
Labels: cherry-pick 🍒, status: ready to merge, type: bug

#662 Allow additional CSS classes to Featured Product block
  assets/js/blocks/featured-product/block.js
  assets/php/class-wgpb-block-featured-product.php
Labels: cherry-pick 🍒, status: ready to merge

#664 Apply Product Categories List additional CSS class in the editor
  assets/js/blocks/product-categories/block.js
Labels: cherry-pick 🍒, status: ready to merge

#655 Move main controllers from assets/php to src
  .travis.yml
  assets/php/class-wgpb-block-library.php
  composer.json
  composer.lock
  phpcs.xml
  phpunit.xml.dist
  src/Assets.php
  src/Library.php
  src/Package.php
  tests/bin/install-wp-tests.sh
  tests/bin/phpunit.sh
  tests/bootstrap.php
  tests/framework/class-wc-api-unit-test-case.php
  tests/framework/class-wc-dummy-data-store.php
  tests/framework/class-wc-mock-payment-gateway.php
  tests/framework/class-wc-mock-session-handler.php
  tests/framework/class-wc-mock-wc-data.php
  tests/framework/class-wc-mock-wc-object-query.php
  tests/framework/class-wc-payment-token-stub.php
  tests/framework/class-wc-rest-unit-test-case.php
  tests/framework/class-wc-unit-test-case.php
  tests/framework/class-wc-unit-test-factory.php
  tests/framework/helpers/class-wc-helper-coupon.php
  tests/framework/helpers/class-wc-helper-customer.php
  tests/framework/helpers/class-wc-helper-fee.php
  tests/framework/helpers/class-wc-helper-order.php
  tests/framework/helpers/class-wc-helper-payment-token.php
  tests/framework/helpers/class-wc-helper-product.php
  tests/framework/helpers/class-wc-helper-settings.php
  tests/framework/helpers/class-wc-helper-shipping-zones.php
  tests/framework/helpers/class-wc-helper-shipping.php
  tests/framework/speed-trap-listener.php
  tests/framework/vendor/class-wp-test-spy-rest-server.php
  tests/framework/wp-http-testcase.php
  woocommerce-gutenberg-products-block.php
Labels: type: refactor

#656 Abstract block refactor
  assets/js/blocks/products-by-attribute/block.js
  assets/js/blocks/products-by-attribute/editor.scss
  assets/php/class-wgpb-block-handpicked-products.php
  assets/php/class-wgpb-block-product-best-sellers.php
  assets/php/class-wgpb-block-product-category.php
  assets/php/class-wgpb-block-product-new.php
  assets/php/class-wgpb-block-product-on-sale.php
  assets/php/class-wgpb-block-product-top-rated.php
  assets/php/class-wgpb-block-products-by-attribute.php
  src/Assets.php
  src/BlockTypes/AbstractBlock.php
  src/BlockTypes/AbstractDynamicBlock.php
  src/BlockTypes/AbstractProductGrid.php
  src/BlockTypes/FeaturedProduct.php
  src/BlockTypes/HandpickedProducts.php
  src/BlockTypes/ProductBestSellers.php
  src/BlockTypes/ProductCategories.php
  src/BlockTypes/ProductCategory.php
  src/BlockTypes/ProductNew.php
  src/BlockTypes/ProductOnSale.php
  src/BlockTypes/ProductTopRated.php
  src/BlockTypes/ProductsByAttribute.php
  src/Library.php
  webpack.config.js
Labels: status: ready to merge

#668 Re-introduce `set_ordering_query_args`
  src/BlockTypes/AbstractProductGrid.php
Labels: status: ready to merge

#667 GitHub deploy script
  bin/github-deploy.sh
  package.json
Labels: status: ready to merge

#675 Introduce `ToggleButtonControl` for Product Category List display type
  assets/js/blocks/product-categories/edit.js
  assets/js/components/toggle-button-control/README.md
  assets/js/components/toggle-button-control/index.js
  assets/js/components/toggle-button-control/screenshot.png
  assets/js/components/toggle-button-control/style.scss
Labels: status: ready to merge

#683 Prepare 2.2.1 for release
  package-lock.json
  package.json
  readme.txt
  woocommerce-gutenberg-products-block.php
Labels: status: ready to merge

#684 Fix lint-staged config
  package.json
Labels: status: ready to merge

#685 WordPress org release script
  .gitattributes
  CONTRIBUTING.md
  bin/github-deploy.sh
  bin/wordpress-deploy.sh
  package.json
Labels: status: ready to merge

#678 Add placeholder when no categories exist to list
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-categories/editor.scss
Labels: status: ready to merge

#671 Add reviews count to Reviews by Product controls
  assets/js/blocks/reviews-by-product/block.js
  assets/js/components/product-control/index.js
  src/RestApi/Controllers/Products.php
Labels: status: ready to merge

#677 Add label to Reviews by Product controls count
  assets/js/blocks/reviews-by-product/block.js
  composer.lock
  package-lock.json
  package.json
Labels: status: ready to merge

#688 Review ordering and placeholders
  assets/js/blocks/reviews-by-product/block.js
  assets/js/blocks/reviews-by-product/editor.scss
  assets/js/blocks/reviews-by-product/index.js
  assets/js/components/product-control/index.js
  assets/js/components/utils/index.js
  src/RestApi/Controllers/Products.php
Labels: status: ready to merge

#693 Fix linting errors and warnings
  assets/js/blocks/reviews-by-product/block.js
  assets/js/components/grid-content-control/index.js
  assets/js/components/product-preview/index.js
  assets/js/components/utils/index.js
Labels: status: ready to merge

#696 Reviews by Product: load and render reviews with JS
  assets/js/blocks/reviews-by-product/block.js
  assets/js/blocks/reviews-by-product/edit.js
  assets/js/blocks/reviews-by-product/frontend.js
  assets/js/blocks/reviews-by-product/index.js
  assets/js/blocks/reviews-by-product/style.scss
  assets/js/blocks/reviews-by-product/utils.js
  package.json
  src/Assets.php
  webpack.config.js
Labels: status: ready to merge

#691 Create Reviews by Product block placeholder
  assets/js/blocks/reviews-by-product/block.js
  assets/js/blocks/reviews-by-product/edit.js
  assets/js/blocks/reviews-by-product/frontend.js
  assets/js/blocks/reviews-by-product/index.js
  assets/js/blocks/reviews-by-product/style.scss
  assets/js/blocks/reviews-by-product/utils.js
  package.json
  src/Assets.php
  src/BlockTypes/ReviewsByProduct.php
  webpack.config.js
Labels: status: ready to merge

#702 Rename 'Reviewer Picture' with 'Avatar'
  assets/js/blocks/reviews-by-product/block.js
  assets/js/blocks/reviews-by-product/edit.js
  assets/js/blocks/reviews-by-product/frontend.js
  assets/js/blocks/reviews-by-product/index.js
  assets/js/blocks/reviews-by-product/style.scss
  assets/js/blocks/reviews-by-product/utils.js
Labels: status: ready to merge

#608 Featured Product Block: Make it possible to feature a specific product variation
  assets/js/blocks/featured-product/block.js
  assets/js/blocks/featured-product/index.js
  assets/js/blocks/featured-product/style.scss
  assets/js/components/product-attribute-control/style.scss
  assets/js/components/product-control/index.js
  assets/js/components/product-control/style.scss
  composer.lock
  src/BlockTypes/FeaturedProduct.php
  src/RestApi.php
  src/RestApi/Controllers/Products.php
  src/RestApi/Controllers/Variations.php
Labels: status: ready to merge

#700 Fix Featured Product block using a Handpicked Products block CSS class
  assets/js/blocks/featured-product/block.js
  assets/js/blocks/featured-product/editor.scss
Labels: status: ready to merge

#699 Add pre-commit CSS and JS linting
  assets/js/blocks/featured-product/editor.scss
  assets/js/blocks/featured-product/style.scss
  assets/js/components/grid-content-control/index.js
  assets/js/components/product-attribute-control/style.scss
  assets/js/components/product-preview/index.js
  package.json
Labels: status: ready to merge

#689 Add `package-plugin` script
  .gitignore
  CONTRIBUTING.md
  bin/build-plugin-zip.sh
  package.json
Labels: status: ready to merge

#676 Featured Category Block
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-category/editor.scss
  assets/js/blocks/featured-category/index.js
  assets/js/blocks/featured-category/style.scss
  assets/js/components/icons/folder-star.js
  assets/js/components/icons/index.js
  assets/js/components/product-category-control/index.js
  src/Assets.php
  src/BlockTypes/FeaturedCategory.php
  src/Library.php
  src/RestApi/Controllers/ProductCategories.php
  webpack.config.js
Labels: status: ready to merge

#554 Introduce a new Products by Tag(s) block
  assets/js/blocks/featured-category/editor.scss
  assets/js/blocks/featured-category/style.scss
  assets/js/blocks/featured-product/editor.scss
  assets/js/blocks/product-tag/block.js
  assets/js/blocks/product-tag/editor.scss
  assets/js/blocks/product-tag/index.js
  assets/js/components/product-control/style.scss
  assets/js/components/product-tag-control/index.js
  assets/js/components/product-tag-control/style.scss
  assets/js/components/utils/index.js
  assets/js/utils/get-query.js
  src/Assets.php
  src/BlockTypes/AbstractProductGrid.php
  src/BlockTypes/ProductCategory.php
  src/BlockTypes/ProductTag.php
  src/Library.php
  src/RestApi.php
  src/RestApi/Controllers/ProductTags.php
  webpack.config.js
Labels: status: ready to merge

#707 Replace stringifyQuery with addQueryArgs
  assets/js/blocks/reviews-by-product/block.js
  src/Assets.php
Labels: status: ready to merge

#672 Rolling 2.3 release changelog
  package.json
  readme.txt
  src/Package.php
  woocommerce-gutenberg-products-block.php
Labels: status: ready to merge

#705 Add reviews endpoint
  assets/js/blocks/reviews-by-product/block.js
  src/RestApi.php
  src/RestApi/ProductReviews.php
Labels: status: ready to merge

#679 Experiment: Handling API fetch errors
  assets/css/editor.scss
  assets/js/blocks/featured-product/block.js
  assets/js/blocks/featured-product/editor.scss
  assets/js/components/api-error-placeholder/index.js
  package-lock.json
Labels: status: ready to merge

#715 Prevent state updates on unmounted components
  assets/js/blocks/reviews-by-product/block.js
  assets/js/blocks/reviews-by-product/edit.js
  assets/js/components/product-control/index.js
Labels: status: ready to merge

#716 Add Order by and Load more controls in Reviews by Product frontend
  assets/js/blocks/reviews-by-product/block.js
  assets/js/blocks/reviews-by-product/edit.js
  assets/js/blocks/reviews-by-product/index.js
  assets/js/blocks/reviews-by-product/style.scss
Labels: status: ready to merge

#721 Export IconReviewsByProduct
  assets/js/blocks/reviews-by-product/edit.js
  assets/js/blocks/reviews-by-product/index.js
  assets/js/components/icons/index.js
Labels: status: ready to merge

#722 Add visibility query to product grids
  src/BlockTypes/AbstractProductGrid.php
Labels: status: ready to merge

#723 Fix Reviews by Product layout in IE11
  assets/js/blocks/reviews-by-product/style.scss
  postcss.config.js
Labels: status: needs review

#731 Reviews by Product: Set minimum to per page input field
  assets/js/blocks/reviews-by-product/block.js
  assets/js/blocks/reviews-by-product/edit.js
Labels: status: ready to merge

#725 Cancel debounced functions on unmount
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-product/block.js
  assets/js/components/product-attribute-control/index.js
  assets/js/components/products-control/index.js
Labels: status: ready to merge

#730 Hide avatars in Reviews by Products if 'show_avatars' setting is false
  assets/js/blocks/reviews-by-product/block.js
  assets/js/blocks/reviews-by-product/edit.js
  assets/js/blocks/reviews-by-product/frontend.js
  assets/js/blocks/reviews-by-product/index.js
  assets/js/blocks/reviews-by-product/style.scss
  assets/js/blocks/reviews-by-product/utils.js
  src/Assets.php
Labels: status: ready to merge

#726 Blocks API - Reviews endpoint with rating sort and category filtering
  assets/js/blocks/reviews-by-product/block.js
  src/RestApi/Controllers/ProductReviews.php
  src/RestApi/ProductReviews.php
Labels: status: ready to merge

#738 add composer install to readme
  README.md
Labels: status: ready to merge

#732 Reviews by Product: add placeholders when loading reviews
  assets/js/blocks/reviews-by-product/block.js
  assets/js/blocks/reviews-by-product/utils.js
Labels: status: ready to merge

#746 Load frontend scripts only when required
  src/Assets.php
  src/BlockTypes/AbstractBlock.php
  src/BlockTypes/ProductCategories.php
Labels: status: ready to merge

#750 Remove vendors.js as a frontend dependency
  src/Assets.php
  webpack.config.js
Labels: status: ready to merge

#756 Use radio buttons instead of checkboxes in Featured Category control
  assets/js/blocks/featured-category/block.js
Labels: status: ready to merge

#733 Add placeholder animation
  assets/css/abstracts/_mixins.scss
Labels: status: ready to merge

#757 Remove constants and unhook old blocks plugin
  src/Assets.php
  src/Package.php
Labels: cherry-pick 🍒, status: ready to merge

#740 Reviews by Product: Hide ratings if they are disabled in settings
  assets/js/blocks/reviews-by-product/block.js
  assets/js/blocks/reviews-by-product/edit.js
  assets/js/blocks/reviews-by-product/utils.js
  src/Assets.php
  src/RestApi/Controllers/ProductReviews.php
Labels: status: ready to merge

#736 Hook up Reviews by Product 'Order by' with endpoint
  assets/js/blocks/reviews-by-product/block.js
  assets/js/blocks/reviews-by-product/edit.js
  assets/js/blocks/reviews-by-product/utils.js
  src/Assets.php
  src/RestApi/Controllers/ProductReviews.php
Labels: status: needs review, status: ready to merge

#775 Refactor register_block_script
  src/Assets.php
  src/BlockTypes/ProductCategories.php
Labels: cherry-pick 🍒, status: ready to merge, type: refactor

#771 Reduce number of dependencies for the product categories list block
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-categories/edit.js
  assets/js/blocks/product-categories/editor.scss
  assets/js/blocks/product-categories/frontend.js
  assets/js/blocks/product-categories/get-categories.js
  assets/js/blocks/product-categories/hierarchy.js
  assets/js/blocks/product-categories/style.scss
  assets/js/utils/with-component-id.js
  babel.config.js
  package-lock.json
  package.json
  src/Assets.php
  webpack.config.js
Labels: cherry-pick 🍒, status: ready to merge, type: refactor

#773 Reviews by Product cleanup
  assets/js/blocks/reviews-by-product/block.js
  assets/js/blocks/reviews-by-product/edit.js
  assets/js/blocks/reviews-by-product/frontend.js
  assets/js/blocks/reviews-by-product/index.js
  assets/js/blocks/reviews-by-product/style.scss
  assets/js/blocks/reviews-by-product/utils.js
Labels: status: needs review, status: ready to merge

#777 Fix ComponentId camelCase
  assets/js/blocks/product-categories/block.js
  assets/js/utils/with-component-id.js
Labels: cherry-pick 🍒, status: ready to merge

#781 Fix Jest missing webpack config
  tests/js/jest.config.json
  tests/js/jestPreprocess.js
Labels: status: ready to merge, type: build

#780 Ensure register_block_type exists
  src/Package.php
Labels: cherry-pick 🍒, status: ready to merge

#774 Reduce the number of dependencies used in Reviews by Product
  assets/js/blocks/reviews-by-product/block.js
  assets/js/blocks/reviews-by-product/frontend.js
  assets/js/blocks/reviews-by-product/utils.js
  src/RestApi/Controllers/ProductReviews.php
Labels: status: ready to merge, type: refactor
