Repository woocommerce/woocommerce-blocks, pull requests merged in 2019-08, with the labels that each got.

#788 Add formatted_date_created schema
  src/RestApi/Controllers/ProductReviews.php
Labels: status: ready to merge

#779 Create `withProduct` HOC
  assets/js/blocks/featured-product/block.js
  assets/js/blocks/featured-product/utils.js
  assets/js/components/api-error-placeholder/index.js
  assets/js/components/utils/index.js
  assets/js/hocs/index.js
  assets/js/hocs/test/with-product.js
  assets/js/hocs/with-product.js
  assets/js/utils/products.js
Labels: status: needs review, type: refactor

#797 Move withComponentId to hocs directory
  assets/js/blocks/product-categories/block.js
  assets/js/hocs/index.js
  assets/js/hocs/with-component-id.js
Labels: status: ready to merge, type: refactor

#697 Add product search block
  assets/js/blocks/product-categories/style.scss
  assets/js/blocks/product-search/block.js
  assets/js/blocks/product-search/editor.scss
  assets/js/blocks/product-search/index.js
  assets/js/blocks/product-search/style.scss
  src/Assets.php
  src/BlockTypes/ProductSearch.php
  src/Library.php
  webpack.config.js
Labels: new block, status: needs design, status: ready to merge

#787 Add new settings to Reviews by Product block
  assets/js/blocks/reviews-by-product/block.js
  assets/js/blocks/reviews-by-product/edit.js
  assets/js/blocks/reviews-by-product/editor.scss
  assets/js/blocks/reviews-by-product/frontend.js
  assets/js/blocks/reviews-by-product/index.js
  assets/js/blocks/reviews-by-product/style.scss
  assets/js/blocks/reviews-by-product/utils.js
  package-lock.json
  package.json
  src/RestApi/Controllers/ProductReviews.php
Labels: status: needs review

#801 Disable HTML editing on dynamic blocks
  assets/js/blocks/featured-product/index.js
  assets/js/blocks/handpicked-products/index.js
  assets/js/blocks/product-best-sellers/index.js
  assets/js/blocks/product-category/index.js
  assets/js/blocks/product-search/block.js
  assets/js/blocks/product-tag/index.js
  assets/js/blocks/product-top-rated/index.js
  assets/js/blocks/products-by-attribute/index.js
Labels: status: needs review

#791 Introduce withSearchedProducts higher order component and refactor ProductsControl Component
  assets/js/components/products-control/index.js
  assets/js/hocs/index.js
  assets/js/hocs/test/with-searched-products.js
  assets/js/hocs/with-searched-products.js
Labels: components, status: ready to merge, type: refactor

#811 Reviews by Product: prevent importing all HOCs and import only withComponentId
  assets/js/blocks/reviews-by-product/block.js
Labels: status: ready to merge, type: refactor

#799 Create a constants.js file with the NAMESPACE value
  assets/js/blocks/featured-category/block.js
  assets/js/components/product-attribute-control/index.js
  assets/js/components/product-category-control/index.js
  assets/js/components/product-control/index.js
  assets/js/components/utils/index.js
  assets/js/constants.js
Labels: status: ready to merge, type: refactor

#806 Reviews by product: Update review styling and content
  assets/js/blocks/reviews-by-product/style.scss
  assets/js/blocks/reviews-by-product/utils.js
  assets/js/components/read-more/index.js
Labels: status: ready to merge

#820 Update renderReview JSDoc
  assets/js/blocks/reviews-by-product/utils.js
Labels: status: ready to merge

#818 Fix Reviews by Product order by select not honoring default setting
  assets/js/blocks/reviews-by-product/block.js
Labels: status: ready to merge

#817 Add tests to utils/products.js
  assets/js/utils/products.js
  assets/js/utils/test/products.js
Labels: status: ready to merge, type: refactor

#813 Featured Product: hide background opacity control if there is no image
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-product/block.js
Labels: cherry-pick 🍒, status: ready to merge, type: enhancement

#816 Disable HTML editing on Featured Category
  assets/js/blocks/featured-category/index.js
Labels: cherry-pick 🍒, status: ready to merge

#826 Call clampLines from componentDidMount
  assets/js/components/read-more/index.js
Labels: status: ready to merge

#825 Update the changelog with changes from #813
  readme.txt
Labels: status: ready to merge

#796 Reduce CSS specificity
  assets/css/style.scss
  src/BlockTypes/AbstractProductGrid.php
Labels: cherry-pick 🍒, status: ready to merge

#819 Add eslint JSDoc checks
  .eslintrc.js
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-product/utils.js
  assets/js/components/product-control/index.js
  assets/js/components/products-control/index.js
  assets/js/components/utils/index.js
  assets/js/utils/products.js
  composer.lock
  package-lock.json
  package.json
Labels: status: ready to merge

#822 Add bundlesize package and tweak travis config
  .travis.yml
  bundlesize.config.json
  package-lock.json
  package.json
  src/Package.php
  src/RestApi/Controllers/Products.php
  tests/bin/install-wp-tests.sh
  tests/bootstrap.php
  tests/framework/class-wc-api-unit-test-case.php
  tests/framework/class-wc-dummy-data-store.php
  tests/framework/class-wc-mock-payment-gateway.php
  tests/framework/class-wc-mock-session-handler.php
  tests/framework/class-wc-mock-wc-data.php
  tests/framework/class-wc-mock-wc-object-query.php
  tests/framework/class-wc-payment-token-stub.php
  tests/framework/class-wc-rest-unit-test-case.php
  tests/framework/class-wc-unit-test-case.php
  tests/framework/class-wc-unit-test-factory.php
  tests/framework/helpers/class-wc-helper-coupon.php
  tests/framework/helpers/class-wc-helper-customer.php
  tests/framework/helpers/class-wc-helper-fee.php
  tests/framework/helpers/class-wc-helper-order.php
  tests/framework/helpers/class-wc-helper-payment-token.php
  tests/framework/helpers/class-wc-helper-product.php
  tests/framework/helpers/class-wc-helper-settings.php
  tests/framework/helpers/class-wc-helper-shipping-zones.php
  tests/framework/helpers/class-wc-helper-shipping.php
  tests/framework/speed-trap-listener.php
  tests/framework/vendor/class-wp-test-spy-rest-server.php
  tests/framework/wp-http-testcase.php
  tests/php/RestApi/Controllers/Products.php
Labels: status: ready to merge, type: build, type: enhancement

#834 Product Categories List: prevent importing all HOCs and import only withComponentId
  assets/js/blocks/product-categories/block.js
Labels: status: ready to merge, type: refactor

#836 Make react-test-renderer import name consistent between tests
  assets/js/components/product-preview/test/index.js
Labels: status: ready to merge, type: refactor

#821 Read more component - change how clamped content is shown
  assets/js/blocks/reviews-by-product/utils.js
  assets/js/components/read-more/index.js
  assets/js/components/read-more/test/index.js
  assets/js/components/read-more/utils.js
  package-lock.json
  package.json
Labels: components, status: ready to merge

#803 Allow hidden products in handpicked products block
  assets/js/components/utils/index.js
  src/BlockTypes/AbstractProductGrid.php
  src/BlockTypes/HandpickedProducts.php
  src/RestApi/Controllers/Products.php
Labels: status: ready to merge

#828 Use withProduct HOC in ReviewsByProductEditor
  assets/js/blocks/reviews-by-product/edit.js
Labels: status: ready to merge, type: refactor

#830 Reviews: only save wrapper element to post
  assets/js/blocks/reviews-by-product/index.js
Labels: status: ready to merge

#840 Fix bundlesize config not picking frontend files
  bundlesize.config.json
Labels: status: ready to merge

#843 Fix duplicated translatable string
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/handpicked-products/block.js
  assets/js/blocks/product-category/block.js
  assets/js/blocks/product-tag/block.js
  assets/js/blocks/product-tag/index.js
Labels: cherry-pick 🍒, status: ready to merge

#839 Add babel-plugin-transform-remove-prop-types Babel plugin
  package-lock.json
  package.json
  webpack.config.js
Labels: status: ready to merge, type: build, type: enhancement

#848 Add global data helpers
  .eslintrc.js
  assets/js/settings/currency.js
  assets/js/settings/index.js
  src/Assets.php
  webpack.config.js
Labels: status: needs review

#841 Reviews by Product: split 'block.js' into smaller chunks
  .eslintrc.js
  assets/js/base/components/load-more-button/index.js
  assets/js/base/components/load-more-button/style.scss
  assets/js/base/components/read-more/index.js
  assets/js/base/components/read-more/test/index.js
  assets/js/base/components/read-more/utils.js
  assets/js/base/components/review-list-item/index.js
  assets/js/base/components/review-list-item/style.scss
  assets/js/base/components/review-list/index.js
  assets/js/base/components/review-list/style.scss
  assets/js/base/components/review-order-select/index.js
  assets/js/base/components/review-order-select/style.scss
  assets/js/base/hocs/with-component-id.js
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/reviews-by-product/block.js
  assets/js/blocks/reviews-by-product/edit.js
  assets/js/blocks/reviews-by-product/editor-block.js
  assets/js/blocks/reviews-by-product/frontend-block.js
  assets/js/blocks/reviews-by-product/frontend.js
  assets/js/blocks/reviews-by-product/index.js
  assets/js/blocks/reviews-by-product/style.scss
  assets/js/blocks/reviews-by-product/utils.js
  assets/js/hocs/index.js
  package.json
  webpack.config.js
Labels: status: ready to merge, type: refactor

#862 Remove unnecessary browserlist configuration from package.json
  package.json
Labels: status: ready to merge, type: build, type: enhancement

#860 Fix Reviews by Product using rating count instead of review count
  assets/js/blocks/reviews-by-product/edit.js
  src/RestApi/Controllers/Products.php
Labels: status: ready to merge, type: bug

#857 Use correct parameter order for implode.
  src/BlockTypes/FeaturedCategory.php
  src/BlockTypes/FeaturedProduct.php
Labels: cherry-pick 🍒, status: ready to merge

#869 Add description to blocks added in last releases
  readme.txt
Labels: cherry-pick 🍒, documentation, status: ready to merge, type: enhancement

#846 Introduce withCategory HOC for featured category block
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-category/utils.js
  assets/js/components/utils/index.js
  assets/js/constants.js
  assets/js/hocs/index.js
  assets/js/hocs/with-category.js
Labels: status: ready to merge

#849 Remove screen-reader-text css rules
  assets/js/blocks/product-categories/style.scss
  assets/js/blocks/product-search/style.scss
Labels: status: ready to merge

#866 Left align stars
  assets/css/style.scss
Labels: cherry-pick 🍒, status: ready to merge

#861 Improve Reviews by Product accessibility
  assets/js/base/components/load-more-button/index.js
  assets/js/base/components/review-order-select/index.js
  assets/js/blocks/reviews-by-product/edit.js
  assets/js/blocks/reviews-by-product/editor-block.js
  assets/js/blocks/reviews-by-product/frontend-block.js
Labels: accessibility, status: ready to merge

#863 Reviews: fix reviews without rating not appearing when sorting by rating
  src/RestApi/Controllers/ProductReviews.php
Labels: status: ready to merge

#871 Update Reviews styles so it looks the same in the editor and the frontend
  assets/js/base/components/load-more-button/index.js
  assets/js/base/components/load-more-button/style.scss
  assets/js/base/components/review-list/style.scss
Labels: status: ready to merge

#870 Move wc_product_block_data variables to constants file
  assets/js/base/components/review-list/index.js
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-category/index.js
  assets/js/blocks/featured-product/block.js
  assets/js/blocks/featured-product/index.js
  assets/js/blocks/handpicked-products/block.js
  assets/js/blocks/handpicked-products/index.js
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-categories/get-categories.js
  assets/js/blocks/product-search/block.js
  assets/js/blocks/product-tag/block.js
  assets/js/blocks/product-tag/index.js
  assets/js/blocks/products-by-attribute/index.js
  assets/js/blocks/reviews-by-product/edit.js
  assets/js/blocks/reviews-by-product/editor-block.js
  assets/js/blocks/reviews-by-product/frontend-block.js
  assets/js/blocks/reviews-by-product/utils.js
  assets/js/components/grid-layout-control/index.js
  assets/js/components/product-control/index.js
  assets/js/components/product-preview/index.js
  assets/js/components/product-preview/test/index.js
  assets/js/components/product-tag-control/index.js
  assets/js/components/utils/index.js
  assets/js/constants.js
  assets/js/hocs/test/with-searched-products.js
  assets/js/hocs/with-searched-products.js
  assets/js/utils/get-query.js
  assets/js/utils/get-shortcode.js
  assets/js/utils/shared-attributes.js
  tests/js/setup-globals.js
Labels: status: ready to merge, type: refactor

#878 Add changelog script
  bin/changelog.js
  package.json
Labels: status: ready to merge

#804 Reviews by category block
  assets/js/base/components/review-list-item/index.js
  assets/js/base/components/review-list-item/style.scss
  assets/js/blocks/reviews-by-product/edit.js
  assets/js/blocks/reviews-by-product/index.js
  assets/js/blocks/reviews/attributes.js
  assets/js/blocks/reviews/edit.js
  assets/js/blocks/reviews/reviews-by-category/edit.js
  assets/js/blocks/reviews/reviews-by-category/editor-block.js
  assets/js/blocks/reviews/reviews-by-category/editor.scss
  assets/js/blocks/reviews/reviews-by-category/frontend-block.js
  assets/js/blocks/reviews/reviews-by-category/frontend.js
  assets/js/blocks/reviews/reviews-by-category/index.js
  assets/js/blocks/reviews/reviews-by-product/edit.js
  assets/js/blocks/reviews/reviews-by-product/editor-block.js
  assets/js/blocks/reviews/reviews-by-product/editor.scss
  assets/js/blocks/reviews/reviews-by-product/frontend-block.js
  assets/js/blocks/reviews/reviews-by-product/frontend.js
  assets/js/blocks/reviews/reviews-by-product/index.js
  assets/js/blocks/reviews/utils.js
  assets/js/components/icons/index.js
  assets/js/components/icons/reviews-by-category.js
  src/Assets.php
  src/BlockTypes/ReviewsByCategory.php
  src/Library.php
  src/RestApi/Controllers/ProductReviews.php
  webpack.config.js
Labels: new block, status: ready to merge

#884 Fix error appearing on Reviews by Product when there were no reviews
  assets/js/blocks/reviews/reviews-by-product/edit.js
  assets/js/blocks/reviews/reviews-by-product/editor-block.js
  assets/js/blocks/reviews/reviews-by-product/no-reviews-placeholder.js
Labels: skip-changelog, status: ready to merge, type: bug

#888 Review blocks: fix attribute notices not appearing
  assets/js/blocks/reviews/edit.js
  assets/js/blocks/reviews/editor.scss
  assets/js/blocks/reviews/reviews-by-category/edit.js
  assets/js/blocks/reviews/reviews-by-category/editor.scss
  assets/js/blocks/reviews/reviews-by-category/index.js
  assets/js/blocks/reviews/reviews-by-product/edit.js
  assets/js/blocks/reviews/reviews-by-product/editor.scss
  assets/js/blocks/reviews/reviews-by-product/index.js
Labels: skip-changelog, status: ready to merge, type: bug

#896 Set eslint version back to 6.1.0
  package.json
Labels: skip-changelog, status: ready to merge

#598 Add schedule to renovate bot config
  renovate.json
Labels: status: ready to merge

#856 Install @babel/plugin-proposal-class-properties.
  assets/js/blocks/product-category/block.js
  package-lock.json
  package.json
  tests/js/jestPreprocess.js
  webpack.config.js
Labels: status: ready to merge, type: build, type: enhancement

#877 Create withReviews base HOC
  assets/js/base/components/review-order-select/index.js
  assets/js/base/hocs/test/with-reviews.js
  assets/js/base/hocs/with-reviews.js
  assets/js/blocks/reviews/frontend-block.js
  assets/js/blocks/reviews/frontend-container-block.js
  assets/js/blocks/reviews/reviews-by-category/edit.js
  assets/js/blocks/reviews/reviews-by-category/editor-block.js
  assets/js/blocks/reviews/reviews-by-category/frontend-block.js
  assets/js/blocks/reviews/reviews-by-category/frontend.js
  assets/js/blocks/reviews/reviews-by-product/edit.js
  assets/js/blocks/reviews/reviews-by-product/editor-block.js
  assets/js/blocks/reviews/reviews-by-product/frontend-block.js
  assets/js/blocks/reviews/reviews-by-product/frontend.js
  package.json
Labels: skip-changelog, status: in progress, status: ready to merge, type: refactor

#903 Refactor: Introduce `wc-block-settings` bundle serving as `@woocommerce/settings` external.
  assets/js/base/components/review-list/index.js
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-category/index.js
  assets/js/blocks/featured-product/block.js
  assets/js/blocks/featured-product/index.js
  assets/js/blocks/handpicked-products/block.js
  assets/js/blocks/handpicked-products/index.js
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-categories/get-categories.js
  assets/js/blocks/product-search/block.js
  assets/js/blocks/product-tag/block.js
  assets/js/blocks/product-tag/index.js
  assets/js/blocks/products-by-attribute/index.js
  assets/js/blocks/reviews/edit.js
  assets/js/blocks/reviews/frontend-block.js
  assets/js/blocks/reviews/reviews-by-category/editor-block.js
  assets/js/blocks/reviews/reviews-by-product/editor-block.js
  assets/js/blocks/reviews/utils.js
  assets/js/components/grid-layout-control/index.js
  assets/js/components/product-attribute-control/index.js
  assets/js/components/product-category-control/index.js
  assets/js/components/product-control/index.js
  assets/js/components/product-preview/index.js
  assets/js/components/product-preview/test/index.js
  assets/js/components/product-tag-control/index.js
  assets/js/components/utils/index.js
  assets/js/hocs/test/with-searched-products.js
  assets/js/hocs/with-searched-products.js
  assets/js/settings/endpoints.js
  assets/js/settings/index.js
  assets/js/settings/product-block-data.js
  assets/js/utils/get-query.js
  assets/js/utils/get-shortcode.js
  assets/js/utils/shared-attributes.js
  src/Assets.php
  tests/js/jest.config.json
  webpack.config.js
Labels: status: ready to merge, type: bug, type: build, type: enhancement

#906 Add babel-loader to webpack CoreConfig
  webpack.config.js
Labels: skip-changelog, status: ready to merge, type: bug

#905 Create OrderSelect and Label components
  assets/js/base/components/label/index.js
  assets/js/base/components/label/test/__snapshots__/index.js.snap
  assets/js/base/components/label/test/index.js
  assets/js/base/components/load-more-button/index.js
  assets/js/base/components/order-select/index.js
  assets/js/base/components/order-select/style.scss
  assets/js/base/components/review-list-item/index.js
  assets/js/base/components/review-order-select/index.js
  assets/js/base/components/review-order-select/style.scss
  package-lock.json
Labels: status: ready to merge, type: refactor

#889 Remove RawHTML used for notice translations
  assets/js/blocks/reviews/edit-utils.js
Labels: skip-changelog, status: ready to merge, type: bug

#910 Exclude bundlesize config file from ZIP
  bin/build-plugin-zip.sh
  bin/wordpress-deploy.sh
Labels: skip-changelog, status: ready to merge, type: build

#908 Reviews blocks: Fix warnings with components state
  assets/js/base/hocs/with-reviews.js
Labels: skip-changelog, status: ready to merge, type: bug

#909 Show API errors in reviews editor block
  assets/js/base/hocs/test/with-reviews.js
  assets/js/base/hocs/with-reviews.js
  assets/js/blocks/reviews/editor-block.js
  assets/js/components/api-error-placeholder/index.js
  src/RestApi/Controllers/ProductReviews.php
Labels: skip-changelog, status: ready to merge, type: bug

#913 Update review block icons
  assets/js/blocks/reviews/all-reviews/edit.js
  assets/js/blocks/reviews/all-reviews/index.js
  assets/js/blocks/reviews/all-reviews/no-reviews-placeholder.js
  assets/js/components/icons/all-reviews.js
  assets/js/components/icons/index.js
  assets/js/components/icons/reviews-by-category.js
Labels: skip-changelog, status: ready to merge

#907 Cleanup withComponentId from base components
  assets/js/base/components/order-select/index.js
  assets/js/base/components/review-list/index.js
  assets/js/base/components/review-order-select/index.js
  assets/js/blocks/reviews/editor-block.js
  assets/js/blocks/reviews/frontend-block.js
Labels: skip-changelog, status: ready to merge, type: refactor

#914 Fix order by and load more buttons not hidden in frontend review blocks
  assets/js/blocks/reviews/frontend-block.js
Labels: skip-changelog, status: ready to merge, type: bug

#918 Fix shared settings overwriting block settings
  webpack.config.js
Labels: skip-changelog, status: needs review

#917 Fix best selling products block query
  src/BlockTypes/ProductBestSellers.php
Labels: cherry-pick 🍒, status: ready to merge

#916 Fix wcSettings conflicts with wc-admin
  assets/js/base/components/review-list/index.js
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-category/index.js
  assets/js/blocks/featured-product/block.js
  assets/js/blocks/featured-product/index.js
  assets/js/blocks/handpicked-products/block.js
  assets/js/blocks/handpicked-products/index.js
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-categories/get-categories.js
  assets/js/blocks/product-search/block.js
  assets/js/blocks/product-tag/block.js
  assets/js/blocks/product-tag/index.js
  assets/js/blocks/products-by-attribute/index.js
  assets/js/blocks/reviews/edit-utils.js
  assets/js/blocks/reviews/editor-block.js
  assets/js/blocks/reviews/frontend-block.js
  assets/js/blocks/reviews/utils.js
  assets/js/components/grid-layout-control/index.js
  assets/js/components/product-attribute-control/index.js
  assets/js/components/product-category-control/index.js
  assets/js/components/product-control/index.js
  assets/js/components/product-preview/index.js
  assets/js/components/product-preview/test/index.js
  assets/js/components/product-tag-control/index.js
  assets/js/components/utils/index.js
  assets/js/hocs/test/with-searched-products.js
  assets/js/hocs/with-searched-products.js
  assets/js/settings/blocks/endpoints.js
  assets/js/settings/blocks/index.js
  assets/js/settings/index.js
  assets/js/settings/shared/currency.js
  assets/js/settings/shared/index.js
  assets/js/utils/get-query.js
  assets/js/utils/get-shortcode.js
  assets/js/utils/shared-attributes.js
  src/Assets.php
  tests/js/jest.config.json
  webpack.config.js
Labels: status: ready to merge

#919 Fix color of All Reviews block icon
  assets/js/blocks/reviews/all-reviews/index.js
Labels: skip-changelog, status: ready to merge

#720 Rolling 2.4 release changelog
  composer.lock
  package-lock.json
  package.json
  readme.txt
  src/Package.php
  woocommerce-gutenberg-products-block.php
Labels: status: in progress

#930 Add reminder to update list of blocks on every release
  CONTRIBUTING.md
Labels: skip-changelog, status: needs review, type: build

#929 Add description to blocks added in 2.4
  readme.txt
Labels: cherry-pick 🍒, documentation, skip-changelog, status: needs review, status: ready to merge

#928 Add error states to all components/blocks which use HOCs
  assets/css/editor.scss
  assets/js/base/hocs/with-reviews.js
  assets/js/base/utils/errors.js
  assets/js/components/api-error-placeholder/error-message.js
  assets/js/components/api-error-placeholder/index.js
  assets/js/components/api-error-placeholder/style.scss
  assets/js/components/products-control/index.js
  assets/js/components/utils/index.js
  assets/js/hocs/with-category.js
  assets/js/hocs/with-product.js
  assets/js/hocs/with-searched-products.js
Labels: status: ready to merge, type: enhancement

#934 Always print shared settings
  src/Assets.php
Labels: cherry-pick 🍒, status: ready to merge, type: bug
