Repository woocommerce/woocommerce-blocks, pull requests merged in 2019-03, with the labels that each got.

#456 Try: Set up plugin to publish on npm
  assets/php/class-wgpb-block-featured-product.php
  assets/php/class-wgpb-block-library.php
  package-lock.json
  package.json
  woocommerce-gutenberg-products-block.php
Labels: Build, [Status] Ready to Merge

#472 Blocks: Add rating to grid previews
  assets/css/style.scss
  assets/js/blocks/handpicked-products/block.js
  assets/js/blocks/handpicked-products/index.js
  assets/js/blocks/product-best-sellers/block.js
  assets/js/blocks/product-best-sellers/index.js
  assets/js/blocks/product-category/block.js
  assets/js/blocks/product-category/index.js
  assets/js/blocks/product-new/block.js
  assets/js/blocks/product-new/index.js
  assets/js/blocks/product-on-sale/block.js
  assets/js/blocks/product-on-sale/index.js
  assets/js/blocks/product-top-rated/block.js
  assets/js/blocks/product-top-rated/index.js
  assets/js/blocks/products-by-attribute/block.js
  assets/js/blocks/products-by-attribute/index.js
  assets/js/components/grid-content-control/index.js
  assets/js/components/product-preview/index.js
  assets/js/components/product-preview/style.scss
  assets/js/utils/shared-attributes.js
Labels: Blocks, [Status] Ready to Merge

#458 Category block: select categories when none selected
  assets/js/blocks/product-category/block.js
Labels: Blocks, [Status] Ready to Merge

#477 Remove blocks API endpoints
  includes/class-wgpb-product-attribute-terms-controller.php
  includes/class-wgpb-product-attributes-controller.php
  includes/class-wgpb-product-categories-controller.php
  includes/class-wgpb-products-controller.php
  tests/api/products-attributes.php
  tests/api/products-categories.php
  tests/api/products-extra.php
  woocommerce-gutenberg-products-block.php
Labels: REST API, WC Core Merge, [Status] Ready to Merge

#478 Bump the version to 2.0.0-beta, update the changelog
  package-lock.json
  package.json
  readme.txt
  woocommerce-gutenberg-products-block.php
Labels: Build, [Status] Ready to Merge

#480 Fix PHP Notice: Check for the existence of `productId` before using it
  assets/php/class-wgpb-block-featured-product.php
Labels: [Status] Ready to Merge, [Type] Bug

#486 Build: Add translation conversion script
  .gitignore
  bin/generate-translation-json.js
  languages/woo-gutenberg-products-block-da_DK-15e4e3df51632e1ca1000ea405c14b95.json
  languages/woo-gutenberg-products-block-da_DK-2674aecf6bb0c5be4f2454ea842be5f6.json
  languages/woo-gutenberg-products-block-da_DK-3f1f6467892f2a342fddcfecdceeb2c3.json
  languages/woo-gutenberg-products-block-da_DK-6e3d95eaf70621f822b845d5bcb2b3cf.json
  languages/woo-gutenberg-products-block-da_DK-84d4253d132f6c5c53fe25d03f5e9200.json
  languages/woo-gutenberg-products-block-da_DK-91f7cd8fa1b168630fc2b3a54cbe410f.json
  languages/woo-gutenberg-products-block-da_DK-a4caf5c468bc583ff7fc9a943d3dc348.json
  languages/woo-gutenberg-products-block-da_DK-d748c5738d57b7518bef14f74456090e.json
  languages/woo-gutenberg-products-block-da_DK-f9f323a7db976a4eafb44c35cc6d5e32.json
  languages/woo-gutenberg-products-block-es_ES-15e4e3df51632e1ca1000ea405c14b95.json
  languages/woo-gutenberg-products-block-es_ES-2674aecf6bb0c5be4f2454ea842be5f6.json
  languages/woo-gutenberg-products-block-es_ES-3f1f6467892f2a342fddcfecdceeb2c3.json
  languages/woo-gutenberg-products-block-es_ES-6e3d95eaf70621f822b845d5bcb2b3cf.json
  languages/woo-gutenberg-products-block-es_ES-84d4253d132f6c5c53fe25d03f5e9200.json
  languages/woo-gutenberg-products-block-es_ES-91f7cd8fa1b168630fc2b3a54cbe410f.json
  languages/woo-gutenberg-products-block-es_ES-a4caf5c468bc583ff7fc9a943d3dc348.json
  languages/woo-gutenberg-products-block-es_ES-d748c5738d57b7518bef14f74456090e.json
  languages/woo-gutenberg-products-block-es_ES-f9f323a7db976a4eafb44c35cc6d5e32.json
  languages/woo-gutenberg-products-block-ru_RU-15e4e3df51632e1ca1000ea405c14b95.json
  languages/woo-gutenberg-products-block-ru_RU-2674aecf6bb0c5be4f2454ea842be5f6.json
  languages/woo-gutenberg-products-block-ru_RU-3f1f6467892f2a342fddcfecdceeb2c3.json
  languages/woo-gutenberg-products-block-ru_RU-6e3d95eaf70621f822b845d5bcb2b3cf.json
  languages/woo-gutenberg-products-block-ru_RU-84d4253d132f6c5c53fe25d03f5e9200.json
  languages/woo-gutenberg-products-block-ru_RU-91f7cd8fa1b168630fc2b3a54cbe410f.json
  languages/woo-gutenberg-products-block-ru_RU-a4caf5c468bc583ff7fc9a943d3dc348.json
  languages/woo-gutenberg-products-block-ru_RU-d748c5738d57b7518bef14f74456090e.json
  languages/woo-gutenberg-products-block-ru_RU-f9f323a7db976a4eafb44c35cc6d5e32.json
  package-lock.json
  package.json
Labels: Build, [Status] Ready to Merge, i18n

#481 Grid blocks: Use a different theme option name for block column/row values
  assets/php/class-wgpb-block-library.php
Labels: Blocks, Extensibility, [Status] Ready to Merge

#489 Update grid blocks preview to match width of products on the frontend
  assets/css/editor.scss
  assets/js/components/product-preview/index.js
  assets/js/components/product-preview/style.scss
  assets/js/components/product-preview/test/__snapshots__/index.js.snap
  assets/php/class-wgpb-block-library.php
  tests/js/setup-globals.js
Labels: Blocks, [Status] Ready to Merge

#494 Add pre-publishing script and bump version to 2.0.0-rc1
  .travis.yml
  package-lock.json
  package.json
  woocommerce-gutenberg-products-block.php
Labels: Build, [Status] Ready to Merge

#504 Add "contributor" docs for developer tools, release processes
  CONTRIBUTING.md
  README.md
Labels: Documentation, [Status] Ready to Merge

#502 Fix fatal with 1.x versions of the feature plugin
  assets/php/class-wgpb-block-library.php
  package-lock.json
  package.json
  woocommerce-gutenberg-products-block.php
Labels: WC Core Merge, [Status] Ready to Merge
