Repository woocommerce/woocommerce-blocks, pull requests merged in 2019-11, with the labels that each got.

#1115 Update `useQueryStateByKey` to return callback which wraps the dispatcher
  assets/js/base/hooks/test/use-query-state.js
  assets/js/base/hooks/use-query-state.js
Labels: status: ready to merge

#1116 Add additional data to new products store endpoint
  src/RestApi/StoreApi/Schemas/ProductSchema.php
  tests/php/RestApi/StoreApi/Controllers/Products.php
Labels: status: ready to merge, type: enhancement

#1119 Fix bug with ProductTitle component
  assets/js/atomic/components/product/title/index.js
Labels: type: bug

#1102 Followup: switch namespace on useStoreProducts hook.
  assets/js/atomic/components/product/button/index.js
  assets/js/base/hooks/use-store-products.js
  assets/js/data/collections/actions.js
Labels: status: ready to merge, type: enhancement

#1123 Add previews for the category list and product search
  assets/js/blocks/product-categories/index.js
  assets/js/blocks/product-search/index.js
Labels: skip-changelog, status: ready to merge

#1122 Add featured category block preview
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-category/example.js
  assets/js/blocks/featured-category/index.js
  assets/js/hocs/with-category.js
  assets/js/previews/categories.js
  assets/js/previews/index.js
Labels: skip-changelog, status: ready to merge

#1124 Fix incorrect parsing of routes from placeholder route strings.
  assets/js/data/schema/test/utils.js
  assets/js/data/schema/utils.js
Labels: status: ready to merge, type: bug

#1128 Move "prices" data from rest API to store API
  src/RestApi/Controllers/Products.php
  src/RestApi/StoreApi/README.md
  src/RestApi/StoreApi/Schemas/ProductSchema.php
  tests/php/RestApi/StoreApi/Controllers/Products.php
Labels: status: ready to merge

#1125 Fix price slider constraints
  assets/js/base/components/price-slider/index.js
  assets/js/base/hooks/index.js
  assets/js/base/hooks/test/use-previous.js
  assets/js/base/hooks/use-previous.js
  assets/js/blocks/price-filter/block.js
Labels: status: ready to merge

#1136 Use renderFrontend function to render the Price Filter block in the frontend
  assets/js/base/components/review-list-item/index.js
  assets/js/blocks/price-filter/frontend.js
  assets/js/data/collections/README.md
  assets/js/data/collections/selectors.js
Labels: skip-changelog, status: ready to merge

#1140 Rename useQueryState to useQueryStateByContext
  assets/js/base/hooks/test/use-query-state.js
  assets/js/base/hooks/use-query-state.js
  assets/js/blocks/price-filter/block.js
Labels: status: ready to merge, type: enhancement

#1142 Add anti yoda conditional eslint rule
  .eslintrc.js
  assets/js/atomic/components/product/rating/index.js
  assets/js/base/components/price-slider/utils.js
  assets/js/base/components/read-more/index.js
  assets/js/blocks/price-filter/edit.js
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/products/all-products/edit.js
  assets/js/blocks/reviews/editor-block.js
  assets/js/blocks/reviews/frontend-block.js
  assets/js/components/product-attribute-control/index.js
  assets/js/utils/get-query.js
  assets/js/utils/get-shortcode.js
Labels: status: ready to merge

#1144 All Products: avoid pagination disappearing when switching pages/changing sort value
  assets/js/base/hooks/use-store-products.js
Labels: status: ready to merge

#1127 Filter all products block by attribute
  assets/js/base/components/checkbox-list/index.js
  assets/js/base/components/checkbox-list/style.scss
  assets/js/base/hooks/use-collection-header.js
  assets/js/base/hooks/use-collection.js
  assets/js/base/hooks/use-query-state.js
  assets/js/blocks/attribute-filter/block.js
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/attribute-filter/editor.scss
  assets/js/blocks/attribute-filter/frontend.js
  assets/js/blocks/attribute-filter/index.js
  assets/js/blocks/attribute-filter/style.scss
  assets/js/blocks/price-filter/edit.js
  assets/js/blocks/products-by-attribute/block.js
  assets/js/components/README.md
  assets/js/components/product-attribute-term-control/index.js
  assets/js/components/product-attribute-term-control/style.scss
  assets/js/settings/blocks/constants.js
  assets/js/utils/attributes.js
  bin/webpack-helpers.js
  src/Assets.php
  src/BlockTypes/AttributeFilter.php
  src/Library.php
  src/RestApi.php
  src/RestApi/StoreApi/Controllers/ProductAttributeTerms.php
  src/RestApi/StoreApi/Controllers/ProductAttributes.php
  src/RestApi/StoreApi/Controllers/Products.php
  src/RestApi/StoreApi/README.md
  src/RestApi/StoreApi/Schemas/ProductAttributeSchema.php
  src/RestApi/StoreApi/Schemas/ProductSchema.php
  src/RestApi/StoreApi/Schemas/TermSchema.php
  src/RestApi/StoreApi/Utilities/ProductFiltering.php
  src/RestApi/StoreApi/Utilities/ProductQuery.php
  src/RestApi/StoreApi/Utilities/TermQuery.php
  tests/php/RestApi/StoreApi/Controllers/Products.php
  webpack.config.js
Labels: new block, status: ready to merge

#1145 Use placeholder when contraints are invalid
  assets/js/base/components/price-slider/index.js
  assets/js/base/components/price-slider/style.scss
Labels: skip-changelog, status: ready to merge

#1152 Move renderFrontend to internal dependencies
  assets/js/blocks/attribute-filter/frontend.js
Labels: status: needs review

#1149 Update WooCommerce compatibility version to 3.8.0
  woocommerce-gutenberg-products-block.php
Labels: status: ready to merge

#1154 Remove unnecessary package version reading of @wordpress/components
  src/Domain/Bootstrap.php
Labels: status: ready to merge, type: bug

#1151 Store API - Add tests for product attributes endpoints
  src/RestApi/StoreApi/Controllers/ProductAttributeTerms.php
  src/RestApi/StoreApi/Controllers/ProductAttributes.php
  src/RestApi/StoreApi/Schemas/TermSchema.php
  src/RestApi/StoreApi/Utilities/TermQuery.php
  tests/php/RestApi/StoreApi/Controllers/ProductAttributeTerms.php
  tests/php/RestApi/StoreApi/Controllers/ProductAttributes.php
Labels: status: ready to merge

#1157 Ensure frontend script assets are registered with the right suffix for the environment.
  bin/webpack-helpers.js
  src/Assets.php
Labels: status: ready to merge, type: bug

#1158 Update version script to account for changes in version setting on bootstrap
  bin/version-changes.sh
  woocommerce-gutenberg-products-block.php
Labels: status: ready to merge, type: build, type: enhancement

#1169 Add editable filter widget headings
  assets/js/atomic/blocks/product/title/index.js
  assets/js/blocks/attribute-filter/block.js
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/attribute-filter/frontend.js
  assets/js/blocks/attribute-filter/index.js
  assets/js/blocks/price-filter/block.js
  assets/js/blocks/price-filter/edit.js
  assets/js/blocks/price-filter/index.js
  assets/js/components/heading-toolbar/heading-level-icon.js
  assets/js/components/heading-toolbar/index.js
Labels: skip-changelog, status: ready to merge

#1167 Remove h1 from atomic title
  assets/js/atomic/blocks/product/title/index.js
  assets/js/components/heading-toolbar/index.js
Labels: accessibility, status: ready to merge

#1171 Set loading state when searching
  assets/js/hocs/with-searched-products.js
  src/Assets.php
Labels: status: ready to merge

#1174 Add context value validation for context apis that receive an object.
  assets/js/base/components/product-list-item/index.js
  assets/js/base/context/inner-block-configuration-context.js
  assets/js/base/context/inner-block-parent-name-context.js
  assets/js/base/context/product-layout-context.js
  assets/js/base/context/test/utils.js
  assets/js/base/context/utils.js
  assets/js/blocks/products/all-products/block.js
Labels: status: ready to merge, type: enhancement

#1173 Rename modelName to resourceName everywhere
  assets/js/base/hooks/use-collection-header.js
  assets/js/base/hooks/use-collection.js
  assets/js/data/collections/README.md
  assets/js/data/collections/actions.js
  assets/js/data/collections/reducers.js
  assets/js/data/collections/resolvers.js
  assets/js/data/collections/selectors.js
  assets/js/data/collections/test/reducers.js
  assets/js/data/collections/test/resolvers.js
  assets/js/data/collections/test/selectors.js
  assets/js/data/schema/README.md
  assets/js/data/schema/reducers.js
  assets/js/data/schema/selectors.js
  assets/js/data/schema/test/selectors.js
  assets/js/data/schema/test/utils.js
  assets/js/data/schema/utils.js
Labels: status: ready to merge

#1172 Add context for query state context string.
  assets/js/base/components/product-list/index.js
  assets/js/base/context/inner-block-configuration-context.js
  assets/js/base/context/product-layout-context.js
  assets/js/base/context/query-state-context.js
  assets/js/base/hooks/test/use-query-state.js
  assets/js/base/hooks/use-query-state.js
  assets/js/blocks/attribute-filter/block.js
  assets/js/blocks/price-filter/block.js
  tests/js/jest.config.json
Labels: status: ready to merge, type: enhancement

#1175 Fix Package::init breakage for including plugin in WC core
  bin/version-changes.sh
  src/Assets/AssetDataRegistry.php
  src/Package.php
  tests/php/Assets/AssetDataRegistry.php
  tests/php/Bootstrap/MainFile.php
  woocommerce-gutenberg-products-block.php
Labels: status: ready to merge, type: blocker, type: bug

#1160 Show notices when WP or PHP versions are not met
  bin/version-changes.sh
  woocommerce-gutenberg-products-block.php
Labels: status: ready to merge

#1166 Add block error boundary to JS-rendered blocks
  assets/img/block-error.svg
  assets/js/base/components/block-error-boundary/block-error.js
  assets/js/base/components/block-error-boundary/index.js
  assets/js/base/components/block-error-boundary/style.scss
  assets/js/blocks/attribute-filter/block.js
  assets/js/blocks/price-filter/block.js
  assets/js/blocks/products/all-products/block.js
  assets/js/blocks/reviews/editor-block.js
  assets/js/blocks/reviews/frontend-block.js
  assets/js/settings/blocks/constants.js
  src/Assets.php
Labels: status: ready to merge

#1118 Add grid block previews using an SVG image
  assets/img/grid.svg
  assets/js/base/hooks/use-store-products.js
  assets/js/blocks/handpicked-products/block.js
  assets/js/blocks/handpicked-products/index.js
  assets/js/blocks/product-best-sellers/block.js
  assets/js/blocks/product-best-sellers/index.js
  assets/js/blocks/product-category/block.js
  assets/js/blocks/product-category/index.js
  assets/js/blocks/product-new/block.js
  assets/js/blocks/product-new/index.js
  assets/js/blocks/product-on-sale/block.js
  assets/js/blocks/product-on-sale/index.js
  assets/js/blocks/product-tag/block.js
  assets/js/blocks/product-tag/index.js
  assets/js/blocks/product-top-rated/block.js
  assets/js/blocks/product-top-rated/index.js
  assets/js/blocks/products-by-attribute/block.js
  assets/js/blocks/products-by-attribute/index.js
  assets/js/blocks/products/all-products/block.js
  assets/js/blocks/products/all-products/index.js
  assets/js/blocks/products/attributes.js
  assets/js/previews/grid-block.js
  assets/js/previews/index.js
  assets/js/utils/shared-attributes.js
  src/BlockTypes/AbstractProductGrid.php
Labels: grid-blocks, status: ready to merge

#1181 Update minimum WooCommerce version to 3.7
  README.md
  readme.txt
  woocommerce-gutenberg-products-block.php
Labels: status: ready to merge

#1182 Enhance useCollection for conditionally returning previous results
  assets/js/base/hooks/test/use-collection.js
  assets/js/base/hooks/use-collection.js
Labels: status: ready to merge, type: enhancement

#1185 Add on_sale to Store API for it to work.
  assets/js/atomic/components/product/sale-badge/index.js
  assets/js/previews/products.js
  src/RestApi/StoreApi/Schemas/ProductSchema.php
  tests/php/RestApi/StoreApi/Controllers/Products.php
Labels: status: ready to merge

#1186 Don't use deprecated imports
  assets/js/atomic/blocks/product/image/index.js
  assets/js/atomic/blocks/product/title/index.js
  assets/js/blocks/active-filters/edit.js
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/price-filter/edit.js
  assets/js/blocks/products/all-products/edit.js
  assets/js/blocks/products/all-products/index.js
Labels: skip-changelog, status: ready to merge, type: bug

#1184 Filter block previews
  assets/js/blocks/attribute-filter/block.js
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/attribute-filter/index.js
  assets/js/blocks/price-filter/index.js
Labels: skip-changelog, status: ready to merge

#1193 Add All Blocks and filter blocks to readme.txt
  readme.txt
Labels: documentation, skip-changelog, status: ready to merge

#1183 Implement useProductLayoutContext for layout prefix in atomic blocks.
  assets/js/atomic/components/product/button/index.js
  assets/js/atomic/components/product/image/index.js
  assets/js/atomic/components/product/price/index.js
  assets/js/atomic/components/product/rating/index.js
  assets/js/atomic/components/product/sale-badge/index.js
  assets/js/atomic/components/product/summary/index.js
  assets/js/atomic/components/product/title/index.js
  assets/js/base/components/product-list-item/index.js
  assets/js/base/components/product-list/index.js
  assets/js/blocks/products/all-products/edit.js
Labels: status: ready to merge, type: enhancement

#1202 Fix paging issues when changing filters affecting number of results
  assets/js/base/components/product-list/index.js
Labels: status: ready to merge

#1205 Fix: Page selection will reset to 1 after deselecting filterable item, re-sorting products, and selecting new page.
  assets/js/base/components/product-list/index.js
Labels: skip-changelog, status: ready to merge, type: blocker, type: bug

#1196 All products - Use same query for headers as collection
  assets/js/base/hooks/use-store-products.js
Labels: skip-changelog, status: ready to merge, type: performance

#1177 Show number of reviews in each category in Reviews per Category block
  assets/js/blocks/reviews/reviews-by-category/edit.js
  assets/js/components/product-category-control/index.js
  assets/js/components/utils/index.js
  assets/js/hocs/test/with-categories.js
  assets/js/hocs/with-categories.js
  src/RestApi/Controllers/ProductCategories.php
Labels: rest-api, status: in progress, status: ready to merge, type: enhancement

#1178 Add no result templates
  assets/img/no-matching-products.svg
  assets/img/no-products.svg
  assets/js/base/components/product-list/index.js
  assets/js/base/components/product-list/no-matching-products.js
  assets/js/base/components/product-list/no-products.js
  assets/js/base/components/product-list/style.scss
Labels: status: ready to merge

#1192 Remove minConstraint and maxConstraint from price filter state
  assets/js/blocks/price-filter/block.js
Labels: skip-changelog, status: ready to merge, type: refactor

#1210 All Products block: fix variable products price format
  src/RestApi/StoreApi/Schemas/ProductSchema.php
Labels: status: ready to merge, type: bug

#1227 Honor CSS classes in editor
  assets/js/base/components/product-list/index.js
  assets/js/blocks/active-filters/edit.js
  assets/js/blocks/active-filters/index.js
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/attribute-filter/index.js
  assets/js/blocks/price-filter/edit.js
  assets/js/blocks/price-filter/index.js
Labels: status: ready to merge, type: bug

#1226 Move ErrorBoundary to renderFrontend() function
  assets/js/blocks/attribute-filter/block.js
  assets/js/blocks/price-filter/block.js
  assets/js/blocks/products/all-products/block.js
  assets/js/blocks/products/all-products/edit.js
  assets/js/blocks/reviews/editor-block.js
  assets/js/blocks/reviews/frontend-block.js
  assets/js/utils/render-frontend.js
  bin/webpack-helpers.js
Labels: skip-changelog, status: ready to merge, type: refactor

#1228 Price Slider -- Only do instant updates if filter button is disabled
  assets/js/blocks/price-filter/block.js
Labels: status: ready to merge

#1230 All Products title block - level -> headingLevel
  assets/js/atomic/blocks/product/title/index.js
Labels: status: ready to merge

#1231 Fix price slider layout in narrow columns
  assets/js/base/components/price-slider/style.scss
Labels: status: needs review, status: ready to merge, type: bug

#1239 Update `useQueryStateByContext` to remove need for context when setting values
  assets/js/base/hooks/test/use-query-state.js
  assets/js/base/hooks/use-query-state.js
Labels: skip-changelog, status: ready to merge

#1240 introduce block title component
  assets/js/blocks/active-filters/edit.js
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/price-filter/edit.js
  assets/js/components/README.md
  assets/js/components/block-title/index.js
Labels: components, skip-changelog, status: ready to merge

#1245 Fix mutation of default state
  assets/js/data/query-state/reducers.js
Labels: status: ready to merge, type: bug

#1206 Hydrate REST endpoint data in the stores
  assets/js/blocks/active-filters/frontend.js
  assets/js/blocks/attribute-filter/frontend.js
  assets/js/blocks/price-filter/frontend.js
  assets/js/blocks/products/all-products/frontend.js
  assets/js/hocs/index.js
  assets/js/hocs/with-rest-api-hydration.js
  assets/js/utils/render-frontend.js
  src/Assets.php
  src/RestApi.php
Labels: skip-changelog, status: ready to merge, type: performance

#1233 Prevent multiple collection data requests using debounce
  assets/js/base/hooks/index.js
  assets/js/base/hooks/use-collection-data.js
  assets/js/blocks/attribute-filter/block.js
  assets/js/blocks/price-filter/block.js
  src/RestApi/StoreApi/Controllers/ProductCollectionData.php
  src/RestApi/StoreApi/README.md
  src/RestApi/StoreApi/Utilities/ProductFiltering.php
  tests/php/RestApi/StoreApi/Controllers/ProductCollectionData.php
Labels: status: in progress, status: ready to merge, type: performance

#1256 Fix inconsistent heading editor styles for filter blocks
  assets/css/editor.scss
  assets/js/components/block-title/editor.scss
  assets/js/components/block-title/index.js
Labels: WP 5.3, status: ready to merge

#1259 Fix wrong proptypes definition in BlockTitle component
  assets/js/components/block-title/index.js
Labels: skip-changelog, status: ready to merge, type: bug

#1257 Fix color on pagination caused by Twenty Twenty
  assets/js/base/components/pagination/style.scss
Labels: WP 5.3, skip-changelog, status: ready to merge, type: bug

#1258 Fix bug with cart not updating
  assets/js/atomic/components/product/button/index.js
Labels: WP 5.3, type: bug

#1264 Filter by Attribute: Allow reselecting unselected attribute
  assets/js/blocks/attribute-filter/edit.js
Labels: status: ready to merge, type: bug

#1271 Use attribute label instead of slug in Filter by Attribute title
  assets/js/blocks/attribute-filter/edit.js
Labels: status: ready to merge, type: bug

#1274 Add source-maps for easier debugging development builds
  bin/webpack-helpers.js
  webpack.config.js
Labels: status: ready to merge, type: build, type: enhancement

#1244 Add getAdminLink() to shared settings export.
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/price-filter/edit.js
  assets/js/blocks/reviews/edit-utils.js
  assets/js/settings/shared/index.js
  package-lock.json
  package.json
Labels: status: ready to merge, type: enhancement

#1278 Fix Price Filter block if minPrice or maxPrice are null
  assets/js/blocks/price-filter/block.js
Labels: status: ready to merge, type: bug

#1284 Add instructions to update a single file to WordPress.org
  CONTRIBUTING.md
Labels: documentation, skip-changelog, status: ready to merge

#1282 Update 'Tested up to' version to WP 5.3
  readme.txt
Labels: skip-changelog, status: ready to merge
