Repository woocommerce/woocommerce-blocks, pull requests merged in 2020-03, with the labels that each got.

#1841 Fix Product Search block in last Gutenberg release
  assets/js/blocks/product-search/block.js
  assets/js/blocks/product-search/edit.js
  assets/js/blocks/product-search/index.js
Labels: scope: blocks, status: ready to merge, type: bug

#1824 Support updating quantity of cart items & sold_individually product option
  assets/js/base/components/quantity-selector/index.js
  assets/js/base/components/quantity-selector/stories/index.js
  assets/js/base/hooks/use-store-cart-item.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/data/cart/action-types.js
  assets/js/data/cart/actions.js
  assets/js/data/cart/reducers.js
  assets/js/type-defs/hooks.js
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
Labels: skip-changelog, status: ready to merge

#1846 Correctly handle store tax options in cart block
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/settings/blocks/constants.js
  src/Assets.php
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  src/RestApi/StoreApi/Schemas/ProductSchema.php
Labels: skip-changelog, status: ready to merge

#1843 Create Context Provider for Notices w/ Notices API
  assets/js/base/components/store-notices-container/index.js
  assets/js/base/components/store-notices-container/style.scss
  assets/js/base/context/store-notices-context.js
  assets/js/base/hooks/index.js
  assets/js/base/hooks/use-store-cart-coupons.js
  assets/js/base/hooks/use-store-notices.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/data/cart/actions.js
  assets/js/data/collections/resolvers.js
  assets/js/data/collections/test/resolvers.js
  assets/js/data/index.js
  package-lock.json
  package.json
  src/RestApi/StoreApi/Utilities/CartController.php
Labels: scope: components, skip-changelog, status: ready to merge

#1847 Create AddressForm component and change its fields dynamically based on country
  assets/js/base/components/address-form/index.js
  assets/js/base/components/country-input/country-input.js
  assets/js/base/components/input-row/index.js
  assets/js/base/components/input-row/style.scss
  assets/js/base/components/shipping-calculator/address.js
  assets/js/base/components/state-input/state-input.js
  assets/js/base/components/text-input/index.js
  assets/js/base/components/text-input/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/style.scss
  assets/js/settings/blocks/constants.js
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
Labels: scope: components, skip-changelog, status: ready to merge

#1852 Hide package name when there is only one
  assets/js/base/components/shipping-rates-control/packages.js
Labels: scope: components, status: ready to merge

#1844 Suggest using `git cherry-pick` instead of `hub am -3` in release docs
  docs/releases/readme.md
Labels: scope: documentation, status: ready to merge

#1854 Add extra block attribute escaping
  src/BlockTypes/FeaturedCategory.php
  src/BlockTypes/FeaturedProduct.php
Labels: scope: blocks, status: cherry-picked 🍒, status: ready to merge, type: bug

#1856 Fix failing travis e2e tests (environment caused)
  .travis.yml
  package-lock.json
Labels: scope: tests, status: ready to merge, type: bug, type: build

#1855 Cleanup draft orders
  src/Library.php
  tests/php/Library/DeleteDraftOrders.php
Labels: status: ready to merge

#1845 Add useStoreCartApiHydration HOC
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/hocs/index.js
  assets/js/hocs/with-store-cart-api-hydration.js
  src/BlockTypes/Cart.php
Labels: action: needs feedback, skip-changelog, status: ready to merge, type: performance

#1809 Add basic tests for Cart & Checkout blocks - snapshot, can only add one instance
  tests/e2e-tests/specs/backend/__snapshots__/cart.test.js.snap
  tests/e2e-tests/specs/backend/__snapshots__/checkout.test.js.snap
  tests/e2e-tests/specs/backend/cart.test.js
  tests/e2e-tests/specs/backend/checkout.test.js
Labels: scope: tests, skip-changelog, status: ready to merge

#1842 Do not allow focus on Country and State input hidden fields
  assets/js/base/components/country-input/country-input.js
  assets/js/base/components/state-input/state-input.js
Labels: scope: accessibility, scope: components, skip-changelog, status: ready to merge

#1857 Option to 'use shipping address for billing': add attribute and make it work in the frontend
  assets/js/base/components/address-form/index.js
  assets/js/base/components/checkout/form-step/index.js
  assets/js/base/components/checkout/form-step/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/editor.scss
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/blocks/cart-checkout/checkout/index.js
  assets/js/blocks/cart-checkout/checkout/style.scss
  assets/js/utils/render-frontend.js
Labels: scope: blocks, status: ready to merge

#1869 Fix broken e2e test for Checkout block
  package.json
  tests/e2e-tests/specs/backend/__snapshots__/checkout.test.js.snap
Labels: scope: tests, status: ready to merge

#1877 Fix undefined variable in cart items terms
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
Labels: status: ready to merge, type: bug

#1874 make product name display block to push stock badge on to its own line
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: skip-changelog, status: ready to merge

#1875 Tidy cart items mobile layout
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: status: ready to merge

#1868 Checkout form options to control field visibility
  assets/js/base/components/address-form/index.js
  assets/js/base/components/checkout/form-step/index.js
  assets/js/blocks/cart-checkout/checkout/attributes.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/editor.scss
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/blocks/cart-checkout/checkout/index.js
  assets/js/hocs/with-feedback-prompt/style.scss
  tests/e2e-tests/specs/backend/__snapshots__/checkout.test.js.snap
  tsconfig.json
Labels: scope: components, status: ready to merge

#1866 Add skeleton markup to the cart block
  assets/js/base/components/store-notices-container/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-table.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  src/BlockTypes/Cart.php
Labels: action: needs feedback, status: ready to merge

#1840 ensure cart totals update when items are removed or quantity changed
  assets/js/data/cart/actions.js
  src/RestApi/StoreApi/Controllers/Cart.php
  src/RestApi/StoreApi/README.md
  tests/php/RestApi/StoreApi/Controllers/Cart.php
Labels: scope: rest-api, skip-changelog, status: ready to merge

#1794 Update and select shipping rates dynamically
  assets/js/base/components/shipping-calculator/address.js
  assets/js/base/components/shipping-location/index.js
  assets/js/base/components/shipping-rates-control/index.js
  assets/js/base/components/shipping-rates-control/package.js
  assets/js/base/components/shipping-rates-control/packages.js
  assets/js/base/hooks/index.js
  assets/js/base/hooks/test/use-shipping-rates.js
  assets/js/base/hooks/use-collection.js
  assets/js/base/hooks/use-select-shipping-rate.js
  assets/js/base/hooks/use-shipping-rates.js
  assets/js/base/hooks/use-store-cart.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/data/cart/action-types.js
  assets/js/data/cart/actions.js
  assets/js/data/cart/reducers.js
  assets/js/data/cart/resolvers.js
  assets/js/data/cart/selectors.js
  assets/js/previews/shipping-rates.js
  assets/js/type-defs/cart.js
  assets/js/type-defs/hooks.js
  src/RestApi/StoreApi/Controllers/Cart.php
  src/RestApi/StoreApi/Controllers/CartShippingRates.php
  src/RestApi/StoreApi/Schemas/CartSchema.php
  src/RestApi/StoreApi/Schemas/CartShippingRateSchema.php
  src/RestApi/StoreApi/Utilities/CartController.php
  tests/php/RestApi/StoreApi/Controllers/Cart.php
  tests/php/RestApi/StoreApi/Controllers/CartShippingRates.php
Labels: scope: rest-api, skip-changelog, status: ready to merge

#1880 Add styling to checkboxes
  assets/js/base/components/checkbox-control/index.js
  assets/js/base/components/checkbox-control/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  bin/webpack-helpers.js
Labels: scope: components, skip-changelog, status: ready to merge

#1853 Cart and checkout error boundaries
  assets/js/base/components/block-error-boundary/block-error.js
  assets/js/base/components/block-error-boundary/index.js
  assets/js/base/components/block-error-boundary/style.scss
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/settings/blocks/constants.js
  assets/js/utils/render-frontend.js
  src/Assets.php
Labels: skip-changelog, status: ready to merge

#1778 Update `reserved stock` class to handle concurrent requests
  src/Library.php
  src/RestApi/StoreApi/Controllers/CartOrder.php
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  src/RestApi/StoreApi/Utilities/ReserveStock.php
  src/RestApi/StoreApi/Utilities/ReserveStockException.php
  tests/php/RestApi/StoreApi/Utilities/ReserveStock.php
  tests/php/RestApi/Utilities/ProductSummary.php
Labels: skip-changelog, status: ready to merge

#1881 Checkout Block: Add Legal links
  assets/css/editor.scss
  assets/js/base/components/checkout/index.js
  assets/js/base/components/checkout/policies/index.js
  assets/js/base/components/checkout/policies/style.scss
  assets/js/blocks/cart-checkout/checkout/attributes.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/reviews/edit-utils.js
  assets/js/blocks/reviews/editor.scss
  assets/js/settings/blocks/constants.js
  src/Assets.php
  tests/e2e-tests/specs/backend/__snapshots__/checkout.test.js.snap
Labels: scope: components, status: ready to merge

#1885 Split Full Cart sidebar totals into several components
  assets/js/base/components/totals/index.js
  assets/js/base/components/totals/subtotals-item/index.js
  assets/js/base/components/totals/totals-discount-item/index.js
  assets/js/base/components/totals/totals-fees-item/index.js
  assets/js/base/components/totals/totals-footer-item/index.js
  assets/js/base/components/totals/totals-footer-item/style.scss
  assets/js/base/components/totals/totals-shipping-item/index.js
  assets/js/base/components/totals/totals-taxes-item/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: scope: components, skip-changelog, status: ready to merge, type: refactor

#1891 Default to empty array if no states are found in state-input
  assets/js/base/components/state-input/state-input.js
Labels: scope: blocks, skip-changelog, status: ready to merge

#1893 Update plugin zip build script with additional options.
  bin/build-plugin-zip.sh
  docs/contributors/getting-started.md
  package.json
Labels: status: ready to merge, type: build, type: enhancement

#1864 improve responsiveness when setting cart item quantities
  assets/js/base/hooks/use-store-cart-item.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/data/cart/actions.js
  assets/js/type-defs/hooks.js
Labels: skip-changelog, status: ready to merge

#1867 Make Shipping packages collapsible in Cart page
  assets/js/base/components/radio-control/_mixin.scss
  assets/js/base/components/radio-control/editor.scss
  assets/js/base/components/radio-control/style.scss
  assets/js/base/components/shipping-rates-control/index.js
  assets/js/base/components/shipping-rates-control/package.js
  assets/js/base/components/shipping-rates-control/packages.js
  assets/js/base/components/shipping-rates-control/style.scss
  assets/js/base/components/totals/totals-coupon-code-input/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: scope: components, skip-changelog, status: ready to merge

#1900 Followup for useStoreCartItem work (change hook name and improve typedefs)
  assets/js/base/hooks/index.js
  assets/js/base/hooks/use-store-cart-item-quantity.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/settings/shared/settings-init.js
  assets/js/type-defs/cart.js
  assets/js/type-defs/hooks.js
  assets/js/type-defs/settings.js
Labels: status: ready to merge, type: enhancement

#1896 Add defaults for cart data totals object
  assets/js/data/cart/reducers.js
Labels: status: ready to merge, type: enhancement

#1892 Include address fields in the AddressForm component
  assets/js/base/components/address-form/country-address-fields.js
  assets/js/base/components/address-form/default-address-fields.js
  assets/js/base/components/address-form/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/settings/blocks/constants.js
  assets/js/type-defs/address-fields.js
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
  src/RestApi/StoreApi/Schemas/OrderSchema.php
Labels: skip-changelog, status: ready to merge

#1906 Add "or continue below" separator to checkout block
  assets/js/base/components/payment-methods/express-checkout.js
  assets/js/base/components/payment-methods/express-payment-methods.js
  assets/js/base/components/payment-methods/style.scss
Labels: skip-changelog, status: ready to merge

#1912 Bump up budget for checkout-frontend.js script
  package.json
Labels: type: build

#1898 mobile layout fixes for cart totals
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: skip-changelog, status: ready to merge

#1909 Refactor 'Hide shipping costs' Cart attribute logic
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/index.js
  tests/e2e-tests/specs/backend/__snapshots__/cart.test.js.snap
Labels: scope: blocks, skip-changelog, status: ready to merge

#1890 Link shipping form fields to shipping rates to load them.
  assets/js/base/components/shipping-rates-control/index.js
  assets/js/base/hooks/test/use-shipping-rates.js
  assets/js/base/hooks/use-shipping-rates.js
  assets/js/base/utils/address.js
  assets/js/base/utils/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
  package.json
Labels: scope: blocks, skip-changelog, status: ready to merge

#1918 Prevent wp.components loading on frontend
  assets/js/base/components/checkout/no-shipping/index.js
  assets/js/base/components/tabs/index.js
  assets/js/icons/icon/index.js
  assets/js/icons/library/bill.js
  assets/js/icons/library/card.js
  assets/js/icons/library/cart.js
  assets/js/icons/library/comment.js
  assets/js/icons/library/discussion.js
  assets/js/icons/library/exclamation.js
  assets/js/icons/library/external.js
  assets/js/icons/library/folder-starred.js
  assets/js/icons/library/folder.js
  assets/js/icons/library/grid.js
  assets/js/icons/library/image.js
  assets/js/icons/library/list.js
  assets/js/icons/library/more.js
  assets/js/icons/library/notes.js
  assets/js/icons/library/notice.js
  assets/js/icons/library/radio-selected.js
  assets/js/icons/library/radio-unselected.js
  assets/js/icons/library/review.js
  assets/js/icons/library/search.js
  assets/js/icons/library/server.js
  assets/js/icons/library/star.js
  assets/js/icons/library/stonks.js
  assets/js/icons/library/tag.js
  assets/js/icons/library/tags.js
  assets/js/icons/library/thumb-up.js
  assets/js/icons/library/toggle.js
  assets/js/icons/library/trash.js
  assets/js/icons/library/truck.js
  assets/js/icons/library/widgets.js
  assets/js/icons/library/woo.js
Labels: status: ready to merge

#1922 Update build-plugin-zip.sh intro text
  bin/build-plugin-zip.sh
Labels: skip-changelog, status: ready to merge, type: build

#1905 Disallow selecting quantity of stock past what's available.
  assets/js/base/hooks/use-store-cart-item-quantity.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/type-defs/cart.js
  assets/js/type-defs/hooks.js
  src/BlockTypes/Cart.php
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  tests/php/RestApi/StoreApi/Controllers/CartItems.php
Labels: status: ready to merge, type: enhancement

#1919 Default to the first state when selecting a country with states
  assets/js/base/components/state-input/state-input.js
Labels: skip-changelog, status: ready to merge

#1915 Add contexts for checkout
  assets/js/atomic/components/product/button/index.js
  assets/js/atomic/components/product/image/index.js
  assets/js/atomic/components/product/price/index.js
  assets/js/atomic/components/product/rating/index.js
  assets/js/atomic/components/product/sale-badge/index.js
  assets/js/atomic/components/product/summary/index.js
  assets/js/atomic/components/product/title/index.js
  assets/js/base/components/product-list-item/index.js
  assets/js/base/components/product-list/index.js
  assets/js/base/components/product-list/no-matching-products.js
  assets/js/base/components/product-list/no-products.js
  assets/js/base/components/store-notices-container/index.js
  assets/js/base/context/cart-checkout/checkout/actions.js
  assets/js/base/context/cart-checkout/checkout/constants.js
  assets/js/base/context/cart-checkout/checkout/event-emit.js
  assets/js/base/context/cart-checkout/checkout/index.js
  assets/js/base/context/cart-checkout/checkout/reducer.js
  assets/js/base/context/cart-checkout/event_emit/index.js
  assets/js/base/context/cart-checkout/event_emit/reducer.js
  assets/js/base/context/cart-checkout/index.js
  assets/js/base/context/cart-checkout/payment-methods/actions.js
  assets/js/base/context/cart-checkout/payment-methods/constants.js
  assets/js/base/context/cart-checkout/payment-methods/index.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/payment-methods/reducer.js
  assets/js/base/context/cart-checkout/shipping/constants.js
  assets/js/base/context/cart-checkout/shipping/event-emit.js
  assets/js/base/context/cart-checkout/shipping/index.js
  assets/js/base/context/cart-checkout/shipping/shipping-data-context.js
  assets/js/base/context/checkout-context.js
  assets/js/base/context/index.js
  assets/js/base/context/store-notices-context.js
  assets/js/base/hooks/checkout/use-checkout-events.js
  assets/js/base/hooks/checkout/use-checkout-notices.js
  assets/js/base/hooks/checkout/use-checkout-place-order-label.js
  assets/js/base/hooks/checkout/use-checkout-redirect-urls.js
  assets/js/base/hooks/payment-methods/use-active-payment-method.js
  assets/js/base/hooks/use-collection-data.js
  assets/js/base/hooks/use-query-state.js
  assets/js/base/hooks/use-store-notices.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/products/all-products/block.js
  assets/js/blocks/products/all-products/edit.js
  assets/js/type-defs/checkout.js
  assets/js/type-defs/contexts.js
  tsconfig.json
Labels: status: ready to merge, type: enhancement

#1923 Switch out usage from withComponentId to tree-shaken withInstanceId
  assets/js/base/components/product-list-item/index.js
  assets/js/base/components/radio-control/index.js
  assets/js/base/components/sort-select/index.js
  assets/js/base/components/tabs/index.js
  assets/js/base/components/text-input/index.js
  assets/js/base/components/totals/totals-coupon-code-input/index.js
  assets/js/base/hocs/test/with-component-id.js
  assets/js/base/hocs/with-component-id.js
  assets/js/components/view-switcher/index.js
Labels: status: ready to merge

#1927 Fix PropTypes warning for CartLineItem component
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/previews/cart.js
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
Labels: skip-changelog, status: ready to merge, type: bug

#1907 Handle Cart API errors
  assets/js/base/hooks/use-shipping-rates.js
  assets/js/base/hooks/use-store-cart-coupons.js
  assets/js/base/hooks/use-store-cart-item-quantity.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/hocs/with-store-cart-api-hydration.js
  assets/js/type-defs/hooks.js
Labels: scope: blocks, skip-changelog, status: ready to merge

#1928 Update payment registration config to include `edit` components
  assets/js/base/components/payment-methods/express-payment-methods.js
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/context/cart-checkout/checkout/index.js
  assets/js/blocks-registry/payment-methods/express-payment-method-config.js
  assets/js/blocks-registry/payment-methods/payment-method-config.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/payment-methods-demo/index.js
  assets/js/payment-methods-demo/payment-methods/index.js
  assets/js/type-defs/contexts.js
Labels: scope: blocks, skip-changelog, status: ready to merge, type: enhancement

#1925 Fix Cart block making 404 requests in the editor
  assets/js/base/hooks/use-store-cart-item-quantity.js
Labels: skip-changelog, status: ready to merge

#1917 Make checkout button sticky footer on mobile
  assets/js/blocks/cart-checkout/cart/full-cart/checkout-button/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: skip-changelog, status: ready to merge

#1929 Add new hooks related to payment methods and checkout and remove obsolete.
  assets/js/base/components/payment-methods/express-payment-methods.js
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/hooks/cart/index.js
  assets/js/base/hooks/cart/use-store-cart-coupons.js
  assets/js/base/hooks/cart/use-store-cart-item-quantity.js
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/base/hooks/checkout/index.js
  assets/js/base/hooks/checkout/use-checkout-data.js
  assets/js/base/hooks/checkout/use-checkout-events.js
  assets/js/base/hooks/checkout/use-checkout-notices.js
  assets/js/base/hooks/checkout/use-checkout-place-order-label.js
  assets/js/base/hooks/checkout/use-checkout-redirect-url.js
  assets/js/base/hooks/checkout/use-checkout-redirect-urls.js
  assets/js/base/hooks/checkout/use-checkout-submit.js
  assets/js/base/hooks/index.js
  assets/js/base/hooks/order/index.js
  assets/js/base/hooks/order/use-billing-data.js
  assets/js/base/hooks/order/use-store-order.js
  assets/js/base/hooks/payment-methods/constants.js
  assets/js/base/hooks/payment-methods/index.js
  assets/js/base/hooks/payment-methods/use-active-payment-method.js
  assets/js/base/hooks/payment-methods/use-payment-events.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/base/hooks/shipping/index.js
  assets/js/base/hooks/shipping/use-select-shipping-rate.js
  assets/js/base/hooks/shipping/use-shipping-rates.js
  assets/js/base/hooks/test/use-shipping-rates.js
  assets/js/type-defs/registered-payment-method-props.js
  tests/js/jest.config.json
Labels: scope: blocks, skip-changelog, status: ready to merge, type: enhancement

#1952 Fix invalid coupon thrown error and form not connected console warning.
  assets/js/base/components/totals/totals-coupon-code-input/index.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
Labels: status: ready to merge, type: bug

#1950 Update/extract prepare total items to utility
  assets/js/base/hooks/payment-methods/index.js
  assets/js/base/hooks/payment-methods/test/use-payment-method-interface.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/type-defs/cart.js
  assets/js/type-defs/registered-payment-method-props.js
Labels: skip-changelog, status: ready to merge, type: enhancement

#1937 Hydrate Checkout block with API data
  assets/js/blocks/cart-checkout/checkout/frontend.js
  src/BlockTypes/Checkout.php
Labels: scope: blocks, skip-changelog, status: ready to merge

#1921 Add Checkout block sidebar
  assets/js/base/components/sidebar-layout/index.js
  assets/js/base/components/sidebar-layout/main.js
  assets/js/base/components/sidebar-layout/sidebar-layout.js
  assets/js/base/components/sidebar-layout/sidebar.js
  assets/js/base/components/sidebar-layout/style.scss
  assets/js/base/components/totals/totals-coupon-code-input/index.js
  assets/js/base/components/totals/totals-shipping-item/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/blocks/cart-checkout/checkout/sidebar.js
  assets/js/data/cart/reducers.js
  assets/js/data/cart/selectors.js
  src/BlockTypes/Cart.php
Labels: scope: components, skip-changelog, status: ready to merge

#1945 Fix select rates when multiple packages exists
  assets/js/base/components/shipping-rates-control/packages.js
  assets/js/base/hooks/shipping/use-select-shipping-rate.js
Labels: status: ready to merge, type: bug

#1949 CSS editor fixes for Cart and Checkout blocks
  assets/js/base/components/button/style.scss
  assets/js/base/components/cart-checkout/button/index.js
  assets/js/base/components/cart-checkout/button/stories/index.js
  assets/js/base/components/cart-checkout/button/style.scss
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/country-input/country-input.js
  assets/js/base/components/shipping-calculator/address.js
  assets/js/base/components/state-input/state-input.js
  assets/js/base/components/totals/totals-coupon-code-input/index.js
  assets/js/base/components/totals/totals-coupon-code-input/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/checkout-button/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: skip-changelog, status: ready to merge

#1957 Break down Store API controllers into specific routes
  src/RestApi.php
  src/RestApi/StoreApi/Controllers/Cart.php
  src/RestApi/StoreApi/Controllers/CartCoupons.php
  src/RestApi/StoreApi/Controllers/CartItems.php
  src/RestApi/StoreApi/Controllers/CartShippingRates.php
  src/RestApi/StoreApi/Controllers/Customer.php
  src/RestApi/StoreApi/Controllers/ProductAttributeTerms.php
  src/RestApi/StoreApi/Controllers/ProductAttributes.php
  src/RestApi/StoreApi/Routes/AbstractRoute.php
  src/RestApi/StoreApi/Routes/Cart.php
  src/RestApi/StoreApi/Routes/CartApplyCoupon.php
  src/RestApi/StoreApi/Routes/CartCoupons.php
  src/RestApi/StoreApi/Routes/CartCouponsByCode.php
  src/RestApi/StoreApi/Routes/CartItems.php
  src/RestApi/StoreApi/Routes/CartItemsByKey.php
  src/RestApi/StoreApi/Routes/CartRemoveCoupon.php
  src/RestApi/StoreApi/Routes/CartRemoveItem.php
  src/RestApi/StoreApi/Routes/CartSelectShippingRate.php
  src/RestApi/StoreApi/Routes/CartUpdateItem.php
  src/RestApi/StoreApi/Routes/CartUpdateShipping.php
  src/RestApi/StoreApi/Routes/ProductAttributeTerms.php
  src/RestApi/StoreApi/Routes/ProductAttributes.php
  src/RestApi/StoreApi/Routes/ProductAttributesById.php
  src/RestApi/StoreApi/Routes/ProductCollectionData.php
  src/RestApi/StoreApi/Routes/Products.php
  src/RestApi/StoreApi/Routes/ProductsById.php
  src/RestApi/StoreApi/Routes/RouteException.php
  src/RestApi/StoreApi/Routes/RouteInterface.php
  src/RestApi/StoreApi/RoutesController.php
  src/RestApi/StoreApi/Schemas/AbstractSchema.php
  src/RestApi/StoreApi/Schemas/CartCouponSchema.php
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  src/RestApi/StoreApi/Schemas/CartSchema.php
  src/RestApi/StoreApi/Schemas/CartShippingRateSchema.php
  src/RestApi/StoreApi/Schemas/CustomerSchema.php
  src/RestApi/StoreApi/Schemas/OrderCouponSchema.php
  src/RestApi/StoreApi/Schemas/OrderItemSchema.php
  src/RestApi/StoreApi/Schemas/OrderSchema.php
  src/RestApi/StoreApi/Schemas/ProductAttributeSchema.php
  src/RestApi/StoreApi/Schemas/ProductCollectionDataSchema.php
  src/RestApi/StoreApi/Schemas/ProductSchema.php
  src/RestApi/StoreApi/Schemas/TermSchema.php
  src/RestApi/StoreApi/Utilities/CartController.php
  tests/php/RestApi/StoreApi/Controllers/CartOrder.php
  tests/php/RestApi/StoreApi/Controllers/CartShippingRates.php
  tests/php/RestApi/StoreApi/Controllers/Customer.php
  tests/php/RestApi/StoreApi/Routes/Cart.php
  tests/php/RestApi/StoreApi/Routes/CartCoupons.php
  tests/php/RestApi/StoreApi/Routes/CartItems.php
  tests/php/RestApi/StoreApi/Routes/ProductAttributeTerms.php
  tests/php/RestApi/StoreApi/Routes/ProductAttributes.php
  tests/php/RestApi/StoreApi/Routes/ProductCollectionData.php
  tests/php/RestApi/StoreApi/Routes/Products.php
Labels: scope: rest-api, skip-changelog, status: ready to merge, type: refactor

#1943 Refactor cart shipping settings and shipping calculator
  assets/js/base/components/shipping-calculator/address.js
  assets/js/base/components/shipping-calculator/index.js
  assets/js/base/components/shipping-rates-control/style.scss
  assets/js/base/components/totals/totals-item/index.js
  assets/js/base/components/totals/totals-shipping-item/has-shipping-rate.js
  assets/js/base/components/totals/totals-shipping-item/index.js
  assets/js/base/components/totals/totals-shipping-item/shipping-rate-selector.js
  assets/js/base/context/cart-checkout/payment-methods/actions.js
  assets/js/base/context/editor/index.js
  assets/js/base/context/index.js
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/base/hooks/shipping/use-shipping-rates.js
  assets/js/blocks/cart-checkout/cart/attributes.js
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-table.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/cart/index.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/hocs/with-feedback-prompt/index.js
  assets/js/previews/cart.js
  assets/js/type-defs/contexts.js
  tests/js/jest.config.json
Labels: skip-changelog, status: ready to merge

#1941 Fix IE11 issues with the Checkout block
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/tabs/style.scss
  assets/js/base/hooks/shipping/use-shipping-rates.js
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: skip-changelog, status: ready to merge, type: refactor

#1959 Add Order Summary card to Checkout sidebar
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/cart-checkout/product-image/index.js
  assets/js/base/components/cart-checkout/product-low-stock-badge/index.js
  assets/js/base/components/cart-checkout/product-low-stock-badge/style.scss
  assets/js/base/components/cart-checkout/product-metadata/index.js
  assets/js/base/components/cart-checkout/product-metadata/style.scss
  assets/js/base/components/cart-checkout/product-name/index.js
  assets/js/base/components/cart-checkout/product-name/style.scss
  assets/js/base/components/cart-checkout/product-price/index.js
  assets/js/base/components/cart-checkout/product-price/style.scss
  assets/js/base/components/cart-checkout/product-sale-badge/index.js
  assets/js/base/components/cart-checkout/product-sale-badge/style.scss
  assets/js/base/components/cart-checkout/product-variation-data/index.js
  assets/js/base/components/shipping-rates-control/style.scss
  assets/js/base/components/sidebar-layout/main.js
  assets/js/base/components/sidebar-layout/sidebar-layout.js
  assets/js/base/components/sidebar-layout/sidebar.js
  assets/js/base/components/sidebar-layout/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/blocks/cart-checkout/checkout/order-summary-item.js
  assets/js/blocks/cart-checkout/checkout/order-summary.js
  assets/js/blocks/cart-checkout/checkout/sidebar.js
  assets/js/blocks/cart-checkout/checkout/style.scss
  bin/webpack-helpers.js
  package.json
  src/Assets.php
Labels: status: ready to merge

#1960 Refactor Cart to include shippingAddress
  assets/js/base/components/address-form/index.js
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/base/hooks/shipping/index.js
  assets/js/base/hooks/shipping/use-shipping-address.js
  assets/js/base/hooks/shipping/use-shipping-rates.js
  assets/js/base/hooks/test/use-shipping-rates.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/data/cart/reducers.js
  assets/js/type-defs/cart.js
  assets/js/type-defs/hooks.js
  assets/js/type-defs/registered-payment-method-props.js
  package-lock.json
  src/RestApi/StoreApi/Schemas/CartSchema.php
  src/RestApi/StoreApi/Schemas/OrderSchema.php
  src/RestApi/StoreApi/Schemas/ShippingAddressSchema.php
Labels: scope: components, scope: rest-api, status: needs review, type: enhancement

#1956 Implement error handling for shipping rates and selected shipping rates.
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/base/hooks/index.js
  assets/js/base/hooks/shipping/constants.js
  assets/js/base/hooks/shipping/use-select-shipping-rate.js
  assets/js/base/hooks/shipping/use-shipping-address.js
  assets/js/base/hooks/use-collection.js
  assets/js/base/hooks/use-throw-error.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/data/cart/actions.js
Labels: status: ready to merge, type: enhancement

#1958 Update Cart Order and Checkout Routes
  src/RestApi/StoreApi/Controllers/CartOrder.php
  src/RestApi/StoreApi/Routes/CartCreateOrder.php
  src/RestApi/StoreApi/Routes/Checkout.php
  src/RestApi/StoreApi/RoutesController.php
  src/RestApi/StoreApi/Schemas/CartSchema.php
  src/RestApi/StoreApi/Schemas/CheckoutSchema.php
  tests/php/RestApi/StoreApi/Routes/CartCreateOrder.php
Labels: scope: rest-api, skip-changelog, status: ready to merge

#1968 Fix layout issues after merges
  assets/js/base/components/cart-checkout/button/style.scss
  assets/js/base/components/select/style.scss
  assets/js/base/components/totals/totals-shipping-item/index.js
  assets/js/base/components/totals/totals-shipping-item/shipping-rate-selector.js
  assets/js/base/components/totals/totals-shipping-item/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/sidebar.js
Labels: skip-changelog, status: ready to merge

#1977 disable coupon submit if the field is empty
  assets/js/base/components/totals/totals-coupon-code-input/index.js
Labels: skip-changelog, status: ready to merge, type: bug

#1926 Implement "return to cart" and "place order" buttons on checkout
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/cart-checkout/place-order-button/index.js
  assets/js/base/components/cart-checkout/return-to-cart-button/index.js
  assets/js/base/components/cart-checkout/return-to-cart-button/style.scss
  assets/js/base/components/checkout/form-step/style.scss
  assets/js/base/components/checkout/form/style.scss
  assets/js/base/components/checkout/policies/style.scss
  assets/js/base/components/payment-methods/style.scss
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/checkout/attributes.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/editor.scss
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/blocks/cart-checkout/checkout/style.scss
  assets/js/components/feedback-prompt/index.js
  assets/js/components/feedback-prompt/style.scss
  assets/js/hocs/with-feedback-prompt/index.js
  assets/js/icons/index.js
  assets/js/icons/library/arrow-back.js
  assets/js/settings/blocks/constants.js
  src/Assets.php
  src/BlockTypes/Checkout.php
  tests/e2e-tests/specs/backend/__snapshots__/checkout.test.js.snap
Labels: status: ready to merge

#1973 Add snackbar notices to notices system and implement for coupon ui/ux
  assets/js/base/components/store-notices-container/index.js
  assets/js/base/components/store-notices-container/snackbar-notices.js
  assets/js/base/components/store-notices-container/store-notices-container.js
  assets/js/base/components/store-notices-container/style.scss
  assets/js/base/context/store-notices-context.js
  assets/js/base/hooks/cart/use-store-cart-coupons.js
  assets/js/base/hooks/use-store-notices.js
  bin/webpack-helpers.js
  package.json
Labels: scope: components, status: ready to merge, type: enhancement

#1981 Configure link for the proceed to checkout button
  assets/js/blocks/cart-checkout/cart/attributes.js
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/cart/editor.scss
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/full-cart/checkout-button/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  src/BlockTypes/Cart.php
  tests/e2e-tests/specs/backend/__snapshots__/cart.test.js.snap
Labels: status: ready to merge

#1972 Add validation context provider and implement validation for shipping country and coupons.
  assets/js/base/components/address-form/index.js
  assets/js/base/components/country-input/country-input.js
  assets/js/base/components/country-input/stories/countries-filler.js
  assets/js/base/components/country-input/stories/index.js
  assets/js/base/components/select/index.js
  assets/js/base/components/select/style.scss
  assets/js/base/components/shipping-calculator/address.js
  assets/js/base/components/shipping-calculator/style.scss
  assets/js/base/components/text-input/index.js
  assets/js/base/components/text-input/style.scss
  assets/js/base/components/totals/totals-coupon-code-input/index.js
  assets/js/base/components/totals/totals-coupon-code-input/stories/index.js
  assets/js/base/components/validation/index.js
  assets/js/base/components/validation/style.scss
  assets/js/base/components/validation/validation-input-error.js
  assets/js/base/context/cart-checkout/index.js
  assets/js/base/context/cart-checkout/validation/index.js
  assets/js/base/hooks/cart/use-store-cart-coupons.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/style.scss
  assets/js/data/cart/actions.js
  assets/js/data/cart/reducers.js
  assets/js/settings/blocks/constants.js
  assets/js/type-defs/contexts.js
  package-lock.json
  package.json
  storybook/style.scss
  storybook/webpack.config.js
Labels: scope: components, status: ready to merge, type: enhancement

#1980 Use correct count from useStoreCart/API
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/previews/cart.js
Labels: skip-changelog, status: ready to merge

#1979 Add line pricing for cart items in the API
  assets/js/base/components/cart-checkout/product-sale-badge/index.js
  assets/js/base/hooks/cart/use-store-cart-item-quantity.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-table.js
  assets/js/blocks/cart-checkout/checkout/order-summary-item.js
  assets/js/previews/cart.js
  package-lock.json
  package.json
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  src/RestApi/StoreApi/Schemas/ProductSchema.php
Labels: skip-changelog, status: ready to merge

#1995 Add checkout skeleton whilst loading
  assets/js/base/components/cart-checkout/button/style.scss
  assets/js/base/components/payment-methods/style.scss
  assets/js/blocks/cart-checkout/checkout/index.js
  assets/js/blocks/cart-checkout/checkout/style.scss
  src/BlockTypes/Checkout.php
  tests/e2e-tests/specs/backend/__snapshots__/checkout.test.js.snap
Labels: skip-changelog, status: ready to merge

#1992 Add nonces to Store API endpoints
  assets/js/data/cart/actions.js
  assets/js/data/cart/index.js
  assets/js/data/collections/index.js
  assets/js/data/collections/resolvers.js
  assets/js/data/collections/test/resolvers.js
  assets/js/data/shared-controls.js
  assets/js/settings/blocks/index.js
  assets/js/settings/blocks/store-api-nonce.js
  src/Assets.php
  src/RestApi.php
  src/RestApi/StoreApi/Routes/AbstractRoute.php
  tests/php/RestApi/StoreApi/Routes/Cart.php
  tests/php/RestApi/StoreApi/Routes/CartCoupons.php
  tests/php/RestApi/StoreApi/Routes/CartCreateOrder.php
  tests/php/RestApi/StoreApi/Routes/CartItems.php
Labels: skip-changelog, status: ready to merge

#1996 Update empty states
  assets/js/base/components/product-list/no-matching-products.js
  assets/js/base/components/product-list/no-products.js
  assets/js/base/components/product-list/style.scss
  assets/js/blocks/cart-checkout/checkout/empty-cart.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: status: ready to merge

#2003 Convert emitters to promise
  assets/js/base/context/cart-checkout/checkout/event-emit.js
  assets/js/base/context/cart-checkout/checkout/index.js
  assets/js/base/context/cart-checkout/event-emit/emitters.js
  assets/js/base/context/cart-checkout/event-emit/index.js
  assets/js/base/context/cart-checkout/event-emit/reducer.js
  assets/js/base/context/cart-checkout/event-emit/test/emitters.js
  assets/js/base/context/cart-checkout/event_emit/index.js
  assets/js/base/context/cart-checkout/shipping/event-emit.js
Labels: status: ready to merge, type: enhancement

#2005 Add bundle size github workflow
  .github/workflows/bundle-size.yml
  .travis.yml
  package-lock.json
  package.json
Labels: skip-changelog, type: build

#2006 Build storybook to github pages on pushes to master
  .travis.yml
  package.json
Labels: scope: documentation, type: build

#2007 Add badges to readme
  README.md
Labels: scope: documentation

#1993 Add Checkout form validation
  assets/js/base/components/address-form/index.js
  assets/js/base/components/cart-checkout/place-order-button/index.js
  assets/js/base/components/country-input/country-input.js
  assets/js/base/components/select/index.js
  assets/js/base/components/select/validated.js
  assets/js/base/components/shipping-calculator/address.js
  assets/js/base/components/state-input/state-input.js
  assets/js/base/components/text-input/index.js
  assets/js/base/components/text-input/style.scss
  assets/js/base/components/text-input/validated.js
  assets/js/base/components/totals/totals-coupon-code-input/index.js
  assets/js/base/components/totals/totals-coupon-code-input/style.scss
  assets/js/base/components/validation/style.scss
  assets/js/base/components/validation/validation-input-error.js
  assets/js/base/context/cart-checkout/validation/index.js
  assets/js/base/hooks/cart/use-store-cart-coupons.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/type-defs/contexts.js
Labels: skip-changelog, status: ready to merge

#2010 Fix event-emitters not accounting for observers as Object type.
  assets/js/base/context/cart-checkout/event-emit/emitters.js
  assets/js/base/context/cart-checkout/event-emit/test/emitters.js
Labels: skip-changelog, status: ready to merge

#2002 Refactor useBillingData to useCheckoutContext and hooking it up to form
  assets/js/base/components/address-form/index.js
  assets/js/base/context/cart-checkout/checkout/actions.js
  assets/js/base/context/cart-checkout/checkout/constants.js
  assets/js/base/context/cart-checkout/checkout/index.js
  assets/js/base/context/cart-checkout/checkout/reducer.js
  assets/js/base/context/cart-checkout/payment-methods/actions.js
  assets/js/base/context/cart-checkout/payment-methods/constants.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/hooks/order/use-billing-data.js
  assets/js/blocks/cart-checkout/checkout/attributes.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/type-defs/cart.js
  assets/js/type-defs/checkout.js
  assets/js/type-defs/contexts.js
  assets/js/type-defs/hooks.js
  assets/js/type-defs/registered-payment-method-props.js
  src/BlockTypes/Checkout.php
  src/RestApi/StoreApi/Routes/CartUpdateShipping.php
  tests/e2e-tests/specs/backend/__snapshots__/checkout.test.js.snap
Labels: scope: blocks, status: ready to merge

#2009 Decode address entities in shipping calculator
  assets/js/base/components/address-form/default-address-fields.js
  assets/js/base/hooks/shipping/use-shipping-address.js
Labels: skip-changelog, status: ready to merge

#2019 Fix 'Show Sorting Dropdown' attribute ignored in All Products block
  assets/js/blocks/products/all-products/index.js
  tests/e2e-tests/specs/backend/__snapshots__/all-products.test.js.snap
Labels: scope: blocks, skip-changelog, status: ready to merge

#2024 Fix cartPageId being printed to screen
  assets/js/blocks/cart-checkout/checkout/edit.js
Labels: skip-changelog, status: ready to merge, type: bug

#1975 Record a tracks event when merchant toggles cart shipping calculator:
  assets/js/base/utils/index.js
  assets/js/base/utils/tracks.js
  assets/js/blocks/cart-checkout/cart/edit.js
Labels: status: ready to merge

#2029 Move payment method registration state to payment data context and add saved payment methods handling
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/components/payment-methods/saved-payment-method-options.js
  assets/js/base/context/cart-checkout/payment-methods/actions.js
  assets/js/base/context/cart-checkout/payment-methods/constants.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/payment-methods/reducer.js
  assets/js/base/context/cart-checkout/payment-methods/use-payment-method-registration.js
  assets/js/base/hooks/payment-methods/use-payment-methods.js
  assets/js/type-defs/contexts.js
  src/BlockTypes/Checkout.php
Labels: scope: components, skip-changelog, status: ready to merge, type: enhancement

#2028 Add URL to feedback prompt
  assets/js/components/feedback-prompt/index.js
Labels: scope: components, skip-changelog, status: ready to merge

#2001 Fix blocks not being added in WP <= 5.2
  assets/js/base/components/product-list-item/index.js
  assets/js/base/components/radio-control/index.js
  assets/js/base/components/select/validated.js
  assets/js/base/components/sort-select/index.js
  assets/js/base/components/tabs/index.js
  assets/js/base/components/text-input/validated.js
  assets/js/base/components/totals/totals-coupon-code-input/index.js
  assets/js/base/hocs/with-instance-id.js
  assets/js/components/view-switcher/index.js
  assets/js/filters/block-list-block.js
  assets/js/legacy/base/hocs/with-instance-id.js
  bin/fallback-module-directory-webpack-plugin.js
Labels: skip-changelog, status: ready to merge, type: bug

#2012 Reinitialise useSelectShippingRate when rates change.
  assets/js/base/hooks/shipping/use-select-shipping-rate.js
Labels: skip-changelog, status: ready to merge

#2026 fix rates not updating if you change coupon
  assets/js/base/components/shipping-rates-control/index.js
Labels: skip-changelog, status: ready to merge, type: bug

#2027 Add billing data context
  assets/js/base/context/cart-checkout/billing/constants.js
  assets/js/base/context/cart-checkout/billing/index.js
  assets/js/base/context/cart-checkout/checkout/actions.js
  assets/js/base/context/cart-checkout/checkout/constants.js
  assets/js/base/context/cart-checkout/checkout/index.js
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/base/context/cart-checkout/checkout/reducer.js
  assets/js/base/context/cart-checkout/index.js
  assets/js/base/context/cart-checkout/payment-methods/actions.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/payment-methods/reducer.js
  assets/js/base/context/cart-checkout/shipping/constants.js
  assets/js/base/context/cart-checkout/shipping/index.js
  assets/js/base/context/cart-checkout/shipping/shipping-data-context.js
  assets/js/base/hooks/order/index.js
  assets/js/base/hooks/order/use-billing-data.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/empty-cart/index.js
  assets/js/blocks/cart-checkout/checkout/example.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/blocks/cart-checkout/checkout/index.js
  assets/js/blocks/cart-checkout/checkout/sidebar/index.js
  assets/js/blocks/cart-checkout/checkout/sidebar/order-summary-item.js
  assets/js/blocks/cart-checkout/checkout/sidebar/order-summary.js
  assets/js/type-defs/billing.js
  assets/js/type-defs/cart.js
  assets/js/type-defs/checkout.js
  assets/js/type-defs/contexts.js
  assets/js/type-defs/hooks.js
  assets/js/type-defs/registered-payment-method-props.js
Labels: status: ready to merge

#2037 Shipping data context: replace address state with useShippingAddress()
  assets/js/base/context/cart-checkout/shipping/index.js
Labels: skip-changelog, status: ready to merge

#2011 Update checkout API endpoint to process orders
  src/Library.php
  src/Payments/PaymentContext.php
  src/Payments/PaymentResult.php
  src/RestApi/StoreApi/Routes/AbstractRoute.php
  src/RestApi/StoreApi/Routes/Checkout.php
  src/RestApi/StoreApi/Schemas/CheckoutSchema.php
Labels: scope: rest-api, status: ready to merge

#2042 Fix build issues for production builds
  assets/js/base/components/payment-methods/express-checkout.js
  assets/js/base/components/payment-methods/index.js
  assets/js/base/components/sidebar-layout/index.js
  assets/js/base/components/sidebar-layout/sidebar-layout.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
  assets/js/settings/blocks/index.js
  assets/js/settings/blocks/store-api-nonce.js
  bin/webpack-helpers.js
  package-lock.json
  package.json
Labels: status: ready to merge, type: bug, type: build

#1983 Implement Stripe CC and Stripe ApplePay payment methods
  assets/css/abstracts/_variables.scss
  assets/js/base/components/payment-methods/express-payment-methods.js
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/tabs/index.js
  assets/js/base/context/cart-checkout/checkout/index.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/validation/index.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/blocks-registry/payment-methods/express-payment-method-config.js
  assets/js/blocks-registry/payment-methods/payment-method-config.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/payment-method-extensions/express-payment/apple-pay/apple-pay-express.js
  assets/js/payment-method-extensions/express-payment/apple-pay/apple-pay-preview.js
  assets/js/payment-method-extensions/express-payment/apple-pay/constants.js
  assets/js/payment-method-extensions/express-payment/apple-pay/index.js
  assets/js/payment-method-extensions/express-payment/apple-pay/normalize.js
  assets/js/payment-method-extensions/express-payment/index.js
  assets/js/payment-method-extensions/index.js
  assets/js/payment-method-extensions/payment-methods/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/cc.js
  assets/js/payment-method-extensions/payment-methods/stripe/constants.js
  assets/js/payment-method-extensions/payment-methods/stripe/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-method.js
  assets/js/payment-method-extensions/stripe-utils/index.js
  assets/js/payment-method-extensions/stripe-utils/load-stripe.js
  assets/js/payment-method-extensions/stripe-utils/type-defs.js
  assets/js/payment-method-extensions/stripe-utils/utils.js
  assets/js/payment-methods-demo/express-payment/index.js
  assets/js/payment-methods-demo/express-payment/paypal.js
  assets/js/payment-methods-demo/index.js
  assets/js/payment-methods-demo/payment-methods/index.js
  assets/js/payment-methods-demo/payment-methods/paypal.js
  assets/js/type-defs/contexts.js
  assets/js/type-defs/registered-payment-method-props.js
  bin/webpack-helpers.js
  package-lock.json
  package.json
  src/Assets/Api.php
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
  src/Domain/Bootstrap.php
  src/PaymentMethodIntegrations/Stripe.php
  webpack.config.js
Labels: scope: components, scope: extensibility, status: ready to merge

#2041 Cart and Checkout accessibility fixes
  assets/js/base/components/cart-checkout/product-price/index.js
  assets/js/base/components/cart-checkout/product-price/style.scss
  assets/js/base/components/checkout/form-step/style.scss
  assets/js/base/components/shipping-rates-control/index.js
  assets/js/base/components/sidebar-layout/style.scss
  assets/js/base/components/text-input/validated.js
  assets/js/base/components/totals/totals-shipping-item/index.js
  assets/js/base/components/totals/totals-shipping-item/shipping-rate-selector.js
  assets/js/base/context/cart-checkout/validation/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/sidebar/order-summary-item.js
Labels: scope: accessibility, skip-changelog, status: ready to merge

#2034 Move some base components to subfolders
  assets/js/base/components/cart-checkout/address-form/country-address-fields.js
  assets/js/base/components/cart-checkout/address-form/default-address-fields.js
  assets/js/base/components/cart-checkout/address-form/index.js
  assets/js/base/components/cart-checkout/form-step/index.js
  assets/js/base/components/cart-checkout/form-step/style.scss
  assets/js/base/components/cart-checkout/form/index.js
  assets/js/base/components/cart-checkout/form/style.scss
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/cart-checkout/no-shipping/index.js
  assets/js/base/components/cart-checkout/no-shipping/style.scss
  assets/js/base/components/cart-checkout/policies/index.js
  assets/js/base/components/cart-checkout/policies/style.scss
  assets/js/base/components/cart-checkout/shipping-calculator/address.js
  assets/js/base/components/cart-checkout/shipping-calculator/index.js
  assets/js/base/components/cart-checkout/shipping-calculator/style.scss
  assets/js/base/components/cart-checkout/shipping-location/index.js
  assets/js/base/components/cart-checkout/shipping-rates-control/index.js
  assets/js/base/components/cart-checkout/shipping-rates-control/package-options.js
  assets/js/base/components/cart-checkout/shipping-rates-control/package.js
  assets/js/base/components/cart-checkout/shipping-rates-control/packages.js
  assets/js/base/components/cart-checkout/shipping-rates-control/style.scss
  assets/js/base/components/cart-checkout/totals/index.js
  assets/js/base/components/cart-checkout/totals/subtotals-item/index.js
  assets/js/base/components/cart-checkout/totals/totals-coupon-code-input/index.js
  assets/js/base/components/cart-checkout/totals/totals-coupon-code-input/stories/index.js
  assets/js/base/components/cart-checkout/totals/totals-coupon-code-input/style.scss
  assets/js/base/components/cart-checkout/totals/totals-discount-item/index.js
  assets/js/base/components/cart-checkout/totals/totals-fees-item/index.js
  assets/js/base/components/cart-checkout/totals/totals-footer-item/index.js
  assets/js/base/components/cart-checkout/totals/totals-footer-item/style.scss
  assets/js/base/components/cart-checkout/totals/totals-item/index.js
  assets/js/base/components/cart-checkout/totals/totals-item/style.scss
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/has-shipping-rate.js
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/index.js
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/shipping-rate-selector.js
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/style.scss
  assets/js/base/components/cart-checkout/totals/totals-taxes-item/index.js
  assets/js/base/components/checkout/index.js
  assets/js/base/components/reviews/index.js
  assets/js/base/components/reviews/review-list-item/index.js
  assets/js/base/components/reviews/review-list-item/style.scss
  assets/js/base/components/reviews/review-list/index.js
  assets/js/base/components/reviews/review-list/style.scss
  assets/js/base/components/reviews/review-sort-select/index.js
  assets/js/base/components/reviews/review-sort-select/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/sidebar/index.js
  assets/js/blocks/reviews/editor-block.js
  assets/js/blocks/reviews/frontend-block.js
Labels: skip-changelog, status: ready to merge

#2013 Add tests to some cart and checkout hooks
  assets/js/base/hooks/cart/test/use-store-cart-item-quantity.js
  assets/js/base/hooks/cart/test/use-store-cart.js
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/base/hooks/checkout/test/use-checkout-redirect-url.js
  assets/js/base/hooks/checkout/test/use-checkout-submit.js
  assets/js/hocs/test/with-attributes.js
Labels: scope: tests, skip-changelog, status: ready to merge

#2051 Add storybook info to dev docs
  docs/contributors/storybook.md
  docs/readme.md
Labels: scope: documentation, status: ready to merge

#2038 Ensure woocommerceanalytics checkout event fires for checkout block
  src/BlockTypes/Checkout.php
Labels: skip-changelog, status: ready to merge

#2000 Load product grid styles in WP <=5.2
  bin/webpack-helpers.js
  webpack.config.js
Labels: status: ready to merge, type: bug, type: build

#2004 [Experiment] Add container to run php unit tests in docker
  .env
  docker-compose.yml
  package.json
  tests/bin/Dockerfile
  tests/bin/docker-entrypoint.sh
  tests/bin/install-wp-tests.sh
Labels: status: ready to merge

#2069 Add checkout error state
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/checkout-order-error/index.js
  assets/js/blocks/cart-checkout/checkout/style.scss
  assets/js/icons/index.js
  assets/js/icons/library/remove-cart.js
  src/RestApi/StoreApi/Routes/AbstractRoute.php
  src/RestApi/StoreApi/Routes/Checkout.php
  src/RestApi/StoreApi/Utilities/ReserveStock.php
  src/RestApi/StoreApi/Utilities/ReserveStockException.php
Labels: status: ready to merge

#2072 add extra checks to checkout/cart/order APIs to avoid editor errors
  src/BlockTypes/Checkout.php
Labels: skip-changelog, status: ready to merge

#2075 Make sure payment method assets are loaded in block editor
  src/PaymentMethodIntegrations/Stripe.php
Labels: skip-changelog, status: ready to merge, type: bug

#2076 Implement mechanism for reliably passing through server data in editor context.
  src/BlockTypes/AbstractBlock.php
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
Labels: skip-changelog, status: ready to merge, type: bug

#2078 Fix minor Stripe payment method issues
  assets/js/payment-method-extensions/payment-methods/stripe/payment-method.js
Labels: skip-changelog, status: ready to merge

#2070 Finish wiring up shipping data context provider and add disabled state to checkout submit button
  assets/js/base/components/cart-checkout/place-order-button/index.js
  assets/js/base/context/cart-checkout/shipping/index.js
  assets/js/base/hooks/shipping/use-select-shipping-rate.js
  assets/js/data/cart/action-types.js
  assets/js/data/cart/actions.js
  assets/js/data/cart/reducers.js
  assets/js/data/cart/selectors.js
Labels: scope: components, skip-changelog, status: ready to merge, type: enhancement

#2080 Parse error response before rejecting
  assets/js/base/hooks/cart/use-store-cart-coupons.js
  assets/js/data/shared-controls.js
  assets/js/type-defs/hooks.js
Labels: status: ready to merge

#2082 Refactor to simplify checkout context error dispatcher.
  assets/js/base/context/cart-checkout/checkout/actions.js
  assets/js/base/context/cart-checkout/checkout/index.js
  assets/js/base/context/cart-checkout/shipping/index.js
  assets/js/type-defs/checkout.js
Labels: skip-changelog, status: ready to merge, type: refactor
