Repository woocommerce/woocommerce-blocks, pull requests merged in 2020-12, with the labels that each got.

#3473 Create IE11 SCSS mixin
  assets/css/abstracts/_mixins.scss
  assets/js/base/components/checkbox-control/style.scss
  assets/js/base/components/price-slider/style.scss
Labels: category: styles, skip-changelog, status: ready to merge

#3472 Fix notice close button color in Twenty Twenty One dark mode
  assets/js/base/components/store-notices-container/style.scss
Labels: category: styles, status: ready to merge

#3454 refactor and reorder checkout processing
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  src/StoreApi/Routes/AbstractRoute.php
  src/StoreApi/Routes/Checkout.php
  src/StoreApi/Schemas/CheckoutSchema.php
Labels: category: rest-api, status: ready to merge, ◼️ block: checkout

#3429 Handle change to logged-in status in checkout API AJAX requests
  assets/js/base/context/cart-checkout/checkout-state/actions.js
  assets/js/base/context/cart-checkout/checkout-state/constants.js
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/context/cart-checkout/checkout-state/reducer.js
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/type-defs/checkout.js
  src/StoreApi/Routes/Checkout.php
Labels: status: ready to merge

#3468 Drop stock reservation when removing item from cart via the Store API
  src/StoreApi/Routes/AbstractCartRoute.php
  src/StoreApi/Routes/CartRemoveItem.php
  src/StoreApi/Routes/Checkout.php
  src/StoreApi/Schemas/CartItemSchema.php
  src/StoreApi/Utilities/CartController.php
  src/StoreApi/Utilities/ReserveStock.php
  src/StoreApi/Utilities/ReserveStockException.php
  tests/php/StoreApi/Utilities/ReserveStock.php
Labels: status: ready to merge

#3457 Update @wordpress/components to v. 11.1.1 and @wordpress/base-styles to v. 3.2.0
  assets/css/abstracts/_colors.scss
  assets/css/abstracts/_variables.scss
  assets/js/atomic/blocks/product-elements/add-to-cart/frontend.js
  assets/js/atomic/blocks/product-elements/image/frontend.js
  assets/js/atomic/blocks/product-elements/title/frontend.js
  assets/js/base/components/chip/test/__snapshots__/index.js.snap
  assets/js/base/components/payment-methods/test/payment-methods.js
  assets/js/base/components/select/index.js
  bin/webpack-helpers.js
  package-lock.json
  package.json
Labels: skip-changelog, status: ready to merge, type: wp dependency

#3488 CartItems must extend AbastractCartRoute otherwise the cart is not loaded from the session
  src/StoreApi/Routes/CartItems.php
Labels: category: rest-api, type: bug

#3503 Add Formatter Classes to the Store API for Extensions to Consume
  src/Domain/Bootstrap.php
  src/Domain/Services/ExtendRestApi.php
  src/StoreApi/Formatters.php
  src/StoreApi/Formatters/CurrencyFormatter.php
  src/StoreApi/Formatters/DefaultFormatter.php
  src/StoreApi/Formatters/FormatterInterface.php
  src/StoreApi/Formatters/HtmlFormatter.php
  src/StoreApi/Formatters/MoneyFormatter.php
  src/StoreApi/Schemas/AbstractSchema.php
  src/StoreApi/Schemas/CartCouponSchema.php
  src/StoreApi/Schemas/CartItemSchema.php
  src/StoreApi/Schemas/CartSchema.php
  src/StoreApi/Schemas/CartShippingRateSchema.php
  src/StoreApi/Schemas/OrderCouponSchema.php
  src/StoreApi/Schemas/ProductCollectionDataSchema.php
  src/StoreApi/Schemas/ProductSchema.php
  tests/php/StoreApi/Formatters/TestCurrencyFormatter.php
  tests/php/StoreApi/Formatters/TestFormatters.php
  tests/php/StoreApi/Formatters/TestHtmlFormatter.php
  tests/php/StoreApi/Formatters/TestMoneyFormatter.php
  tests/php/StoreApi/Routes/Cart.php
  tests/php/StoreApi/Routes/CartCoupons.php
  tests/php/StoreApi/Routes/CartItems.php
  tests/php/StoreApi/Routes/ProductAttributeTerms.php
  tests/php/StoreApi/Routes/ProductAttributes.php
  tests/php/StoreApi/Routes/ProductCollectionData.php
  tests/php/StoreApi/Routes/Products.php
Labels: category: rest-api, status: ready to merge

#3502 Fix:3501 Omit keys in `customerPaymentMethods` that have an empty list as a value.
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
Labels: skip-changelog, status: ready to merge

#3498 Introduce pluginArea in Cart and Checkout
  assets/js/base/components/block-error-boundary/index.js
  assets/js/base/context/cart-checkout/checkout/index.js
  package-lock.json
  package.json
Labels: category: extensibility, skip-changelog, status: ready to merge, ◼️ block: cart, ◼️ block: checkout

#3508 Add __experimental_woocommerce_blocks_checkout_order_processed to the feature flags page.
  docs/blocks/feature-flags-and-experimental-interfaces.md
Labels: skip-changelog, status: needs review, type: documentation

#3520 Rename Cart & Checkout totals components
  assets/js/base/components/cart-checkout/totals/coupon/index.js
  assets/js/base/components/cart-checkout/totals/coupon/stories/index.js
  assets/js/base/components/cart-checkout/totals/coupon/style.scss
  assets/js/base/components/cart-checkout/totals/discount/index.js
  assets/js/base/components/cart-checkout/totals/discount/style.scss
  assets/js/base/components/cart-checkout/totals/fees/index.js
  assets/js/base/components/cart-checkout/totals/footer-item/index.js
  assets/js/base/components/cart-checkout/totals/footer-item/style.scss
  assets/js/base/components/cart-checkout/totals/index.js
  assets/js/base/components/cart-checkout/totals/item/index.js
  assets/js/base/components/cart-checkout/totals/item/style.scss
  assets/js/base/components/cart-checkout/totals/shipping/has-shipping-rate.js
  assets/js/base/components/cart-checkout/totals/shipping/index.js
  assets/js/base/components/cart-checkout/totals/shipping/shipping-rate-selector.js
  assets/js/base/components/cart-checkout/totals/shipping/style.scss
  assets/js/base/components/cart-checkout/totals/subtotal/index.js
  assets/js/base/components/cart-checkout/totals/taxes/index.js
  assets/js/base/components/cart-checkout/totals/taxes/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/sidebar/index.js
Labels: category: refactor, status: ready to merge, ◼️ block: cart, ◼️ block: checkout

#3524 Update Release Template and Docs
  .github/patch-initial-checklist.md
  .github/release-initial-checklist.md
  README.md
  docs/readme.md
  docs/releases/handling-releases.md
  docs/releases/readme.md
  docs/releases/wordpress-update-testing-checklist.md
Labels: status: ready to merge

#3522 Add missing experimental functions to the feature flags page
  assets/js/data/collections/actions.js
  docs/blocks/feature-flags-and-experimental-interfaces.md
Labels: skip-changelog, status: ready to merge, type: documentation

#3535 Update WP versions used in Travis e2e tests
  .travis.yml
  tests/e2e/specs/backend/all-products.test.js
  tests/e2e/specs/backend/cart.test.js
  tests/e2e/specs/backend/checkout.test.js
  tests/e2e/specs/backend/single-product.test.js
Labels: skip-changelog, status: ready to merge

#3030 Add storybook demo for CheckboxControl
  assets/js/base/components/checkbox-control/stories/index.js
Labels: status: ready to merge, type: build, type: cooldown

#3540 Add Close stale issues workflow
  .github/workflows/close-stale-issues.yml
Labels: skip-changelog, status: ready to merge

#3537 Update minimum required WP version to 5.4
  README.md
  assets/js/filters/block-list-block.js
  docs/testing/cart-checkout/cross-browser.md
  readme.txt
  src/Library.php
  woocommerce-gutenberg-products-block.php
Labels: status: ready to merge

#3533 Add stories to Cart & Checkout totals components
  assets/js/base/components/cart-checkout/totals/coupon/stories/index.js
  assets/js/base/components/cart-checkout/totals/discount/stories/index.js
  assets/js/base/components/cart-checkout/totals/fees/stories/index.js
  assets/js/base/components/cart-checkout/totals/footer-item/stories/index.js
  assets/js/base/components/cart-checkout/totals/item/stories/index.js
  assets/js/base/components/cart-checkout/totals/shipping/stories/index.js
  assets/js/base/components/cart-checkout/totals/subtotal/stories/index.js
  assets/js/base/components/cart-checkout/totals/taxes/stories/index.js
  assets/js/base/components/product-price/stories/index.js
  storybook/__mocks__/woocommerce-base-hooks.js
  storybook/__mocks__/woocommerce-block-settings.js
  storybook/knobs/currency-knob.js
  storybook/knobs/index.js
  storybook/webpack.config.js
  tsconfig.json
Labels: category: components, skip-changelog, status: ready to merge

#3536 Switch to Fragment Short Syntax (`<>`)
  .eslintrc.js
  assets/js/base/components/block-error-boundary/index.js
  assets/js/base/components/checkbox-list/index.js
  assets/js/base/components/price-slider/index.js
  assets/js/base/hocs/with-scroll-to-top/index.js
  assets/js/blocks/active-filters/block.js
  assets/js/blocks/attribute-filter/block.js
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/attribute-filter/label.js
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-product/block.js
  assets/js/blocks/handpicked-products/block.js
  assets/js/blocks/price-filter/block.js
  assets/js/blocks/price-filter/edit.js
  assets/js/blocks/product-best-sellers/block.js
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-category/block.js
  assets/js/blocks/product-new/block.js
  assets/js/blocks/product-on-sale/block.js
  assets/js/blocks/product-tag/block.js
  assets/js/blocks/product-top-rated/block.js
  assets/js/blocks/products-by-attribute/block.js
  assets/js/blocks/reviews/all-reviews/edit.js
  assets/js/blocks/reviews/frontend-block.js
  assets/js/blocks/reviews/reviews-by-category/edit.js
  assets/js/blocks/reviews/reviews-by-product/edit.js
  assets/js/editor-components/error-placeholder/index.js
  assets/js/editor-components/grid-content-control/index.js
  assets/js/editor-components/grid-layout-control/index.js
  assets/js/editor-components/product-attribute-term-control/index.js
  assets/js/editor-components/product-category-control/index.js
  assets/js/editor-components/product-tag-control/index.js
  assets/js/editor-components/view-switcher/index.js
Labels: status: ready to merge

#3541 Update usage of legacy packages (inc. ServerSideRender)
  assets/js/blocks/handpicked-products/block.js
  assets/js/blocks/product-best-sellers/block.js
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-category/block.js
  assets/js/blocks/product-new/block.js
  assets/js/blocks/product-on-sale/block.js
  assets/js/blocks/product-tag/block.js
  assets/js/blocks/product-top-rated/block.js
  assets/js/blocks/products-by-attribute/block.js
  bin/webpack-helpers.js
  package-lock.json
  package.json
Labels: status: ready to merge

#3550 GitHub Stale Action: Tweak message for stale activity and bump close boundary
  .github/workflows/close-stale-issues.yml
Labels: status: ready to merge, type: build, type: cooldown, type: enhancement

#3548 Rename version compare functions to isWpVersion and isWcVersion and add docblocks
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/settings/shared/index.js
  assets/js/settings/shared/test/compare-with-wp-version.js
Labels: skip-changelog, status: ready to merge, type: documentation

#3554 Fix select inputs when dark mode is enabled in Twenty Twenty-One
  assets/js/base/components/select/style.scss
Labels: category: accessibility, category: components, category: styles, status: ready to merge, type: bug, ◼️ block: checkout

#3552 Fix Address Validation in the Store API and client
  assets/js/base/components/cart-checkout/address-form/index.js
  assets/js/base/components/state-input/state-input.js
  assets/js/base/components/text-input/debounced-validated.js
  assets/js/base/components/text-input/index.js
  assets/js/base/components/text-input/validated.js
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/base/hooks/customer/use-customer-data.js
  assets/js/base/utils/address.js
  assets/js/base/utils/errors.js
  assets/js/blocks/cart-checkout/checkout/form/contact-fields-step.js
  assets/js/blocks/cart-checkout/checkout/form/phone-number/index.js
  src/StoreApi/Routes/CartUpdateCustomer.php
  src/StoreApi/Routes/Checkout.php
  src/StoreApi/Schemas/AbstractAddressSchema.php
  src/StoreApi/Schemas/BillingAddressSchema.php
  src/StoreApi/Schemas/CheckoutSchema.php
  src/StoreApi/Schemas/ShippingAddressSchema.php
  src/StoreApi/Utilities/OrderController.php
  tests/php/StoreApi/Routes/Cart.php
Labels: category: rest-api, status: ready to merge, type: cooldown

#3557 add fallback screen reader styles
  assets/css/abstracts/_mixins.scss
  assets/css/style.scss
Labels: status: ready to merge

#3551 Remove customer saved payment methods from context if they are not enabled.
  assets/js/base/components/payment-methods/saved-payment-method-options.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
Labels: category: blocks, category: refactor, skip-changelog, status: ready to merge

#3547 Replace IconButton component with Button
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-product/block.js
  assets/js/blocks/products/all-products/edit.js
  assets/js/blocks/products/all-products/editor.scss
  assets/js/blocks/products/edit.js
Labels: category: components, status: ready to merge, ◼️ block: all products

#3521 Fix Fees not visible in Cart & Checkout blocks when order doesn't need shipping
  assets/js/base/components/cart-checkout/totals/fees/index.js
Labels: status: needs review, type: bug, ◼️ block: cart, ◼️ block: checkout

#3553 Fix product list images skewed in Widgets editor
  assets/css/style.scss
Labels: category: styles, status: ready to merge, 🔹 block-type: product-grid

#3562 Merge markup from Product Title atomic block and ProductName component
  assets/js/atomic/blocks/product-elements/title/block.js
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/base/components/product-name/index.js
  assets/js/base/components/product-name/stories/index.js
  assets/js/base/components/product-name/style.scss
  assets/js/base/components/product-name/test/__snapshots__/index.js.snap
  assets/js/base/components/product-name/test/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: category: refactor, skip-changelog, status: needs review

#3569 Add 'hidden' class name when using the 'hidden' attribute
  assets/js/atomic/blocks/product-elements/add-to-cart/shared/quantity-input.js
  assets/js/base/components/panel/index.js
Labels: status: ready to merge

#3575 Use em for coupon code button height
  assets/js/base/components/cart-checkout/totals/coupon/style.scss
Labels: category: accessibility, category: styles, status: needs review

#3576 Fix data type used for paymentData.paymentMethods handling.
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
Labels: skip-changelog, status: ready to merge, ◼️ block: checkout

#3578 Fix direct call to setAttribute in EditProductSearch body
  assets/js/blocks/product-search/edit.js
Labels: status: ready to merge, type: bug, ◼️ block: product search

#3577 Fix isDefault on Buttons and switch Toolbar with ToolbarGroup
  assets/js/atomic/blocks/product-elements/shared/with-product-selector.js
  assets/js/base/components/payment-methods/no-payment-methods/index.js
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/cart-checkout/checkout/form/no-shipping-placeholder/index.js
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-product/block.js
  assets/js/blocks/handpicked-products/block.js
  assets/js/blocks/price-filter/edit.js
  assets/js/blocks/product-category/block.js
  assets/js/blocks/product-tag/block.js
  assets/js/blocks/products-by-attribute/block.js
  assets/js/blocks/products/all-products/edit.js
  assets/js/blocks/products/utils.js
  assets/js/blocks/reviews/edit-utils.js
  assets/js/blocks/single-product/edit/editor-block-controls.js
  assets/js/blocks/single-product/edit/index.js
  assets/js/editor-components/error-placeholder/index.js
  assets/js/editor-components/heading-toolbar/index.js
  assets/js/editor-components/toggle-button-control/index.js
Labels: status: ready to merge, type: compatibility, ◼️ block: all products, ◼️ block: all reviews, ◼️ block: featured category, ◼️ block: featured product, ◼️ block: filter products by attribute, ◼️ block: hand-picked products, ◼️ block: product, ◼️ block: products by attribute, ◼️ block: products by category, ◼️ block: products by tag, 🔹 block-type: atomic blocks

#3579 use ReplaceMediaFlow in featured category and feature product
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-product/block.js
Labels: status: ready to merge, type: enhancement, ◼️ block: featured category, ◼️ block: featured product

#3582 Don't add the hidden class name to elements with the hidden attribute
  assets/js/atomic/blocks/product-elements/add-to-cart/shared/quantity-input.js
  assets/js/base/components/panel/index.js
  assets/js/base/components/panel/style.scss
  docs/theming/README.md
Labels: category: styles, skip-changelog, status: ready to merge

#3567 use consistent product name `WooCommerce Blocks`
  README.md
  readme.txt
  tests/bootstrap.php
Labels: skip-changelog, status: ready to merge, type: documentation

#3568 respect merchant setting for Stripe CC `title`
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/index.js
  src/Payments/Integrations/Stripe.php
Labels: status: ready to merge, ◼️ block: checkout

#3593 sync shipping with billing when shipping is disabled
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/base/hooks/checkout/use-checkout-address.js
Labels: status: ready to merge

#3594 Get the latest stable version of WooCommerce for PHPUnit testing
  tests/bin/install-wp-tests.sh
Labels: priority: high, status: needs review, type: build

#3598 Fix nonce issues when adding product to cart from All Products
  assets/js/data/shared-controls.js
  src/StoreApi/Routes/CartCoupons.php
  src/StoreApi/Routes/CartCouponsByCode.php
  src/StoreApi/Routes/CartItemsByKey.php
  src/StoreApi/Routes/Products.php
Labels: category: rest-api, status: ready to merge, type: blocker, type: bug, ◼️ block: all products

#3599 fix: shipping_address/billing_address use properties instead on items
  src/StoreApi/Schemas/CartSchema.php
Labels: category: rest-api, skip-changelog, type: enhancement

#3465 Add the "Fix package lock" script
  bin/fix-package-lock.sh
  package.json
Labels: skip-changelog, status: ready to merge, type: build, type: dependencies

#3604 SearchListControl styles cleanup
  assets/css/editor.scss
Labels: category: components, category: refactor, skip-changelog, status: ready to merge
