Repository woocommerce/woocommerce-blocks, pull requests merged in 2020-06, with the labels that each got.

#2594 Use named font sizes in filter block styles
  assets/js/base/components/dropdown-selector/style.scss
  assets/js/blocks/active-filters/style.scss
Labels: status: ready to merge

#2590 Remove CURRENT_TIMESTAMP default on the stock table
  src/Installer.php
  src/StoreApi/Utilities/ReserveStock.php
Labels: status: ready to merge

#2573 Fixes to Twenty Twenty product grid styles
  assets/js/atomic/blocks/product/sale-badge/block.js
  assets/js/base/components/product-list/style.scss
Labels: status: ready to merge

#2593 Fix Cart sidebar styles after font size changes
  assets/js/base/components/cart-checkout/shipping-calculator/style.scss
  assets/js/base/components/cart-checkout/totals/totals-item/style.scss
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/index.js
  assets/js/base/components/select/style.scss
Labels: skip-changelog, status: ready to merge

#2592 Add context support to Atomic Blocks
  assets/js/atomic/blocks/product/button/block.js
  assets/js/atomic/blocks/product/image/attributes.js
  assets/js/atomic/blocks/product/image/block.js
  assets/js/atomic/blocks/product/price/block.js
  assets/js/atomic/blocks/product/rating/block.js
  assets/js/atomic/blocks/product/sale-badge/block.js
  assets/js/atomic/blocks/product/shared-config.js
  assets/js/atomic/blocks/product/summary/block.js
  assets/js/atomic/blocks/product/title/attributes.js
  assets/js/atomic/blocks/product/title/block.js
  assets/js/base/components/product-list-item/index.js
  assets/js/base/components/product-list/index.js
  assets/js/base/components/product-list/no-matching-products.js
  assets/js/base/components/product-list/no-products.js
  assets/js/blocks/products/all-products/block.js
  assets/js/blocks/products/all-products/edit.js
  assets/js/blocks/single-product/edit/layout-editor.js
  assets/js/shared/context/index.js
  assets/js/shared/context/inner-block-layout-context.js
  assets/js/shared/context/product-data-context.js
Labels: status: ready to merge, type: refactor

#2428 Fix product grid blocks markup & design inconsistencies
  assets/js/atomic/blocks/product/price/block.js
  assets/js/atomic/blocks/product/rating/block.js
  assets/js/base/components/product-list/style.scss
  docs/theming/README.md
  docs/theming/product-grid-270.md
  src/BlockTypes/AbstractProductGrid.php
Labels: status: ready to merge, status:needs-dev-note

#2598 2.6.0 followups for release process etc.
  .github/release_pull_request_template.md
  docs/releases/readme.md
  docs/testing/releases/260.md
  docs/testing/releases/261.md
  docs/testing/releases/README.md
Labels: scope: documentation, status: ready to merge

#2647 Avoid some theme style properties leaking into the Cart and Checkout select controls
  assets/js/base/components/select/style.scss
Labels: status: ready to merge, type: bug

#2597 Update Cart & Checkout heading styles
  assets/css/abstracts/_mixins.scss
  assets/js/base/components/cart-checkout/form-step/index.js
  assets/js/base/components/cart-checkout/form-step/style.scss
  assets/js/base/components/cart-checkout/shipping-rates-control/package.js
  assets/js/base/components/cart-checkout/shipping-rates-control/style.scss
  assets/js/base/components/cart-checkout/totals/totals-coupon-code-input/index.js
  assets/js/base/components/cart-checkout/totals/totals-coupon-code-input/style.scss
  assets/js/base/components/panel/index.js
  assets/js/base/components/panel/style.scss
  assets/js/base/components/payment-methods/express-checkout.js
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/sidebar-layout/style.scss
  assets/js/base/components/title/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/sidebar/order-summary.js
  assets/js/blocks/cart-checkout/checkout/style.scss
  assets/js/icons/index.js
  assets/js/icons/library/chevron-down.js
  assets/js/icons/library/chevron-up.js
  bin/webpack-helpers.js
Labels: scope: components, status: ready to merge

#2643 Update WC tested version to 4.2
  woocommerce-gutenberg-products-block.php
Labels: skip-changelog, status: ready to merge

#2644 Update README.md with a note about L2 version support.
  README.md
Labels: status: ready to merge

#2607 Add Inner Block Rendering and Atomic Block Styles
  assets/css/style.scss
  assets/js/atomic/blocks/product/block-components.js
  assets/js/atomic/blocks/product/button/block.js
  assets/js/atomic/blocks/product/button/style.scss
  assets/js/atomic/blocks/product/image/block.js
  assets/js/atomic/blocks/product/image/frontend.js
  assets/js/atomic/blocks/product/image/style.scss
  assets/js/atomic/blocks/product/price/block.js
  assets/js/atomic/blocks/product/price/style.scss
  assets/js/atomic/blocks/product/rating/block.js
  assets/js/atomic/blocks/product/rating/style.scss
  assets/js/atomic/blocks/product/sale-badge/block.js
  assets/js/atomic/blocks/product/sale-badge/style.scss
  assets/js/atomic/blocks/product/save.js
  assets/js/atomic/blocks/product/shared-config.js
  assets/js/atomic/blocks/product/summary/block.js
  assets/js/atomic/blocks/product/summary/style.scss
  assets/js/atomic/blocks/product/title/block.js
  assets/js/atomic/blocks/product/title/edit.js
  assets/js/atomic/blocks/product/title/frontend.js
  assets/js/atomic/blocks/product/title/style.scss
  assets/js/atomic/utils/get-block-map.js
  assets/js/atomic/utils/index.js
  assets/js/atomic/utils/render-inner-blocks.js
  assets/js/atomic/utils/render-parent-block.js
  assets/js/base/components/payment-methods/express-checkout.js
  assets/js/base/components/payment-methods/express-payment-methods.js
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/product-list-item/index.js
  assets/js/base/components/product-list/index.js
  assets/js/base/components/product-list/no-matching-products.js
  assets/js/base/components/product-list/no-products.js
  assets/js/base/components/product-list/style.scss
  assets/js/base/hocs/with-filtered-attributes.js
  assets/js/base/utils/get-valid-block-attributes.js
  assets/js/base/utils/index.js
  assets/js/base/utils/render-frontend.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/blocks/cart-checkout/checkout/style.scss
  assets/js/blocks/products/all-products/block.js
  assets/js/blocks/products/all-products/edit.js
  assets/js/blocks/single-product/block.js
  assets/js/blocks/single-product/constants.js
  assets/js/blocks/single-product/edit/layout-editor.js
  assets/js/blocks/single-product/frontend.js
  assets/js/components/block-title/editor.scss
  assets/js/components/block-title/index.js
  assets/js/shared/context/inner-block-layout-context.js
  package-lock.json
  package.json
  src/BlockTypes/AtomicBlock.php
  src/BlockTypes/Checkout.php
  src/Library.php
Labels: status: ready to merge, status:needs-dev-note

#2648 Rename wc-single-product script name
  src/Assets.php
  src/BlockTypes/SingleProduct.php
Labels: scope: blocks, skip-changelog, status: ready to merge, type: blocker

#2615 Unify Cart headers
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-title.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: status: ready to merge

#2645 Add Atomic SKU block
  assets/js/atomic/blocks/index.js
  assets/js/atomic/blocks/product/sku/block.js
  assets/js/atomic/blocks/product/sku/edit.js
  assets/js/atomic/blocks/product/sku/index.js
  assets/js/atomic/blocks/product/sku/style.scss
  assets/js/atomic/utils/get-block-map.js
  assets/js/blocks/single-product/constants.js
  assets/js/blocks/single-product/edit/edit-product-link.js
  assets/js/blocks/single-product/edit/index.js
  assets/js/components/edit-product-link/index.js
  assets/js/icons/index.js
  assets/js/icons/library/barcode.js
  src/Library.php
Labels: status: ready to merge

#2544 Refactor E2E setup routine
  tests/e2e-tests/config/jest.setup.js
Labels: scope: tests, skip-changelog, status: ready to merge

#2619 Update item count badge styles
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/cart-checkout/order-summary/index.js
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/blocks/cart-checkout/checkout/sidebar/index.js
  assets/js/blocks/cart-checkout/checkout/style.scss
  docs/theming/README.md
  docs/theming/cart-and-checkout.md
Labels: scope: components, status: ready to merge

#2622 Audit payment method interface API
  assets/js/base/hooks/index.js
  assets/js/base/hooks/order/index.js
  assets/js/base/hooks/order/use-store-order.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/type-defs/registered-payment-method-props.js
  docs/extensibility/payment-method-integration.md
Labels: skip-changelog, status: ready to merge, type: blocker

#2548 Add fixtures data for all entities.
  .env
  bin/docker/wordpress/Dockerfile
  bin/docker/wp-cli/entrypoint.sh
  package-lock.json
  package.json
  tests/e2e-tests/config/default.json
  tests/e2e-tests/config/jest.config.js
  tests/e2e-tests/config/setup.js
  tests/e2e-tests/config/teardown.js
  tests/e2e-tests/fixtures/fixture-data.js
  tests/e2e-tests/fixtures/fixture-loaders.js
Labels: scope: tests, status: ready to merge

#2591 Expand Feature flags
  .eslintrc.js
  .travis.yml
  assets/js/blocks/cart-checkout/cart/index.js
  assets/js/blocks/cart-checkout/checkout/index.js
  assets/js/blocks/single-product/index.js
  assets/js/settings/blocks/constants.js
  assets/js/settings/blocks/feature-flags.js
  assets/js/settings/blocks/index.js
  bin/eslint-plugin-woocommerce/rules/feature-flag.js
  bin/webpack-helpers.js
  package-lock.json
  package.json
  src/Assets.php
  src/Domain/Bootstrap.php
  src/Domain/Package.php
  src/Library.php
  src/Package.php
  webpack.config.js
  woocommerce-gutenberg-products-block.php
Labels: skip-changelog, status: ready to merge, type: blocker, type: build

#2655 Fix retrying after failed payment processed server side.
  assets/js/base/components/payment-methods/saved-payment-method-options.js
  assets/js/base/context/cart-checkout/payment-methods/constants.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/payment-methods/reducer.js
Labels: scope: extensibility, status: ready to merge, type: blocker, type: bug

#2652 Fix styling issues introduced in #2597 and #2619
  assets/js/base/components/cart-checkout/order-summary/index.js
  assets/js/base/components/cart-checkout/order-summary/style.scss
  assets/js/base/components/panel/style.scss
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/sidebar-layout/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: skip-changelog, status: ready to merge

#2662 Fix credit card validation errors alignment
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/text-input/style.scss
Labels: status: ready to merge, type: bug

#2649 Update Checkout step progress indicator design
  assets/js/base/components/cart-checkout/form-step/index.js
  assets/js/base/components/cart-checkout/form-step/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
  src/BlockTypes/Checkout.php
Labels: scope: components, status: ready to merge, type: enhancement

#2664 Ignore dashicons imports
  assets/js/icons/index.js
  assets/js/icons/library/arrow-down-alt2.js
  assets/js/icons/library/no-alt.js
  assets/js/module_replacements/dashicon.js
  bin/webpack-helpers.js
Labels: skip-changelog, status: ready to merge, type: performance, ◼️ block: all products, ◼️ block: cart, ◼️ block: checkout, ◼️ block: product

#2666 Release: 2.7.0
  docs/testing/releases/270.md
  docs/testing/releases/README.md
  package.json
  readme.txt
  src/Package.php
  woocommerce-gutenberg-products-block.php
Labels: status: ready to merge, type: release

#2665 Fix release PR template link in release docs
  docs/releases/readme.md
Labels: scope: documentation, skip-changelog, status: ready to merge

#2677 Add expected folder for testing instructions to the release PR template
  .github/release_pull_request_template.md
  docs/releases/readme.md
Labels: scope: documentation, skip-changelog, status: ready to merge

#2691 Add theming docs
  assets/js/base/components/formatted-monetary-amount/index.js
  assets/js/base/components/formatted-monetary-amount/style.scss
  assets/js/base/components/product-sort-select/index.js
  assets/js/base/components/product-sort-select/style.scss
  assets/js/base/components/reviews/review-sort-select/index.js
  assets/js/base/components/reviews/review-sort-select/style.scss
  assets/js/base/components/sort-select/index.js
  assets/js/base/components/sort-select/style.scss
  docs/contributors/coding-guidelines.md
  docs/readme.md
  docs/theming/README.md
  docs/theming/class-names-update-280.md
Labels: status: ready to merge, status:needs-dev-note

#2694 Fix Cart and Checkout sidebar styling issues
  assets/js/base/components/cart-checkout/form-step/style.scss
  assets/js/base/components/cart-checkout/order-summary/style.scss
  assets/js/base/components/cart-checkout/product-metadata/index.js
  assets/js/base/components/cart-checkout/product-metadata/style.scss
  assets/js/base/components/cart-checkout/product-summary/index.js
  assets/js/base/components/cart-checkout/shipping-rates-control/package.js
  assets/js/base/components/cart-checkout/shipping-rates-control/style.scss
  assets/js/base/components/cart-checkout/totals/totals-coupon-code-input/index.js
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/style.scss
  assets/js/base/components/panel/index.js
  assets/js/base/components/panel/style.scss
  assets/js/base/components/sidebar-layout/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: status: ready to merge

#2708 Use IE11 friendly code for Dashicon component replacement.
  assets/js/module_replacements/dashicon.js
Labels: status: ready to merge, type: blocker, type: bug

#2704 Remove background color from Express Checkout title
  assets/js/base/components/payment-methods/express-checkout.js
  assets/js/base/components/payment-methods/style.scss
Labels: status: ready to merge, ◼️ block: checkout

#2722 Fix notices on variations without prices
  src/StoreApi/Schemas/AbstractSchema.php
  src/StoreApi/Schemas/ProductSchema.php
Labels: scope: rest-api, status: ready to merge, type: bug

#2723 Fix undefined index notice for query_type on the product collection data endpoint.
  src/StoreApi/Routes/ProductCollectionData.php
Labels: scope: rest-api, status: ready to merge, type: bug, ◼️ block: filter products by attribute

#2724 Fix missing scoped variable in closure and missing schema definitions.
  src/StoreApi/Routes/ProductCollectionData.php
  src/StoreApi/Routes/Products.php
Labels: scope: rest-api, status: ready to merge, type: bug, ◼️ block: filter products by attribute

#2700 Fix Product Categories List align attribute
  assets/js/blocks/product-categories/index.js
  src/BlockTypes/ProductCategories.php
Labels: status: ready to merge, type: bug, ◼️ block: product categories list

#2686 Expand travis matrix
  .travis.yml
  bin/docker/wp-cli/entrypoint.sh
  docker-compose.yml
  package-lock.json
  package.json
  tests/e2e-tests/specs/backend/all-products.test.js
  tests/e2e-tests/specs/backend/cart.test.js
  tests/e2e-tests/specs/backend/checkout.test.js
  tests/e2e-tests/specs/backend/single-product.test.js
Labels: scope: tests, skip-changelog, status: ready to merge

#2720 Update documentation indexes and add checkout docs
  docs/blocks/README.md
  docs/blocks/checkout.jpg
  docs/blocks/reserve-stock.jpg
  docs/blocks/stock-reservation.md
  docs/contributors/README.md
  docs/readme.md
  docs/releases/handling-releases.md
  docs/releases/readme.md
Labels: scope: documentation, status: ready to merge

#2705 Introduce Atomic Add to Cart Block
  assets/js/atomic/blocks/index.js
  assets/js/atomic/blocks/product/add-to-cart/attributes.js
  assets/js/atomic/blocks/product/add-to-cart/block.js
  assets/js/atomic/blocks/product/add-to-cart/edit.js
  assets/js/atomic/blocks/product/add-to-cart/frontend.js
  assets/js/atomic/blocks/product/add-to-cart/index.js
  assets/js/atomic/blocks/product/add-to-cart/product-types/external.js
  assets/js/atomic/blocks/product/add-to-cart/product-types/grouped/group-list/index.js
  assets/js/atomic/blocks/product/add-to-cart/product-types/grouped/index.js
  assets/js/atomic/blocks/product/add-to-cart/product-types/index.js
  assets/js/atomic/blocks/product/add-to-cart/product-types/simple.js
  assets/js/atomic/blocks/product/add-to-cart/product-types/variable/index.js
  assets/js/atomic/blocks/product/add-to-cart/product-types/variable/variation-picker/index.js
  assets/js/atomic/blocks/product/add-to-cart/shared/add-to-cart-button.js
  assets/js/atomic/blocks/product/add-to-cart/shared/index.js
  assets/js/atomic/blocks/product/add-to-cart/shared/product-unavailable.js
  assets/js/atomic/blocks/product/add-to-cart/shared/quantity-input.js
  assets/js/atomic/blocks/product/add-to-cart/style.scss
  assets/js/atomic/blocks/product/category-list/block.js
  assets/js/atomic/blocks/product/stock-indicator/block.js
  assets/js/atomic/blocks/product/tag-list/block.js
  assets/js/atomic/utils/get-block-map.js
  assets/js/base/components/button/index.js
  assets/js/base/components/button/stories/index.js
  assets/js/base/components/button/style.scss
  assets/js/base/context/add-to-cart-form-context.js
  assets/js/base/context/index.js
  assets/js/base/hooks/index.js
  assets/js/base/hooks/use-store-add-to-cart.js
  assets/js/base/hooks/use-trigger-fragment-refresh.js
  assets/js/base/utils/get-valid-block-attributes.js
  assets/js/blocks/single-product/constants.js
  assets/js/type-defs/contexts.js
  src/Library.php
  src/StoreApi/Schemas/CartItemSchema.php
  src/StoreApi/Schemas/ProductSchema.php
  tsconfig.json
Labels: status: ready to merge, 🔺 atomic-block: add to cart

#2688 `registerInnerBlock` ->`registerBlockComponent`
  assets/js/atomic/blocks/component-init.js
  assets/js/atomic/utils/get-block-map.js
  assets/js/blocks-registry/block-components/get-registered-block-components.js
  assets/js/blocks-registry/block-components/index.js
  assets/js/blocks-registry/block-components/register-block-component.js
  assets/js/blocks-registry/block-components/registered-block-components-init.js
  assets/js/blocks-registry/block-components/test/index.js
  assets/js/blocks-registry/get-registered-inner-blocks.js
  assets/js/blocks-registry/index.js
  assets/js/blocks-registry/register-inner-block.js
  assets/js/blocks-registry/registered-blocks-init.js
  assets/js/blocks-registry/test/index.js
  package-lock.json
  package.json
Labels: status: ready to merge, type: refactor

#2730 Switch to use `wp-env` as the development/test environment
  .env
  .gitignore
  .travis.yml
  .wp-env.json
  bin/.htaccess
  bin/wp-env-config.sh
  bin/wp-env-pre-config.sh
  package-lock.json
  package.json
  tests/e2e-tests/config/default.json
  tests/e2e-tests/config/env.setup.js
  tests/e2e-tests/config/jest.config.js
  tests/e2e-tests/config/setup.js
  tests/e2e-tests/fixtures/fixture-loaders.js
  tests/e2e-tests/specs/backend/__fixtures__/product-search.fixture.json
  tests/e2e-tests/specs/backend/__snapshots__/product-search.test.js.snap
Labels: scope: tests, status: ready to merge

#2497 Introduce Variation Picker Component
  assets/js/atomic/blocks/product/add-to-cart/product-types/variable/index.js
  assets/js/atomic/blocks/product/add-to-cart/product-types/variable/variation-attributes/attribute-picker.js
  assets/js/atomic/blocks/product/add-to-cart/product-types/variable/variation-attributes/attribute-select-control.js
  assets/js/atomic/blocks/product/add-to-cart/product-types/variable/variation-attributes/index.js
  assets/js/atomic/blocks/product/add-to-cart/product-types/variable/variation-attributes/style.scss
  assets/js/atomic/blocks/product/add-to-cart/product-types/variable/variation-attributes/utils.js
  assets/js/atomic/blocks/product/add-to-cart/product-types/variable/variation-picker/index.js
  assets/js/atomic/blocks/product/add-to-cart/style.scss
  assets/js/hocs/test/with-product-variations.js
  assets/js/hocs/with-attributes.js
  assets/js/hocs/with-product-variations.js
  src/StoreApi/Schemas/ProductAttributeSchema.php
  src/StoreApi/Schemas/ProductSchema.php
  tests/php/StoreApi/Routes/ProductAttributes.php
Labels: scope: components, status: ready to merge

#2748 Cart & Checkout: show shipping method prices with taxes when required
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/shipping-rate-selector.js
  assets/js/blocks/cart-checkout/checkout/block.js
  src/StoreApi/Schemas/CartShippingRateSchema.php
Labels: status: ready to merge, type: bug, ◼️ block: cart, ◼️ block: checkout

#2763 Call add to cart in click handler
  assets/js/atomic/blocks/product/button/block.js
Labels: status: ready to merge

#2745 Remove text color from Cart and Checkout blocks
  assets/css/abstracts/_mixins.scss
  assets/js/base/components/cart-checkout/form-step/style.scss
  assets/js/base/components/cart-checkout/order-summary/style.scss
  assets/js/base/components/cart-checkout/product-low-stock-badge/style.scss
  assets/js/base/components/cart-checkout/product-metadata/style.scss
  assets/js/base/components/cart-checkout/product-price/index.js
  assets/js/base/components/cart-checkout/product-price/style.scss
  assets/js/base/components/cart-checkout/product-sale-badge/index.js
  assets/js/base/components/cart-checkout/product-sale-badge/style.scss
  assets/js/base/components/cart-checkout/return-to-cart-button/style.scss
  assets/js/base/components/cart-checkout/shipping-location/index.js
  assets/js/base/components/cart-checkout/shipping-location/style.scss
  assets/js/base/components/cart-checkout/shipping-rates-control/style.scss
  assets/js/base/components/cart-checkout/totals/totals-footer-item/style.scss
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/style.scss
  assets/js/base/components/cart-checkout/totals/totals-taxes-item/index.js
  assets/js/base/components/cart-checkout/totals/totals-taxes-item/style.scss
  assets/js/base/components/panel/style.scss
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/radio-control/_mixin.scss
  assets/js/base/components/tabs/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
  docs/theming/class-names-update-280.md
Labels: status: ready to merge, ◼️ block: cart, ◼️ block: checkout

#2747 Update reserved stock when a row already exists
  src/StoreApi/Utilities/ReserveStock.php
Labels: status: ready to merge

#2755 Use WooCommerce thumbnail images in Blocks
  assets/js/atomic/blocks/product/image/attributes.js
  assets/js/atomic/blocks/product/image/block.js
  assets/js/atomic/blocks/product/image/edit.js
  assets/js/base/components/cart-checkout/product-image/index.js
  assets/js/base/components/reviews/review-list-item/index.js
  assets/js/base/components/reviews/review-list-item/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/product-image.js
  assets/js/blocks/cart-checkout/cart/full-cart/product-low-stock-badge.js
  assets/js/blocks/cart-checkout/cart/full-cart/product-variation-data.js
Labels: status: ready to merge, ◼️ block: all products, ◼️ block: cart, ◼️ block: checkout, ◼️ block: product, 🔹 block-type: reviews

#2764 Fix instability with snapshot tests
  tests/utils/visit-block-page.js
Labels: scope: tests, skip-changelog, type: bug

#2769 More e2e snapshot instability investigation
  tests/utils/visit-block-page.js
Labels: scope: tests, skip-changelog, type: bug

#2742 Auto-merge renovate dependency updates (except major versions)
  docs/releases/handling-releases.md
  renovate.json
Labels: status: ready to merge

#2780 Add custom jest e2e matcher
  tests/e2e-tests/config/custom-matchers/index.js
  tests/e2e-tests/config/custom-matchers/to-render-block.js
  tests/e2e-tests/config/jest.config.js
  tests/e2e-tests/specs/backend/all-products.test.js
  tests/e2e-tests/specs/backend/cart.test.js
  tests/e2e-tests/specs/backend/checkout.test.js
  tests/e2e-tests/specs/backend/product-search.test.js
  tests/e2e-tests/specs/backend/single-product.test.js
Labels: scope: tests, status: ready to merge

#2781 Replace usage of `cart-checkout/button` with `@woocommerce/base-components/button`
  assets/js/base/components/button/index.js
  assets/js/base/components/button/stories/index.js
  assets/js/base/components/cart-checkout/button/index.js
  assets/js/base/components/cart-checkout/button/stories/index.js
  assets/js/base/components/cart-checkout/button/style.scss
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/cart-checkout/place-order-button/index.js
  assets/js/base/components/cart-checkout/shipping-calculator/address.js
  assets/js/base/components/cart-checkout/totals/totals-coupon-code-input/index.js
  assets/js/blocks/cart-checkout/cart/checkout-button/index.js
Labels: status: ready to merge

#2774 Reorder internal/external dependencies
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/data/query-state/test/selectors.js
  assets/js/data/schema/test/reducers.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/payment-method.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/payment-request-express.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/utils.js
  assets/js/settings/shared/index.js
Labels: status: ready to merge, type: cooldown

#2787 Add storybook story for icon library
  assets/js/filters/block-list-block.js
  assets/js/filters/get-block-attributes.js
  assets/js/icons/library/arrow-back.js
  assets/js/icons/library/arrow-down-alt2.js
  assets/js/icons/library/no-alt.js
  assets/js/icons/library/woo.js
  assets/js/icons/stories/index.js
  assets/js/index.js
  assets/js/module_replacements/dashicon.js
Labels: status: ready to merge, type: bug, type: build, type: enhancement
