Repository woocommerce/woocommerce-blocks, pull requests merged in 2020-11, with the labels that each got.

#3238 Add __experimental_woocommerce_blocks_checkout_order_processed action
  src/StoreApi/Routes/Checkout.php
Labels: scope: extensibility, scope: rest-api, status: ready to merge, status:needs-dev-note, ◼️ block: checkout

#3351 Improve smoke testing docs
  .github/patch-initial-checklist.md
  .github/release-initial-checklist.md
  docs/contributors/README.md
  docs/contributors/smoke-testing.md
  docs/releases/wordpress-update-testing-checklist.md
  docs/testing/README.md
  docs/testing/smoke-testing.md
Labels: scope: documentation, status: ready to merge

#3371 Fix account creation bugs
  assets/js/blocks/cart-checkout/checkout/attributes.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/form/contact-fields-step.js
  src/Assets.php
  src/Domain/Services/CreateAccount.php
  tests/php/Domain/Services/CreateAccount.php
Labels: status: ready to merge, type: bug, ◼️ block: checkout

#3380 Force node 12 for action
  .github/workflows/bundle-size.yml
Labels: skip-changelog, type: bug, type: build

#3360 Change delimiter used for spltChunks from tilde to hyphens
  bin/webpack-configs.js
Labels: skip-changelog, status: ready to merge, type: build

#3376 Show the phone number field in the billing section when shipping is disabled in settings
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/blocks/cart-checkout/checkout/form/address-step.js
  assets/js/blocks/cart-checkout/checkout/form/billing-fields-step.js
  assets/js/blocks/cart-checkout/checkout/form/index.js
  assets/js/blocks/cart-checkout/checkout/form/order-notes-step.js
  assets/js/blocks/cart-checkout/checkout/form/phone-number/index.js
  assets/js/blocks/cart-checkout/checkout/form/shipping-fields-step.js
  assets/js/type-defs/contexts.js
Labels: status: ready to merge

#3377 Add WordPress.org assets folder and add latest assets.
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-772x250.png
  .wordpress-org/icon-128x128.png
  .wordpress-org/icon-256x256.png
Labels: status: ready to merge

#3381 Fix PHP8 Unsupported Types with Operators warnings for PHP8
  src/BlockTypes/ProductCategories.php
  src/StoreApi/Routes/AbstractTermsRoute.php
  src/StoreApi/Routes/CartItemsByKey.php
  src/StoreApi/Routes/CartRemoveItem.php
  src/StoreApi/Routes/Checkout.php
  src/StoreApi/Utilities/CartController.php
Labels: skip-changelog, status: ready to merge, type: bug

#3401 Print wordpress version in e2e tests.
  bin/wp-env-config.sh
Labels: scope: tests, skip-changelog, status: ready to merge

#3400 Fix incorrect usage of static method in Stripe payment method integration
  phpcs.xml
  src/Payments/Integrations/Stripe.php
Labels: scope: extensibility, status: ready to merge, type: bug, ◼️ block: checkout

#3399 Expose `discount_type` in Store API coupon endpoints
  src/StoreApi/Schemas/CartCouponSchema.php
  src/StoreApi/docs/cart-coupons.md
Labels: status: ready to merge

#3356 Introduce ExtendRestApi
  src/Domain/Bootstrap.php
  src/Domain/Services/ExtendRestApi.php
  src/RestApi.php
  src/StoreApi/SchemaController.php
  src/StoreApi/Schemas/AbstractSchema.php
  src/StoreApi/Schemas/BillingAddressSchema.php
  src/StoreApi/Schemas/CartCouponSchema.php
  src/StoreApi/Schemas/CartItemSchema.php
  src/StoreApi/Schemas/CartSchema.php
  src/StoreApi/Schemas/CartShippingRateSchema.php
  src/StoreApi/Schemas/CheckoutSchema.php
  src/StoreApi/Schemas/ErrorSchema.php
  src/StoreApi/Schemas/ImageAttachmentSchema.php
  src/StoreApi/Schemas/OrderCouponSchema.php
  src/StoreApi/Schemas/ProductAttributeSchema.php
  src/StoreApi/Schemas/ProductCategorySchema.php
  src/StoreApi/Schemas/ProductCollectionDataSchema.php
  src/StoreApi/Schemas/ProductReviewSchema.php
  src/StoreApi/Schemas/ProductSchema.php
  src/StoreApi/Schemas/ShippingAddressSchema.php
  src/StoreApi/Schemas/TermSchema.php
  tests/php/StoreApi/Routes/Cart.php
  tests/php/StoreApi/Routes/CartCoupons.php
  tests/php/StoreApi/Routes/CartItems.php
  tests/php/StoreApi/Routes/ProductAttributeTerms.php
  tests/php/StoreApi/Routes/ProductAttributes.php
  tests/php/StoreApi/Routes/ProductCollectionData.php
  tests/php/StoreApi/Routes/Products.php
Labels: scope: extensibility, scope: rest-api, status: ready to merge

#3403 Fix: orders not being placed when paying with an Express payment method from the Cart block
  assets/js/base/context/cart-checkout/cart/index.js
  assets/js/base/context/cart-checkout/checkout/index.js
  assets/js/blocks/cart-checkout/cart/block.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  src/StoreApi/Routes/Checkout.php
Labels: status: ready to merge, type: bug, ◼️ block: cart

#3343 Move feature flag PHP logic to a service class
  src/Assets.php
  src/Domain/Bootstrap.php
  src/Domain/Package.php
  src/Domain/Services/CreateAccount.php
  src/Domain/Services/DraftOrders.php
  src/Domain/Services/FeatureGating.php
  src/Library.php
  src/Package.php
  tests/php/Domain/Package.php
  tests/php/Domain/Services/CreateAccount.php
  tests/php/Domain/Services/DeleteDraftOrders.php
Labels: skip-changelog, status: ready to merge, type: refactor

#3410 Show Express Payment Method Error Notices after Payment Failure
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/context/cart-checkout/checkout-state/reducer.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/use-checkout-subscriptions.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/use-initialization.js
  src/Payments/Integrations/Stripe.php
Labels: status: ready to merge

#3408 Fix cart block isLarge console error in the editor when running WordPress 5.6 beta
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/price-filter/edit.js
  assets/js/blocks/products/all-products/edit.js
  assets/js/blocks/products/utils.js
  assets/js/editor-components/view-switcher/index.js
Labels: status: ready to merge

#3383 Cart and checkout should respect the global "Hide shipping costs until an address is entered" setting
  assets/js/base/components/cart-checkout/shipping-calculator/address.js
  assets/js/base/components/cart-checkout/shipping-rates-control/index.js
  assets/js/base/components/cart-checkout/shipping-rates-control/package-options.js
  assets/js/base/components/cart-checkout/shipping-rates-control/package.js
  assets/js/base/components/cart-checkout/shipping-rates-control/packages.js
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/index.js
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/shipping-rate-selector.js
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/style.scss
  assets/js/base/context/cart-checkout/shipping/index.js
  assets/js/base/hooks/cart/test/use-store-cart.js
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/blocks/cart-checkout/cart/attributes.js
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/test/block.js
  assets/js/blocks/cart-checkout/checkout/form/shipping-options-step.js
  assets/js/blocks/cart-checkout/checkout/sidebar/index.js
  assets/js/previews/cart.js
  assets/js/type-defs/contexts.js
  assets/js/type-defs/hooks.js
  src/Assets.php
  src/StoreApi/Schemas/CartSchema.php
  tests/e2e/specs/backend/cart.test.js
Labels: status: ready to merge

#3413 Add FeatureGating parameter to Package in tests
  tests/php/StoreApi/Routes/Cart.php
  tests/php/StoreApi/Routes/CartCoupons.php
  tests/php/StoreApi/Routes/CartItems.php
  tests/php/StoreApi/Routes/ProductAttributeTerms.php
  tests/php/StoreApi/Routes/ProductAttributes.php
  tests/php/StoreApi/Routes/ProductCollectionData.php
  tests/php/StoreApi/Routes/Products.php
Labels: scope: tests, skip-changelog, status: ready to merge

#3379 Exclude checkout-draft orders from WC Admin reports and My Account > Orders
  assets/js/settings/shared/exclude-draft-status-from-analytics.js
  assets/js/settings/shared/index.js
  src/Domain/Services/DraftOrders.php
Labels: status: ready to merge, type: enhancement, ◼️ block: checkout

#3404 Support a plain js config argument to payment method registration APIs
  assets/js/base/components/payment-methods/test/payment-methods.js
  assets/js/base/context/cart-checkout/payment-methods/test/payment-method-data-context.js
  assets/js/blocks-registry/payment-methods/assertions.js
  assets/js/blocks-registry/payment-methods/registry.js
  assets/js/payment-method-extensions/payment-methods/bacs/index.js
  assets/js/payment-method-extensions/payment-methods/cheque/index.js
  assets/js/payment-method-extensions/payment-methods/cod/index.js
  assets/js/payment-method-extensions/payment-methods/paypal/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/index.js
  assets/js/type-defs/payments.js
  docs/extensibility/payment-method-integration.md
Labels: status: needs review

#3406 Use latest ( tracked ) patch releases for E2E tests.
  .travis.yml
Labels: type: bug, type: build

#3424 Improve Stripe (chrome pay) express payment method availability
  assets/js/base/context/cart-checkout/payment-methods/reducer.js
  assets/js/base/context/cart-checkout/payment-methods/use-payment-method-registration.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/index.js
Labels: status: ready to merge

#3425 Prevent checkout step heading text overlapping actual heading on small viewports
  assets/js/base/components/cart-checkout/form-step/style.scss
Labels: status: ready to merge, type: bug, ◼️ block: checkout

#3427 Ensure "Add a note to your order" section is styled correctly when disabled
  assets/js/base/components/cart-checkout/form-step/index.js
  assets/js/base/components/cart-checkout/form-step/style.scss
  assets/js/base/components/cart-checkout/form-step/test/__snapshots__/index.js.snap
  assets/js/blocks/cart-checkout/checkout/form/order-notes-step.js
Labels: status: ready to merge, type: bug, ◼️ block: checkout

#3358 Sync shipping address with billing address when shipping address fields are disabled
  assets/js/base/context/cart-checkout/billing/constants.js
  assets/js/base/context/cart-checkout/billing/index.js
  assets/js/base/context/cart-checkout/checkout/index.js
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/base/context/cart-checkout/checkout/processor/utils.js
  assets/js/base/context/cart-checkout/customer/index.js
  assets/js/base/context/cart-checkout/index.js
  assets/js/base/context/cart-checkout/payment-methods/actions.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/shipping/constants.js
  assets/js/base/context/cart-checkout/shipping/index.js
  assets/js/base/hooks/cart/test/use-store-cart.js
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/base/hooks/checkout/use-checkout-address.js
  assets/js/base/hooks/customer/index.js
  assets/js/base/hooks/customer/use-customer-data.js
  assets/js/base/hooks/customer/utils.js
  assets/js/base/hooks/index.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/base/hooks/shipping/index.js
  assets/js/base/hooks/shipping/use-shipping-address.js
  assets/js/base/utils/address.js
  assets/js/data/cart/action-types.js
  assets/js/data/cart/actions.js
  assets/js/data/cart/reducers.js
  assets/js/data/cart/selectors.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/normalize.js
  assets/js/type-defs/cart.js
  assets/js/type-defs/contexts.js
  assets/js/type-defs/hooks.js
  assets/js/type-defs/registered-payment-method-props.js
  assets/js/type-defs/shipping.js
  docs/block-client-apis/checkout/checkout-api.md
  src/StoreApi/README.md
  src/StoreApi/Routes/CartUpdateCustomer.php
  src/StoreApi/Routes/CartUpdateShipping.php
  src/StoreApi/Routes/Checkout.php
  src/StoreApi/RoutesController.php
  src/StoreApi/SchemaController.php
  src/StoreApi/Schemas/BillingAddressSchema.php
  src/StoreApi/Schemas/CartSchema.php
  src/StoreApi/docs/cart.md
  tests/php/StoreApi/Routes/Cart.php
Labels: status: ready to merge

#3430 Refresh PaymentRequest after cancelling payment to prevent addresses remaining populated on repeat attempts
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/use-initialization.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/normalize.js
Labels: status: ready to merge, ◼️ block: checkout

#3432 Fixed express payment methods processing not completing when stripe payment method active.
  assets/js/base/components/payment-methods/payment-method-options.js
Labels: status: ready to merge, type: blocker, type: bug, ◼️ block: checkout

#3415 Stop hidden products from being linked in cart and checkout blocks
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/base/components/cart-checkout/product-name/index.js
  assets/js/base/components/cart-checkout/product-name/stories/index.js
  assets/js/base/components/cart-checkout/product-name/test/__snapshots__/index.js.snap
  assets/js/base/components/cart-checkout/product-name/test/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  src/StoreApi/Schemas/CartItemSchema.php
  tests/php/StoreApi/Routes/CartItems.php
Labels: status: ready to merge, type: bug, ◼️ block: cart, ◼️ block: checkout

#3436 Hide spinner on cart block's "Proceed to Checkout" link when page unloads
  assets/js/blocks/cart-checkout/cart/checkout-button/index.js
Labels: status: ready to merge, type: bug, ◼️ block: cart

#3444 Fix Twenty Twenty One Price filter, Active filters and radio control styling
  assets/js/base/components/price-slider/style.scss
  assets/js/base/components/radio-control/_mixin.scss
  assets/js/base/components/radio-control/style.scss
  assets/js/blocks/active-filters/style.scss
Labels: scope: styles, status: ready to merge

#3443 Fix Twenty Twenty One Button and Placeholder Styling
  assets/css/abstracts/_colors.scss
  assets/css/abstracts/_mixins.scss
  assets/css/editor.scss
  assets/css/style.scss
  assets/js/atomic/blocks/product-elements/button/style.scss
  assets/js/base/components/product-list/style.scss
Labels: scope: styles, status: ready to merge

#3446 Fix radio controls and checkboxes in Twenty Twenty One dark theme
  assets/js/base/components/checkbox-control/style.scss
  assets/js/base/components/radio-control/style.scss
Labels: scope: styles, status: ready to merge, ◼️ block: checkout

#3450 Fix checkbox and textarea styles in Twenty Twenty One when it has dark controls
  assets/js/base/components/checkbox-control/style.scss
  assets/js/base/components/textarea/style.scss
Labels: scope: styles, status: ready to merge, ◼️ block: checkout

#3451 Improve deploy script to properly account for releases not deployed to wp.org
  bin/github-deploy.sh
Labels: skip-changelog, status: ready to merge, type: bug, type: build

#3455 Ensure correct alignment of checkout notice's dismiss button
  assets/js/base/components/store-notices-container/style.scss
Labels: status: ready to merge, type: bug, ◼️ block: checkout

#3445 Expose store/cart via ExtendRestApi
  src/Domain/Services/ExtendRestApi.php
  src/StoreApi/Schemas/CartSchema.php
Labels: scope: extensibility, scope: rest-api, status: ready to merge, type: enhancement

#3464 Stop hidden/search-only product names being links in checkout sidebar
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
Labels: status: ready to merge, type: bug, ◼️ block: checkout

#3463 Prevent exclude drafts filter being tree shaken
  assets/js/filters/exclude-draft-status-from-analytics.js
  assets/js/settings/shared/index.js
Labels: skip-changelog, status: ready to merge, type: blocker, type: bug

#3478 Change register_endpoint_data to use an array of params instead of individual params.
  src/Domain/Services/ExtendRestApi.php
Labels: category: extensibility, category: rest-api, status: ready to merge, type: enhancement
