Repository woocommerce/woocommerce-blocks, pull requests merged in 2020-09, with the labels that each got.

#3090 Use wp_login_url instead of hardcoding login path
  assets/js/blocks/cart-checkout/checkout/utils.js
  assets/js/settings/blocks/constants.js
  src/Assets.php
Labels: status: ready to merge, type: bug

#3095 Fix product element styling class names
  assets/js/atomic/blocks/product-elements/image/style.scss
  assets/js/atomic/blocks/product-elements/price/block.js
  assets/js/atomic/blocks/product-elements/price/style.scss
  assets/js/atomic/blocks/product-elements/sale-badge/block.js
  assets/js/atomic/blocks/product-elements/title/block.js
Labels: status: ready to merge, 🔺 atomic-block: product title

#3107 Wrap complex computations in Country/State inputs with useMemo
  assets/js/base/components/country-input/country-input.js
  assets/js/base/components/state-input/state-input.js
Labels: scope: components, skip-changelog, status: ready to merge, ◼️ block: checkout

#3109 Fix product reviews schema date fields to use new (WP 5.5) `date-time` format
  src/StoreApi/Schemas/ProductReviewSchema.php
Labels: scope: rest-api, status: ready to merge

#3111 Fix Cart & Checkout sidebar layout broken in some themes
  assets/js/base/components/sidebar-layout/style.scss
Labels: scope: styles, status: ready to merge, type: bug, ◼️ block: cart, ◼️ block: checkout

#3106 Split Checkout form component into smaller files (II)
  assets/js/base/components/form/index.js
  assets/js/blocks/cart-checkout/checkout/form/address-step.js
  assets/js/blocks/cart-checkout/checkout/form/billing-fields-step.js
  assets/js/blocks/cart-checkout/checkout/form/contact-fields-step.js
  assets/js/blocks/cart-checkout/checkout/form/index.js
  assets/js/blocks/cart-checkout/checkout/form/order-notes-step.js
  assets/js/blocks/cart-checkout/checkout/form/payment-method-step.js
  assets/js/blocks/cart-checkout/checkout/form/shipping-fields-step.js
  assets/js/blocks/cart-checkout/checkout/form/shipping-options-step.js
Labels: skip-changelog, status: ready to merge, type: refactor, ◼️ block: checkout

#3108 Create DebouncedValidatedTextInput component
  assets/js/base/components/cart-checkout/address-form/index.js
  assets/js/base/components/state-input/state-input.js
  assets/js/base/components/text-input/debounced-validated.js
  assets/js/base/components/text-input/index.js
  assets/js/blocks/cart-checkout/checkout/form/contact-fields-step.js
  assets/js/blocks/cart-checkout/checkout/form/shipping-fields-step.js
Labels: scope: components, status: ready to merge, type: performance, ◼️ block: checkout

#3131 Ensure shopper saved card is used as default payment method (default was being overwritten in some circumstances)
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
Labels: status: ready to merge

#3139 Update package-lock.json (fix e2e tests)
  package-lock.json
Labels: scope: tests, skip-changelog, status: ready to merge

#3058 Add several tests to Checkout block in the editor
  tests/e2e/config/custom-matchers/index.js
  tests/e2e/config/custom-matchers/to-toggle-element.js
  tests/e2e/config/custom-matchers/to-toggle-required-attr-of.js
  tests/e2e/specs/backend/cart.test.js
  tests/e2e/specs/backend/checkout.test.js
  tests/e2e/specs/backend/product-search.test.js
  tests/utils/find-label-with-text.js
  tests/utils/index.js
Labels: scope: tests, skip-changelog, status: ready to merge, ◼️ block: checkout

#3065 Merge ProductPrice atomic block and component
  assets/js/atomic/blocks/product-elements/price/block.js
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/base/components/cart-checkout/product-name/index.js
  assets/js/base/components/cart-checkout/product-price/index.js
  assets/js/base/components/cart-checkout/product-price/style.scss
  assets/js/base/components/product-price/index.js
  assets/js/base/components/product-price/stories/index.js
  assets/js/base/components/product-price/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
Labels: skip-changelog, status: ready to merge, type: refactor

#3088 Fix an issue with COD not showing when first enabled
  assets/js/payment-method-extensions/payment-methods/cod/index.js
  src/Payments/Integrations/CashOnDelivery.php
Labels: status: ready to merge, type: bug

#3124 Update release docs (including release pull request templates)
  .github/patch-initial-checklist.md
  .github/patch-release-pull-request.md
  .github/release-initial-checklist.md
  .github/release-pull-request.md
  docs/releases/handling-releases.md
Labels: scope: documentation, skip-changelog, status: ready to merge, type: enhancement

#3143 Update .gitattributes to reduce what is pulled into projects via composer.
  .gitattributes
Labels: type: build

#3147 Fix State label for Spain
  assets/js/base/components/cart-checkout/address-form/country-address-fields.js
Labels: scope: components, status: ready to merge, ◼️ block: cart, ◼️ block: checkout

#3134 Don't throw an error when registering a payment method fails
  assets/js/base/components/payment-methods/express-payment-methods.js
  assets/js/base/components/payment-methods/express-payment/checkout-express-payment.js
  assets/js/base/components/payment-methods/payment-method-error-boundary.js
  assets/js/base/components/payment-methods/saved-payment-method-options.js
  assets/js/base/context/cart-checkout/payment-methods/use-payment-method-registration.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/index.js
Labels: status: ready to merge, type: bug, ◼️ block: checkout

#3161 Use noticeContexts from useEmitResponse instead of hardcoded values
  assets/js/base/components/payment-methods/express-payment/cart-express-payment.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/blocks/cart-checkout/checkout/form/payment-method-step.js
Labels: status: ready to merge, type: refactor, ◼️ block: cart, ◼️ block: checkout

#3162 Add useStoreNotices tests
  assets/js/base/hooks/test/use-store-notices.js
  assets/js/base/hooks/use-store-notices.js
  assets/js/type-defs/contexts.js
Labels: scope: tests, skip-changelog, status: ready to merge

#3167 Re-enable WooCommerce dependency group rule for linting and fix errors.
  .eslintrc.js
  assets/js/base/components/payment-methods/express-payment-methods.js
  assets/js/base/components/payment-methods/express-payment/checkout-express-payment.js
  assets/js/settings/shared/set-setting.js
Labels: skip-changelog, status: ready to merge, type: build

#3165 Fix broken Express Payment Method use in the Checkout block for logged out or incognito users.
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/payment-methods/test/payment-method-data-context.js
  assets/js/blocks-registry/payment-methods/registry.js
Labels: status: ready to merge, type: blocker, type: bug, ◼️ block: checkout

#3192 Update @wordpress/scripts to latest version
  package-lock.json
  package.json
Labels: skip-changelog, status: needs review, type: build

#3193 Add puppeteer-core as dev-dependency
  package-lock.json
  renovate.json
Labels: skip-changelog, type: bug, type: build

#3200 Fix esLint rule violations for @wordpress/i18n-translator-comments rule.
  .eslintrc.js
  assets/js/atomic/blocks/product-elements/rating/block.js
  assets/js/base/components/checkbox-list/index.js
  assets/js/base/components/dropdown-selector/menu.js
  assets/js/base/components/dropdown-selector/selected-chip.js
  assets/js/base/components/payment-methods/saved-payment-method-options.js
  assets/js/base/components/quantity-selector/index.js
  assets/js/base/components/reviews/review-list-item/index.js
  assets/js/blocks/attribute-filter/block.js
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/cart-checkout/cart/empty-cart-edit/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-title.js
  assets/js/blocks/reviews/frontend-container-block.js
  assets/js/blocks/reviews/reviews-by-category/edit.js
  assets/js/blocks/reviews/reviews-by-product/edit.js
  assets/js/blocks/reviews/reviews-by-product/no-reviews-placeholder.js
  assets/js/editor-components/product-attribute-term-control/index.js
  assets/js/editor-components/product-category-control/index.js
  assets/js/editor-components/product-control/index.js
  assets/js/editor-components/product-tag-control/index.js
  assets/js/editor-components/products-control/index.js
Labels: skip-changelog, type: build, type: enhancement

#3201 Re-enable @wordpress/valid-sprintf eslint rule and fix violations
  .eslintrc.js
  assets/js/base/components/cart-checkout/shipping-rates-control/package.js
  assets/js/blocks/active-filters/utils.js
  assets/js/blocks/attribute-filter/block.js
  assets/js/blocks/reviews/reviews-by-category/edit.js
  assets/js/blocks/reviews/reviews-by-product/edit.js
  assets/js/data/schema/selectors.js
  assets/js/editor-components/product-attribute-term-control/index.js
  assets/js/editor-components/product-category-control/index.js
  assets/js/editor-components/product-tag-control/index.js
Labels: skip-changelog, type: build, type: enhancement

#3202 Enable @wordpress/no-unused-vars-before-return eslint rule and fix rule violations.
  .eslintrc.js
  assets/js/base/components/store-notices-container/snackbar-notices.js
  assets/js/base/components/store-notices-container/store-notices-container.js
Labels: skip-changelog, type: build, type: enhancement

#3203 Enable testing-library/no-await-sync-query ESLint rule and fix rule violations
  .eslintrc.js
  assets/js/blocks/cart-checkout/cart/test/block.js
Labels: skip-changelog, type: build, type: enhancement

#3189 Use light default background colour for country/state dropdowns
  assets/js/base/components/select/style.scss
Labels: scope: components, scope: styles, status: ready to merge, ◼️ block: checkout

#3135 Remove selectedToken state from PaymentMethods
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/components/payment-methods/saved-payment-method-options.js
Labels: skip-changelog, status: ready to merge, type: refactor, ◼️ block: checkout
