Repository woocommerce/woocommerce-blocks, pull requests merged in 2020-04, with the labels that each got.

#2083 Refactor checkout context provider to be more flexible and implement CartProvider
  assets/js/base/components/payment-methods/express-payment-methods.js
  assets/js/base/components/payment-methods/no-payment-methods/index.js
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/context/cart-checkout/cart/index.js
  assets/js/base/context/cart-checkout/checkout-state/actions.js
  assets/js/base/context/cart-checkout/checkout-state/constants.js
  assets/js/base/context/cart-checkout/checkout-state/event-emit.js
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/context/cart-checkout/checkout-state/reducer.js
  assets/js/base/context/cart-checkout/checkout/index.js
  assets/js/base/context/cart-checkout/index.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/payment-methods/use-payment-method-registration.js
  assets/js/base/context/editor/index.js
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/type-defs/billing.js
  assets/js/type-defs/checkout.js
  assets/js/type-defs/contexts.js
Labels: skip-changelog, status: ready to merge, type: refactor

#2089 Refactor: split up payment-method.js for stripe extension into smaller files.
  assets/js/payment-method-extensions/payment-methods/stripe/elements.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-method.js
  assets/js/payment-method-extensions/payment-methods/stripe/use-checkout-subscriptions.js
  assets/js/payment-method-extensions/payment-methods/stripe/use-element-options.js
  assets/js/payment-method-extensions/stripe-utils/type-defs.js
  assets/js/type-defs/contexts.js
Labels: scope: extensibility, skip-changelog, status: ready to merge, type: refactor

#2033 Hook up checkout validation with context
  assets/js/base/components/cart-checkout/address-form/index.js
  assets/js/base/components/cart-checkout/place-order-button/index.js
  assets/js/base/components/country-input/country-input.js
  assets/js/base/components/select/validated.js
  assets/js/base/components/state-input/state-input.js
  assets/js/base/components/text-input/validated.js
  assets/js/base/context/cart-checkout/billing/constants.js
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/base/context/cart-checkout/event-emit/emitters.js
  assets/js/base/context/cart-checkout/event-emit/reducer.js
  assets/js/base/context/cart-checkout/event-emit/test/emitters.js
  assets/js/base/context/cart-checkout/payment-methods/reducer.js
  assets/js/base/context/cart-checkout/shipping/index.js
  assets/js/base/context/cart-checkout/validation/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/payment-method-extensions/payment-methods/stripe/use-checkout-subscriptions.js
Labels: skip-changelog, status: ready to merge

#2099 Update Checkout skeleton to match layout introduced in #2041
  src/BlockTypes/Checkout.php
Labels: skip-changelog, status: ready to merge

#2079 Cart item validation and notices in cart/checkout
  assets/js/base/hooks/cart/test/use-store-cart.js
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/checkout-order-error/constants.js
  assets/js/blocks/cart-checkout/checkout/checkout-order-error/index.js
  assets/js/type-defs/hooks.js
  src/RestApi/StoreApi/Schemas/CartSchema.php
  src/RestApi/StoreApi/Schemas/ErrorSchema.php
  src/RestApi/StoreApi/Utilities/CartController.php
  src/RestApi/StoreApi/Utilities/OrderController.php
  src/RestApi/StoreApi/Utilities/ReserveStock.php
Labels: scope: rest-api, status: ready to merge

#2102 fix broken e2e-tests
  package-lock.json
  package.json
Labels: scope: tests, skip-changelog, status: ready to merge, type: build

#2090 Add Payment Methods Registry for registering scripts and data
  assets/js/payment-method-extensions/express-payment/apple-pay/index.js
  assets/js/payment-method-extensions/index.js
  assets/js/payment-method-extensions/payment-methods/cheque/constants.js
  assets/js/payment-method-extensions/payment-methods/cheque/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/apple-pay/apple-pay-express.js
  assets/js/payment-method-extensions/payment-methods/stripe/apple-pay/apple-pay-preview.js
  assets/js/payment-method-extensions/payment-methods/stripe/apple-pay/constants.js
  assets/js/payment-method-extensions/payment-methods/stripe/apple-pay/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/apple-pay/normalize.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/cc.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/constants.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/elements.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/payment-method.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-checkout-subscriptions.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-element-options.js
  assets/js/payment-method-extensions/payment-methods/stripe/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/constants.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/load-stripe.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/type-defs.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/utils.js
  assets/js/payment-method-extensions/utils/index.js
  bin/webpack-helpers.js
  package-lock.json
  src/Assets/PaymentMethodAssets.php
  src/BlockTypes/AbstractBlock.php
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
  src/Domain/Bootstrap.php
  src/Library.php
  src/PaymentMethodIntegrations/Stripe.php
  src/Payments/Integrations/AbstractPaymentMethodType.php
  src/Payments/Integrations/Cheque.php
  src/Payments/Integrations/Stripe.php
  src/Payments/PaymentMethodRegistry.php
  src/Payments/PaymentMethodTypeInterface.php
Labels: status: ready to merge

#1978 disable proceed to checkout if rates are loading or being selected
  assets/js/base/context/cart-checkout/shipping/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/checkout-button/index.js
Labels: action: needs feedback, status: ready to merge, type: bug

#2101 Respect needs_shipping in Cart and Checkout
  assets/js/base/components/cart-checkout/totals/totals-fees-item/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/sidebar/index.js
Labels: skip-changelog, status: ready to merge

#2109 Checkout: fix skeleton and responsive styles
  assets/js/base/components/cart-checkout/form-step/style.scss
  assets/js/base/components/cart-checkout/form/style.scss
  assets/js/base/components/cart-checkout/totals/totals-coupon-code-input/style.scss
  assets/js/base/components/sidebar-layout/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/style.scss
  src/BlockTypes/Checkout.php
Labels: skip-changelog, status: ready to merge

#2113 Ensure `AbstractBlock::enqueue_data` is only run once in the editor request.
  src/BlockTypes/AbstractBlock.php
  src/BlockTypes/ActiveFilters.php
  src/BlockTypes/AllReviews.php
  src/BlockTypes/AttributeFilter.php
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
  src/BlockTypes/PriceFilter.php
  src/BlockTypes/ReviewsByCategory.php
  src/BlockTypes/ReviewsByProduct.php
Labels: skip-changelog, status: ready to merge

#2105 Switch 'Try reloading the page' from links to buttons
  assets/css/abstracts/_mixins.scss
  assets/css/style.scss
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/frontend.js
Labels: skip-changelog, status: ready to merge

#2119 Fix runaway state change loop for showing validation errors in event subscription.
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: scope: components, status: ready to merge, type: bug

#2117 Add forcing source map on production to analyze tree-shaking
  package-lock.json
  package.json
  webpack.config.js
Labels: skip-changelog, status: ready to merge, type: performance

#2103 Update add to cart to useStoreCart hook
  assets/js/atomic/components/product/button/index.js
  assets/js/base/hooks/index.js
  assets/js/base/hooks/use-store-add-to-cart.js
  assets/js/data/cart/actions.js
  assets/js/type-defs/hooks.js
  src/RestApi.php
  src/RestApi/StoreApi/Routes/CartAddItem.php
  src/RestApi/StoreApi/RoutesController.php
  src/RestApi/StoreApi/SchemaController.php
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  src/RestApi/StoreApi/Schemas/CartSchema.php
  src/RestApi/StoreApi/Schemas/CheckoutSchema.php
  src/RestApi/StoreApi/Schemas/OrderSchema.php
  src/RestApi/StoreApi/Schemas/ProductSchema.php
  tests/php/RestApi/StoreApi/Routes/Cart.php
  tests/php/RestApi/StoreApi/Routes/CartCoupons.php
  tests/php/RestApi/StoreApi/Routes/CartItems.php
  tests/php/RestApi/StoreApi/Routes/ProductAttributeTerms.php
  tests/php/RestApi/StoreApi/Routes/ProductAttributes.php
  tests/php/RestApi/StoreApi/Routes/ProductCollectionData.php
  tests/php/RestApi/StoreApi/Routes/Products.php
Labels: skip-changelog, status: ready to merge

#2116 Refactor payment method interface to remove payment status dispatcher
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/payment-method-extensions/payment-methods/stripe/apple-pay/apple-pay-express.js
  assets/js/type-defs/registered-payment-method-props.js
Labels: scope: extensibility, skip-changelog, status: ready to merge, type: refactor

#1999 Storefront compatibility for sticky proceed to checkout button on mobile
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  src/BlockTypes/Cart.php
Labels: status: ready to merge

#2115 Update stripe payment methods to work with new event emitters
  assets/js/base/components/payment-methods/express-checkout.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/payment-method-extensions/payment-methods/stripe/apple-pay/apple-pay-express.js
  assets/js/payment-method-extensions/payment-methods/stripe/apple-pay/normalize.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/payment-method.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-checkout-subscriptions.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/utils.js
  assets/js/type-defs/contexts.js
  assets/js/type-defs/registered-payment-method-props.js
Labels: scope: extensibility, skip-changelog, status: ready to merge, type: refactor

#2120 Implement stripe server-side handling (stripe cc)
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-checkout-subscriptions.js
  assets/js/type-defs/payments.js
Labels: scope: extensibility, skip-changelog, status: ready to merge, type: enhancement

#2128 Disable checkout form in the editor
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/payment-methods/no-payment-methods/index.js
  assets/js/base/components/payment-methods/no-payment-methods/style.scss
  assets/js/base/components/payment-methods/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/no-shipping-placeholder/index.js
  assets/js/blocks/cart-checkout/checkout/no-shipping-placeholder/style.scss
Labels: status: ready to merge

#2129 Use mousedown event so view switches before blur event
  assets/js/components/view-switcher/index.js
Labels: status: ready to merge

#2057 Remove Keep me updated
  assets/js/base/components/text-input/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: status: ready to merge

#2132 Bump required jetpack autoloader version
  composer.json
  composer.lock
Labels: status: ready to merge

#2135 Update CONTRIBUTING links
  .github/CONTRIBUTING.md
Labels: status: ready to merge

#2136 Revert "Record a tracks event when merchant toggles cart shipping calculator:"
  assets/js/base/utils/index.js
  assets/js/base/utils/tracks.js
  assets/js/blocks/cart-checkout/cart/edit.js
Labels: status: ready to merge

#2106 Disable continue to checkout if Item quantity is being updated and immediately remove items.
  assets/js/base/components/cart-checkout/product-name/index.js
  assets/js/base/hooks/cart/test/use-store-cart-item-quantity.js
  assets/js/base/hooks/cart/use-store-cart-item-quantity.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/data/cart/action-types.js
  assets/js/data/cart/actions.js
  assets/js/data/cart/reducers.js
  assets/js/data/cart/selectors.js
  assets/js/type-defs/hooks.js
Labels: skip-changelog, status: ready to merge, type: refactor

#2138 Show "save payment information" checkbox only if customer ID > 0
  assets/js/base/context/cart-checkout/checkout-state/constants.js
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/payment-method.js
  assets/js/type-defs/contexts.js
  assets/js/type-defs/registered-payment-method-props.js
  src/RestApi/StoreApi/Schemas/CheckoutSchema.php
  src/RestApi/StoreApi/Schemas/OrderSchema.php
Labels: status: ready to merge

#2137 CheckboxControl: stop using Gutenberg's CheckboxControl
  assets/js/base/components/checkbox-control/index.js
  assets/js/base/components/checkbox-control/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  bin/webpack-helpers.js
Labels: scope: components, skip-changelog, status: ready to merge

#2134 Get preview data from Editor Context /
  assets/js/base/context/editor/index.js
  assets/js/base/hooks/cart/test/use-store-cart.js
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/previews/cart.js
  assets/js/type-defs/contexts.js
Labels: status: ready to merge, type: performance

#2133 Don't show "select" labels for shipping or payment method steps if there is only one option
  assets/js/base/components/cart-checkout/form-step/index.js
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/shipping-rate-selector.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/utils.js
Labels: status: ready to merge

#2153 Use new util functions in ShippingRatesControl
  assets/js/base/components/cart-checkout/shipping-rates-control/index.js
  assets/js/base/utils/index.js
  assets/js/base/utils/shipping-rates.js
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: scope: components, skip-changelog, status: ready to merge

#2144 Fix cached shipping fees on consecutive orders
  src/RestApi.php
  src/RestApi/Controllers/Cart.php
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  src/RestApi/StoreApi/Schemas/OrderSchema.php
  src/RestApi/StoreApi/Utilities/CartController.php
  src/RestApi/StoreApi/Utilities/OrderController.php
  src/RestApi/StoreApi/Utilities/ProductQuery.php
  woocommerce-gutenberg-products-block.php
Labels: status: ready to merge

#2146 Refactor some of the shipping hooks/context usage
  assets/js/base/components/cart-checkout/shipping-calculator/index.js
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/index.js
  assets/js/base/context/cart-checkout/shipping/index.js
  assets/js/base/hooks/cart/test/use-store-cart.js
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/base/hooks/shipping/index.js
  assets/js/base/hooks/shipping/use-shipping-rates.js
  assets/js/base/hooks/test/use-shipping-rates.js
  assets/js/type-defs/hooks.js
Labels: status: ready to merge

#2161 Render the checkout shortcode if viewing an unsupported endpoint
  src/BlockTypes/Checkout.php
Labels: status: ready to merge

#2160 Update previews and editor styles for cart and checkout blocks
  .sources/block-previews.sketch
  assets/img/beanie.jpg
  assets/img/cap.jpg
  assets/img/cart-preview.svg
  assets/img/checkout-preview.svg
  assets/img/pennant.jpg
  assets/js/base/components/cart-checkout/totals/totals-coupon-code-input/index.js
  assets/js/blocks/cart-checkout/cart/attributes.js
  assets/js/blocks/cart-checkout/cart/block.js
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/cart/empty-cart-edit/icon-data-uri.js
  assets/js/blocks/cart-checkout/cart/empty-cart-edit/index.js
  assets/js/blocks/cart-checkout/cart/empty-cart-edit/style.scss
  assets/js/blocks/cart-checkout/cart/example.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/full-cart/editor.scss
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/cart/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/editor.scss
  assets/js/blocks/cart-checkout/checkout/index.js
  assets/js/blocks/products/all-products/block.js
  assets/js/previews/cart-block.js
  assets/js/previews/cart.js
  assets/js/previews/checkout-block.js
  assets/js/previews/index.js
  assets/js/previews/product-image.js
  assets/js/previews/products.js
Labels: status: ready to merge

#2162 Increase specificity of `wc-block-totals__change-address-button`
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/style.scss
Labels: status: ready to merge

#2156 Handle errors in processOrder
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/base/context/store-notices-context.js
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: skip-changelog, status: ready to merge

#2163 Move calculating state outside of checkout state
  assets/js/base/components/payment-methods/saved-payment-method-options.js
  assets/js/base/context/cart-checkout/checkout-state/constants.js
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/context/cart-checkout/checkout-state/reducer.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/payment-methods/reducer.js
  assets/js/base/context/cart-checkout/shipping/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/type-defs/checkout.js
Labels: status: ready to merge, type: refactor

#2127 Convert apple pay integration to payment request integration and finish implementation
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/context/cart-checkout/checkout/index.js
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/base/context/cart-checkout/event-emit/emitter-callback.js
  assets/js/base/context/cart-checkout/event-emit/emitters.js
  assets/js/base/context/cart-checkout/event-emit/test/emitters.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/shipping/event-emit.js
  assets/js/base/context/cart-checkout/shipping/index.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/base/utils/address.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/payment-method.js
  assets/js/payment-method-extensions/payment-methods/stripe/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/apple-pay-preview.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/constants.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/payment-request-express.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/load-stripe.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/normalize.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/utils.js
  assets/js/type-defs/contexts.js
  assets/js/type-defs/registered-payment-method-props.js
  src/Payments/Integrations/Stripe.php
  src/RestApi/StoreApi/Routes/Checkout.php
Labels: scope: extensibility, status: ready to merge, type: refactor

#2169 Use cart data to provide country and currency_code for payment method registration config
  assets/js/base/context/cart-checkout/payment-methods/use-payment-method-registration.js
  assets/js/blocks-registry/payment-methods/express-payment-method-config.js
  assets/js/blocks-registry/payment-methods/payment-method-config.js
  assets/js/payment-method-extensions/payment-methods/cheque/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/apple-pay/apple-pay-express.js
  assets/js/payment-method-extensions/payment-methods/stripe/apple-pay/apple-pay-preview.js
  assets/js/payment-method-extensions/payment-methods/stripe/apple-pay/constants.js
  assets/js/payment-method-extensions/payment-methods/stripe/apple-pay/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/index.js
  assets/js/payment-method-extensions/utils/index.js
Labels: scope: extensibility, status: ready to merge, type: bug, type: refactor

#2176 Prevent data hydration on REST requests
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
Labels: scope: rest-api, status: ready to merge

#2178 Fix prices overflowing in some widths in the Order summary panel
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: skip-changelog, status: ready to merge

#2175 Update cart after conflicts
  assets/js/data/cart/actions.js
  src/RestApi/StoreApi/Routes/AbstractCartRoute.php
  src/RestApi/StoreApi/Routes/AbstractRoute.php
  src/RestApi/StoreApi/Routes/Cart.php
  src/RestApi/StoreApi/Routes/CartAddItem.php
  src/RestApi/StoreApi/Routes/CartApplyCoupon.php
  src/RestApi/StoreApi/Routes/CartRemoveCoupon.php
  src/RestApi/StoreApi/Routes/CartRemoveItem.php
  src/RestApi/StoreApi/Routes/CartSelectShippingRate.php
  src/RestApi/StoreApi/Routes/CartUpdateItem.php
  tests/php/RestApi/StoreApi/Routes/Cart.php
Labels: scope: rest-api, status: ready to merge

#2177 Check if cart needs payment before showing payment methods
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/base/hooks/cart/test/use-store-cart.js
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/data/cart/test/selectors.js
  assets/js/previews/cart.js
  assets/js/type-defs/hooks.js
  src/RestApi/StoreApi/README.md
  src/RestApi/StoreApi/Routes/Checkout.php
  src/RestApi/StoreApi/Schemas/CartSchema.php
  tests/php/RestApi/StoreApi/Routes/Cart.php
Labels: skip-changelog, status: ready to merge

#2181 fix broken labels on twentyTwenty
  assets/js/base/components/text-input/style.scss
Labels: skip-changelog, status: ready to merge, type: bug

#2170 Refactor logic for handling active payment method with express payment methods via checkout
  assets/js/base/components/payment-methods/express-payment-methods.js
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/payment-methods/reducer.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/blocks-registry/payment-methods/assertions.js
  assets/js/blocks-registry/payment-methods/express-payment-method-config.js
  assets/js/blocks-registry/payment-methods/payment-method-config.js
  assets/js/blocks-registry/payment-methods/registry.js
  assets/js/payment-method-extensions/payment-methods/cheque/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/payment-request-express.js
  assets/js/type-defs/registered-payment-method-props.js
  src/Library.php
  src/Payments/Integrations/Stripe.php
  src/RestApi/StoreApi/Routes/Checkout.php
Labels: scope: extensibility, status: ready to merge, type: refactor

#2184 Prevent auto-scroll to invalid fields
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: skip-changelog, status: ready to merge

#2185 Fix currency format in On Sale badge
  assets/js/base/components/cart-checkout/product-sale-badge/index.js
  assets/js/base/utils/price.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: status: ready to merge

#2187 Sync name and company to account
  src/RestApi/StoreApi/Utilities/OrderController.php
Labels: status: ready to merge

#2188 Use icons directly from stripe
  assets/js/base/components/payment-methods/style.scss
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/cc.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/payment-method.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/type-defs.js
  src/Payments/Integrations/Stripe.php
Labels: skip-changelog, status: ready to merge

#2190 Implement editor previews for stripe cc and check payment methods
  assets/js/payment-method-extensions/payment-methods/cheque/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/index.js
Labels: scope: extensibility, skip-changelog, status: ready to merge

#2202 respect SHIPPING_ENABLED in Cart and Checkout blocks in Editor
  assets/js/previews/cart.js
Labels: skip-changelog, status: ready to merge, type: bug

#2208 Fix build styles incosistencies
  assets/css/abstracts/_mixins.scss
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/style.scss
  assets/js/base/components/radio-control/_mixin.scss
  assets/js/base/components/select/style.scss
  assets/js/base/components/sidebar-layout/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
  bin/webpack-helpers.js
Labels: skip-changelog, status: ready to merge

#2189 Refactor checkout status and event emitters to support stripe intents and more complex payment methods.
  assets/js/base/context/cart-checkout/checkout-state/actions.js
  assets/js/base/context/cart-checkout/checkout-state/constants.js
  assets/js/base/context/cart-checkout/checkout-state/event-emit.js
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/context/cart-checkout/checkout-state/reducer.js
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/base/context/cart-checkout/payment-methods/event-emit.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/hooks/checkout/index.js
  assets/js/base/hooks/checkout/use-emit-response.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/payment-method.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-checkout-subscriptions.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-payment-intents.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/payment-request-express.js
  assets/js/type-defs/checkout.js
  assets/js/type-defs/contexts.js
  assets/js/type-defs/hooks.js
  assets/js/type-defs/registered-payment-method-props.js
  src/Library.php
  src/Payments/Integrations/Stripe.php
  src/Payments/PaymentContext.php
  src/RestApi/StoreApi/Schemas/CheckoutSchema.php
Labels: scope: extensibility, status: ready to merge, type: refactor

#2214 Lazy load stripe.js and preserve payment method registration order.
  assets/js/base/context/cart-checkout/payment-methods/actions.js
  assets/js/base/context/cart-checkout/payment-methods/constants.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/payment-methods/reducer.js
  assets/js/base/context/cart-checkout/payment-methods/use-payment-method-registration.js
  src/Assets.php
  src/Payments/Integrations/Stripe.php
Labels: scope: extensibility, status: ready to merge, type: bug, type: enhancement

#2151 show preview "saved payment methods" in editor
  assets/js/base/components/payment-methods/saved-payment-method-options.js
  assets/js/base/context/cart-checkout/checkout/index.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/editor/index.js
  assets/js/base/hooks/cart/test/use-store-cart.js
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/previews/index.js
  assets/js/previews/saved-payment-methods.js
  assets/js/type-defs/contexts.js
Labels: skip-changelog, status: ready to merge

#2179 Fix entities in coupon validation error messages
  assets/js/base/hooks/cart/use-store-cart-coupons.js
  src/RestApi/StoreApi/Routes/CartApplyCoupon.php
Labels: status: ready to merge

#2228 Handle errors when loading payment methods
  assets/js/base/components/block-error-boundary/index.js
  assets/js/base/components/payment-methods/payment-method-error-boundary.js
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/context/cart-checkout/payment-methods/use-payment-method-registration.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/load-stripe.js
Labels: skip-changelog, status: ready to merge

#2232 Fix global validation error reporting and cheque payment method regressions
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/context/cart-checkout/checkout-state/reducer.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/payment-method-extensions/payment-methods/cheque/index.js
Labels: scope: extensibility, status: ready to merge, type: bug

#2186 Show feedback on buttons/checkout when processing
  assets/js/base/components/cart-checkout/button/index.js
  assets/js/base/components/cart-checkout/button/stories/index.js
  assets/js/base/components/cart-checkout/button/style.scss
  assets/js/base/components/cart-checkout/form-step/index.js
  assets/js/base/components/cart-checkout/form-step/style.scss
  assets/js/base/components/cart-checkout/place-order-button/index.js
  assets/js/base/components/cart-checkout/totals/totals-coupon-code-input/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/checkout-button/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/style.scss
  assets/js/icons/index.js
  assets/js/icons/library/done.js
Labels: status: ready to merge

#2209 Add block asset documentation
  docs/contributors/block-assets.md
Labels: scope: documentation, status: ready to merge

#2238 Capture legacy payment notices
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/context/cart-checkout/checkout-state/reducer.js
  src/Library.php
Labels: status: ready to merge

#2203 create a notice instead of throwing an errors if there is an error for shipping update
  assets/js/base/hooks/shipping/use-shipping-address.js
Labels: status: ready to merge, type: bug

#2234 Improve "sold individually" validation
  assets/js/base/hooks/use-store-add-to-cart.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/checkout/checkout-order-error/constants.js
  assets/js/blocks/cart-checkout/checkout/checkout-order-error/index.js
  src/RestApi/StoreApi/Routes/CartItemsByKey.php
  src/RestApi/StoreApi/Routes/CartUpdateItem.php
  src/RestApi/StoreApi/Utilities/CartController.php
Labels: status: ready to merge

#2241 Update payment method data context to use noticeContexts.
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
Labels: scope: extensibility, status: ready to merge, type: enhancement

#2230 Documentation for the Store API
  docs/readme.md
  src/BlockTypes/Checkout.php
  src/RestApi/StoreApi/README.md
  src/RestApi/StoreApi/Routes/AbstractRoute.php
  src/RestApi/StoreApi/Routes/CartUpdateShipping.php
  src/RestApi/StoreApi/Routes/Checkout.php
  src/RestApi/StoreApi/docs/cart-coupons.md
  src/RestApi/StoreApi/docs/cart-items.md
  src/RestApi/StoreApi/docs/cart.md
  src/RestApi/StoreApi/docs/checkout.md
  src/RestApi/StoreApi/docs/nonce-tokens.md
  src/RestApi/StoreApi/docs/product-attribute-terms.md
  src/RestApi/StoreApi/docs/product-attributes.md
  src/RestApi/StoreApi/docs/product-collection-data.md
  src/RestApi/StoreApi/docs/products.md
Labels: scope: documentation, status: ready to merge

#2237 rename docker-related npm scripts so it's clear they are e2e infrastructure
  .travis.yml
  package.json
Labels: status: ready to merge

#2246 Add documentation for checkout flow and payment method integrations
  assets/js/blocks-registry/payment-methods/registry.js
  docs/block-client-apis/README.md
  docs/block-client-apis/checkout/checkout-api.md
  docs/extensibility/README.md
  docs/extensibility/checkout-flow-and-events.md
  docs/extensibility/payment-method-integration.md
Labels: scope: documentation, scope: extensibility, skip-changelog, status: ready to merge

#2245 Coupon and Cart Item Validation Fixes
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/base/hooks/cart/test/use-store-cart.js
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/checkout-order-error/constants.js
  assets/js/blocks/cart-checkout/checkout/checkout-order-error/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-checkout-subscriptions.js
  assets/js/type-defs/hooks.js
  src/Library.php
  src/RestApi/StoreApi/Routes/AbstractCartRoute.php
  src/RestApi/StoreApi/Routes/AbstractRoute.php
  src/RestApi/StoreApi/Routes/Checkout.php
  src/RestApi/StoreApi/Routes/RouteException.php
  src/RestApi/StoreApi/Schemas/CartSchema.php
  src/RestApi/StoreApi/Utilities/CartController.php
  src/RestApi/StoreApi/Utilities/NoticeHandler.php
  src/RestApi/StoreApi/Utilities/OrderController.php
Labels: scope: rest-api, status: ready to merge

#2253 Individually used coupons were not replacing other applied coupons
  src/RestApi/StoreApi/Utilities/CartController.php
Labels: status: ready to merge

#2247 Do not scroll to top when payment methods have an error
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/base/hooks/use-store-notices.js
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: scope: blocks, skip-changelog, status: ready to merge

#2248 Improvements to REST API performance
  src/Domain/Bootstrap.php
  src/Library.php
  src/RestApi.php
  src/RestApi/StoreApi/Routes/CartSelectShippingRate.php
  src/RestApi/StoreApi/Utilities/OrderController.php
Labels: status: ready to merge, type: performance

#2258 Check for instance of WP_Block in render_callback
  src/BlockTypes/AbstractBlock.php
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
Labels: status: ready to merge

#2256 Add quantity limit at product level
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  src/BlockTypes/Cart.php
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  src/RestApi/StoreApi/Utilities/CartController.php
  src/RestApi/StoreApi/docs/cart-items.md
  src/RestApi/StoreApi/docs/cart.md
Labels: status: ready to merge

#2255 Fix snackbar being too high and covering coupon section
  assets/js/base/components/store-notices-container/style.scss
Labels: status: ready to merge, type: bug

#2196 Testing checklist
  docs/testing/cart-checkout/coupons.md
  docs/testing/cart-checkout/cross-browser.md
  docs/testing/cart-checkout/editor.md
  docs/testing/cart-checkout/general-flow.md
  docs/testing/cart-checkout/items.md
  docs/testing/cart-checkout/payment.md
  docs/testing/cart-checkout/readme.md
  docs/testing/cart-checkout/shipping.md
  docs/testing/cart-checkout/taxes.md
Labels: action: needs feedback

#2259 Revert "Improvements to REST API performance"
  src/Domain/Bootstrap.php
  src/Library.php
  src/RestApi.php
  src/RestApi/StoreApi/Routes/CartSelectShippingRate.php
  src/RestApi/StoreApi/Utilities/OrderController.php
Labels: status: ready to merge

#2261 Move blocks to stable flag
  assets/js/blocks/cart-checkout/cart/index.js
  assets/js/blocks/cart-checkout/checkout/index.js
  src/Assets.php
  src/Domain/Bootstrap.php
  src/Library.php
Labels: status: ready to merge

#2249 Modify emitEventWithAbort so it handles non object or invalid object responses.
  assets/js/base/context/cart-checkout/event-emit/emitters.js
  assets/js/base/context/cart-checkout/event-emit/test/emitters.js
Labels: scope: extensibility, status: ready to merge, type: enhancement

#2264 Checkout: Rename address2 attribute
  assets/js/blocks/cart-checkout/checkout/attributes.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  tests/e2e-tests/specs/backend/__snapshots__/checkout.test.js.snap
Labels: status: ready to merge

#2265 Decode entities in cart shipping data
  assets/js/base/hooks/cart/use-store-cart.js
Labels: status: ready to merge

#2268 Decode billing address data from the server
  assets/js/base/context/cart-checkout/billing/constants.js
  assets/js/type-defs/billing.js
Labels: status: ready to merge

#2269 Prevent All Products block from crashing when error has no json method
  assets/js/data/shared-controls.js
Labels: skip-changelog, status: ready to merge

#2275 Fixes to totals recalculation and taxes
  assets/js/base/components/cart-checkout/totals/totals-taxes-item/index.js
  assets/js/settings/blocks/constants.js
  src/Assets.php
  src/RestApi.php
  src/RestApi/StoreApi/Routes/AbstractCartRoute.php
  src/RestApi/StoreApi/Routes/CartSelectShippingRate.php
  src/RestApi/StoreApi/Routes/CartUpdateShipping.php
  src/RestApi/StoreApi/Routes/Checkout.php
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  src/RestApi/StoreApi/Schemas/CartSchema.php
  src/RestApi/StoreApi/Schemas/CartShippingRateSchema.php
  src/RestApi/StoreApi/Utilities/OrderController.php
  src/RestApi/StoreApi/Utilities/ProductQuery.php
Labels: status: ready to merge

#2270 Abstract Page selector and fix some issues in sidebar.
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/editor.scss
  assets/js/components/page-selector/index.js
  assets/js/components/utils/index.js
Labels: status: ready to merge, type: enhancement

#2283 Cart & Checkout: Update styles to better match designs
  assets/css/abstracts/_mixins.scss
  assets/js/base/components/cart-checkout/button/style.scss
  assets/js/base/components/cart-checkout/form-step/index.js
  assets/js/base/components/cart-checkout/form-step/style.scss
  assets/js/base/components/cart-checkout/policies/style.scss
  assets/js/base/components/cart-checkout/product-low-stock-badge/style.scss
  assets/js/base/components/cart-checkout/product-metadata/style.scss
  assets/js/base/components/cart-checkout/product-name/style.scss
  assets/js/base/components/cart-checkout/product-sale-badge/style.scss
  assets/js/base/components/cart-checkout/return-to-cart-button/style.scss
  assets/js/base/components/cart-checkout/totals/totals-coupon-code-input/style.scss
  assets/js/base/components/cart-checkout/totals/totals-item/style.scss
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/product-list/style.scss
  assets/js/base/components/quantity-selector/style.scss
  assets/js/base/components/radio-control/_mixin.scss
  assets/js/base/components/select/style.scss
  assets/js/base/components/sidebar-layout/style.scss
  assets/js/base/components/tabs/style.scss
  assets/js/base/components/text-input/style.scss
  assets/js/base/hooks/cart/use-store-cart-coupons.js
  assets/js/base/hooks/use-store-add-to-cart.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: scope: accessibility, skip-changelog, status: ready to merge

#2285 Add screen reader text to remove item icon
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
Labels: scope: accessibility, skip-changelog, status: ready to merge

#2266 Trigger fragment refresh after editing cart item quantities
  assets/js/atomic/components/product/button/index.js
  assets/js/base/hooks/cart/use-store-cart-item-quantity.js
  assets/js/base/utils/index.js
  assets/js/base/utils/legacy-events.js
Labels: status: ready to merge

#2276 Support itemized taxes in cart/checkout
  assets/js/base/components/cart-checkout/totals/totals-taxes-item/index.js
  assets/js/settings/blocks/constants.js
  src/Assets.php
Labels: status: ready to merge

#2286 Avoid loading Assets API during REST requests
  src/Assets.php
  src/Assets/PaymentMethodAssets.php
  src/BlockTypes/Checkout.php
  src/Domain/Bootstrap.php
  src/Library.php
  src/Payments/Api.php
  src/Payments/PaymentMethodRegistry.php
  src/RestApi.php
Labels: status: ready to merge

#2273 Inject block attributes rather than save them
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/index.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/blocks/cart-checkout/checkout/index.js
  assets/js/utils/render-frontend.js
  src/BlockTypes/AbstractBlock.php
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
  tests/e2e-tests/specs/backend/__snapshots__/cart.test.js.snap
  tests/e2e-tests/specs/backend/__snapshots__/checkout.test.js.snap
Labels: status: ready to merge

#2278 Add notice errors to add to cart button and All products
  assets/js/base/hooks/use-store-add-to-cart.js
  assets/js/blocks/products/all-products/frontend.js
  assets/js/data/cart/actions.js
Labels: status: ready to merge, type: enhancement

#2318 Remove order note
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: status: ready to merge, type: bug

#2287 Table creation validation for install routine
  src/Domain/Bootstrap.php
  src/Installer.php
  src/Library.php
  src/StoreApi/Utilities/ReserveStock.php
  tests/bootstrap.php
Labels: status: ready to merge

#2347 Quantity badge white separator + center tweak
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: skip-changelog, status: ready to merge

#2328 Update shipping endpoint should extend the correct route
  src/StoreApi/Routes/CartUpdateShipping.php
Labels: status: ready to merge, type: bug

#2289 Pin WooCommerce version
  package-lock.json
  package.json
Labels: status: ready to merge

#2330 Import from `@woocommerce/settings` in `@woocommerce/block-settings`
  assets/js/settings/blocks/constants.js
  assets/js/settings/blocks/store-api-nonce.js
Labels: status: ready to merge, type: bug, type: build, type: performance

#2348 Fix low stock badge not breaking in a new line
  assets/js/base/components/cart-checkout/product-name/style.scss
Labels: skip-changelog, status: ready to merge

#2267 Update payment method config to include icons
  assets/img/payment-methods/alipay.svg
  assets/img/payment-methods/amex.svg
  assets/img/payment-methods/bancontact.svg
  assets/img/payment-methods/diners.svg
  assets/img/payment-methods/discover.svg
  assets/img/payment-methods/eps.svg
  assets/img/payment-methods/giropay.svg
  assets/img/payment-methods/ideal.svg
  assets/img/payment-methods/jcb.svg
  assets/img/payment-methods/laser.svg
  assets/img/payment-methods/maestro.svg
  assets/img/payment-methods/mastercard.svg
  assets/img/payment-methods/multibanco.svg
  assets/img/payment-methods/p24.svg
  assets/img/payment-methods/sepa.svg
  assets/img/payment-methods/sofort.svg
  assets/img/payment-methods/unionpay.svg
  assets/img/payment-methods/visa.svg
  assets/img/payment-methods/wechat.svg
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/cart-checkout/payment-method-icons/common-icons.js
  assets/js/base/components/cart-checkout/payment-method-icons/index.js
  assets/js/base/components/cart-checkout/payment-method-icons/payment-method-icon.js
  assets/js/base/components/cart-checkout/payment-method-icons/style.scss
  assets/js/base/components/cart-checkout/payment-method-icons/utils.js
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/components/tabs/index.js
  assets/js/base/components/tabs/style.scss
  assets/js/base/context/cart-checkout/cart/index.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/blocks-registry/payment-methods/assertions.js
  assets/js/blocks-registry/payment-methods/payment-method-config.js
  assets/js/blocks/cart-checkout/cart/checkout-button/index.js
  assets/js/blocks/cart-checkout/cart/checkout-button/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/checkout-button/american-express-logo.js
  assets/js/blocks/cart-checkout/cart/full-cart/checkout-button/payment-logos.js
  assets/js/blocks/cart-checkout/cart/full-cart/checkout-button/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/payment-method-extensions/payment-methods/cheque/index.js
  assets/js/payment-method-extensions/payment-methods/paypal/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/payment-method.js
  src/Payments/Api.php
  src/Payments/Integrations/Stripe.php
  tests/js/jest.config.json
  tsconfig.json
Labels: status: ready to merge

#2346 align cart main heading and totals sidebar heading
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: skip-changelog, status: ready to merge

#2353 Update API status codes
  assets/js/data/shared-controls.js
  src/StoreApi/Routes/AbstractRoute.php
  src/StoreApi/Routes/CartRemoveCoupon.php
  src/StoreApi/Routes/CartSelectShippingRate.php
  src/StoreApi/Utilities/CartController.php
  src/StoreApi/Utilities/ReserveStock.php
  src/StoreApi/docs/cart.md
  tests/php/StoreApi/Routes/Cart.php
  tests/php/StoreApi/Routes/CartItems.php
Labels: status: ready to merge

#2354 Fix Cart block interaction in the editor (mobile)
  assets/js/base/components/store-notices-container/snackbar-notices.js
  assets/js/base/components/store-notices-container/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/editor.scss
Labels: skip-changelog, status: ready to merge, type: blocker, type: bug

#2352 Fix payment method error notices issues
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/validation/index.js
  assets/js/base/context/store-notices-context.js
Labels: skip-changelog, status: ready to merge, type: bug

#2355 Checkout Block Order Summary Styles
  assets/js/blocks/cart-checkout/checkout/sidebar/order-summary-item.js
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: status: ready to merge

#2362 Payment methods `placeOrderButtonLabel` config
  assets/js/base/components/cart-checkout/place-order-button/index.js
  assets/js/base/context/cart-checkout/cart/index.js
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/context/cart-checkout/checkout/index.js
  assets/js/base/hooks/checkout/test/use-checkout-submit.js
  assets/js/base/hooks/checkout/use-checkout-submit.js
  assets/js/blocks-registry/payment-methods/payment-method-config.js
  assets/js/payment-method-extensions/payment-methods/paypal/index.js
  assets/js/type-defs/contexts.js
  docs/block-client-apis/checkout/checkout-api.md
Labels: status: ready to merge

#2291 Make all font sizes accessible + add docs about font-size() mixin
  assets/css/abstracts/_mixins.scss
  assets/js/base/components/payment-methods/no-payment-methods/style.scss
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/select/style.scss
  assets/js/base/components/text-input/style.scss
  assets/js/blocks/attribute-filter/editor.scss
  assets/js/blocks/cart-checkout/checkout/editor.scss
  assets/js/blocks/cart-checkout/checkout/no-shipping-placeholder/style.scss
  assets/js/blocks/price-filter/editor.scss
  assets/js/blocks/product-categories/style.scss
  assets/js/blocks/product-search/style.scss
  assets/js/blocks/products/editor.scss
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-element-options.js
  docs/contributors/coding-guidelines.md
Labels: skip-changelog, status: ready to merge

#2364 only show checkout login prompt if store allows it
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/settings/blocks/constants.js
  src/Assets.php
Labels: status: ready to merge
