Repository woocommerce/woocommerce-blocks, pull requests merged in 2020-07, with the labels that each got.

#2779 Sort states and countries correctly using `deep_sort_with_accents`
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
Labels: status: ready to merge, ◼️ block: cart, ◼️ block: checkout

#1758 update wporg readme docs to link to primary docs on docs.woocommerce.com
  readme.txt
Labels: scope: documentation, status: ready to merge, type: cooldown

#2799 basic e2e test for instantiating All Reviews block
  tests/e2e-tests/config/setup.js
  tests/e2e-tests/fixtures/fixture-loaders.js
  tests/e2e-tests/specs/backend/__fixtures__/all-reviews.fixture.json
  tests/e2e-tests/specs/backend/all-reviews.test.js
Labels: scope: tests, skip-changelog, status: ready to merge

#2768 Release: 2.8.0
  docs/testing/releases/260.md
  docs/testing/releases/261.md
  docs/testing/releases/270.md
  docs/testing/releases/271.md
  docs/testing/releases/280.md
  docs/testing/releases/README.md
  package.json
  readme.txt
  src/Package.php
  woocommerce-gutenberg-products-block.php
Labels: status: ready to merge

#2778 Tweak some logic in our cart Integration test.
  assets/js/blocks/cart-checkout/cart/test/block.js
Labels: scope: tests, status: ready to merge

#2800 add basic docs for running e2e tests
  docs/contributors/javascript-testing.md
Labels: skip-changelog, status: ready to merge

#2804 Dashicon module replacement: prevent cloning a non-element
  assets/js/module_replacements/dashicon.js
Labels: scope: components, skip-changelog, status: ready to merge, type: blocker, type: bug, ◼️ block: cart, ◼️ block: checkout

#2808 Reviews by product/category e2e tests
  assets/js/blocks/reviews/reviews-by-category/edit.js
  assets/js/blocks/reviews/reviews-by-product/edit.js
  tests/e2e-tests/config/setup.js
  tests/e2e-tests/fixtures/fixture-data.js
  tests/e2e-tests/fixtures/fixture-loaders.js
  tests/e2e-tests/specs/backend/__fixtures__/reviews-by-category.fixture.json
  tests/e2e-tests/specs/backend/__fixtures__/reviews-by-product.fixture.json
  tests/e2e-tests/specs/backend/all-reviews.test.js
  tests/e2e-tests/specs/backend/reviews-by-category.test.js
  tests/e2e-tests/specs/backend/reviews-by-product.test.js
Labels: status: ready to merge

#2816 Release: 2.9.0
  docs/testing/releases/290.md
  docs/testing/releases/README.md
  package-lock.json
  package.json
  readme.txt
  src/Package.php
  woocommerce-gutenberg-products-block.php
Labels: status: ready to merge

#2788 Don't load frontend scripts in the editor
  src/Assets.php
  src/Assets/Api.php
  src/Library.php
Labels: status: ready to merge, type: performance

#2817 Split up webpack files for better readability
  bin/webpack-configs.js
  bin/webpack-entries.js
  bin/webpack-helpers.js
  package-lock.json
  package.json
  storybook/webpack.config.js
  webpack.config.js
Labels: skip-changelog, status: ready to merge, type: build

#2814 Document Cart & Checkout button styles
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  docs/theming/cart-and-checkout.md
Labels: scope: documentation, status: ready to merge, ◼️ block: cart

#2821 Support bank transfer (BACS) payment method in checkout block
  assets/js/payment-method-extensions/payment-methods/bacs/constants.js
  assets/js/payment-method-extensions/payment-methods/bacs/index.js
  bin/webpack-entries.js
  src/Domain/Bootstrap.php
  src/Payments/Api.php
  src/Payments/Integrations/BankTransfer.php
Labels: status: ready to merge, ◼️ block: checkout

#2834 Update minimum required versions in readme.txt to align them with readme.md
  readme.txt
Labels: scope: documentation, skip-changelog, status: ready to merge

#2832 lots of release process doc tweaks
  docs/releases/handling-releases.md
Labels: status: ready to merge

#2847 Update automattic/jetpack-autoloader to 2.0 branch
  composer.json
  composer.lock
Labels: status: ready to merge, type: build, type: dependencies

#2765 Unify Chip styles
  assets/js/base/components/cart-checkout/totals/totals-discount-item/index.js
  assets/js/base/components/chip/chip.js
  assets/js/base/components/chip/index.js
  assets/js/base/components/chip/removable-chip.js
  assets/js/base/components/chip/style.scss
  assets/js/base/components/chip/test/__snapshots__/index.js.snap
  assets/js/base/components/chip/test/index.js
  assets/js/base/components/dropdown-selector/index.js
  assets/js/base/components/dropdown-selector/selected-chip.js
  assets/js/base/components/dropdown-selector/selected-value.js
  assets/js/base/components/dropdown-selector/style.scss
  assets/js/blocks/active-filters/active-attribute-filters.js
  assets/js/blocks/active-filters/block.js
  assets/js/blocks/active-filters/style.scss
  assets/js/blocks/active-filters/utils.js
Labels: scope: components, status: ready to merge, type: enhancement, ◼️ block: active product filters, ◼️ block: filter products by attribute

#2848 Remove dashicon classes
  assets/js/base/components/chip/removable-chip.js
  assets/js/base/components/chip/style.scss
  assets/js/base/components/chip/test/__snapshots__/index.js.snap
  assets/js/base/components/dropdown-selector/style.scss
  assets/js/icons/library/arrow-down-alt2.js
  assets/js/icons/library/no-alt.js
Labels: scope: components, status: ready to merge, type: refactor, ◼️ block: cart, ◼️ block: filter products by attribute, ◼️ block: product categories list, ◼️ block: product search

#2840 allow payment methods to disable based on shipping (API change)
  assets/js/base/context/cart-checkout/payment-methods/reducer.js
  assets/js/base/context/cart-checkout/payment-methods/use-payment-method-registration.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/index.js
Labels: scope: documentation, scope: extensibility, status: ready to merge, status:needs-dev-note, ◼️ block: checkout

#2777 Lazy Loading Atomic Components
  assets/css/style.scss
  assets/js/atomic/blocks/component-init.js
  assets/js/atomic/utils/render-inner-blocks.js
  assets/js/base/components/product-list-item/utils.js
  assets/js/blocks-registry/block-components/register-block-component.js
  assets/js/blocks-registry/block-components/test/index.js
  assets/js/settings/blocks/constants.js
  package.json
  src/Assets.php
Labels: status: ready to merge, type: cooldown

#2833 Cart block: show products on backorder
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/base/components/cart-checkout/product-backorder-badge/index.js
  assets/js/base/components/cart-checkout/product-badge/index.js
  assets/js/base/components/cart-checkout/product-badge/style.scss
  assets/js/base/components/cart-checkout/product-low-stock-badge/index.js
  assets/js/base/components/cart-checkout/product-sale-badge/index.js
  assets/js/base/components/cart-checkout/product-sale-badge/style.scss
  assets/js/base/components/cart-checkout/product-variation-data/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/previews/cart.js
  assets/js/type-defs/cart.js
  src/StoreApi/Schemas/CartItemSchema.php
  src/StoreApi/docs/cart-items.md
  src/StoreApi/docs/cart.md
  tests/php/StoreApi/Routes/CartItems.php
Labels: status: ready to merge, type: enhancement, ◼️ block: cart, ◼️ block: checkout

#2842 Deregister core cart/checkout scripts and styles when rendering the blocks
  .eslintrc.js
  assets/js/base/utils/legacy-events.js
  assets/js/blocks/cart-checkout/cart/block.js
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
  tests/js/setup-globals.js
Labels: status: ready to merge, type: performance, ◼️ block: cart, ◼️ block: checkout

#2831 Support cash on delivery payment method in checkout block
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/payment-method-extensions/payment-methods/cheque/index.js
  assets/js/payment-method-extensions/payment-methods/cod/constants.js
  assets/js/payment-method-extensions/payment-methods/cod/index.js
  bin/webpack-entries.js
  docs/extensibility/payment-method-integration.md
  src/Domain/Bootstrap.php
  src/Payments/Api.php
  src/Payments/Integrations/BankTransfer.php
  src/Payments/Integrations/CashOnDelivery.php
  src/Payments/Integrations/Cheque.php
  src/Payments/Integrations/Stripe.php
Labels: status: ready to merge, ◼️ block: checkout

#2874 Move Draft order logic behind feature flag.
  src/Domain/Bootstrap.php
  src/Domain/Services/DraftOrders.php
  src/Installer.php
  src/Library.php
  tests/php/Domain/Services/DeleteDraftOrders.php
  tests/php/Library/DeleteDraftOrders.php
Labels: status: ready to merge, type: enhancement

#2875 Extract ProgressBarPlugin config
  bin/webpack-configs.js
Labels: skip-changelog, status: ready to merge, type: refactor

#2878 Fix undefined index 'enabled' for multiple payment method registrations
  src/Payments/Integrations/AbstractPaymentMethodType.php
  src/Payments/Integrations/BankTransfer.php
  src/Payments/Integrations/CashOnDelivery.php
  src/Payments/Integrations/Cheque.php
  src/Payments/Integrations/PayPal.php
  src/Payments/Integrations/Stripe.php
Labels: status: ready to merge

#2869 Fix Credit Card input font size in some themes
  assets/css/abstracts/_variables.scss
  assets/js/base/components/payment-methods/style.scss
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-element-options.js
Labels: status: ready to merge, ◼️ block: checkout

#2890 remove duplicate back order badge for cart
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
Labels: status: ready to merge, type: blocker, type: bug, ◼️ block: cart

#2860 Update ⚛️ ‎‎‏‏‎ Product Title
  assets/js/atomic/blocks/product/title/attributes.js
  assets/js/atomic/blocks/product/title/block.js
  assets/js/atomic/blocks/product/title/edit.js
  assets/js/atomic/blocks/product/title/index.js
  assets/js/atomic/blocks/product/title/style.scss
  assets/js/atomic/utils/block-styling.js
  assets/js/atomic/utils/index.js
  assets/js/blocks/single-product/constants.js
  assets/js/icons/index.js
  assets/js/icons/library/heading.js
Labels: status: ready to merge, status:needs-dev-note, type: enhancement, 🔺 atomic-block: product title

#2881 Update ⚛️ Product Price
  assets/js/atomic/blocks/product/price/attributes.js
  assets/js/atomic/blocks/product/price/block.js
  assets/js/atomic/blocks/product/price/edit.js
  assets/js/atomic/blocks/product/price/index.js
  assets/js/atomic/blocks/product/price/style.scss
Labels: status: ready to merge, type: enhancement, 🔺 atomic-block: product price

#2891 Cart & Checkout: fix '0' visible when product stock was 0 and it allowed backorders
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
Labels: skip-changelog, status: ready to merge, type: bug

#2894 Fix Cash on Delivery not accounting for global rate values
  assets/js/payment-method-extensions/payment-methods/cod/index.js
Labels: scope: extensibility, status: ready to merge, type: blocker, type: bug

#2895 Fix unnecessary checks happening for wc_reserved_stock table in site dashboard
  src/Installer.php
Labels: status: ready to merge, type: bug, type: performance

#2818 Make stylesheets order consistent between build and dev
  assets/js/base/components/quantity-selector/stories/index.js
  assets/js/base/components/quantity-selector/stories/style.scss
  bin/merge-extract-files-webpack-plugin.js
  bin/remove-files-webpack-plugin.js
  bin/webpack-configs.js
  bin/webpack-entries.js
  package.json
  storybook/webpack.config.js
  webpack.config.js
Labels: skip-changelog, status: ready to merge, type: build

#2887 Release: 3.0.0
  .distignore
  .github/workflows/wordpress-deploy.yml
  .travis.yml
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  bin/github-deploy.sh
  bin/version-changes.sh
  docs/releases/handling-releases.md
  docs/testing/releases/300.md
  package.json
  readme.txt
  src/Package.php
  src/Payments/Integrations/BankTransfer.php
  src/Payments/Integrations/CashOnDelivery.php
  woocommerce-gutenberg-products-block.php
Labels: status: ready to merge, type: release

#2886 Add query filter when searching for a table
  src/Installer.php
Labels: status: ready to merge

#2926 Fix missing permissions_callback arg in StoreApi route definitions
  src/StoreApi/Routes/Cart.php
  src/StoreApi/Routes/CartAddItem.php
  src/StoreApi/Routes/CartApplyCoupon.php
  src/StoreApi/Routes/CartCoupons.php
  src/StoreApi/Routes/CartCouponsByCode.php
  src/StoreApi/Routes/CartItems.php
  src/StoreApi/Routes/CartItemsByKey.php
  src/StoreApi/Routes/CartRemoveCoupon.php
  src/StoreApi/Routes/CartRemoveItem.php
  src/StoreApi/Routes/CartSelectShippingRate.php
  src/StoreApi/Routes/CartUpdateItem.php
  src/StoreApi/Routes/CartUpdateShipping.php
  src/StoreApi/Routes/Checkout.php
  src/StoreApi/Routes/ProductAttributeTerms.php
  src/StoreApi/Routes/ProductAttributes.php
  src/StoreApi/Routes/ProductAttributesById.php
  src/StoreApi/Routes/ProductCategories.php
  src/StoreApi/Routes/ProductCategoriesById.php
  src/StoreApi/Routes/ProductCollectionData.php
  src/StoreApi/Routes/ProductReviews.php
  src/StoreApi/Routes/ProductTags.php
  src/StoreApi/Routes/Products.php
  src/StoreApi/Routes/ProductsById.php
Labels: scope: rest-api, status: ready to merge, type: blocker

#2921 add hover style to ensure consistent margin/padding for order summary so it doesn't jump on mouseover
  assets/js/base/components/panel/style.scss
Labels: skip-changelog, status: ready to merge

#2937 Update WP tested up to version to 5.5
  readme.txt
Labels: scope: documentation, status: ready to merge

#2925 Fix typo in state property for idle status in checkout state reducer
  assets/js/base/context/cart-checkout/checkout-state/reducer.js
  tests/php/StoreApi/Routes/CartItems.php
Labels: status: ready to merge, type: bug, ◼️ block: checkout

#2939 Update wp.deploy workflow adding slack hook
  .github/workflows/wordpress-deploy.yml
Labels: skip-changelog, status: ready to merge, type: build

#2883 Add attributes and view toggle tests to the Cart block
  tests/e2e-tests/config/setup.js
  tests/e2e-tests/fixtures/fixture-data.js
  tests/e2e-tests/fixtures/fixture-loaders.js
  tests/e2e-tests/specs/backend/cart.test.js
  tests/e2e-tests/specs/backend/product-search.test.js
  tests/utils/find-toggle-with-label.js
  tests/utils/index.js
Labels: scope: tests, skip-changelog, status: ready to merge, ◼️ block: cart

#2940 Fix reviews blocks in WP 5.2
  assets/js/base/utils/render-frontend.js
Labels: skip-changelog, status: ready to merge, type: bug, 🔹 block-type: reviews

#2941 Fix Reviews editor styles
  assets/js/blocks/reviews/reviews-by-category/editor.scss
  assets/js/blocks/reviews/reviews-by-category/index.js
  assets/js/blocks/reviews/reviews-by-product/editor.scss
  bin/webpack-entries.js
Labels: scope: styles, skip-changelog, status: ready to merge, ◼️ block: reviews by category, ◼️ block: reviews by product

#2920 enqueue and respect merchant option for disabling stripe express pay
  assets/js/payment-method-extensions/payment-methods/stripe/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/type-defs.js
  src/Payments/Integrations/Stripe.php
Labels: status: ready to merge, ◼️ block: checkout

#2935 Fix WP_CONTENT_DIR path in PHP unit tests
  tests/bootstrap.php
Labels: skip-changelog

#2903 Add to cart context provider
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/simple.js
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/index.js
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/attribute-picker.js
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/attribute-select-control.js
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/index.js
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/style.scss
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/test/index.js
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/utils.js
  assets/js/atomic/blocks/product-elements/add-to-cart/shared/add-to-cart-button.js
  assets/js/atomic/blocks/product-elements/add-to-cart/style.scss
  assets/js/atomic/blocks/product/price/attributes.js
  assets/js/atomic/blocks/product/price/index.js
  assets/js/base/components/store-notices-container/style.scss
  assets/js/base/context/add-to-cart-form-context.js
  assets/js/base/context/add-to-cart-form/form-state/actions.js
  assets/js/base/context/add-to-cart-form/form-state/constants.js
  assets/js/base/context/add-to-cart-form/form-state/event-emit.js
  assets/js/base/context/add-to-cart-form/form-state/index.js
  assets/js/base/context/add-to-cart-form/form-state/reducer.js
  assets/js/base/context/add-to-cart-form/form/index.js
  assets/js/base/context/add-to-cart-form/form/submit/index.js
  assets/js/base/context/add-to-cart-form/index.js
  assets/js/base/context/cart-checkout/checkout-state/event-emit.js
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/context/cart-checkout/index.js
  assets/js/base/context/cart-checkout/payment-methods/event-emit.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/shipping/event-emit.js
  assets/js/base/context/index.js
  assets/js/base/context/shared/event-emit/emitter-callback.js
  assets/js/base/context/shared/event-emit/emitters.js
  assets/js/base/context/shared/event-emit/index.js
  assets/js/base/context/shared/event-emit/reducer.js
  assets/js/base/context/shared/event-emit/test/emitters.js
  assets/js/base/context/shared/index.js
  assets/js/base/context/shared/validation/index.js
  assets/js/blocks/single-product/block.js
  assets/js/blocks/single-product/frontend.js
  assets/js/type-defs/add-to-cart-form.js
  assets/js/type-defs/contexts.js
Labels: status: ready to merge

#2877 Add 'Order notes' to Checkout block
  assets/js/base/components/cart-checkout/form-step/index.js
  assets/js/base/components/cart-checkout/form-step/style.scss
  assets/js/base/components/cart-checkout/form-step/test/__snapshots__/index.js.snap
  assets/js/base/components/cart-checkout/form-step/test/index.js
  assets/js/base/components/checkbox-control/style.scss
  assets/js/base/components/textarea/index.js
  assets/js/base/components/textarea/style.scss
  assets/js/base/context/cart-checkout/checkout-state/actions.js
  assets/js/base/context/cart-checkout/checkout-state/constants.js
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/context/cart-checkout/checkout-state/reducer.js
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/blocks/cart-checkout/checkout/attributes.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/checkout-order-notes/index.js
  assets/js/blocks/cart-checkout/checkout/checkout-order-notes/style.scss
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/style.scss
  assets/js/type-defs/checkout.js
  assets/js/type-defs/contexts.js
Labels: status: ready to merge, type: enhancement, ◼️ block: checkout
