Repository woocommerce/woocommerce-blocks, pull requests merged in 2020-02, with the labels that each got.

#1700 Default to experimental flag locally when no flag is present
  bin/webpack-helpers.js
Labels: status: ready to merge, type: build

#1698 Check for instance of WooCommerce and WP_Error before initializing session and cart in `rest_authentication_errors` callback.
  src/RestApi.php
Labels: scope: rest-api, status: ready to merge, type: bug

#1702 Give Woo Icon special treatment by making it a component
  assets/js/icons/icon/index.js
  assets/js/icons/library/woo.js
  assets/js/index.js
Labels: scope: components, skip-changelog, status: ready to merge

#1696 Add eslint to ensure correct usage of feature flag
  .eslintrc.js
  bin/eslint-plugin-woocommerce/package.json
  bin/eslint-plugin-woocommerce/rules/__tests__/feature-flag.js
  bin/eslint-plugin-woocommerce/rules/feature-flag.js
Labels: status: ready to merge, type: build

#1713 Update eslint config to use non-deprecated value for global configuration.
  .eslintrc.js
Labels: status: ready to merge, type: build, type: enhancement

#1718 Update Attribute Filter strings to ease translation
  assets/js/blocks/attribute-filter/edit.js
Labels: scope: i18n, skip-changelog, status: ready to merge, type: enhancement

#1719 Fix Reviews blocks loading @wordpress/element in the frontend
  assets/js/base/components/block-error-boundary/index.js
Labels: scope: components, skip-changelog, status: ready to merge, type: performance

#1716 Fix wp-cli container permissions issues for e2e docker test environment
  .env
  .eslintrc.js
  .travis.yml
  babel.config.js
  bin/docker/wordpress/Dockerfile
  bin/docker/wp-cli/Dockerfile
  bin/docker/wp-cli/entrypoint.sh
  bin/docker/wp-cli/wait-for-it.sh
  bin/webpack-helpers.js
  docker-compose.yaml
  package-lock.json
  package.json
  tests/bin/e2e-test-integration.js
  tests/bin/install-wp-tests.sh
  tests/bootstrap.php
  tests/e2e-tests/config/default.json
  tests/e2e-tests/config/env.setup.js
  tests/e2e-tests/config/jest-custom-sequencer.js
  tests/e2e-tests/config/jest-puppeteer.config.js
  tests/e2e-tests/config/jest-puppeteer.dev.config.js
  tests/e2e-tests/config/jest.config.js
  tests/e2e-tests/config/jest.setup.js
  tests/e2e-tests/config/test:e2e.json
  tests/e2e-tests/specs/backend/__snapshots__/all-products.test.js.snap
  tests/e2e-tests/specs/backend/all-products.test.js
  tests/js/jest.config.json
Labels: type: bug, type: build

#1712 Product search block e2e test
  .gitignore
  .travis.yml
  composer.json
  composer.lock
  package-lock.json
  package.json
  tests/bootstrap.php
  tests/e2e-tests/config/jest-puppeteer.config.js
  tests/e2e-tests/config/jest-puppeteer.dev.config.js
  tests/e2e-tests/specs/backend/__snapshots__/product-search.test.js.snap
  tests/e2e-tests/specs/backend/product-search.test.js
Labels: scope: tests, skip-changelog, status: ready to merge

#1721 Change 'country' to 'country / region' label
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: scope: blocks, skip-changelog, status: ready to merge, type: enhancement

#1726 Load countries in wcSettings only when a block requires them
  src/Assets.php
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
Labels: status: ready to merge

#1729 Fix ESLint error when commiting bin/webpack-helpers.js
  bin/eslint-plugin-woocommerce/rules/feature-flag.js
  bin/webpack-helpers.js
  package.json
Labels: status: ready to merge, type: build

#1731 Update testPathIgnorePatterns to exclude vendor directory
  tests/js/jest.config.json
Labels: skip-changelog, status: ready to merge, type: build

#1468 Hook up shipping methods to API
  assets/js/base/components/radio-control/index.js
  assets/js/base/components/radio-control/option-layout.js
  assets/js/base/components/radio-control/option.js
  assets/js/base/components/radio-control/style.scss
  assets/js/base/components/shipping-rates-control/index.js
  assets/js/base/components/shipping-rates-control/package-options.js
  assets/js/base/components/shipping-rates-control/package.js
  assets/js/base/components/shipping-rates-control/style.scss
  assets/js/base/hooks/index.js
  assets/js/base/hooks/test/use-shipping-rates.js
  assets/js/base/hooks/use-shipping-rates.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/placeholder-shipping-methods.js
  src/RestApi/StoreApi/Controllers/CartShippingRates.php
  src/RestApi/StoreApi/Schemas/CartShippingRateSchema.php
  tests/php/RestApi/StoreApi/Controllers/CartShippingRates.php
Labels: skip-changelog, status: ready to merge

#1732 Fix composer config and regenerate composer.lock
  composer.json
  composer.lock
Labels: status: ready to merge, type: bug, type: build

#1727 Create CountyInput component
  assets/js/base/components/country-input/country-input.js
  assets/js/base/components/county-input/billing-county-input.js
  assets/js/base/components/county-input/county-input.js
  assets/js/base/components/county-input/index.js
  assets/js/base/components/county-input/shipping-county-input.js
  assets/js/base/components/input-row/style.scss
  assets/js/base/components/select/index.js
  assets/js/base/components/select/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/settings/blocks/constants.js
  src/BlockTypes/Checkout.php
Labels: scope: components, status: ready to merge

#1740 Ensure travis is using php 7.3 for the linting job
  .travis.yml
Labels: skip-changelog, type: bug, type: build

#1749 link to docs.woocommerce.com from repo readme
  README.md
Labels: scope: documentation, status: ready to merge

#1559 Add ShippingCalculator component
  assets/js/base/components/county-input/index.js
  assets/js/base/components/select/style.scss
  assets/js/base/components/shipping-calculator/address.js
  assets/js/base/components/shipping-calculator/index.js
  assets/js/base/components/shipping-calculator/style.scss
  assets/js/base/components/shipping-rates-control/package-options.js
  assets/js/base/components/state-input/billing-state-input.js
  assets/js/base/components/state-input/index.js
  assets/js/base/components/state-input/shipping-state-input.js
  assets/js/base/components/state-input/state-input.js
  assets/js/base/components/text-input/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  package.json
  src/BlockTypes/Cart.php
Labels: scope: components, skip-changelog, status: ready to merge

#1753 Add catalog visibility arg to product query attributes
  assets/js/base/components/product-list/index.js
Labels: status: ready to merge

#1736 Implement __experimentalCreateInterpolateElement for translations.
  assets/js/blocks/reviews/edit-utils.js
  package-lock.json
  package.json
Labels: status: ready to merge

#1737 Change PropType validation for Icon component
  assets/js/icons/icon/index.js
Labels: status: ready to merge

#1750 update all block one-line descriptions to match documentation
  assets/js/blocks/active-filters/index.js
  assets/js/blocks/attribute-filter/index.js
  assets/js/blocks/price-filter/index.js
  assets/js/blocks/product-categories/index.js
  assets/js/blocks/product-on-sale/index.js
  assets/js/blocks/product-search/index.js
  assets/js/blocks/product-tag/index.js
  assets/js/blocks/products-by-attribute/index.js
  assets/js/blocks/products/all-products/index.js
  assets/js/blocks/reviews/all-reviews/index.js
  assets/js/blocks/reviews/reviews-by-product/index.js
Labels: status: needs review

#1757 Adjust shipping price in REST API
  src/RestApi/StoreApi/Schemas/CartShippingRateSchema.php
Labels: scope: rest-api, skip-changelog, status: ready to merge

#1762 Shipping rates: decode entities
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: skip-changelog, status: ready to merge, type: bug

#1760 fix cart api total_price value
  src/RestApi/StoreApi/Schemas/CartSchema.php
Labels: scope: rest-api, skip-changelog, status: ready to merge

#1647 Implement last modified header for the products endpoint to allow for cache busting
  assets/js/base/hooks/use-collection.js
  assets/js/data/collections/action-types.js
  assets/js/data/collections/actions.js
  assets/js/data/collections/reducers.js
  assets/js/data/collections/resolvers.js
  assets/js/data/collections/selectors.js
  src/RestApi/StoreApi/Controllers/Products.php
  src/RestApi/StoreApi/Utilities/ProductQuery.php
Labels: status: ready to merge

#1768 Update WooCommerce tested version up to 4.0
  woocommerce-gutenberg-products-block.php
Labels: skip-changelog, status: ready to merge

#1741 hook up cart items to API data in front end
  assets/js/base/hooks/index.js
  assets/js/base/hooks/use-store-cart.js
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/previews/cart-items.js
  assets/js/previews/cart.js
  assets/js/previews/index.js
Labels: scope: blocks, skip-changelog, status: ready to merge, type: new block

#1764 Add loading state to shipping rates selector
  assets/js/base/components/loading-mask/index.js
  assets/js/base/components/loading-mask/style.scss
  assets/js/base/components/shipping-rates-control/index.js
  bin/webpack-helpers.js
Labels: scope: components, skip-changelog, status: ready to merge

#1755 Implement browser autocomplete for checkout address fields
  assets/js/base/components/country-input/country-input.js
  assets/js/base/components/shipping-calculator/address.js
  assets/js/base/components/state-input/state-input.js
  assets/js/base/components/text-input/index.js
  assets/js/base/components/text-input/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: skip-changelog, status: ready to merge

#1739 Add support for image for product categories block
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-categories/index.js
  assets/js/blocks/product-categories/style.scss
  src/BlockTypes/ProductCategories.php
Labels: scope: blocks, status: ready to merge, type: enhancement

#1561 Add Shipping settings to Cart block
  assets/js/base/components/totals/totals-coupon-code-input/index.js
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/index.js
  assets/js/settings/blocks/constants.js
  src/Assets.php
Labels: skip-changelog, status: ready to merge

#1767 Display selected shipping location in cart block
  assets/js/base/components/shipping-location/index.js
  assets/js/base/components/state-input/billing-state-input.js
  assets/js/base/components/state-input/shipping-state-input.js
  assets/js/base/components/state-input/state-input.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/settings/blocks/constants.js
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
Labels: status: ready to merge

#1782 Cart & Checkout: conditionally register country and state settings
  src/Assets/AssetDataRegistry.php
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
  tests/php/Assets/AssetDataRegistry.php
Labels: status: ready to merge

#1788 Add `isLoading` property to `LoadingMask` component
  assets/js/base/components/loading-mask/index.js
Labels: skip-changelog, status: ready to merge

#1785 Add type="submit" to the Shipping Calculator button
  assets/js/base/components/shipping-calculator/address.js
Labels: scope: accessibility, skip-changelog, status: ready to merge

#1777 disable shipping if shipping is disabled site wide
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: scope: blocks, status: ready to merge

#1792 Remove/update broken links from README.md
  README.md
Labels: scope: documentation, status: ready to merge

#1791 Add permalink to cart line items
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: skip-changelog, status: ready to merge

#1796 Create typedefs and add basic typescript configuration
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/type-defs/cart.js
  package-lock.json
  package.json
  tsconfig.json
Labels: status: ready to merge, type: build, type: enhancement

#1789 Add style to radio control
  assets/js/base/components/radio-control/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: scope: components, skip-changelog, status: ready to merge

#1800 Add missing alias for tsconfig and re-order alphabetically
  tsconfig.json
Labels: status: ready to merge, type: bug, type: build

#1783 Add product name and quantity to cart shipping rates endpoint
  assets/js/base/components/shipping-rates-control/index.js
  assets/js/base/components/shipping-rates-control/package-options.js
  assets/js/base/components/shipping-rates-control/package.js
  assets/js/base/components/shipping-rates-control/packages.js
  assets/js/base/components/shipping-rates-control/style.scss
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/previews/index.js
  assets/js/previews/shipping-rates.js
  src/RestApi/StoreApi/Schemas/CartShippingRateSchema.php
Labels: skip-changelog, status: ready to merge

#1790 Allow coupons to be applied and removed from the cart
  assets/js/base/components/shipping-rates-control/index.js
  assets/js/base/components/totals/totals-coupon-code-input/index.js
  assets/js/base/hooks/index.js
  assets/js/base/hooks/use-store-cart-coupons.js
  assets/js/base/hooks/use-store-cart.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/data/cart/action-types.js
  assets/js/data/cart/actions.js
  assets/js/data/cart/constants.js
  assets/js/data/cart/index.js
  assets/js/data/cart/reducers.js
  assets/js/data/cart/resolvers.js
  assets/js/data/cart/selectors.js
  assets/js/data/cart/test/reducers.js
  assets/js/data/cart/test/resolvers.js
  assets/js/data/cart/test/selectors.js
  assets/js/data/collections/actions.js
  assets/js/data/index.js
  assets/js/type-defs/cart.js
  assets/js/type-defs/hooks.js
  package-lock.json
  package.json
  src/RestApi/StoreApi/Controllers/Cart.php
  src/RestApi/StoreApi/Controllers/CartCoupons.php
  tests/php/RestApi/StoreApi/Controllers/Cart.php
Labels: skip-changelog, status: ready to merge

#1784 show discount badge in line items in cart
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/previews/cart.js
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  src/RestApi/StoreApi/Schemas/OrderItemSchema.php
  src/RestApi/StoreApi/Schemas/ProductSchema.php
Labels: status: ready to merge

#1808 Updated `store/cart` endpoint coupon formatting and handling
  assets/js/data/cart/actions.js
  src/RestApi/StoreApi/Controllers/Cart.php
  tests/php/RestApi/StoreApi/Controllers/Cart.php
Labels: scope: rest-api, skip-changelog, status: ready to merge

#1818 Wrap Coupon code input/button in a <form> element
  assets/js/base/components/totals/totals-coupon-code-input/index.js
  assets/js/base/components/totals/totals-coupon-code-input/style.scss
Labels: scope: components, skip-changelog, status: ready to merge

#1817 Fix radio control styles in editor
  assets/js/base/components/radio-control/_mixin.scss
  assets/js/base/components/radio-control/editor.scss
  assets/js/base/components/radio-control/index.js
  assets/js/base/components/radio-control/style.scss
Labels: scope: components, skip-changelog, status: ready to merge

#1819 Add loading placeholder for cart block (inital load)
  assets/css/abstracts/_mixins.scss
  assets/js/base/utils/price.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-table.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-title.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/product-image.js
  assets/js/blocks/cart-checkout/cart/full-cart/product-low-stock-badge.js
  assets/js/blocks/cart-checkout/cart/full-cart/product-variation-data.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: skip-changelog, status: ready to merge

#1804 Checkout block: don't show message of missing shipping options if they are already set
  assets/js/base/components/checkout/no-shipping/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/settings/blocks/constants.js
  src/BlockTypes/Checkout.php
Labels: scope: blocks, skip-changelog, status: ready to merge

#1807 Add chip component for coupons in the cart
  assets/js/base/components/chip/index.js
  assets/js/base/components/chip/style.scss
  assets/js/base/components/chip/test/__snapshots__/index.js.snap
  assets/js/base/components/chip/test/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: scope: components, skip-changelog, status: ready to merge

#1828 Add aria labels for category list product counts
  src/BlockTypes/ProductCategories.php
Labels: scope: accessibility, status: ready to merge

#1826 Add screen reader text to sale badge for SSR rendered blocks
  src/BlockTypes/AbstractProductGrid.php
Labels: scope: accessibility, status: ready to merge

#1806 Persist previous shipping rates while loading and show its package name
  assets/js/base/components/radio-control/_mixin.scss
  assets/js/base/components/shipping-calculator/style.scss
  assets/js/base/components/shipping-rates-control/index.js
  assets/js/base/components/shipping-rates-control/package-options.js
  assets/js/base/components/shipping-rates-control/package.js
  assets/js/base/components/shipping-rates-control/packages.js
  assets/js/base/components/shipping-rates-control/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  src/RestApi/StoreApi/Controllers/CartShippingRates.php
  src/RestApi/StoreApi/Schemas/CartShippingRateSchema.php
  tests/php/RestApi/StoreApi/Controllers/CartShippingRates.php
Labels: scope: components, scope: rest-api, skip-changelog, status: ready to merge

#1823 support disabled QuantitySelector [in progress]
  assets/js/base/components/quantity-selector/index.js
  assets/js/base/components/quantity-selector/stories/index.js
  assets/js/base/components/quantity-selector/stories/style.scss
  assets/js/base/components/quantity-selector/style.scss
Labels: scope: components, status: ready to merge

#1813 support removing cart items
  assets/js/base/hooks/index.js
  assets/js/base/hooks/use-store-cart-item.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/data/cart/action-types.js
  assets/js/data/cart/actions.js
  assets/js/data/cart/reducers.js
  assets/js/data/cart/selectors.js
  assets/js/type-defs/hooks.js
Labels: skip-changelog, status: ready to merge

#1837 Switch lint:js command to use wp-scripts and address errors.
  assets/js/blocks/active-filters/utils.js
  package.json
  tests/bin/e2e-test-integration.js
  webpack.config.js
Labels: type: build
