Repository woocommerce/woocommerce-blocks, pull requests merged in 2020-10, with the labels that each got.

#2851 Support "create account" option in checkout block
  .travis.yml
  assets/js/base/context/cart-checkout/checkout-state/actions.js
  assets/js/base/context/cart-checkout/checkout-state/constants.js
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/context/cart-checkout/checkout-state/reducer.js
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/blocks/cart-checkout/checkout/attributes.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/form/address-step.js
  assets/js/blocks/cart-checkout/checkout/form/contact-fields-step.js
  assets/js/blocks/cart-checkout/checkout/form/index.js
  assets/js/blocks/cart-checkout/checkout/form/style.scss
  src/Assets.php
  src/Domain/Bootstrap.php
  src/Domain/Services/CreateAccount.php
  src/Domain/Services/Email/CustomerNewAccount.php
  src/StoreApi/Routes/Checkout.php
  src/StoreApi/Schemas/CheckoutSchema.php
  templates/emails/customer-new-account-blocks.php
  templates/emails/plain/customer-new-account-blocks.php
  tests/php/Domain/Services/CreateAccount.php
Labels: status: ready to merge, ◼️ block: checkout

#3219 Load WC Blocks CSS after editor CSS
  src/Assets.php
Labels: scope: styles, status: ready to merge, ◼️ block: checkout

#3226 Refactor payment methods components
  assets/js/base/components/payment-methods/payment-method-options.js
  assets/js/base/components/payment-methods/payment-method-tab.js
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/type-defs/registered-payment-method-props.js
Labels: skip-changelog, status: ready to merge, type: refactor, ◼️ block: checkout

#3227 Don't load contents of payment method hidden tabs
  assets/js/base/components/tabs/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/payment-method.js
Labels: status: ready to merge, ◼️ block: checkout

#3242 Fix PaymentMethodTab wrong propType
  assets/js/base/components/payment-methods/payment-method-tab.js
Labels: skip-changelog, status: ready to merge

#3210 Restore saved payment method data after closing an express payment method
  assets/js/base/components/payment-methods/express-payment-methods.js
  assets/js/base/components/payment-methods/index.js
  assets/js/base/components/title/index.js
  assets/js/base/context/cart-checkout/payment-methods/test/payment-method-data-context.js
Labels: status: ready to merge, type: bug, ◼️ block: checkout

#3256 Simplify emitEventWithAbort logic
  assets/js/base/context/shared/event-emit/emitters.js
Labels: status: ready to merge, type: refactor, ◼️ block: checkout

#3261 Make 'retry' property on errors from checkoutAfterProcessingWithSuccess/Error observers default to true if it's undefined
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/hooks/checkout/use-emit-response.js
  assets/js/type-defs/hooks.js
  docs/extensibility/checkout-flow-and-events.md
Labels: status: ready to merge

#3247 Ensure new payment methods are only displayed when no saved payment method is selected
  assets/js/base/components/label/index.js
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/components/payment-methods/saved-payment-method-options.js
  assets/js/base/components/payment-methods/test/payment-methods.js
  assets/js/base/context/cart-checkout/payment-methods/test/payment-method-data-context.js
Labels: status: ready to merge, type: blocker, type: bug, ◼️ block: checkout

#3185 Fixed issue current values doesn't persist in Products by Attribute block
  assets/js/hocs/with-attributes.js
Labels: status: ready to merge, type: bug, ◼️ block: products by attribute

#3236 Use store-themed set password form for checkout signup
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/settings/shared/index.js
  src/Assets/AssetDataRegistry.php
  src/Domain/Services/CreateAccount.php
  src/Domain/Services/Email/CustomerNewAccount.php
  src/StoreApi/Routes/Checkout.php
Labels: scope: core, status: ready to merge, type: enhancement, ◼️ block: checkout

#3269 Some changes/additions to the release checklist
  .github/release-initial-checklist.md
Labels: skip-changelog, status: ready to merge, type: build

#3290 Escape basename paths with spaces correctly while running E2E tests.
  bin/wp-env-pre-config.sh
Labels: scope: tests, skip-changelog, status: ready to merge, type: refactor

#3294 Add workflow for linting js and css
  .github/workflows/js-css-linting.yml
  .travis.yml
Labels: status: ready to merge, type: build, type: cooldown, type: enhancement

#3292 Add a php coding standards action
  .github/workflows/php-coding-standards.yml
  .travis.yml
  composer.json
  composer.lock
Labels: status: ready to merge, type: build, type: cooldown, type: enhancement

#3284 Document how to update E2E WP versions.
  docs/contributors/javascript-testing.md
Labels: scope: documentation, scope: tests, skip-changelog

#3297 Update ESLint workflow to only add comment on error.
  .github/workflows/js-css-linting.yml
Labels: skip-changelog, status: needs review, type: build, type: cooldown

#3272 Fix 3D secure payment errors
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/hooks/checkout/index.js
  assets/js/base/hooks/checkout/use-checkout-notices.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-checkout-subscriptions.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-payment-intents.js
  assets/js/type-defs/hooks.js
Labels: status: ready to merge, type: bug, ◼️ block: checkout

#3298 Correctly process $0 checkouts
  src/Domain/Services/DraftOrders.php
Labels: scope: rest-api, status: ready to merge, status:needs-dev-note, ◼️ block: checkout

#3300 Use @wordpress/base-styles and @automattic/color-studio as a base for our styles
  assets/css/abstracts/_breakpoints.scss
  assets/css/abstracts/_colors.scss
  assets/css/abstracts/_mixins.scss
  assets/css/abstracts/_variables.scss
  assets/css/editor.scss
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/style.scss
  assets/js/atomic/blocks/product-elements/shared/editor.scss
  assets/js/atomic/blocks/product-elements/stock-indicator/style.scss
  assets/js/base/components/button/style.scss
  assets/js/base/components/cart-checkout/policies/style.scss
  assets/js/base/components/chip/style.scss
  assets/js/base/components/dropdown-selector/style.scss
  assets/js/base/components/payment-methods/no-payment-methods/style.scss
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/price-slider/style.scss
  assets/js/base/components/quantity-selector/style.scss
  assets/js/base/components/select/style.scss
  assets/js/base/components/text-input/style.scss
  assets/js/base/components/validation/style.scss
  assets/js/blocks/cart-checkout/cart/checkout-button/style.scss
  assets/js/blocks/cart-checkout/checkout/form/no-shipping-placeholder/style.scss
  assets/js/blocks/featured-category/style.scss
  assets/js/blocks/featured-product/style.scss
  assets/js/blocks/product-categories/style.scss
  assets/js/blocks/product-search/style.scss
  assets/js/blocks/products/editor.scss
  assets/js/blocks/single-product/edit/editor.scss
  assets/js/editor-components/feedback-prompt/style.scss
  assets/js/editor-components/product-attribute-term-control/style.scss
  assets/js/editor-components/product-control/style.scss
  assets/js/editor-components/text-toolbar-button/style.scss
  assets/js/editor-components/view-switcher/editor.scss
  assets/js/icons/library/radio-unselected.js
  docs/theming/README.md
  docs/theming/all-products-and-filters.md
  package-lock.json
  package.json
Labels: scope: styles, status: ready to merge

#3310 E2E WC Core Terms Consistency
  assets/js/blocks/cart-checkout/checkout/edit.js
  tests/e2e/specs/backend/checkout.test.js
Labels: skip-changelog, status: ready to merge, type: refactor, ◼️ block: checkout

#3291 Respect Enable Taxes setting for checkout block taxe display.
  assets/js/base/components/cart-checkout/totals/totals-footer-item/index.js
Labels: status: ready to merge, ◼️ block: checkout

#3323 Convert `composer/installers` to range instead of pinned dependency
  composer.json
  composer.lock
  renovate.json
Labels: skip-changelog, type: build

#3315 Fix PHP 8 error when argument is not invocable in AssetsDataRegistry::add_data
  src/Assets/AssetDataRegistry.php
  src/Registry/AbstractDependencyType.php
Labels: status: ready to merge, type: bug

#3324 Fix Gutenberg e2e tests failures.
  .travis.yml
  tests/e2e/specs/backend/all-products.test.js
  tests/e2e/specs/backend/cart.test.js
  tests/e2e/specs/backend/checkout.test.js
  tests/e2e/utils.js
Labels: scope: tests, skip-changelog, status: ready to merge

#3299 Change items organisation on smaller viewports.
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: action: needs design, scope: styles, ◼️ block: cart

#3314 Fix React hook dependency warnings in Cart & Checkout blocks + withAttributes HOC
  assets/js/base/components/cart-checkout/address-form/index.js
  assets/js/base/components/country-input/stories/index.js
  assets/js/base/components/select/validated.js
  assets/js/base/components/text-input/validated.js
  assets/js/base/hooks/cart/use-store-cart-item-quantity.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/test/block.js
  assets/js/hocs/with-attributes.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-element-options.js
Labels: skip-changelog, status: ready to merge, type: refactor

#3285 Fix React hook dependency warnings in filter an All Products blocks
  assets/js/base/components/checkbox-list/index.js
  assets/js/base/components/price-slider/constrain-range-slider-values.js
  assets/js/base/components/price-slider/index.js
  assets/js/base/components/product-list/index.js
  assets/js/base/hooks/use-previous.js
  assets/js/base/hooks/use-query-state.js
  assets/js/blocks/active-filters/block.js
  assets/js/blocks/attribute-filter/block.js
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/price-filter/block.js
  assets/js/blocks/price-filter/use-price-constraints.js
Labels: skip-changelog, status: ready to merge, type: refactor

#3325 Enable 'react-hooks/exhaustive-deps' ESLint flag
  .eslintrc.js
Labels: skip-changelog, status: ready to merge, type: build

#3260 Save order after creating an account
  src/Domain/Services/CreateAccount.php
  src/StoreApi/Routes/Checkout.php
  tests/php/Domain/Services/CreateAccount.php
Labels: action: needs feedback, scope: extensibility, skip-changelog, status: ready to merge, ◼️ block: checkout

#3331 Allow shoppers to sign-up for an account from the Checkout block
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/form/address-step.js
  assets/js/blocks/cart-checkout/checkout/form/contact-fields-step.js
  assets/js/blocks/cart-checkout/checkout/form/index.js
  src/Domain/Services/CreateAccount.php
Labels: status: ready to merge, ◼️ block: checkout

#3335 Update composer.lock to v. 2
  composer.lock
Labels: skip-changelog, status: ready to merge, type: blocker, type: build

#3348 Add new doc referencing feature flags and experimental interfaces.
  .github/pull_request_template.md
  docs/blocks/README.md
  docs/blocks/feature-flags-and-experimental-interfaces.md
Labels: scope: documentation, status: ready to merge
