Repository woocommerce/woocommerce-blocks, pull requests merged in 2020-05, with the labels that each got.

#2368 Fix summary styles and margins/padding #2340
  assets/js/base/components/cart-checkout/product-metadata/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: status: ready to merge

#2366 Change when InnerBlocks are rendered to fix image alignment issues in empty cart
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/cart/empty-cart-edit/index.js
Labels: status: ready to merge

#2367 Rename the discount section when discount total is zero
  assets/js/base/components/cart-checkout/totals/totals-discount-item/index.js
  assets/js/base/components/formatted-monetary-amount/index.js
Labels: status: ready to merge

#2369 Assets/Block settings: Only lookup page if ID > 0
  src/Assets.php
  tests/bootstrap.php
Labels: status: ready to merge

#2372 Ensure stripe payment request "canMakePayment" configuration uses site country.
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/payment-request-express.js
  src/Assets.php
Labels: scope: extensibility, status: ready to merge, type: bug

#2384 Add Todo Probot config
  .github/config.yml
  assets/js/base/context/cart-checkout/checkout/processor/index.js
Labels: type: build

#2391 Fix long product names regression
  assets/js/base/components/cart-checkout/product-name/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: scope: components, skip-changelog, status: ready to merge, type: bug

#2375 Don't show checkout block for logged out users unless store is configured to allow guest checkout
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/settings/blocks/constants.js
  src/Assets.php
Labels: skip-changelog, status: ready to merge

#2389 decode html entities in ProductName component
  assets/js/base/components/cart-checkout/product-name/index.js
Labels: skip-changelog, status: ready to merge

#2390 remove radius from checkout submit button (use theme button style)
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: status: ready to merge

#2370 Use container queries to load Cart and Checkout responsive styles
  assets/css/abstracts/_breakpoints.scss
  assets/js/base/components/cart-checkout/form-step/style.scss
  assets/js/base/components/sidebar-layout/sidebar-layout.js
  assets/js/base/components/sidebar-layout/style.scss
  assets/js/base/hooks/index.js
  assets/js/base/hooks/use-container-queries.js
  assets/js/blocks/cart-checkout/cart/full-cart/editor.scss
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
  package-lock.json
  package.json
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
Labels: skip-changelog, status: ready to merge, type: enhancement

#2400 ensure checkout submit button doesn't get pushed offscreen by big spenders
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: status: ready to merge

#2401 clarify various checkout block editor sidebar wording
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/index.js
Labels: status: ready to merge

#2374 Store billing address to local state and persist globally to prevent loss of data
  assets/js/base/components/select/validated.js
  assets/js/base/components/state-input/state-input.js
  assets/js/base/components/text-input/validated.js
  assets/js/base/context/cart-checkout/billing/constants.js
  assets/js/base/context/cart-checkout/validation/index.js
  assets/js/base/hooks/checkout/index.js
  assets/js/base/hooks/checkout/use-checkout-address.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/type-defs/billing.js
  assets/js/type-defs/contexts.js
Labels: status: ready to merge

#2387 Remove API summaries in favour of client side code
  assets/js/atomic/components/product/summary/index.js
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/cart-checkout/product-metadata/index.js
  assets/js/base/components/cart-checkout/product-summary/index.js
  assets/js/base/components/cart-checkout/product-variation-data/index.js
  assets/js/base/components/summary/index.js
  assets/js/base/components/summary/test/index.js
  assets/js/base/components/summary/utils.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/checkout/sidebar/order-summary-item.js
  assets/js/blocks/featured-product/block.js
  assets/js/data/cart/test/selectors.js
  assets/js/previews/cart.js
  assets/js/previews/products.js
  package-lock.json
  package.json
  src/Assets.php
  src/StoreApi/Schemas/CartItemSchema.php
  src/StoreApi/Schemas/ProductSchema.php
  src/StoreApi/Utilities/ProductSummary.php
  tests/php/StoreApi/Utilities/ProductSummary.php
Labels: status: ready to merge

#2417 Update Stripe/payment payment notices
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/elements.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-checkout-subscriptions.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/type-defs.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/utils.js
Labels: status: ready to merge

#2416 Allow validated text inputs to focus on mount
  assets/js/base/components/cart-checkout/totals/totals-coupon-code-input/index.js
  assets/js/base/components/text-input/validated.js
Labels: status: ready to merge

#2405 SCSS mixins cleanup
  assets/css/abstracts/_mixins.scss
  assets/js/base/components/cart-checkout/form-step/style.scss
  assets/js/base/components/cart-checkout/policies/style.scss
  assets/js/base/components/cart-checkout/product-low-stock-badge/style.scss
  assets/js/base/components/cart-checkout/product-metadata/style.scss
  assets/js/base/components/cart-checkout/product-name/style.scss
  assets/js/base/components/cart-checkout/product-sale-badge/style.scss
  assets/js/base/components/cart-checkout/shipping-rates-control/style.scss
  assets/js/base/components/cart-checkout/totals/totals-item/style.scss
  assets/js/base/components/payment-methods/no-payment-methods/style.scss
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/select/style.scss
  assets/js/base/components/text-input/style.scss
  assets/js/base/components/validation/style.scss
  assets/js/blocks/attribute-filter/editor.scss
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/editor.scss
  assets/js/blocks/cart-checkout/checkout/no-shipping-placeholder/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
  assets/js/blocks/price-filter/editor.scss
  assets/js/blocks/product-categories/style.scss
  assets/js/blocks/product-search/style.scss
  assets/js/blocks/products/editor.scss
  assets/js/components/product-attribute-term-control/style.scss
  assets/js/components/product-control/style.scss
Labels: status: ready to merge

#2420 Add an inline skeleton sizing script
  src/BlockTypes/AbstractBlock.php
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
Labels: status: ready to merge

#2436 Add eslint-plugin-react-hooks
  .eslintrc.js
  package-lock.json
  package.json
Labels: skip-changelog, status: ready to merge, type: build

#2431 Fix 'Try reloading the page' button styles
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
Labels: skip-changelog, status: ready to merge

#2443 Fix PayPal file name
  src/Payments/Integrations/PayPal.php
Labels: status: ready to merge

#2444 Fix multiple extra stripe createSource requests than necessary
  assets/js/base/context/cart-checkout/validation/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/payment-method.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-checkout-subscriptions.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-payment-processing.js
Labels: scope: extensibility, status: ready to merge, type: bug, type: refactor

#2450 Fixes regression with payment method validation
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/components/payment-methods/saved-payment-method-options.js
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/validation/index.js
  assets/js/base/context/store-notices-context.js
  assets/js/base/hooks/use-store-notices.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/payment-method.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-payment-processing.js
  assets/js/previews/saved-payment-methods.js
  assets/js/type-defs/contexts.js
Labels: scope: extensibility, status: ready to merge, type: bug

#2448 fix broken cart styles in Editor
  assets/js/blocks/cart-checkout/cart/full-cart/editor.scss
Labels: skip-changelog, status: ready to merge

#2425 Fix saved payment method selection not working for purchases.
  assets/js/base/components/payment-methods/saved-payment-method-options.js
  assets/js/base/components/radio-control/index.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
Labels: scope: extensibility, status: ready to merge, type: bug

#2432 Introduce ContainerQueryContextProvider - hide order summary on mobile
  assets/js/base/components/sidebar-layout/sidebar-layout.js
  assets/js/base/context/container-width-context.js
  assets/js/base/context/index.js
  assets/js/base/hooks/use-container-queries.js
  assets/js/blocks/cart-checkout/checkout/sidebar/order-summary.js
  assets/js/type-defs/contexts.js
Labels: status: ready to merge

#2463 Add 'Handpicked Products' block keyword
  assets/js/blocks/handpicked-products/index.js
Labels: skip-changelog, status: ready to merge, type: enhancement

#1894 If product is changed for featured product block, update the link in the button.
  assets/js/blocks/featured-product/block.js
Labels: scope: blocks, status: ready to merge, type: bug

#2462 All Products Block: Update sorting labels to match frontend options
  assets/js/blocks/products/edit.js
Labels: status: ready to merge

#2465 Remove Shipping totals editor.scss file
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/index.js
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/shipping-rate-selector.js
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/style.scss
  assets/js/base/components/quantity-selector/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/editor.scss
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
Labels: skip-changelog, status: ready to merge, type: refactor

#2461 Use display table instead of flex in radio control group
  assets/js/base/components/radio-control/_mixin.scss
  assets/js/base/components/radio-control/option-layout.js
Labels: status: ready to merge

#2464 Avoid const and let in inline JS
  src/BlockTypes/AbstractBlock.php
Labels: status: ready to merge

#2453 Allow shopper to save Stripe payment method in user account for subsequent purchases
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/base/context/cart-checkout/payment-methods/actions.js
  assets/js/base/context/cart-checkout/payment-methods/constants.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/payment-methods/reducer.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/blocks-registry/payment-methods/payment-method-config.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/payment-method.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-checkout-subscriptions.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/use-payment-processing.js
  assets/js/type-defs/contexts.js
  assets/js/type-defs/registered-payment-method-props.js
Labels: status: ready to merge

#2467 Refactor `usePaymentMethodRegistration` to ensure payment methods are populated once initialization is true
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/payment-methods/use-payment-method-registration.js
Labels: status: ready to merge

#2434 Update wp.editor references, bump min version support
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-category/index.js
  assets/js/blocks/featured-product/block.js
  assets/js/blocks/featured-product/index.js
  assets/js/blocks/handpicked-products/block.js
  assets/js/blocks/product-best-sellers/block.js
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-category/block.js
  assets/js/blocks/product-new/block.js
  assets/js/blocks/product-on-sale/block.js
  assets/js/blocks/product-search/edit.js
  assets/js/blocks/product-tag/block.js
  assets/js/blocks/product-top-rated/block.js
  assets/js/blocks/products-by-attribute/block.js
  assets/js/blocks/reviews/all-reviews/edit.js
  assets/js/blocks/reviews/edit-utils.js
  assets/js/blocks/reviews/reviews-by-category/edit.js
  assets/js/blocks/reviews/reviews-by-product/edit.js
  package-lock.json
  woocommerce-gutenberg-products-block.php
Labels: scope: documentation, status: ready to merge

#2469 Account for middlewares as effectful code
  package.json
Labels: skip-changelog, status: ready to merge

#2470 Fix missing Checkout order summary component
  assets/js/blocks/cart-checkout/checkout/sidebar/order-summary.js
Labels: status: ready to merge

#2473 Fix regression for payment methods in incognito mode.
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/components/tabs/index.js
Labels: scope: extensibility, status: ready to merge, type: bug

#2477 Ensure email and phone are persisted through `setBillingData`
  assets/js/base/context/cart-checkout/billing/index.js
  assets/js/base/hooks/checkout/use-checkout-address.js
Labels: status: ready to merge

#2466 Update Stripe Method to display generic icon and text in label, with cards below
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/cart-checkout/payment-method-icons/index.js
  assets/js/base/components/cart-checkout/payment-method-icons/style.scss
  assets/js/base/components/cart-checkout/payment-method-label/index.js
  assets/js/base/components/cart-checkout/payment-method-label/style.scss
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/blocks/cart-checkout/cart/checkout-button/style.scss
  assets/js/icons/index.js
  assets/js/icons/library/bank.js
  assets/js/icons/library/check-payment.js
  assets/js/payment-method-extensions/payment-methods/cheque/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/payment-method.js
  assets/js/type-defs/registered-payment-method-props.js
Labels: status: ready to merge

#2482 Fix all shipping address changes in stripe payment request timing out with no rate update.
  assets/js/base/hooks/checkout/use-checkout-address.js
Labels: scope: extensibility, status: ready to merge, type: bug

#2478 Add CSS resets for better theme compatibility
  assets/css/abstracts/_mixins.scss
  assets/js/base/components/cart-checkout/button/style.scss
  assets/js/base/components/cart-checkout/form-step/style.scss
  assets/js/base/components/cart-checkout/policies/style.scss
  assets/js/base/components/cart-checkout/return-to-cart-button/style.scss
  assets/js/base/components/cart-checkout/shipping-rates-control/style.scss
  assets/js/base/components/cart-checkout/totals/totals-shipping-item/style.scss
  assets/js/base/components/checkbox-control/style.scss
  assets/js/base/components/dropdown-selector/style.scss
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/product-list/style.scss
  assets/js/base/components/quantity-selector/style.scss
  assets/js/base/components/radio-control/_mixin.scss
  assets/js/base/components/select/style.scss
  assets/js/base/components/sidebar-layout/style.scss
  assets/js/base/components/sort-select/style.scss
  assets/js/base/components/tabs/style.scss
  assets/js/base/components/text-input/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: status: ready to merge

#2479 Add docs for CSS specificity
  docs/contributors/coding-guidelines.md
Labels: status: ready to merge

#2485 Only set to pristine when checkout is idle, not when idle status changes
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
Labels: status: ready to merge

#2455 respect stripe saved cards store setting
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/index.js
  src/Payments/Integrations/Stripe.php
Labels: skip-changelog, status: ready to merge

#2484 Fix shipping rate and address handling in Stripe payment request payment method.
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/shipping/constants.js
  assets/js/base/context/cart-checkout/shipping/index.js
  assets/js/base/context/store-notices-context.js
  assets/js/base/hooks/shipping/constants.js
  assets/js/base/hooks/shipping/use-shipping-address.js
  assets/js/base/hooks/use-store-notices.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/payment-request-express.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/use-checkout-subscriptions.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/use-event-handlers.js
  assets/js/payment-method-extensions/payment-methods/stripe/payment-request/use-initialization.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/type-defs.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/utils.js
  assets/js/type-defs/contexts.js
  assets/js/type-defs/registered-payment-method-props.js
Labels: scope: extensibility, status: ready to merge, type: bug, type: refactor

#2492 Checkout block: fix error 'setIsSuppressed' in editor
  assets/js/base/context/store-notices-context.js
Labels: skip-changelog, status: ready to merge, type: blocker, type: bug

#2495 Fix Editor performance issues with checkout block.
  assets/js/base/hooks/cart/test/use-store-cart.js
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/type-defs.js
Labels: skip-changelog, status: ready to merge, type: bug

#2496 Swap shipping rate pricing for Editor preview data
  assets/js/previews/shipping-rates.js
Labels: status: ready to merge, type: bug

#2371 Use Reakit in payment tabs
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/components/tabs/index.js
  assets/js/base/components/tabs/tab-button.js
  package-lock.json
  package.json
Labels: skip-changelog, status: ready to merge, type: enhancement

#2499 Remove ProductPreview component
  assets/js/components/README.md
  assets/js/components/product-preview/index.js
  assets/js/components/product-preview/style.scss
  assets/js/components/product-preview/test/__snapshots__/index.js.snap
  assets/js/components/product-preview/test/index.js
Labels: skip-changelog, status: ready to merge, type: refactor

#2494 Remove class 'button' from Button component
  assets/js/base/components/cart-checkout/button/index.js
  assets/js/base/components/cart-checkout/button/style.scss
Labels: skip-changelog, status: ready to merge

#2502 Add notices docs
  assets/js/data/query-state/README.md
  docs/block-client-apis/README.md
  docs/block-client-apis/notices.md
Labels: scope: documentation, status: ready to merge

#2498 Remove some unique font-size
  assets/js/base/components/payment-methods/no-payment-methods/style.scss
  assets/js/blocks/cart-checkout/checkout/no-shipping-placeholder/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
  assets/js/blocks/product-categories/style.scss
  assets/js/blocks/product-search/style.scss
Labels: skip-changelog, status: ready to merge

#2507 Fix decimal ratings not correctly displayed
  assets/js/atomic/components/product/rating/index.js
  assets/js/base/components/product-list/style.scss
  assets/js/base/components/reviews/review-list-item/index.js
Labels: scope: components, status: ready to merge, type: bug

#2518 Fix misalignment between value and label in form components
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/select/style.scss
  assets/js/base/components/text-input/style.scss
Labels: scope: components, skip-changelog, status: ready to merge

#2528 Add React Testing Library
  package-lock.json
  package.json
  tests/js/jest.config.json
  tests/js/setup-fetch.js
  tests/js/setup-globals.js
Labels: scope: tests

#2517 Align Product Categories List select and button
  assets/js/blocks/product-categories/style.scss
Labels: status: needs review

#2513 Import TwentyTwenty block styles from Core
  assets/css/editor.scss
  assets/js/base/components/product-list/style.scss
  src/Assets.php
Labels: status: ready to merge

#2532 Include `onSubmit` handler for CheckoutForm component.
  assets/js/base/components/cart-checkout/form/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: scope: accessibility, status: ready to merge, type: bug

#2545 Ensure default selected tab is set for payment methods selection ui.
  assets/js/base/components/tabs/index.js
Labels: scope: extensibility, status: ready to merge, type: bug

#2547 Fix broken dynamic address fields dependent on locale for selected country.
  assets/js/base/components/cart-checkout/address-form/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: status: ready to merge, type: bug

#2514 Exclude three more files from the build ZIP
  bin/build-plugin-zip.sh
  bin/wordpress-deploy.sh
Labels: skip-changelog, status: ready to merge, type: build

#2553 Improve readme.txt with note about nature of feature plugin
  README.md
  readme.txt
Labels: scope: documentation, status: ready to merge

#2551 Fix Products by Category JSON response error
  src/StoreApi/Routes/AbstractTermsRoute.php
Labels: skip-changelog, status: ready to merge, type: blocker, type: bug

#2486 Fix Cart style discrepancies (editor-frontend)
  assets/js/base/components/cart-checkout/button/style.scss
  assets/js/base/components/title/index.js
  assets/js/base/components/title/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-title.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: skip-changelog, status: ready to merge

#2563 Use absint for per-page param validation
  src/StoreApi/Routes/AbstractTermsRoute.php
Labels: skip-changelog, status: ready to merge

#2557 Ensure all inline @todos in code are covered by issues and obsolete @todos removed.
  assets/css/abstracts/_colors.scss
  assets/js/base/components/payment-methods/express-checkout.js
  assets/js/base/hooks/order/use-store-order.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/base/hooks/test/use-query-state.js
  assets/js/blocks-registry/payment-methods/assertions.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/normalize.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/utils.js
  src/BlockTypes/Checkout.php
  src/Library.php
  src/StoreApi/Routes/AbstractRoute.php
  src/StoreApi/Schemas/CartItemSchema.php
  src/StoreApi/Utilities/CartController.php
Labels: status: ready to merge

#2567 Accept object parameters in renderFrontend utility
  assets/js/base/utils/index.js
  assets/js/base/utils/render-frontend.js
  assets/js/blocks/active-filters/frontend.js
  assets/js/blocks/attribute-filter/frontend.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/blocks/price-filter/frontend.js
  assets/js/blocks/products/all-products/frontend.js
  assets/js/blocks/reviews/frontend.js
Labels: status: ready to merge

#2566 Updates for the abstract block class
  src/BlockTypes/AbstractBlock.php
Labels: status: ready to merge

#2543 Add arguments to wc_get_shipping_method_count()
  src/BlockTypes/Checkout.php
Labels: skip-changelog, status: ready to merge

#2574 Delete orders using delete method in batches of 20
  src/Library.php
Labels: status: ready to merge

#2569 Create single product block placeholder
  assets/js/blocks/single-product/attributes.js
  assets/js/blocks/single-product/block.js
  assets/js/blocks/single-product/constants.js
  assets/js/blocks/single-product/edit.js
  assets/js/blocks/single-product/frontend.js
  assets/js/blocks/single-product/index.js
  assets/js/blocks/single-product/save.js
  assets/js/icons/index.js
  assets/js/icons/library/reader.js
  assets/js/icons/library/restore.js
  bin/webpack-helpers.js
  src/Assets.php
  src/BlockTypes/SingleProduct.php
  src/Library.php
  tests/e2e-tests/specs/__snapshots__/single-product.test.js.snap
  tests/e2e-tests/specs/single-product.test.js
  webpack.config.js
Labels: status: ready to merge

#2530 Checkout steps improvements
  assets/js/base/components/cart-checkout/form-step/index.js
  assets/js/base/components/cart-checkout/form-step/style.scss
Labels: scope: accessibility, skip-changelog, status: ready to merge

#2579 Fix registered payment methods not recognized by Checkout block on initial insertion into content
  src/Payments/Api.php
Labels: status: ready to merge, type: bug

#2580 Fix undefined index for `saved_cards`
  src/Payments/Integrations/Stripe.php
Labels: status: ready to merge, type: bug

#2568 Create shared contexts handle for inner blocks
  assets/js/atomic/components/product/button/index.js
  assets/js/atomic/components/product/image/index.js
  assets/js/atomic/components/product/price/index.js
  assets/js/atomic/components/product/rating/index.js
  assets/js/atomic/components/product/sale-badge/index.js
  assets/js/atomic/components/product/summary/index.js
  assets/js/atomic/components/product/title/index.js
  assets/js/base/components/product-list-item/index.js
  assets/js/base/components/product-list/index.js
  assets/js/base/components/product-list/no-matching-products.js
  assets/js/base/components/product-list/no-products.js
  assets/js/base/context/index.js
  assets/js/base/context/inner-block-configuration-context.js
  assets/js/base/context/product-layout-context.js
  assets/js/blocks/products/all-products/block.js
  assets/js/blocks/products/all-products/edit.js
  assets/js/shared/context/index.js
  assets/js/shared/context/inner-block-configuration-context.js
  assets/js/shared/context/product-data-context.js
  bin/webpack-helpers.js
  src/Assets.php
  tests/js/jest.config.json
  webpack.config.js
Labels: status: ready to merge, type: refactor

#2456 Update placeholder styles
  assets/css/editor.scss
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-category/editor.scss
  assets/js/blocks/featured-product/block.js
  assets/js/blocks/featured-product/editor.scss
  assets/js/blocks/handpicked-products/block.js
  assets/js/blocks/product-category/block.js
  assets/js/blocks/product-category/editor.scss
  assets/js/blocks/product-tag/block.js
  assets/js/blocks/product-tag/editor.scss
  assets/js/blocks/products-by-attribute/block.js
  assets/js/blocks/reviews/reviews-by-category/edit.js
  assets/js/blocks/reviews/reviews-by-product/edit.js
  assets/js/components/product-attribute-term-control/style.scss
  assets/js/components/product-category-control/style.scss
  assets/js/components/product-tag-control/style.scss
Labels: skip-changelog, status: ready to merge, type: bug

#2533 Use named font sizes instead of values in px
  assets/css/abstracts/_mixins.scss
  assets/js/base/components/block-error-boundary/style.scss
  assets/js/base/components/cart-checkout/button/style.scss
  assets/js/base/components/cart-checkout/form-step/style.scss
  assets/js/base/components/cart-checkout/policies/style.scss
  assets/js/base/components/cart-checkout/product-low-stock-badge/style.scss
  assets/js/base/components/cart-checkout/product-metadata/style.scss
  assets/js/base/components/cart-checkout/product-name/style.scss
  assets/js/base/components/cart-checkout/product-sale-badge/style.scss
  assets/js/base/components/cart-checkout/shipping-rates-control/style.scss
  assets/js/base/components/cart-checkout/totals/totals-footer-item/style.scss
  assets/js/base/components/cart-checkout/totals/totals-item/style.scss
  assets/js/base/components/chip/style.scss
  assets/js/base/components/pagination/style.scss
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/quantity-selector/style.scss
  assets/js/base/components/radio-control/_mixin.scss
  assets/js/base/components/reviews/review-list-item/style.scss
  assets/js/base/components/select/style.scss
  assets/js/base/components/tabs/style.scss
  assets/js/base/components/text-input/style.scss
  assets/js/base/components/title/style.scss
  assets/js/base/components/validation/style.scss
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/attribute-filter/editor.scss
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/editor.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
  assets/js/blocks/price-filter/edit.js
  assets/js/blocks/price-filter/editor.scss
  assets/js/blocks/product-categories/style.scss
  assets/js/blocks/product-search/style.scss
  assets/js/blocks/products/editor.scss
  assets/js/blocks/products/utils.js
  docs/contributors/coding-guidelines.md
Labels: scope: components, skip-changelog, status: ready to merge

#2586 Add layout editor to the single product block
  assets/js/atomic/utils/create-blocks-from-template.js
  assets/js/atomic/utils/get-block-map.js
  assets/js/atomic/utils/index.js
  assets/js/base/components/product-list-item/utils.js
  assets/js/blocks/products/all-products/edit.js
  assets/js/blocks/products/base-utils.js
  assets/js/blocks/single-product/constants.js
  assets/js/blocks/single-product/edit/editor.scss
  assets/js/blocks/single-product/edit/index.js
  assets/js/blocks/single-product/edit/layout-editor.js
  bin/webpack-helpers.js
  tests/js/jest.config.json
  tsconfig.json
Labels: status: ready to merge

#2587 Update atomic block structure
  assets/js/atomic/blocks/index.js
  assets/js/atomic/blocks/product/block-components.js
  assets/js/atomic/blocks/product/button/block.js
  assets/js/atomic/blocks/product/button/edit.js
  assets/js/atomic/blocks/product/button/index.js
  assets/js/atomic/blocks/product/image/attributes.js
  assets/js/atomic/blocks/product/image/block.js
  assets/js/atomic/blocks/product/image/edit.js
  assets/js/atomic/blocks/product/image/index.js
  assets/js/atomic/blocks/product/index.js
  assets/js/atomic/blocks/product/price/block.js
  assets/js/atomic/blocks/product/price/edit.js
  assets/js/atomic/blocks/product/price/index.js
  assets/js/atomic/blocks/product/rating/block.js
  assets/js/atomic/blocks/product/rating/edit.js
  assets/js/atomic/blocks/product/rating/index.js
  assets/js/atomic/blocks/product/sale-badge/block.js
  assets/js/atomic/blocks/product/sale-badge/edit.js
  assets/js/atomic/blocks/product/sale-badge/index.js
  assets/js/atomic/blocks/product/shared-config.js
  assets/js/atomic/blocks/product/summary/block.js
  assets/js/atomic/blocks/product/summary/edit.js
  assets/js/atomic/blocks/product/summary/index.js
  assets/js/atomic/blocks/product/title/attributes.js
  assets/js/atomic/blocks/product/title/block.js
  assets/js/atomic/blocks/product/title/edit.js
  assets/js/atomic/blocks/product/title/index.js
  assets/js/atomic/components/product/index.js
  assets/js/atomic/utils/get-block-map.js
  assets/js/blocks/products/all-products/index.js
  assets/js/legacy/README.md
  bin/webpack-helpers.js
  tests/js/jest.config.json
  tsconfig.json
Labels: status: ready to merge

#2585 Add "edit product" card to single product block sidebar
  assets/js/blocks/single-product/edit/edit-product-link.js
  assets/js/blocks/single-product/edit/editor.scss
  assets/js/blocks/single-product/edit/index.js
Labels: status: ready to merge
