Repository woocommerce/woocommerce-blocks, pull requests merged in 2020-01, with the labels that each got.

#1459 Update Node.js to v12.13.0
  .travis.yml
  bin/eslint-plugin-woocommerce/package.json
  package.json
Labels: skip-changelog, status: ready to merge

#1453 Make price slider accurately represent the selected price independently from step
  assets/js/base/components/price-slider/index.js
Labels: status: ready to merge, type: bug

#1466 Remove outdated comments from useStoreProducts
  assets/js/base/hooks/use-store-products.js
Labels: skip-changelog, status: ready to merge

#1458 Price filter: allow negative numbers in input fields
  assets/js/base/components/formatted-monetary-amount/index.js
  assets/js/base/components/price-slider/index.js
  assets/js/base/components/price-slider/test/constrain-range-slider-values.js
  assets/js/blocks/price-filter/block.js
Labels: status: ready to merge, type: bug

#1457 Price filter: allow any numeric input
  assets/js/base/components/formatted-monetary-amount/index.js
  assets/js/base/components/price-slider/constrain-range-slider-values.js
  assets/js/base/components/price-slider/index.js
  assets/js/base/components/price-slider/test/constrain-range-slider-values.js
  assets/js/blocks/price-filter/block.js
Labels: status: ready to merge

#1467 Checkout: Fix city input field showing country value
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: skip-changelog, status: ready to merge

#1447 Fix empty cart inner blocks disabled
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/cart/index.js
Labels: skip-changelog, status: ready to merge, type: bug

#1449 Rename checkout classes from 'wc-blocks-xyz' to 'wc-block-xyz'
  assets/js/base/components/checkout/form-step/index.js
  assets/js/base/components/checkout/form-step/style.scss
  assets/js/base/components/checkout/form/index.js
  assets/js/base/components/checkout/form/style.scss
  assets/js/base/components/checkout/no-shipping/index.js
  assets/js/base/components/checkout/no-shipping/style.scss
  assets/js/base/components/input-row/index.js
  assets/js/base/components/input-row/style.scss
  assets/js/base/components/radio-control/index.js
  assets/js/base/components/radio-control/style.scss
  assets/js/base/components/text-input/index.js
  assets/js/base/components/text-input/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/editor.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: skip-changelog, status: ready to merge

#1493 Show grouped products with tax rate
  src/RestApi/StoreApi/Schemas/ProductSchema.php
Labels: status: ready to merge

#1446 Fix Cart buttons misalignment in Firefox
  assets/js/components/text-toolbar-button/style.scss
Labels: skip-changelog, status: ready to merge, type: bug

#1349 Add payment method api and components to checkout steps
  assets/js/base/components/payment-methods/express-checkout.js
  assets/js/base/components/payment-methods/express-payment-methods.js
  assets/js/base/components/payment-methods/index.js
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/tabs/index.js
  assets/js/base/components/tabs/style.scss
  assets/js/base/context/checkout-context.js
  assets/js/base/hooks/checkout/index.js
  assets/js/base/hooks/checkout/use-checkout-data.js
  assets/js/base/hooks/checkout/use-checkout-events.js
  assets/js/base/hooks/checkout/use-checkout-notices.js
  assets/js/base/hooks/checkout/use-checkout-place-order-label.js
  assets/js/base/hooks/checkout/use-checkout-redirect-urls.js
  assets/js/base/hooks/index.js
  assets/js/base/hooks/payment-methods/constants.js
  assets/js/base/hooks/payment-methods/index.js
  assets/js/base/hooks/payment-methods/use-active-payment-method.js
  assets/js/base/hooks/payment-methods/use-payment-events.js
  assets/js/base/hooks/payment-methods/use-payment-methods.js
  assets/js/blocks-registry/index.js
  assets/js/blocks-registry/payment-methods/assertions.js
  assets/js/blocks-registry/payment-methods/express-payment-method-config.js
  assets/js/blocks-registry/payment-methods/index.js
  assets/js/blocks-registry/payment-methods/payment-method-config.js
  assets/js/blocks-registry/payment-methods/registry.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/payment-methods-demo/express-payment/apple-pay.js
  assets/js/payment-methods-demo/express-payment/index.js
  assets/js/payment-methods-demo/express-payment/paypal.js
  assets/js/payment-methods-demo/index.js
  assets/js/payment-methods-demo/payment-methods/cc.js
  assets/js/payment-methods-demo/payment-methods/index.js
  assets/js/payment-methods-demo/payment-methods/paypal.js
  package-lock.json
  tests/js/jest.config.json
  webpack.config.js
Labels: components, skip-changelog, status: ready to merge, type: feature request

#1423 Use Card component for cart's sidebar
  assets/js/base/components/radio-control/index.js
  assets/js/base/components/radio-control/option.js
  assets/js/base/components/totals/totals-coupon-code-input/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  package-lock.json
  package.json
Labels: skip-changelog, status: ready to merge, type: refactor

#1503 All Products: fix variable products subtracting taxes in some configurations
  src/RestApi/StoreApi/Schemas/ProductSchema.php
Labels: status: ready to merge, type: bug

#1505 Remove duplicate application of taxes to price display for grouped products
  src/RestApi/StoreApi/Schemas/ProductSchema.php
Labels: skip-changelog, status: ready to merge, type: bug

#1513 Fix withFeedbackPrompt JSDoc definition
  assets/js/hocs/with-feedback-prompt/index.js
Labels: skip-changelog, status: ready to merge

#1512 Add ESLint radix rule
  .eslintrc.js
  assets/js/base/components/product-list/index.js
  assets/js/blocks/featured-category/block.js
  assets/js/blocks/featured-product/block.js
Labels: skip-changelog, status: ready to merge

#1518 Convert variable product prices to float
  assets/js/atomic/components/product/price/index.js
Labels: status: needs review, type: bug

#1520 Add padding zeros to displayed prices
  assets/js/base/components/formatted-monetary-amount/index.js
Labels: status: ready to merge, type: enhancement

#1524 readme.txt updates: contributors and minimum PHP version
  readme.txt
Labels: skip-changelog, status: ready to merge

#1523 Fix minor issues with TextInput component
  assets/js/base/components/text-input/index.js
  assets/js/base/components/text-input/style.scss
Labels: status: ready to merge

#1333 Add/cart lineitems content
  assets/css/abstracts/_variables.scss
  assets/js/base/components/quantity-selector/index.js
  assets/js/base/components/quantity-selector/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-table.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-title.js
  assets/js/blocks/cart-checkout/cart/full-cart/editor.scss
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/cart/style.scss
  assets/js/components/text-toolbar-button/README.md
  assets/js/previews/cart-items.js
  assets/js/previews/index.js
  assets/js/previews/product-image.js
  assets/js/previews/products.js
  package.json
Labels: skip-changelog, status: in progress, status: ready to merge

#1540 Fix Attribute Filter not reacting to query changes
  assets/js/blocks/attribute-filter/block.js
Labels: skip-changelog, status: ready to merge

#1541 Rename wc-blocks to wc-block classname prefix
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: status: ready to merge

#1515 Fix prices showing two currencies in some occasions
  assets/js/base/utils/price.js
Labels: skip-changelog, status: ready to merge

#1425 REST API - Cart Order API
  src/Library.php
  src/RestApi.php
  src/RestApi/StoreApi/Controllers/CartOrder.php
  src/RestApi/StoreApi/Controllers/Customer.php
  src/RestApi/StoreApi/README.md
  src/RestApi/StoreApi/Schemas/CartSchema.php
  src/RestApi/StoreApi/Schemas/CartShippingRateSchema.php
  src/RestApi/StoreApi/Schemas/CustomerSchema.php
  src/RestApi/StoreApi/Schemas/OrderItemSchema.php
  src/RestApi/StoreApi/Schemas/OrderSchema.php
  src/RestApi/StoreApi/Utilities/ReserveStock.php
  tests/php/RestApi/StoreApi/Controllers/CartOrder.php
  tests/php/RestApi/StoreApi/Controllers/CartShippingRates.php
  tests/php/RestApi/StoreApi/Controllers/Customer.php
  tests/php/RestApi/StoreApi/Utilities/ReserveStock.php
Labels: rest-api, status: ready to merge

#1411 Add Cart totals to Cart block
  assets/js/base/components/button/index.js
  assets/js/base/components/button/style.scss
  assets/js/base/components/radio-control/index.js
  assets/js/base/components/radio-control/option.js
  assets/js/base/components/totals/index.js
  assets/js/base/components/totals/totals-coupon-code-input/index.js
  assets/js/base/components/totals/totals-coupon-code-input/style.scss
  assets/js/base/components/totals/totals-item/index.js
  assets/js/base/components/totals/totals-item/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/checkout-button/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/placeholder-shipping-methods.js
  assets/js/settings/blocks/constants.js
  bin/webpack-helpers.js
  package-lock.json
  package.json
  src/Assets.php
  src/BlockTypes/Cart.php
Labels: skip-changelog, status: ready to merge

#1519 Add Empty Placeholder for the on-sale product block
  assets/js/blocks/product-categories/block.js
  assets/js/blocks/product-on-sale/block.js
  assets/js/blocks/product-on-sale/editor.scss
  assets/js/blocks/product-on-sale/index.js
Labels: status: ready to merge, type: bug

#1544 Remove vendors-frontend from Webpack config
  bin/webpack-helpers.js
  package.json
  src/BlockTypes/Cart.php
Labels: status: ready to merge

#1546 Remove 'wc-vendors-frontend' registration
  src/Assets.php
Labels: status: ready to merge

#1543 Improve changelog script
  bin/changelog.js
  bin/changelog/common/get-entry.js
  bin/changelog/common/index.js
  bin/changelog/common/make.js
  bin/changelog/config.js
  bin/changelog/github/index.js
  bin/changelog/github/make-change-log.js
  bin/changelog/github/requests.js
  bin/changelog/index.js
  bin/changelog/zenhub/index.js
  bin/changelog/zenhub/make-change-log.js
  bin/changelog/zenhub/requests.js
  package-lock.json
  package.json
Labels: skip-changelog, status: ready to merge, type: build

#1547 Fix errors caused by demo payment methods
  assets/js/payment-methods-demo/express-payment/index.js
  assets/js/payment-methods-demo/index.js
  assets/js/payment-methods-demo/payment-methods/index.js
Labels: skip-changelog, status: ready to merge, type: bug

#1400 add fieldset and legend to FormStep component
  assets/js/base/components/checkout/form-step/index.js
  assets/js/base/components/checkout/form-step/style.scss
  assets/js/base/components/checkout/form/style.scss
Labels: accessibility, skip-changelog, status: ready to merge

#1549 show product details in cart line items: attributes (variations), product short description
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/previews/cart-items.js
Labels: skip-changelog, status: ready to merge

#1560 Make TextInput id optional
  assets/js/base/components/text-input/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: skip-changelog, status: ready to merge

#1563 Make RadioControl id optional
  assets/js/base/components/radio-control/index.js
Labels: status: ready to merge

#1557 show low stock warning badge on cart line items
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-table.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/previews/cart-items.js
Labels: skip-changelog, status: ready to merge

#1548 show discount on cart line items & price styling
  assets/js/base/components/formatted-monetary-amount/index.js
  assets/js/base/components/formatted-monetary-amount/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: skip-changelog, status: ready to merge

#1564 follow up fixes on cart low stock warning badge
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-table.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: skip-changelog, status: ready to merge

#1558 Add Quantity selector component for cart line items
  assets/js/base/components/quantity-selector/index.js
  assets/js/base/components/quantity-selector/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: components, skip-changelog, status: ready to merge

#1580 Checkout: Fix city input field showing country value (II)
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: skip-changelog, status: ready to merge

#1576 Introduce view switcher component for the cart block
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/components/view-switcher/editor.scss
  assets/js/components/view-switcher/index.js
Labels: components, skip-changelog, status: ready to merge

#1552 add product short description to cart/items api
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
Labels: rest-api, status: ready to merge

#1593 fix react runtime js error when "link to product" = off in All Products inner blocks editor
  assets/js/atomic/components/product/image/index.js
Labels: status: ready to merge

#1583 Add `low_stock_remaining` field to cart items API
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  tests/php/RestApi/StoreApi/Controllers/CartItems.php
Labels: rest-api, skip-changelog, status: ready to merge

#1582 Focus on Full Cart mode after inserting
  assets/js/blocks/cart-checkout/cart/empty-cart/index.js
Labels: skip-changelog, status: ready to merge

#1579 UI for removing cart items (not including hooking up to API)
  assets/css/abstracts/_mixins.scss
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/editor.scss
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/components/icons/index.js
  assets/js/components/icons/trash.js
Labels: status: ready to merge

#1585 Create CountryInput component
  assets/js/base/components/country-input/billing-country-input.js
  assets/js/base/components/country-input/country-input.js
  assets/js/base/components/country-input/index.js
  assets/js/base/components/country-input/shipping-country-input.js
  assets/js/base/components/country-input/style.scss
  assets/js/base/components/input-row/style.scss
  assets/js/base/components/text-input/style.scss
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/settings/blocks/constants.js
  bin/webpack-helpers.js
  package.json
  src/Assets.php
Labels: skip-changelog, status: ready to merge

#1588 Make TextInput respect prefers-reduced-motion preference
  assets/js/base/components/text-input/style.scss
Labels: accessibility, skip-changelog, status: ready to merge

#1596 fix issue when user re-selects same attr when setting up filter block:
  assets/js/blocks/attribute-filter/edit.js
Labels: status: ready to merge

#1598 Fix issue in order by date
  assets/js/base/components/product-list/index.js
Labels: status: ready to merge, type: bug

#1611 Preserve query key order in All Products
  assets/js/base/hooks/use-query-state.js
Labels: status: ready to merge, type: bug

#1587 Improved cart styling for desktop and mobile
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-table.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: skip-changelog, status: ready to merge

#1612 Fix price filter for products when stored prices do not match displayed prices (tax settings)
  src/RestApi/StoreApi/Utilities/ProductQuery.php
Labels: status: ready to merge

#1613 Change default rows for product grid blocks to 3
  assets/js/blocks/products/all-products/index.js
  assets/js/blocks/products/attributes.js
  assets/js/blocks/products/utils.js
  assets/js/filters/block-list-block.js
  assets/js/filters/get-block-attributes.js
  assets/js/hocs/index.js
  assets/js/index.js
  assets/js/settings/blocks/constants.js
  package.json
  src/Assets.php
  src/BlockTypes/AbstractProductGrid.php
  src/BlockTypes/ProductTag.php
  src/BlockTypes/ProductsByAttribute.php
Labels: status: ready to merge

#1614 Document release process
  CONTRIBUTING.md
  RELEASE.md
Labels: status: ready to merge

#1629 Make 'Add order notes?' string localizable
  assets/js/blocks/cart-checkout/checkout/block.js
Labels: skip-changelog, status: ready to merge

#1638 Move default population to class method instead of constructor
  assets/js/filters/block-list-block.js
Labels: skip-changelog, status: ready to merge

#1642 All Products: fix 'Add to Cart' in IE11
  assets/js/atomic/components/product/button/index.js
Labels: status: ready to merge, type: bug

#1633 Reorganize dependencies in package.json
  package-lock.json
  package.json
Labels: skip-changelog, status: ready to merge

#1632 Add renovate config to avoid pinning `jetpack-autoloader` package
  composer.json
  renovate.json
Labels: skip-changelog, status: ready to merge

#1640 Only populate default attributes on initial mount of block.
  assets/js/filters/block-list-block.js
Labels: skip-changelog, status: ready to merge

#1650 Product grid blocks: display rating stars in the editor
  assets/js/base/components/product-list/style.scss
Labels: scope: blocks, status: ready to merge, type: bug

#1651 Fix RTL price slider display issues
  assets/js/base/components/price-slider/style.scss
Labels: status: ready to merge

#1648 Update renovate to assign `type: dependencies` label for pulls
  renovate.json
Labels: skip-changelog, status: ready to merge, type: build

#1655 Update changelog script.
  RELEASE.md
  bin/changelog/README.md
  bin/changelog/common/get-entry.js
  bin/changelog/config.js
  bin/changelog/github/make-change-log.js
  bin/changelog/index.js
  bin/changelog/zenhub/make-change-log.js
  bin/changelog/zenhub/requests.js
  package-lock.json
  package.json
Labels: status: ready to merge, type: build, type: enhancement

#1653 CSS naming convention docs
  .gitattributes
  .github/CODEOWNERS
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/SECURITY.md
  RELEASE.md
  bin/build-plugin-zip.sh
  bin/wordpress-deploy.sh
  docs/coding-guidelines.md
  docs/releasing-new-versions.md
Labels: skip-changelog, status: ready to merge

#1659 Rename the "Align Buttons" option for the All Products Block
  assets/js/base/components/product-list/style.scss
  assets/js/components/grid-layout-control/index.js
Labels: action: needs feedback, status: ready to merge

#1639 Summary/description consistency update
  assets/js/atomic/blocks/product/button/index.js
  assets/js/atomic/blocks/product/summary/index.js
  assets/js/atomic/components/product/summary/index.js
  assets/js/previews/cart-items.js
  assets/js/previews/products.js
  src/RestApi/StoreApi/Schemas/CartItemSchema.php
  src/RestApi/StoreApi/Schemas/ProductSchema.php
  src/RestApi/Utilities/ProductSummary.php
  tests/php/RestApi/Utilities/ProductSummary.php
Labels: skip-changelog, status: ready to merge

#1672 Replace three dots with an ellipsis in Product Search placeholder
  assets/js/blocks/product-search/index.js
Labels: scope: accessibility, status: ready to merge, type: bug

#1656 All Products & filters accessibility improvements
  assets/js/atomic/components/product/rating/index.js
  assets/js/atomic/components/product/sale-badge/index.js
  assets/js/base/components/dropdown-selector/index.js
  assets/js/base/components/dropdown-selector/input.js
  assets/js/base/components/dropdown-selector/selected-value.js
  assets/js/base/components/filter-submit-button/index.js
  assets/js/base/components/pagination/index.js
  assets/js/base/components/price-slider/index.js
  assets/js/base/components/product-list/index.js
  assets/js/base/components/product-list/style.scss
  assets/js/blocks/active-filters/block.js
  assets/js/blocks/active-filters/utils.js
Labels: scope: accessibility, status: ready to merge

#1636 Basic storybook implementation
  .gitignore
  assets/js/base/components/button/stories/index.js
  assets/js/base/components/price-slider/stories/index.js
  assets/js/base/components/read-more/stories/index.js
  assets/js/components/error-placeholder/stories/index.js
  package-lock.json
  package.json
  storybook/main.js
  storybook/preview.js
  storybook/style.scss
  storybook/webpack.config.js
Labels: action: needs feedback, status: ready to merge, type: build

#1630 Add and/or labelling to active filters block
  assets/js/blocks/active-filters/active-attribute-filters.js
  assets/js/blocks/active-filters/block.js
  assets/js/blocks/active-filters/style.scss
  assets/js/blocks/active-filters/utils.js
Labels: status: ready to merge

#1691 Re-organise docs and add WP update instructions
  .github/CONTRIBUTING.md
  README.md
  docs/contributors/coding-guidelines.md
  docs/contributors/getting-started.md
  docs/contributors/javascript-testing.md
  docs/contributors/smoke-testing.md
  docs/readme.md
  docs/releases/readme.md
  docs/releases/wordpress-update-testing-checklist.md
Labels: scope: documentation, status: ready to merge

#1687 Add API fetch error handling
  assets/js/base/components/block-error-boundary/block-error.js
  assets/js/base/components/block-error-boundary/index.js
  assets/js/base/components/block-error-boundary/style.scss
  assets/js/base/components/product-list/index.js
  assets/js/base/hooks/test/use-collection.js
  assets/js/base/hooks/test/use-store-products.js
  assets/js/base/hooks/use-collection.js
  assets/js/base/hooks/use-store-products.js
  assets/js/data/collections/action-types.js
  assets/js/data/collections/actions.js
  assets/js/data/collections/reducers.js
  assets/js/data/collections/resolvers.js
  assets/js/data/collections/selectors.js
Labels: action: needs feedback, status: ready to merge

#1694 Load core translations for PHP strings that don't have a translation
  woocommerce-gutenberg-products-block.php
Labels: scope: i18n, status: ready to merge

#1631 Introduce feature flags
  .gitignore
  .travis.yml
  assets/js/blocks/cart-checkout/cart/index.js
  assets/js/blocks/cart-checkout/checkout/index.js
  bin/webpack-helpers.js
  package-lock.json
  package.json
  src/Assets.php
  src/Domain/Bootstrap.php
  src/Library.php
  src/RestApi.php
  webpack.config.js
Labels: skip-changelog, status: ready to merge, type: build
