Repository woocommerce/woocommerce-blocks, pull requests merged in 2021-06, with the labels that each got.

#4294 remove usage of mustBeString
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/base/components/cart-checkout/totals/discount/index.js
  assets/js/base/components/cart-checkout/totals/footer-item/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.tsx
  packages/checkout/registry/index.ts
  packages/checkout/utils/validation/index.ts
Labels: category: extensibility, category: refactor, skip-changelog, status: ready to merge, ◼️ block: cart, ◼️ block: checkout

#4282 Add documentation for the `couponName` filter
  docs/extensibility/available-filters.md
Labels: skip-changelog, status: ready to merge, type: documentation

#4284 Check if there are tax lines before rendering the container for them
  packages/checkout/totals/taxes/index.tsx
Labels: category: blocks, category: styles, status: ready to merge, type: bug, ◼️ block: cart, ◼️ block: checkout

#4295 Fix missing translation in Cart and Checkout blocks
  src/Assets/AssetDataRegistry.php
Labels: category: i18n, status: ready to merge, type: blocker, type: bug, ◼️ block: cart, ◼️ block: checkout

#4293 Fix flickering in checkout button when updating quantity in Cart.
  assets/js/base/context/hooks/cart/use-store-cart-item-quantity.ts
Labels: status: ready to merge, type: bug, ◼️ block: cart

#4305 Fix broken phpunit tests
  .env
  .github/workflows/unit-tests.yml
  docker-compose.yml
  tests/bin/Dockerfile
  tests/bin/install-wp-tests.sh
Labels: category: tests, skip-changelog, status: ready to merge, type: bug

#4303 Hide Cart and Checkout blocks from the widget editor
  src/BlockTypesController.php
Labels: category: fse, status: ready to merge, type: enhancement

#4291 Update Cart Widget when adding an item in All Products
  assets/js/data/cart/index.ts
Labels: status: ready to merge, type: bug, ◼️ block: all products

#4292 Block Widgets: add block transforms for legacy widgets with a block equivalent
  assets/js/blocks/product-categories/index.js
  assets/js/blocks/product-search/index.js
  assets/js/blocks/reviews/all-reviews/index.js
Labels: category: fse, status: ready to merge, type: enhancement

#4298 Add cart/extensions endpoint to allow third party extensions to process server-side and get a new cart
  assets/js/base/components/cart-checkout/totals/coupon/index.js
  assets/js/base/components/cart-checkout/totals/coupon/style.scss
  assets/js/base/components/text-input/text-input.tsx
  assets/js/base/components/text-input/validated-text-input.tsx
  assets/js/base/context/providers/validation/components/validation-input-error/index.js
  assets/js/blocks/cart-checkout/checkout/form/contact-fields-step.js
  assets/js/data/cart/actions.ts
  assets/js/types/type-defs/cart.ts
  packages/checkout/panel/style.scss
  packages/checkout/utils/extension-cart-update.ts
  packages/checkout/utils/index.js
  packages/checkout/utils/update-cart-from-api.ts
  src/Domain/Services/ExtendRestApi.php
  src/StoreApi/Routes/CartExtensions.php
  src/StoreApi/RoutesController.php
  src/StoreApi/SchemaController.php
  src/StoreApi/Schemas/CartExtensionsSchema.php
  tests/php/Domain/Services/TestExtendRestApi.php
  tests/php/StoreApi/Routes/CartExtensions.php
Labels: category: extensibility, category: rest-api, status: ready to merge, type: compatibility

#4316 Ensure directories with spaces work with our WP Deploy script
  bin/wordpress-deploy.sh
Labels: skip-changelog, status: ready to merge, type: bug, type: build, type: cooldown

#4324 Document and update naming of Block Asset Handles
  bin/webpack-configs.js
  bin/webpack-entries.js
  bin/webpack-helpers.js
  docs/contributors/block-assets.md
  src/Assets/Api.php
  src/AssetsController.php
  src/BlockTypes/AbstractBlock.php
  src/BlockTypes/AllReviews.php
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
  src/BlockTypes/ReviewsByCategory.php
  src/BlockTypes/ReviewsByProduct.php
  src/BlockTypes/SingleProduct.php
Labels: needs dev-note, status: ready to merge

#4325 Refactor Render Parent Block Function for Atomic Blocks
  assets/js/atomic/utils/index.js
  assets/js/atomic/utils/render-inner-blocks.js
  assets/js/atomic/utils/render-parent-block.js
  assets/js/atomic/utils/render-parent-block.tsx
  assets/js/blocks/single-product/frontend.js
  global.d.ts
Labels: skip-changelog, status: needs review

#4310 Add DiscountsMeta slot to Checkout sidebar
  assets/js/blocks/cart-checkout/checkout/sidebar/index.js
  assets/js/blocks/cart-checkout/checkout/sidebar/test/__snapshots__/index.js.snap
Labels: category: blocks, category: components, category: extensibility, status: ready to merge, ◼️ block: checkout

#4335 Fix Product Categories List display issues in WP 5.8
  assets/js/blocks/product-categories/style.scss
Labels: category: fse, status: ready to merge, type: blocker, ◼️ block: product categories list

#3029 Add storybook demo for Chip
  assets/js/base/components/chip/stories/index.js
Labels: skip-changelog, status: ready to merge, type: build, type: cooldown, type: enhancement

#4339 Make Product Categories List links unclickable in the editor
  assets/js/blocks/product-categories/block.js
Labels: status: ready to merge, type: bug, ◼️ block: product categories list

#4345 Load woocommerce.css in Site editor
  src/AssetsController.php
Labels: category: fse, status: ready to merge, type: bug, 🔹 block-type: reviews

#4349 Add documentation for `__experimentalDiscountsMeta` slot
  docs/blocks/feature-flags-and-experimental-interfaces.md
Labels: skip-changelog, status: ready to merge, type: documentation

#4350 Use old wc-block-style handle
  src/AssetsController.php
Labels: skip-changelog, status: ready to merge, type: blocker

#4351 Add 5.3.1 testing instructions
  docs/testing/releases/531.md
  docs/testing/releases/README.md
  readme.txt
  woocommerce-gutenberg-products-block.php
Labels: skip-changelog, status: ready to merge, type: documentation

#4228 Update Express Payments Loading UI
  assets/js/base/components/cart-checkout/place-order-button/index.js
  assets/js/base/components/loading-mask/index.js
  assets/js/base/components/loading-mask/style.scss
  assets/js/base/components/spinner/index.tsx
  assets/js/base/components/spinner/style.scss
  assets/js/base/context/hooks/payment-methods/use-payment-method-interface.ts
  assets/js/base/context/hooks/payment-methods/use-payment-methods.js
  assets/js/base/context/hooks/test/use-checkout-submit.js
  assets/js/base/context/hooks/use-checkout-submit.js
  assets/js/base/context/hooks/use-store-events.ts
  assets/js/base/context/providers/cart-checkout/checkout/processor/index.js
  assets/js/base/context/providers/cart-checkout/payment-methods/actions.ts
  assets/js/base/context/providers/cart-checkout/payment-methods/constants.ts
  assets/js/base/context/providers/cart-checkout/payment-methods/payment-method-data-context.tsx
  assets/js/base/context/providers/cart-checkout/payment-methods/reducer.ts
  assets/js/base/context/providers/cart-checkout/payment-methods/types.ts
  assets/js/base/context/providers/cart-checkout/payment-methods/use-active-payment-method.ts
  assets/js/base/context/providers/cart-checkout/payment-methods/use-payment-method-dispatchers.ts
  assets/js/base/context/providers/cart-checkout/payment-methods/utils.ts
  assets/js/base/hooks/use-shallow-equal.ts
  assets/js/blocks/cart-checkout/cart/test/__snapshots__/block.js.snap
  assets/js/blocks/cart-checkout/checkout/form/billing-fields-step.js
  assets/js/blocks/cart-checkout/checkout/form/contact-fields-step.js
  assets/js/blocks/cart-checkout/checkout/form/order-notes-step.js
  assets/js/blocks/cart-checkout/checkout/form/payment-method-step.js
  assets/js/blocks/cart-checkout/checkout/form/shipping-fields-step.js
  assets/js/blocks/cart-checkout/checkout/form/shipping-options-step.tsx
  assets/js/blocks/cart-checkout/checkout/sidebar/test/__snapshots__/index.js.snap
  assets/js/blocks/cart-checkout/payment-methods/express-payment-methods.js
  assets/js/blocks/cart-checkout/payment-methods/express-payment/cart-express-payment.js
  assets/js/blocks/cart-checkout/payment-methods/express-payment/checkout-express-payment.js
  assets/js/blocks/cart-checkout/payment-methods/payment-method-options.js
  assets/js/types/type-defs/contexts.js
  packages/checkout/button/index.tsx
  packages/checkout/button/style.scss
Labels: status: ready to merge

#4360 Fix error regarding duplicate keys in TotalsFees
  packages/checkout/totals/fees/index.tsx
Labels: category: blocks, status: ready to merge, type: bug, ◼️ block: cart, ◼️ block: checkout

#4361 Add type argument to `getSetting`
  assets/js/settings/shared/utils.ts
Labels: category: refactor, skip-changelog, status: ready to merge, type: technical debt

#4366 Append SKU to name for SearchListControl
  assets/js/editor-components/products-control/index.js
Labels: status: ready to merge

#4208 Add ExtendRestAPI and SlotFills docs
  docs/extensibility/README.md
  docs/extensibility/available-endpoints-to-extend.md
  docs/extensibility/available-slot-fills.md
  docs/extensibility/extend-rest-api-add-data.md
  docs/extensibility/extend-rest-api-new-endpoint.md
  docs/extensibility/slot-fills.md
  src/StoreApi/Schemas/CartItemSchema.php
Labels: category: extensibility, status: ready to merge, type: documentation

#4370 Storybook to gh-pages deployment
  .gitignore
  package-lock.json
  package.json
Labels: status: ready to merge

#4363 Allow HTML in the All Products Block Product Titles
  assets/js/base/components/product-name/index.js
  assets/js/base/components/product-name/index.tsx
  assets/js/base/components/product-name/test/__snapshots__/index.js.snap
Labels: status: ready to merge

#4367 Add screen reader text to price range
  assets/js/base/components/product-price/index.js
Labels: status: ready to merge

#4394 Add `IntegrationInterface` documentation
  docs/extensibility/README.md
  docs/extensibility/integration-interface.md
Labels: category: extensibility, status: ready to merge, type: documentation

#4398 Remove/snackbar filters
  assets/js/atomic/blocks/product-elements/add-to-cart/shared/add-to-cart-button.js
  assets/js/atomic/blocks/product-elements/sale-badge/block.js
  assets/js/base/components/button/index.tsx
  assets/js/base/components/button/stories/index.js
  assets/js/base/components/button/style.scss
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/base/components/cart-checkout/place-order-button/index.js
  assets/js/base/components/cart-checkout/shipping-calculator/address.tsx
  assets/js/base/components/cart-checkout/shipping-rates-control-package/index.tsx
  assets/js/base/components/cart-checkout/totals/coupon/index.js
  assets/js/base/components/filter-submit-button/index.js
  assets/js/base/components/label/index.tsx
  assets/js/base/components/label/test/__snapshots__/index.js.snap
  assets/js/base/components/label/test/index.js
  assets/js/base/components/load-more-button/index.js
  assets/js/base/components/pagination/index.js
  assets/js/base/components/sort-select/index.js
  assets/js/base/components/text-input/text-input.tsx
  assets/js/base/context/providers/store-notices/components/snackbar-notices-container.js
  assets/js/blocks/active-filters/block.js
  assets/js/blocks/active-filters/utils.js
  assets/js/blocks/attribute-filter/label.js
  assets/js/blocks/cart-checkout/cart/checkout-button/index.js
  assets/js/blocks/cart-checkout/payment-methods/payment-methods.js
  docs/extensibility/available-filters.md
  packages/checkout/index.js
  packages/checkout/registry/index.ts
Labels: status: ready to merge, type: blocker, type: bug, type: build, ◼️ block: all products, 🔹 block-type: filter blocks, 🔹 block-type: reviews

#4403 Update/5.3.2 testing instructions
  docs/testing/releases/532.md
  docs/testing/releases/README.md
  readme.txt
Labels: status: ready to merge

#4379 Add Terser to preserve translator comments
  .github/workflows/bundle-size.yml
  bin/webpack-configs.js
  bin/webpack-helpers.js
  package-lock.json
  package.json
Labels: skip-changelog, status: ready to merge, type: build

#4389 Audit and Move Image Assets, update error state
  assets/img/avatar.jpg
  assets/img/block-error.svg
  assets/img/grid.svg
  assets/img/no-matching-products.svg
  assets/img/no-products.svg
  assets/img/single-product-preview.svg
  assets/js/base/components/block-error-boundary/block-error.js
  assets/js/base/components/block-error-boundary/index.js
  assets/js/base/components/block-error-boundary/style.scss
  assets/js/base/components/cart-checkout/payment-method-icons/common-icons.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/test/__snapshots__/block.js.snap
  assets/js/blocks/cart-checkout/checkout/frontend.js
  assets/js/previews/cart.ts
  assets/js/previews/categories.js
  assets/js/previews/grid-block.js
  assets/js/previews/products.js
  assets/js/previews/reviews.js
  assets/js/previews/single-product-block.js
  assets/js/settings/blocks/constants.ts
  images/block-error.svg
  images/payment-methods/alipay.svg
  images/payment-methods/amex.svg
  images/payment-methods/bancontact.svg
  images/payment-methods/diners.svg
  images/payment-methods/discover.svg
  images/payment-methods/eps.svg
  images/payment-methods/giropay.svg
  images/payment-methods/ideal.svg
  images/payment-methods/jcb.svg
  images/payment-methods/laser.svg
  images/payment-methods/maestro.svg
  images/payment-methods/mastercard.svg
  images/payment-methods/multibanco.svg
  images/payment-methods/p24.svg
  images/payment-methods/sepa.svg
  images/payment-methods/sofort.svg
  images/payment-methods/unionpay.svg
  images/payment-methods/visa.svg
  images/payment-methods/wechat.svg
  images/previews/beanie.jpg
  images/previews/cap.jpg
  images/previews/collection.jpg
  images/previews/pennant.jpg
  package-lock.json
  package.json
  src/BlockTypes/AbstractBlock.php
Labels: skip-changelog, status: ready to merge
