Repository woocommerce/woocommerce-blocks, pull requests merged in 2021-10, with the labels that each got.

#4852 Mini Cart block: improve button accessibility
  assets/js/blocks/cart-checkout/mini-cart/block.tsx
  packages/prices/utils/price.ts
  packages/prices/utils/test/price.js
  src/BlockTypes/MiniCart.php
Labels: status: ready to merge, category: accessibility, skip-changelog, category: fse, ◼️ block: mini cart

#4815 AttributePicker: Set default values if they exist
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/attribute-picker.js
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/index.js
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/test/index.js
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/utils.js
  assets/js/types/type-guards/index.ts
  assets/js/types/type-guards/test/index.ts
  src/StoreApi/Schemas/ProductSchema.php
Labels: status: ready to merge, type: enhancement, category: rest-api, ◼️ block: all products, 🔺 atomic-block

#4839 Fix/price slider aria values
  assets/js/base/components/price-slider/index.js
Labels: status: ready to merge, type: bug, 🔹 block-type: filter blocks

#4876 Document DOM events used in WC Blocks
  docs/extensibility/README.md
  docs/extensibility/available-filters.md
  docs/extensibility/dom-events.md
  docs/extensibility/extend-rest-api-formatters.md
Labels: status: ready to merge, type: documentation, skip-changelog

#4899 Improve the engines support in package.json
  package.json
Labels: status: ready to merge, type: enhancement, type: build
