Repository woocommerce/woocommerce-blocks, pull requests merged in 2021-02, with the labels that each got.

#3770 Improve nonce handling by rejecting stale values
  .eslintrc.js
  assets/js/middleware/store-api-nonce.js
  src/Assets.php
  src/StoreApi/Routes/AbstractRoute.php
Labels: status: ready to merge

#3439 Update checkout payment methods design.
  assets/js/base/components/cart-checkout/form-step/style.scss
  assets/js/base/components/payment-methods/payment-method-card.js
  assets/js/base/components/payment-methods/payment-method-options.js
  assets/js/base/components/payment-methods/payment-methods.js
  assets/js/base/components/payment-methods/saved-payment-method-options.js
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/payment-methods/test/payment-methods.js
  assets/js/base/components/radio-control-accordion/index.js
  assets/js/base/components/radio-control/option.js
  assets/js/base/context/cart-checkout/payment-methods/constants.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/form/order-notes-step.js
  assets/js/blocks/cart-checkout/checkout/form/order-notes/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
  assets/js/type-defs/contexts.js
Labels: category: refactor, status: ready to merge, ◼️ block: checkout

#3775 Increase width of Cart's product column on <= medium screens
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: category: blocks, category: styles, skip-changelog, status: needs review, type: bug, ◼️ block: cart

#3767 Move "no rates found" logic to package level
  packages/checkout/shipping/shipping-rates-control/shipping-rates-control.js
  src/StoreApi/Routes/CartSelectShippingRate.php
Labels: category: extensibility, skip-changelog, status: ready to merge

#3778 Fix broken shipping Calculator
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/cart-checkout/shipping-rates-control/index.js
  assets/js/base/components/cart-checkout/totals/index.js
  assets/js/base/components/cart-checkout/totals/shipping/has-shipping-rate.js
  assets/js/base/components/cart-checkout/totals/shipping/index.js
  assets/js/base/components/cart-checkout/totals/shipping/shipping-rate-selector.js
  assets/js/base/components/cart-checkout/totals/shipping/stories/index.js
  assets/js/base/components/cart-checkout/totals/shipping/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/form/shipping-options-step.js
  assets/js/blocks/cart-checkout/checkout/sidebar/index.js
  packages/checkout/shipping/shipping-rates-control/index.js
  packages/checkout/shipping/shipping-rates-control/style.scss
  packages/checkout/totals/index.js
Labels: category: components, priority: high, status: ready to merge, type: blocker, type: bug

#3790 Introduce price-format package.
  .eslintrc.js
  assets/js/atomic/blocks/product-elements/price/block.js
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/blocks/active-filters/utils.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/form/shipping-options-step.js
  assets/js/blocks/cart-checkout/checkout/sidebar/index.js
  assets/js/blocks/price-filter/block.js
  bin/webpack-entries.js
  bin/webpack-helpers.js
  packages/checkout/index.js
  packages/checkout/shipping/shipping-rates-control/render-package-rate-option.js
  packages/prices/index.js
  packages/prices/utils/index.js
  packages/prices/utils/price.js
  packages/prices/utils/test/price.js
  src/Assets.php
  tests/js/jest.config.json
  tsconfig.json
Labels: skip-changelog, status: ready to merge, type: build

#3721 Decode fees name so special characters are rendered correctly
  assets/js/base/context/cart-checkout/payment-methods/test/payment-method-data-context.js
  assets/js/base/hooks/cart/test/use-store-cart.js
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/blocks/cart-checkout/cart/test/block.js
  assets/js/data/cart/test/reducers.js
  assets/js/data/cart/test/resolvers.js
  assets/js/data/default-states.js
Labels: status: ready to merge, type: bug, ◼️ block: cart, ◼️ block: checkout

#3785 Add new links to experimental docs and update JS testing docs
  docs/blocks/feature-flags-and-experimental-interfaces.md
  docs/contributors/javascript-testing.md
Labels: status: ready to merge, type: documentation

#3796 Use default "features" values for payment methods.
  assets/js/blocks-registry/payment-methods/express-payment-method-config.js
  assets/js/blocks-registry/payment-methods/payment-method-config.js
  docs/extensibility/payment-method-integration.md
Labels: priority: critical, status: ready to merge, type: bug, ◼️ block: checkout

#3772 Add guards to useSlot and move shared code to a new file.
  packages/checkout/index.js
  packages/checkout/order-meta/index.js
  packages/checkout/order-shipping-packages/index.js
  packages/checkout/slot/README.md
  packages/checkout/slot/index.js
Labels: category: refactor, status: ready to merge, type: technical debt

#3803 Align Place Order button to the right
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/form/order-notes/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: category: styles, status: ready to merge, ◼️ block: checkout

#3797 Update Cart and Checkout sidebar design
  assets/js/base/components/cart-checkout/order-summary/index.js
  assets/js/base/components/cart-checkout/order-summary/style.scss
  assets/js/base/components/cart-checkout/product-details/style.scss
  assets/js/base/components/cart-checkout/shipping-rates-control/index.js
  assets/js/base/components/cart-checkout/totals/coupon/index.js
  assets/js/base/components/cart-checkout/totals/footer-item/style.scss
  assets/js/base/components/cart-checkout/totals/shipping/style.scss
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/radio-control/style.scss
  assets/js/base/components/select/style.scss
  assets/js/base/components/sidebar-layout/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/form/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
  packages/checkout/panel/style.scss
  packages/checkout/shipping/shipping-rates-control/package.js
  packages/checkout/shipping/shipping-rates-control/style.scss
  packages/checkout/totals/item/style.scss
  packages/checkout/totals/taxes/index.js
  packages/checkout/totals/taxes/style.scss
Labels: category: styles, status: ready to merge, ◼️ block: cart, ◼️ block: checkout

#3810 Validate order items on post, not on draft order creation
  src/StoreApi/Routes/Checkout.php
Labels: status: ready to merge

#3774 Replace filters with an extendibility API to hook into Cart and Checkout blocks
  assets/js/base/components/cart-checkout/totals/footer-item/index.js
  docs/blocks/feature-flags-and-experimental-interfaces.md
  packages/checkout/index.js
  packages/checkout/registry/index.js
  packages/checkout/registry/test/index.js
Labels: category: extensibility, skip-changelog, status: needs review, ◼️ block: cart, ◼️ block: checkout

#3814 Use cart item key instead of name as the React key in Package
  packages/checkout/shipping/shipping-rates-control/package.js
Labels: status: ready to merge, type: bug, ◼️ block: cart, ◼️ block: checkout

#3816 Add filters for subtotalSuffix and saleBadgeSuffix
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/base/components/cart-checkout/product-sale-badge/index.js
  assets/js/base/components/product-price/index.js
  assets/js/base/components/product-price/test/__snapshots__/index.js.snap
  assets/js/base/components/product-price/test/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/checkout/style.scss
Labels: category: extensibility, skip-changelog, status: ready to merge, ◼️ block: cart, ◼️ block: checkout

#3807 Allow extensions to extend Cart Item Name in Cart and Checkout.
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
Labels: category: extensibility, skip-changelog, status: ready to merge, ◼️ block: cart, ◼️ block: checkout

#3812 Moved Nonce Logic to Cart API Classes
  src/StoreApi/Routes/AbstractCartRoute.php
  src/StoreApi/Routes/AbstractRoute.php
  src/StoreApi/Routes/CartUpdateCustomer.php
  src/StoreApi/Routes/Checkout.php
  src/StoreApi/Routes/Products.php
  src/StoreApi/RoutesController.php
  src/StoreApi/SchemaController.php
  src/StoreApi/Schemas/CartSchema.php
Labels: status: ready to merge

#3662 Extensibility for Block Checkout Address Fields
  assets/js/base/components/cart-checkout/address-form/address-form.js
  assets/js/base/components/cart-checkout/address-form/country-address-fields.js
  assets/js/base/components/cart-checkout/address-form/default-address-fields.js
  assets/js/base/components/cart-checkout/address-form/prepare-address-fields.js
  assets/js/base/components/cart-checkout/address-form/test/index.js
  assets/js/blocks/cart-checkout/checkout/form/address-step.js
  package-lock.json
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
  src/StoreApi/Schemas/AbstractAddressSchema.php
  tests/js/setup-globals.js
Labels: category: extensibility, status: ready to merge

#3832 Update jetpack autoloader dependency to 2.9.1
  composer.json
  composer.lock
Labels: skip-changelog, status: ready to merge

#3811 Remove unused imports from Cheque.php
  src/Payments/Integrations/Cheque.php
Labels: skip-changelog, type: technical debt

#3750 Allow extensions to extend cart item price
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/base/components/cart-checkout/order-summary/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
Labels: category: extensibility, skip-changelog, status: ready to merge

#3703 Catch errors during cart validation
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  src/StoreApi/Routes/AbstractRoute.php
  src/StoreApi/Routes/Checkout.php
  src/StoreApi/Schemas/CartSchema.php
  src/StoreApi/Schemas/ErrorSchema.php
  src/StoreApi/Utilities/CartController.php
  src/StoreApi/Utilities/InvalidStockLevelsInCartException.php
  src/StoreApi/Utilities/NotPurchasableException.php
  src/StoreApi/Utilities/OutOfStockException.php
  src/StoreApi/Utilities/PartialOutOfStockException.php
  src/StoreApi/Utilities/StockAvailabilityException.php
  src/StoreApi/Utilities/TooManyInCartException.php
  src/Utils/ArrayUtils.php
  tests/php/StoreApi/Utilities/CartController.php
Labels: category: blocks, category: rest-api, status: ready to merge, ◼️ block: cart, ◼️ block: checkout

#3844 Login links should use the account page
  assets/js/settings/blocks/constants.js
  src/Assets.php
Labels: status: ready to merge

#3843 Checkout should only link through to pages that are published
  src/Assets.php
Labels: status: needs review

#3851 Show cart item total price including taxes when DISPLAY_CART_PRICES_INCLUDING_TAX is true
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
Labels: status: ready to merge, type: bug, ◼️ block: cart, ◼️ block: checkout

#3853 Fix product price not displaying properly when product is on sale
  assets/js/base/components/product-price/index.js
  assets/js/base/components/product-price/test/__snapshots__/index.js.snap
Labels: category: blocks, skip-changelog, status: ready to merge, type: bug, ◼️ block: cart, ◼️ block: checkout

#3846 Remove shadows from text buttons and gradient background from selects in some themes
  assets/css/abstracts/_mixins.scss
  assets/js/base/components/select/style.scss
Labels: category: styles, status: ready to merge, ◼️ block: cart, ◼️ block: checkout

#3835 Enhance checkout filter system.
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/base/components/cart-checkout/totals/footer-item/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  package-lock.json
  package.json
  packages/checkout/index.js
  packages/checkout/registry/index.js
  packages/checkout/registry/test/admin.js
  packages/checkout/registry/test/index.js
  packages/checkout/utils/index.js
  packages/checkout/utils/validation/index.js
  tests/js/setup-globals.js
Labels: category: extensibility, skip-changelog, status: ready to merge

#3829 Refactor block types to include script registration and integration classes
  docs/contributors/block-assets.md
  src/Assets.php
  src/Assets/Api.php
  src/BlockTypes/AbstractBlock.php
  src/BlockTypes/AbstractDynamicBlock.php
  src/BlockTypes/AbstractProductGrid.php
  src/BlockTypes/ActiveFilters.php
  src/BlockTypes/AllProducts.php
  src/BlockTypes/AllReviews.php
  src/BlockTypes/AtomicBlock.php
  src/BlockTypes/AttributeFilter.php
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
  src/BlockTypes/FeaturedCategory.php
  src/BlockTypes/FeaturedProduct.php
  src/BlockTypes/HandpickedProducts.php
  src/BlockTypes/PriceFilter.php
  src/BlockTypes/ProductCategories.php
  src/BlockTypes/ProductCategory.php
  src/BlockTypes/ProductOnSale.php
  src/BlockTypes/ProductSearch.php
  src/BlockTypes/ProductTag.php
  src/BlockTypes/ProductsByAttribute.php
  src/BlockTypes/ReviewsByCategory.php
  src/BlockTypes/ReviewsByProduct.php
  src/BlockTypes/SingleProduct.php
  src/Integrations/IntegrationInterface.php
  src/Integrations/IntegrationRegistry.php
  src/Library.php
  src/Payments/Api.php
  src/Payments/Integrations/AbstractPaymentMethodType.php
  src/Payments/PaymentMethodRegistry.php
  src/Payments/PaymentMethodTypeInterface.php
Labels: category: extensibility, category: refactor, status: ready to merge

#3860 Update Panel component class names to follow guidelines
  assets/js/base/components/payment-methods/style.scss
  assets/js/base/components/sidebar-layout/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  docs/theming/README.md
  docs/theming/class-names-update-460.md
  packages/checkout/panel/index.js
  packages/checkout/panel/style.scss
  packages/checkout/shipping/shipping-rates-control/style.scss
Labels: category: styles, status: ready to merge

#3845 Only use SHOP_URL if set
  assets/js/blocks/cart-checkout/cart/empty-cart-edit/index.js
  assets/js/blocks/cart-checkout/checkout/empty-cart/index.js
Labels: status: ready to merge

#3859 Handle out of stock product visibility setting in All Products block.
  assets/js/base/components/product-list/product-list.js
  src/Assets.php
  src/StoreApi/Routes/Products.php
  src/StoreApi/Utilities/ProductQuery.php
  src/StoreApi/docs/products.md
Labels: category: blocks, status: ready to merge, type: bug, 🔹 block-type: product-grid

#3869 Replace uppercase Translators with translators & make comment style consistent
  assets/js/atomic/blocks/product-elements/add-to-cart/shared/add-to-cart-button.js
  assets/js/atomic/blocks/product-elements/button/block.js
  assets/js/atomic/blocks/product-elements/image/block.js
  assets/js/atomic/blocks/product-elements/rating/block.js
  assets/js/base/components/cart-checkout/address-form/country-address-fields.js
  assets/js/base/components/cart-checkout/shipping-location/index.js
  assets/js/base/components/cart-checkout/shipping-rates-control/index.js
  assets/js/base/components/cart-checkout/totals/discount/index.js
  assets/js/base/components/checkbox-list/index.js
  assets/js/base/components/dropdown-selector/index.js
  assets/js/base/components/dropdown-selector/menu.js
  assets/js/base/components/dropdown-selector/selected-chip.js
  assets/js/base/components/filter-submit-button/index.js
  assets/js/base/components/payment-methods/saved-payment-method-options.js
  assets/js/base/components/product-list/product-list.js
  assets/js/base/components/quantity-selector/index.js
  assets/js/base/components/reviews/review-list-item/index.js
  assets/js/base/hooks/cart/use-store-cart-coupons.js
  assets/js/blocks/attribute-filter/block.js
  assets/js/blocks/attribute-filter/edit.js
  assets/js/blocks/attribute-filter/label.js
  assets/js/blocks/cart-checkout/cart/empty-cart-edit/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-title.js
  assets/js/blocks/reviews/frontend-container-block.js
  assets/js/blocks/reviews/reviews-by-category/edit.js
  assets/js/blocks/reviews/reviews-by-product/edit.js
  assets/js/blocks/reviews/reviews-by-product/no-reviews-placeholder.js
  assets/js/editor-components/heading-toolbar/index.js
  assets/js/editor-components/product-attribute-term-control/index.js
  assets/js/editor-components/product-category-control/index.js
  assets/js/editor-components/product-control/index.js
  assets/js/editor-components/product-tag-control/index.js
  assets/js/editor-components/products-control/index.js
  packages/checkout/shipping/shipping-rates-control/package.js
  packages/checkout/utils/validation/index.js
  src/Assets/Api.php
  src/Domain/Bootstrap.php
  src/Installer.php
  src/StoreApi/Utilities/CartController.php
  src/StoreApi/Utilities/OrderController.php
  src/Utils/ArrayUtils.php
  woocommerce-gutenberg-products-block.php
Labels: category: i18n, skip-changelog, status: ready to merge, type: cooldown

#3866 Move payment-methods folder from base components to cart-checkout block
  assets/js/base/context/cart-checkout/payment-methods/test/payment-method-data-context.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/form/payment-method-step.js
  assets/js/blocks/cart-checkout/payment-methods/express-payment-methods.js
  assets/js/blocks/cart-checkout/payment-methods/express-payment/cart-express-payment.js
  assets/js/blocks/cart-checkout/payment-methods/express-payment/checkout-express-payment.js
  assets/js/blocks/cart-checkout/payment-methods/express-payment/index.js
  assets/js/blocks/cart-checkout/payment-methods/express-payment/style.scss
  assets/js/blocks/cart-checkout/payment-methods/index.js
  assets/js/blocks/cart-checkout/payment-methods/no-payment-methods/index.js
  assets/js/blocks/cart-checkout/payment-methods/no-payment-methods/style.scss
  assets/js/blocks/cart-checkout/payment-methods/payment-method-card.js
  assets/js/blocks/cart-checkout/payment-methods/payment-method-error-boundary.js
  assets/js/blocks/cart-checkout/payment-methods/payment-method-options.js
  assets/js/blocks/cart-checkout/payment-methods/payment-methods.js
  assets/js/blocks/cart-checkout/payment-methods/saved-payment-method-options.js
  assets/js/blocks/cart-checkout/payment-methods/style.scss
  assets/js/blocks/cart-checkout/payment-methods/test/payment-methods.js
  package-lock.json
Labels: skip-changelog, status: ready to merge

#3861 Add information about hub authentication and GitHub releases to the release PR template
  .github/release-initial-checklist.md
Labels: skip-changelog, status: ready to merge, type: documentation, type: release

#3870 Move ProductSortSelect and ProductListItem under /product-list
  assets/js/base/components/product-list/product-list-item/index.js
  assets/js/base/components/product-list/product-list-item/utils.js
  assets/js/base/components/product-list/product-list.js
  assets/js/base/components/product-list/product-sort-select/index.js
  assets/js/base/components/product-list/product-sort-select/style.scss
Labels: skip-changelog, status: ready to merge

#3871 StoreAPI: Inject Order and Cart Controllers into Routes
  src/StoreApi/Routes/AbstractCartRoute.php
  src/StoreApi/Routes/Cart.php
  src/StoreApi/Routes/CartAddItem.php
  src/StoreApi/Routes/CartApplyCoupon.php
  src/StoreApi/Routes/CartCoupons.php
  src/StoreApi/Routes/CartCouponsByCode.php
  src/StoreApi/Routes/CartItems.php
  src/StoreApi/Routes/CartItemsByKey.php
  src/StoreApi/Routes/CartRemoveCoupon.php
  src/StoreApi/Routes/CartRemoveItem.php
  src/StoreApi/Routes/CartSelectShippingRate.php
  src/StoreApi/Routes/CartUpdateCustomer.php
  src/StoreApi/Routes/CartUpdateItem.php
  src/StoreApi/Routes/Checkout.php
  src/StoreApi/RoutesController.php
  src/StoreApi/Utilities/CartController.php
Labels: status: ready to merge

#3854 Use variation prices in Store API prices response.
  src/StoreApi/Schemas/ProductSchema.php
Labels: category: rest-api, status: ready to merge

#3862 Twenty Nineteen: Fix link button style in editor
  assets/css/style.scss
Labels: status: ready to merge

#3876 Fix cart line subtotal display when currency has 0 decimals
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/test/block.js
Labels: status: ready to merge, type: bug, ◼️ block: cart, ◼️ block: checkout

#3879 Show total sale badge in medium carts & make it display below price
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: category: blocks, status: ready to merge, type: bug, ◼️ block: cart

#3889 Update Label component to TSX
  assets/js/base/components/label/index.tsx
  assets/js/base/components/tsconfig.json
  package-lock.json
  package.json
  tests/js/jest.config.json
  tests/js/jestPreprocess.js
  tsconfig.json
Labels: category: components, skip-changelog, status: ready to merge
