Repository woocommerce/woocommerce-blocks, pull requests merged in 2021-01, with the labels that each got.

#3627 Convert saved payment methods token to a string
  assets/js/base/components/payment-methods/saved-payment-method-options.js
Labels: status: ready to merge, type: bug, ◼️ block: checkout

#3585 Add/GitHub status badges
  README.md
Labels: status: ready to merge

#3641 Try using new lines instead of html break tags for stale automation
  .github/workflows/close-stale-issues.yml
Labels: skip-changelog, type: bug, type: build

#3640 Revert test badge name back to Automated Tests
  README.md
Labels: status: ready to merge

#3607 Remove setSettings.
  assets/js/settings/shared/index.js
  assets/js/settings/shared/set-setting.js
  assets/js/settings/shared/test/compare-with-wp-version.js
  assets/js/settings/shared/test/set-setting.js
Labels: category: refactor, status: ready to merge

#3634 Add "you don't need lodash/underscore" eslint rule
  .eslintrc.js
  assets/js/base/context/shared/validation/index.js
  assets/js/base/hooks/use-query-state.js
  assets/js/editor-components/grid-layout-control/index.js
  assets/js/editor-components/utils/index.js
  assets/js/hocs/with-transform-single-select-to-multiple-select.js
  package-lock.json
  package.json
Labels: status: ready to merge, type: build, type: enhancement

#3621 Add tests to AddressForm
  assets/js/base/components/cart-checkout/address-form/test/index.js
  assets/js/base/components/read-more/test/index.js
  package-lock.json
  package.json
  tests/js/setup-globals.js
Labels: skip-changelog, status: ready to merge, type: technical debt

#3652 Add puppeteer directly to dev dependencies.
  package.json
Labels: category: tests, skip-changelog, type: dependencies

#3654 Create @woocommerce/checkout to export components to a global
  assets/js/base/components/cart-checkout/totals/discount/index.js
  assets/js/base/components/cart-checkout/totals/fees/index.js
  assets/js/base/components/cart-checkout/totals/footer-item/index.js
  assets/js/base/components/cart-checkout/totals/index.js
  assets/js/base/components/cart-checkout/totals/shipping/index.js
  assets/js/base/components/cart-checkout/totals/subtotal/index.js
  assets/js/base/components/cart-checkout/totals/taxes/index.js
  assets/js/base/context/cart-checkout/checkout/index.js
  bin/webpack-configs.js
  bin/webpack-entries.js
  bin/webpack-helpers.js
  package-lock.json
  packages/checkout/error-boundary/index.js
  packages/checkout/index.js
  packages/checkout/style.scss
  packages/checkout/totals/index.js
  packages/checkout/totals/item/index.js
  packages/checkout/totals/item/stories/index.js
  packages/checkout/totals/item/style.scss
  src/Assets.php
  tests/js/jest.config.json
  tsconfig.json
Labels: category: extensibility, skip-changelog, status: ready to merge

#3653 Add major for devDependencies.
  renovate.json
Labels: skip-changelog, type: dependencies

#3361 introduce SlotFill for Sidebar
  .eslintrc.js
  assets/js/base/context/cart-checkout/checkout/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/sidebar/index.js
  bin/webpack-entries.js
  bin/webpack-helpers.js
  package-lock.json
  packages/checkout/index.js
  packages/checkout/order-meta/index.js
  src/Assets.php
Labels: category: extensibility, status: ready to merge, ◼️ block: cart, ◼️ block: checkout

#3665 Cart & Checkout blocks: print all item data and update variation designs
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/base/components/cart-checkout/product-details/index.js
  assets/js/base/components/cart-checkout/product-details/style.scss
  assets/js/base/components/cart-checkout/product-metadata/index.js
  assets/js/base/components/cart-checkout/product-variation-data/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  src/StoreApi/Schemas/CartItemSchema.php
  src/StoreApi/docs/cart-items.md
  tests/php/StoreApi/Routes/CartItems.php
Labels: category: extensibility, status: ready to merge

#3651 Remove default address_type so it's required
  src/StoreApi/Utilities/OrderController.php
Labels: skip-changelog, status: ready to merge

#3679 Create get_item_responses_from_schema abstraction
  src/StoreApi/Schemas/AbstractSchema.php
  src/StoreApi/Schemas/CartSchema.php
Labels: status: ready to merge

#3680 Improve Package Handling in CartShippingRateSchema
  src/StoreApi/Schemas/CartShippingRateSchema.php
  src/StoreApi/Utilities/CartController.php
Labels: status: ready to merge

#3678 Support for multiple fee rows in the cart
  assets/js/base/components/cart-checkout/totals/fees/index.js
  assets/js/base/components/cart-checkout/totals/fees/stories/index.js
  assets/js/base/hooks/cart/test/use-store-cart.js
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/sidebar/index.js
  assets/js/previews/cart.js
  assets/js/type-defs/hooks.js
  packages/checkout/totals/item/style.scss
  src/Domain/Bootstrap.php
  src/RestApi.php
  src/StoreApi/Routes/AbstractCartRoute.php
  src/StoreApi/SchemaController.php
  src/StoreApi/Schemas/CartFeeSchema.php
  src/StoreApi/Schemas/CartSchema.php
  storybook/__mocks__/woocommerce-base-hooks.js
Labels: category: rest-api, status: ready to merge

#3683 Update Jetpack autoloader to 2.7.1
  composer.json
  composer.lock
Labels: skip-changelog, status: needs review, type: build

#3690 Fix broken PHPunit tests
  src/StoreApi/Schemas/CartSchema.php
  tests/bootstrap.php
Labels: category: tests, priority: high, skip-changelog, status: needs review, type: bug

#3693 Fix error with eslint workflow artifact download issues.
  .github/workflows/js-css-linting.yml
  .gitignore
  package.json
Labels: status: ready to merge, type: bug, type: build

#3656 Improve error displayed to customers when an item's stock status changes during checkout.
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  src/StoreApi/Routes/AbstractRoute.php
  src/StoreApi/Routes/Checkout.php
  src/StoreApi/Utilities/CartController.php
  src/StoreApi/Utilities/InvalidStockLevelsInCartException.php
  src/StoreApi/Utilities/NotPurchasableException.php
  src/StoreApi/Utilities/OutOfStockException.php
  src/StoreApi/Utilities/PartialOutOfStockException.php
  src/StoreApi/Utilities/StockAvailabilityException.php
  src/StoreApi/Utilities/TooManyInCartException.php
  src/Utils/ArrayUtils.php
Labels: category: blocks, category: rest-api, status: ready to merge, ◼️ block: checkout

#3704 Fix circular dependencies
  assets/js/base/components/cart-checkout/address-form/address-form.js
  assets/js/base/components/cart-checkout/address-form/index.js
  assets/js/base/components/cart-checkout/address-form/test/index.js
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/base/components/cart-checkout/shipping-calculator/address.js
  assets/js/base/components/cart-checkout/totals/shipping/index.js
  assets/js/base/components/cart-checkout/totals/shipping/shipping-rate-selector.js
  assets/js/base/components/chip/removable-chip.js
  assets/js/base/components/product-list/container.js
  assets/js/base/components/product-list/index.js
  assets/js/base/components/product-list/product-list.js
  assets/js/base/components/text-input/index.js
  assets/js/base/components/text-input/text-input.js
  assets/js/base/components/text-input/validated-text-input.js
  assets/js/base/context/add-to-cart-form/form/index.js
  assets/js/base/context/add-to-cart-form/form/submit/index.js
  assets/js/base/context/cart-checkout/checkout/processor/index.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/payment-methods/use-payment-method-registration.js
  assets/js/base/context/cart-checkout/shipping/index.js
  assets/js/base/hooks/cart/use-store-cart-item-quantity.js
  assets/js/base/hooks/checkout/test/use-checkout-submit.js
  assets/js/base/hooks/checkout/use-checkout-address.js
  assets/js/base/hooks/checkout/use-checkout-notices.js
  assets/js/base/hooks/checkout/use-checkout-submit.js
  assets/js/base/hooks/customer/use-customer-data.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/base/hooks/shipping/use-select-shipping-rate.js
  assets/js/base/hooks/use-collection-data.js
  assets/js/base/hooks/use-collection.js
  assets/js/base/hooks/use-query-state.js
  assets/js/base/hooks/use-store-add-to-cart.js
  assets/js/blocks/products/all-products/block.js
Labels: status: ready to merge, type: bug, type: build, ◼️ block: all products, ◼️ block: cart, ◼️ block: checkout

#3706 add missing aria-label for stars image in review-list-item component
  assets/js/base/components/reviews/review-list-item/index.js
Labels: category: accessibility, status: ready to merge

#3695 Add circular dependency check and fix it
  .github/workflows/php-js-e2e-tests.yml
  bin/webpack-configs.js
  src/Assets/Api.php
  src/Domain/Services/FeatureGating.php
Labels: type: build, type: enhancement

#3671 Move Total components to checkout package
  assets/js/atomic/blocks/product-elements/price/block.js
  assets/js/base/components/cart-checkout/index.js
  assets/js/base/components/cart-checkout/order-summary/index.js
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/base/components/cart-checkout/totals/coupon/index.js
  assets/js/base/components/cart-checkout/totals/index.js
  assets/js/base/hooks/cart/test/use-store-cart.js
  assets/js/base/hooks/cart/use-store-cart.js
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/base/utils/index.js
  assets/js/blocks/active-filters/utils.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.js
  assets/js/blocks/cart-checkout/checkout/form/shipping-options-step.js
  assets/js/blocks/cart-checkout/checkout/sidebar/index.js
  assets/js/blocks/price-filter/block.js
  assets/js/type-defs/hooks.js
  packages/checkout/index.js
  packages/checkout/order-meta/index.js
  packages/checkout/panel/index.js
  packages/checkout/panel/style.scss
  packages/checkout/shipping/index.js
  packages/checkout/shipping/shipping-rates-control/index.js
  packages/checkout/shipping/shipping-rates-control/package-options.js
  packages/checkout/shipping/shipping-rates-control/package.js
  packages/checkout/shipping/shipping-rates-control/packages.js
  packages/checkout/shipping/shipping-rates-control/shipping-rates-control.js
  packages/checkout/shipping/shipping-rates-control/style.scss
  packages/checkout/totals/fees/index.js
  packages/checkout/totals/fees/stories/index.js
  packages/checkout/totals/index.js
  packages/checkout/totals/item/stories/index.js
  packages/checkout/totals/shipping/has-shipping-rate.js
  packages/checkout/totals/shipping/index.js
  packages/checkout/totals/shipping/shipping-rate-selector.js
  packages/checkout/totals/shipping/stories/index.js
  packages/checkout/totals/shipping/style.scss
  packages/checkout/totals/subtotal/index.js
  packages/checkout/totals/subtotal/stories/index.js
  packages/checkout/totals/taxes/index.js
  packages/checkout/totals/taxes/stories/index.js
  packages/checkout/totals/taxes/style.scss
  packages/checkout/utils/index.js
  packages/checkout/utils/price.js
  packages/checkout/utils/test/price.js
Labels: category: components

#3716 Allow extensions to filter Total label
  assets/js/base/components/cart-checkout/totals/footer-item/index.js
  docs/blocks/feature-flags-and-experimental-interfaces.md
  packages/checkout/index.js
Labels: category: extensibility, skip-changelog, status: ready to merge, ◼️ block: cart, ◼️ block: checkout

#3720 Move error to admin notice
  src/Assets/Api.php
Labels: skip-changelog, status: ready to merge, type: build

#3686 Change payment processing for subscriptions
  assets/js/base/components/payment-methods/payment-method-options.js
  assets/js/base/components/payment-methods/payment-method-tab.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js
  assets/js/base/context/cart-checkout/payment-methods/test/payment-method-data-context.js
  assets/js/blocks-registry/payment-methods/payment-method-config.js
  assets/js/payment-method-extensions/payment-methods/stripe/credit-card/index.js
  assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/type-defs.js
  docs/blocks/feature-flags-and-experimental-interfaces.md
  docs/extensibility/payment-method-integration.md
  src/Payments/Integrations/Stripe.php
  src/StoreApi/Routes/Checkout.php
Labels: category: extensibility, category: rest-api, status: ready to merge, ◼️ block: checkout

#3717 Remove star-rating class from Product rating block
  assets/js/atomic/blocks/product-elements/rating/block.js
Labels: category: styles, status: ready to merge

#3732 Honor hidden property of cart item data and add support for experimenal property
  assets/js/base/components/cart-checkout/product-details/index.js
  assets/js/base/components/cart-checkout/product-details/test/__snapshots__/index.js.snap
  assets/js/base/components/cart-checkout/product-details/test/index.js
  docs/blocks/feature-flags-and-experimental-interfaces.md
  src/StoreApi/Schemas/CartItemSchema.php
Labels: category: extensibility, status: ready to merge

#3737 Hide All Products Block from Widget Areas
  src/Library.php
Labels: status: ready to merge

#3734 Add subtotal to cart and checkout and update the CartLineItem component with new styles
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/base/components/cart-checkout/order-summary/style.scss
  assets/js/base/components/cart-checkout/product-details/style.scss
  assets/js/base/components/cart-checkout/product-metadata/style.scss
  assets/js/base/components/quantity-selector/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-table.js
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/icons/index.js
  assets/js/icons/library/trash.js
  src/BlockTypes/Cart.php
Labels: category: blocks, status: ready to merge, ◼️ block: cart, ◼️ block: checkout

#3745 Panel component: allow all kind of nodes as title
  assets/js/blocks/README.md
  packages/checkout/panel/index.js
Labels: category: extensibility, skip-changelog, status: ready to merge, type: bug

#3738 Fix color for BlockErrorBoundry
  assets/js/base/components/block-error-boundary/style.scss
Labels: category: styles, status: ready to merge, type: bug

#3746 Add missing wrapper from FeaturedCategory & FeatureProduct blocks
  src/BlockTypes/FeaturedCategory.php
  src/BlockTypes/FeaturedProduct.php
Labels: category: blocks, status: ready to merge, type: bug, ◼️ block: featured category

#3749 Update @wordpress/scripts and eslint and stylint configurations
  .eslintrc.js
  .prettierrc
  .prettierrc.js
  .stylelintrc.json
  package-lock.json
  package.json
Labels: skip-changelog, status: ready to merge, type: build

#3722 Fix image link in all products block.
  assets/js/atomic/blocks/product-elements/image/block.js
  assets/js/atomic/blocks/product-elements/image/test/block.test.js
Labels: category: accessibility, status: ready to merge

#3755 Enable defaults for new import rules and configure
  .eslintrc.js
  package-lock.json
  package.json
Labels: skip-changelog, status: ready to merge, type: build

#3687 Subscriptions Shipping Packages Integration Points
  assets/js/base/components/radio-control/index.js
  assets/js/base/context/cart-checkout/shipping/constants.js
  assets/js/base/context/cart-checkout/shipping/index.js
  assets/js/base/context/cart-checkout/shipping/reducers.js
  assets/js/base/context/cart-checkout/shipping/utils.js
  assets/js/base/hooks/shipping/index.js
  assets/js/base/hooks/shipping/use-select-shipping-rate.js
  assets/js/base/hooks/shipping/use-select-shipping-rates.js
  assets/js/base/hooks/use-throw-error.js
  assets/js/base/utils/derive-selected-shipping-rates.js
  assets/js/base/utils/index.js
  assets/js/blocks/cart-checkout/checkout/form/shipping-options-step.js
  assets/js/data/cart/actions.js
  assets/js/type-defs/contexts.js
  packages/checkout/index.js
  packages/checkout/order-meta/index.js
  packages/checkout/order-shipping-packages/index.js
  packages/checkout/shipping/shipping-rates-control/index.js
  packages/checkout/shipping/shipping-rates-control/package-rates.js
  packages/checkout/shipping/shipping-rates-control/package.js
  packages/checkout/shipping/shipping-rates-control/packages.js
  packages/checkout/shipping/shipping-rates-control/render-package-rate-option.js
  packages/checkout/shipping/shipping-rates-control/shipping-rates-control.js
  packages/checkout/totals/shipping/index.js
  packages/checkout/totals/shipping/shipping-rate-selector.js
  src/Domain/Services/ExtendRestApi.php
  src/StoreApi/Routes/CartSelectShippingRate.php
  src/StoreApi/SchemaController.php
  src/StoreApi/Schemas/CartShippingRateSchema.php
  src/StoreApi/Utilities/CartController.php
  src/StoreApi/docs/cart.md
  tests/php/StoreApi/Routes/Cart.php
  tests/php/StoreApi/Routes/CartCoupons.php
  tests/php/StoreApi/Routes/CartItems.php
  tests/php/StoreApi/Routes/ProductAttributeTerms.php
  tests/php/StoreApi/Routes/ProductAttributes.php
  tests/php/StoreApi/Routes/ProductCollectionData.php
  tests/php/StoreApi/Routes/Products.php
Labels: category: extensibility, status: ready to merge

#3765 Hide categories with 0 products from the Product Categories block
  src/BlockTypes/ProductCategories.php
Labels: category: blocks, status: ready to merge, type: bug, 🔹 block-type: product
