Repository woocommerce/woocommerce-blocks, pull requests merged in 2021-04, with the labels that each got.

#4017 Update experimental flags documentation
  docs/blocks/feature-flags-and-experimental-interfaces.md
Labels: skip-changelog, status: ready to merge, type: documentation

#4028 Fix Featured Product and Featured Category button alignment
  assets/js/blocks/featured-category/style.scss
  assets/js/blocks/featured-product/style.scss
Labels: category: styles, status: ready to merge, ◼️ block: featured category, ◼️ block: featured product

#4024 Update @automattic/data-stores and remove mapped-types.ts
  assets/js/data/cart/actions.ts
  assets/js/data/cart/index.ts
  assets/js/mapped-types.ts
  package-lock.json
  package.json
Labels: skip-changelog, type: build, type: technical debt

#4020 Enable Google Analytics Integration
  docs/blocks/feature-flags-and-experimental-interfaces.md
  src/Domain/Services/GoogleAnalytics.php
Labels: needs dev-note, status: ready to merge, type: compatibility, type: enhancement

#3999 Add emitResponse prop to the Payment Method Nodes props docs
  docs/extensibility/checkout-flow-and-events.md
  docs/extensibility/payment-method-integration.md
Labels: needs docs, skip-changelog, status: ready to merge

#4032 Remove useCheckoutRedirectUrl()
  assets/js/base/hooks/checkout/index.js
  assets/js/base/hooks/checkout/test/use-checkout-redirect-url.js
  assets/js/base/hooks/checkout/use-checkout-redirect-url.js
Labels: category: refactor, skip-changelog, status: ready to merge

#4044 Cart: fix headline alignment in the empty state of the cart block
  assets/js/blocks/cart-checkout/cart/empty-cart-edit/index.js
Labels: category: blocks, status: ready to merge, ◼️ block: cart

#4010 Remove deprecated shortcode save handling from SSR Blocks
  assets/js/blocks/README.md
  assets/js/blocks/handpicked-products/index.js
  assets/js/blocks/product-best-sellers/index.js
  assets/js/blocks/product-category/index.js
  assets/js/blocks/product-new/index.js
  assets/js/blocks/product-on-sale/index.js
  assets/js/blocks/product-top-rated/index.js
  assets/js/blocks/products-by-attribute/index.js
  assets/js/utils/deprecations.js
  assets/js/utils/get-shortcode.js
Labels: category: refactor, status: ready to merge

#4034 unqeueue WooCore scripts instead of deregister.
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
Labels: category: performance, skip-changelog, status: ready to merge, ◼️ block: cart, ◼️ block: checkout

#4033 provide fallback for extensions when store hasn't loaded yet
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/type-defs/cart.js
  packages/checkout/registry/index.ts
Labels: category: extensibility, skip-changelog, status: ready to merge, ◼️ block: cart

#4049 Stop shipping package titles breaking in the middle of a word
  assets/js/base/components/title/style.scss
Labels: category: styles, status: ready to merge, type: bug, ◼️ block: checkout

#4051 Use font color in payment methods border
  assets/js/blocks/cart-checkout/payment-methods/style.scss
Labels: category: styles, status: ready to merge, ◼️ block: checkout

#4046 Fix TwentyX styling issues for cart/checkout form fields
  assets/js/base/components/checkbox-control/style.scss
  assets/js/base/components/quantity-selector/style.scss
  assets/js/base/components/select/style.scss
  assets/js/base/components/text-input/style.scss
  packages/checkout/panel/style.scss
Labels: category: styles, status: ready to merge

#4050 Load translation file for JS files that has translatable strings
  src/Assets.php
Labels: category: i18n, status: ready to merge, type: bug, ◼️ block: cart, ◼️ block: checkout

#4054 Remove BackCompatAssetDataRegistry
  src/Assets/BackCompatAssetDataRegistry.php
  src/Domain/Bootstrap.php
Labels: skip-changelog, status: ready to merge

#4056 Check if Cart and Checkout are registered before removing payment methods
  src/Payments/Api.php
Labels: priority: high, status: ready to merge, type: bug, type: compatibility, ◼️ block: cart, ◼️ block: checkout

#4004 Add initial e2e tests to Checkout block frontend
  tests/e2e/config/jest.setup.js
  tests/e2e/specs/backend/cart.test.js
  tests/e2e/specs/frontend/cart.test.js
  tests/e2e/specs/frontend/checkout.test.js
  tests/utils/get-block-page-permalink.js
  tests/utils/index.js
  tests/utils/scroll-to.ts
  tests/utils/shopper.js
Labels: category: tests, skip-changelog, status: ready to merge, ◼️ block: checkout

#4068 Fix failing e2e tests
  package-lock.json
  package.json
  tests/e2e/specs/backend/__fixtures__/product-search.fixture.json
  tests/e2e/specs/backend/__snapshots__/product-search.test.js.snap
  tests/e2e/specs/backend/reviews-by-product.test.js
  tests/e2e/utils.js
Labels: category: tests, skip-changelog, status: needs review, type: build

#3899 Rest API batching support
  assets/js/atomic/blocks/product-elements/button/block.js
  assets/js/base/context/hooks/cart/use-store-cart-item-quantity.ts
  assets/js/base/context/providers/add-to-cart-form/form/submit/index.js
  assets/js/base/hooks/index.js
  assets/js/base/hooks/use-trigger-fragment-refresh.ts
  assets/js/base/utils/legacy-events.js
  assets/js/data/cart/action-types.ts
  assets/js/data/cart/actions.ts
  assets/js/data/cart/controls.js
  assets/js/data/shared-controls.ts
  assets/js/data/tsconfig.json
  assets/js/data/types.ts
  assets/js/middleware/store-api-nonce.js
  package-lock.json
  package.json
  src/StoreApi/Routes/AbstractCartRoute.php
  src/StoreApi/Routes/Batch.php
  src/StoreApi/Routes/Cart.php
  src/StoreApi/Routes/CartAddItem.php
  src/StoreApi/Routes/CartApplyCoupon.php
  src/StoreApi/Routes/CartCoupons.php
  src/StoreApi/Routes/CartCouponsByCode.php
  src/StoreApi/Routes/CartItems.php
  src/StoreApi/Routes/CartItemsByKey.php
  src/StoreApi/Routes/CartRemoveCoupon.php
  src/StoreApi/Routes/CartRemoveItem.php
  src/StoreApi/Routes/CartSelectShippingRate.php
  src/StoreApi/Routes/CartUpdateCustomer.php
  src/StoreApi/Routes/CartUpdateItem.php
  src/StoreApi/Routes/Checkout.php
  src/StoreApi/RoutesController.php
  tests/e2e/config/jest.setup.js
  tests/php/StoreApi/Routes/Batch.php
Labels: status: ready to merge

#4071 Update @wordpress/env to 4.0.2 and test default config with core property set to null.
  .wp-env.json
  package-lock.json
  package.json
Labels: category: tests, type: build

#4075 Rest API batching support (2)
  assets/js/atomic/blocks/product-elements/button/block.js
  assets/js/base/context/hooks/cart/use-store-cart-item-quantity.ts
  assets/js/base/context/providers/add-to-cart-form/form/submit/index.js
  assets/js/base/hooks/index.js
  assets/js/base/hooks/use-trigger-fragment-refresh.ts
  assets/js/base/utils/legacy-events.js
  assets/js/data/cart/action-types.ts
  assets/js/data/cart/actions.ts
  assets/js/data/cart/controls.js
  assets/js/data/shared-controls.ts
  assets/js/data/tsconfig.json
  assets/js/data/types.ts
  assets/js/middleware/cart-update.ts
  assets/js/middleware/store-api-nonce.js
  package-lock.json
  package.json
  src/StoreApi/Routes/AbstractCartRoute.php
  src/StoreApi/Routes/Batch.php
  src/StoreApi/Routes/CartAddItem.php
  src/StoreApi/Routes/CartApplyCoupon.php
  src/StoreApi/Routes/CartCoupons.php
  src/StoreApi/Routes/CartCouponsByCode.php
  src/StoreApi/Routes/CartItems.php
  src/StoreApi/Routes/CartItemsByKey.php
  src/StoreApi/Routes/CartRemoveCoupon.php
  src/StoreApi/Routes/CartRemoveItem.php
  src/StoreApi/Routes/CartSelectShippingRate.php
  src/StoreApi/Routes/CartUpdateCustomer.php
  src/StoreApi/Routes/CartUpdateItem.php
  src/StoreApi/Routes/Checkout.php
  src/StoreApi/RoutesController.php
  tests/e2e/specs/frontend/cart.test.js
  tests/php/StoreApi/Routes/Batch.php
Labels: status: ready to merge

#4079 Add When to employ end to end (E2E) testing documentation
  docs/testing/README.md
  docs/testing/when-to-employ-e2e-testing.md
Labels: skip-changelog, status: ready to merge, type: documentation

#4077 Make error messages in front-end cart E2E tests better
  tests/e2e/specs/frontend/cart.test.js
Labels: category: tests, skip-changelog, status: ready to merge

#4088 Convert Cart Table to TypeScript
  assets/js/base/components/cart-checkout/product-low-stock-badge/index.tsx
  assets/js/base/components/quantity-selector/index.tsx
  assets/js/base/context/hooks/cart/use-store-cart-item-quantity.ts
  assets/js/base/context/tsconfig.json
  assets/js/base/utils/index.js
  assets/js/base/utils/type-guards.ts
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.tsx
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-table.tsx
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-items-title.tsx
  assets/js/blocks/cart-checkout/cart/full-cart/index.tsx
  assets/js/type-defs/cart-response.ts
  assets/js/type-defs/cart.ts
  package-lock.json
  package.json
  packages/checkout/registry/index.ts
Labels: skip-changelog, type: task, ◼️ block: cart

#4038 Prevent unwanted parts of address being displayed
  assets/js/base/components/cart-checkout/shipping-location/index.js
  assets/js/base/context/hooks/cart/use-store-cart.ts
  assets/js/base/context/providers/cart-checkout/checkout/processor/index.js
  assets/js/base/context/tsconfig.json
  assets/js/base/utils/address.js
  assets/js/base/utils/test/address.ts
Labels: category: blocks, status: ready to merge, type: bug, ◼️ block: cart, ◼️ block: checkout

#4092 Deprecate the woocommerce_shared_settings hook
  composer.json
  composer.lock
  docs/contributors/block-assets.md
  phpunit.xml.dist
  src/Assets/AssetDataRegistry.php
  tests/php/Assets/AssetDataRegistry.php
Labels: needs dev-note, status: ready to merge

#4094 Create AssetsController and BlockTypesController (replaces Assets.php and Library.php)
  src/Assets.php
  src/Assets/Api.php
  src/AssetsController.php
  src/BlockTypesController.php
  src/Domain/Bootstrap.php
  src/Library.php
Labels: needs dev-note, status: ready to merge

#4091 Update `Button` component to ts
  assets/js/base/components/button/index.tsx
  package-lock.json
  package.json
Labels: category: components, category: refactor, skip-changelog, status: needs review

#4098 Convert Product components to TS
  assets/js/base/components/cart-checkout/policies/index.tsx
  assets/js/base/components/cart-checkout/product-backorder-badge/index.tsx
  assets/js/base/components/cart-checkout/product-badge/index.tsx
  assets/js/base/components/cart-checkout/product-details/index.tsx
  assets/js/base/components/cart-checkout/product-image/index.tsx
  assets/js/base/components/cart-checkout/product-low-stock-badge/index.tsx
  assets/js/base/components/cart-checkout/product-metadata/index.tsx
  assets/js/base/components/cart-checkout/product-sale-badge/index.tsx
  assets/js/base/components/cart-checkout/shipping-location/index.js
  assets/js/base/components/tsconfig.json
  assets/js/settings/shared/default-constants.ts
  assets/js/type-defs/product-response.ts
  package-lock.json
Labels: category: blocks, category: refactor, skip-changelog, status: ready to merge, 🔹 block-type: product

#4039 Rename onCheckoutBeforeProcessing to onCheckoutValidationBeforeProcessing
  assets/js/base/context/hooks/payment-methods/use-payment-method-interface.js
  assets/js/base/context/providers/cart-checkout/checkout-state/event-emit.js
  assets/js/base/context/providers/cart-checkout/checkout-state/index.js
  assets/js/base/context/providers/cart-checkout/checkout/processor/index.js
  assets/js/type-defs/contexts.js
  assets/js/type-defs/registered-payment-method-props.js
  docs/block-client-apis/checkout/checkout-api.md
  docs/extensibility/checkout-flow-and-events.md
  docs/extensibility/payment-method-integration.md
Labels: category: blocks, status: ready to merge, type: enhancement

#4078 Remove woocommerce as a dependency and install @woocommerce/e2e-utils
  bin/webpack-helpers.js
  package-lock.json
  package.json
  tests/e2e/config/jest.config.js
  tests/e2e/specs/backend/product-search.test.js
  tsconfig.base.json
Labels: category: tests, skip-changelog, status: ready to merge

#4087 Check for element before trying to click it in cart backend test
  tests/e2e/specs/backend/cart.test.js
Labels: category: tests, skip-changelog, status: ready to merge

#4090 Switch to `rest_preload_api_request` for API hydration in cart and checkout blocks.
  assets/js/base/context/providers/cart-checkout/checkout-state/constants.js
  assets/js/blocks/cart-checkout/checkout/checkout-order-error/index.js
  assets/js/hocs/with-store-cart-api-hydration.js
  src/Assets/AssetDataRegistry.php
  src/BlockTypes/Cart.php
  src/BlockTypes/Checkout.php
Labels: status: ready to merge

#4097 Remove work-around to load our stylesheets after wp-edit-post
  src/AssetsController.php
Labels: category: refactor, skip-changelog, status: needs review

#4099 Convert Product summary to TypeScript
  assets/js/base/components/cart-checkout/product-summary/index.tsx
  assets/js/base/components/summary/index.tsx
  assets/js/settings/blocks/constants.ts
Labels: category: components, category: refactor, skip-changelog, status: ready to merge

#4143 Add inline console warning if shared settings hook is consumed
  src/Assets/AssetDataRegistry.php
Labels: skip-changelog, status: ready to merge
