Repository woocommerce/woocommerce-blocks, pull requests merged in 2021-07, with the labels that each got.

#4418 Remove source assets from ZIP and releases
  bin/copy-plugin-files.sh
Labels: status: ready to merge, type: build

#4312 Change `couponName` filter to `coupons` and update documentation
  assets/js/base/components/cart-checkout/totals/discount/index.js
  assets/js/base/context/hooks/cart/use-store-cart.ts
  assets/js/types/type-defs/cart-response.ts
  assets/js/types/type-defs/cart.ts
  docs/extensibility/available-filters.md
  packages/checkout/registry/index.ts
Labels: category: blocks, category: extensibility, status: ready to merge, type: bug, ◼️ block: cart, ◼️ block: checkout

#4406 Export `Button` and `Label` from `wc-blocks-checkout` package
  assets/js/atomic/blocks/product-elements/add-to-cart/shared/add-to-cart-button.js
  assets/js/atomic/blocks/product-elements/sale-badge/block.js
  assets/js/base/components/button/index.tsx
  assets/js/base/components/button/stories/index.js
  assets/js/base/components/button/style.scss
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/base/components/cart-checkout/place-order-button/index.js
  assets/js/base/components/cart-checkout/shipping-calculator/address.tsx
  assets/js/base/components/cart-checkout/shipping-rates-control-package/index.tsx
  assets/js/base/components/cart-checkout/totals/coupon/index.js
  assets/js/base/components/filter-submit-button/index.js
  assets/js/base/components/label/index.tsx
  assets/js/base/components/label/test/__snapshots__/index.js.snap
  assets/js/base/components/label/test/index.js
  assets/js/base/components/load-more-button/index.js
  assets/js/base/components/pagination/index.js
  assets/js/base/components/sort-select/index.js
  assets/js/base/components/text-input/text-input.tsx
  assets/js/blocks/active-filters/block.js
  assets/js/blocks/active-filters/utils.js
  assets/js/blocks/attribute-filter/label.js
  assets/js/blocks/cart-checkout/cart/checkout-button/index.js
  assets/js/blocks/cart-checkout/payment-methods/payment-methods.js
  packages/checkout/button/index.ts
  packages/checkout/label/index.ts
Labels: category: extensibility, skip-changelog, status: ready to merge

#4415 Add `TotalsWrapper` component
  assets/js/base/components/cart-checkout/order-summary/index.js
  assets/js/base/components/cart-checkout/order-summary/style.scss
  assets/js/base/components/cart-checkout/shipping-rates-control-package/style.scss
  assets/js/base/components/cart-checkout/totals/coupon/index.js
  assets/js/base/components/cart-checkout/totals/coupon/style.scss
  assets/js/blocks/cart-checkout/cart/full-cart/index.tsx
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
  assets/js/blocks/cart-checkout/cart/test/__snapshots__/block.js.snap
  assets/js/blocks/cart-checkout/checkout/sidebar/index.js
  assets/js/blocks/cart-checkout/checkout/sidebar/test/__snapshots__/index.js.snap
  assets/js/blocks/cart-checkout/checkout/sidebar/test/index.js
  assets/js/blocks/cart-checkout/checkout/style.scss
  packages/checkout/discounts-meta/index.js
  packages/checkout/index.js
  packages/checkout/order-meta/index.js
  packages/checkout/panel/style.scss
  packages/checkout/slot/index.js
  packages/checkout/totals/item/style.scss
  packages/checkout/wrapper/index.tsx
  packages/checkout/wrapper/style.scss
Labels: category: blocks, category: styles, status: ready to merge, type: bug, ◼️ block: cart, ◼️ block: checkout

#4419 Block Widgets: fix product grid display
  assets/js/base/components/product-list/style.scss
Labels: category: fse, status: ready to merge, type: enhancement

#4422 Fix filtering by product type on Store API
  src/StoreApi/Utilities/ProductQuery.php
Labels: type: bug

#4424 Ensure product grids display as intended in the editor
  assets/js/base/components/product-list/style.scss
Labels: status: ready to merge, type: bug

#4427 Make payment method icons display well even if theme tries to override their height/width
  assets/js/base/components/cart-checkout/payment-method-icons/style.scss
  assets/js/blocks/cart-checkout/payment-methods/style.scss
Labels: category: styles, status: ready to merge, type: enhancement, ◼️ block: cart, ◼️ block: checkout

#4435 Add styles to stop totals items being padded inside panels
  assets/js/base/components/sidebar-layout/style.scss
Labels: category: styles, status: ready to merge, type: bug, ◼️ block: cart, ◼️ block: checkout

#4368 Import `createInterpolateElement ` from `@wordpress/element`
  assets/js/atomic/blocks/product-elements/image/edit.js
  assets/js/base/components/cart-checkout/product-sale-badge/index.tsx
  assets/js/base/components/cart-checkout/totals/footer-item/index.js
  assets/js/base/components/product-price/index.js
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/reviews/edit-utils.js
  assets/js/editor-components/compatibility-notices/cart-checkout-compatibility-notice.tsx
  package-lock.json
  package.json
Labels: skip-changelog, status: needs review, type: technical debt

#4342 Add a workflow for the assign-milestone automation
  .github/workflows/approved-with-labels.yml
Labels: status: ready to merge

#4437 Move SlotFillProvider to frontend only
  assets/js/base/context/providers/cart-checkout/checkout/index.js
  assets/js/blocks/cart-checkout/cart/frontend.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.tsx
  assets/js/blocks/cart-checkout/cart/test/__snapshots__/block.js.snap
  assets/js/blocks/cart-checkout/cart/test/block.js
  assets/js/blocks/cart-checkout/checkout/block.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/blocks/cart-checkout/checkout/frontend.js
  bin/webpack-configs.js
  bin/webpack-helpers.js
  src/AssetsController.php
  webpack.config.js
Labels: category: extensibility, skip-changelog, type: build, ◼️ block: cart, ◼️ block: checkout

#4390 Add documentation for Formatters
  docs/extensibility/README.md
  docs/extensibility/extend-rest-api-add-data.md
  docs/extensibility/extend-rest-api-formatters.md
Labels: category: extensibility, status: ready to merge, type: documentation

#4382 Add camelcase rule to eslint config
  .eslintrc.js
  assets/js/atomic/blocks/product-elements/rating/block.js
  assets/js/base/components/cart-checkout/shipping-rates-control-package/index.tsx
  assets/js/base/components/cart-checkout/totals/shipping/index.tsx
  assets/js/base/components/product-list/product-list.js
  assets/js/base/context/providers/cart-checkout/payment-methods/types.ts
  assets/js/blocks/products-by-attribute/block.js
  assets/js/data/cart/actions.ts
  assets/js/extensions/google-analytics/utils.ts
  assets/js/settings/shared/default-address-fields.ts
  assets/js/types/type-defs/cart-response.ts
  assets/js/types/type-defs/cart.ts
  assets/js/types/type-defs/currency.ts
  assets/js/types/type-defs/product-response.ts
  assets/js/types/type-defs/shipping.ts
  global.d.ts
  packages/checkout/totals/subtotal/index.tsx
  packages/checkout/totals/taxes/index.tsx
Labels: skip-changelog, type: build, type: technical debt

#4364 Switch arrow unicode characters
  assets/js/base/components/pagination/index.js
  assets/js/base/components/pagination/style.scss
Labels: status: ready to merge

#4455 Update notices documentation to reflect changes to Snackbar Notices
  docs/block-client-apis/notices.md
Labels: skip-changelog, status: ready to merge, type: documentation

#4428 Fix all review memory leak on block transform
  assets/js/base/hocs/with-reviews.js
Labels: category: blocks, status: ready to merge, type: bug, ◼️ block: all reviews

#4457 Checkout i2: Enable shipping toggle in the editor
  assets/js/blocks/cart-checkout/checkout-i2/inner-blocks/checkout-billing-address-block/block.tsx
  assets/js/blocks/cart-checkout/checkout-i2/inner-blocks/checkout-billing-address-block/edit.tsx
  assets/js/blocks/cart-checkout/checkout-i2/inner-blocks/checkout-shipping-address-block/block.tsx
  assets/js/blocks/cart-checkout/checkout-i2/inner-blocks/checkout-shipping-address-block/edit.tsx
  assets/js/blocks/cart-checkout/checkout-i2/phone-number/index.tsx
Labels: skip-changelog, status: ready to merge

#4471 Remove utils dead files
  assets/js/utils/get-query.js
  assets/js/utils/test/get-query.js
Labels: skip-changelog, status: ready to merge, type: technical debt

#4469 Fix SKU search in the Store API
  src/StoreApi/Utilities/ProductQuery.php
  tests/php/StoreApi/Routes/Products.php
Labels: category: rest-api, status: ready to merge

#4496 Add checkout term field validation
  assets/js/base/components/checkbox-control/style.scss
  assets/js/base/context/hooks/use-store-notices.ts
  assets/js/base/context/providers/cart-checkout/checkout-state/index.tsx
  assets/js/base/context/providers/cart-checkout/checkout/processor/index.js
  assets/js/base/hocs/with-scroll-to-top/index.tsx
  assets/js/blocks/cart-checkout/checkout-i2/block.tsx
  assets/js/blocks/cart-checkout/checkout-i2/inner-blocks/checkout-terms-block/frontend.tsx
  assets/js/blocks/cart-checkout/checkout-i2/inner-blocks/checkout-terms-block/style.scss
  assets/js/types/type-defs/contexts.js
Labels: skip-changelog, status: ready to merge

#4503 initialize checkout alongside checkout-i2
  src/BlockTypes/CheckoutI2.php
Labels: category: extensibility, skip-changelog, status: ready to merge

#4501 move SlotFillProvider before pluginArea in Checkout i2
  assets/js/blocks/cart-checkout/checkout-i2/block.tsx
Labels: category: extensibility, status: ready to merge, type: bug

#4417 Update `snackbarNotices` filter to `snackbarNoticeVisibility`
  assets/js/base/context/providers/store-snackbar-notices/components/snackbar-notices-container.js
  packages/checkout/registry/index.ts
Labels: category: extensibility, status: needs review, ◼️ block: cart, ◼️ block: checkout

#4499 Update getting-started.md
  docs/contributors/getting-started.md
Labels: skip-changelog, type: documentation

#4507 Fix e2e tests: Remove paypal from fixture data
  assets/js/base/hocs/with-scroll-to-top/index.tsx
  assets/js/base/hocs/with-scroll-to-top/test/index.js
  assets/js/blocks/cart-checkout/cart/full-cart/index.tsx
  assets/js/blocks/cart-checkout/checkout-i2/block.tsx
  package-lock.json
  package.json
  tests/e2e/fixtures/fixture-loaders.js
  tests/e2e/specs/backend/single-product.test.js
  tests/e2e/specs/frontend/checkout.test.js
  tests/e2e/utils.js
Labels: status: ready to merge

#4460 Fix Store API cart links in main readme
  src/StoreApi/README.md
Labels: status: ready to merge, type: documentation

#4490 Update extend-rest-api-add-data.md
  docs/extensibility/extend-rest-api-add-data.md
Labels: skip-changelog, status: ready to merge, type: documentation

#4497 Fix Hand-picked Products block name inconsistencies
  docs/testing/releases/260.md
  docs/testing/releases/270.md
  docs/testing/releases/310.md
  docs/testing/releases/490.md
  docs/testing/releases/520.md
  docs/testing/releases/540.md
  readme.txt
Labels: skip-changelog, status: ready to merge, type: documentation

#4498 Add missing class to Cart skeleton title
  src/BlockTypes/Cart.php
Labels: status: ready to merge, type: bug, ◼️ block: cart

#4484 Update relevant files due to L2->L0 policy change for minimum required versions.
  .env
  .github/patch-initial-checklist.md
  .github/release-initial-checklist.md
  .github/workflows/php-js-e2e-tests.yml
  .github/workflows/unit-tests.yml
  README.md
  phpcs.xml
  readme.txt
  src/Domain/Bootstrap.php
  tests/bootstrap.php
  woocommerce-gutenberg-products-block.php
Labels: skip-changelog, status: ready to merge, type: build
