Repository woocommerce/woocommerce-blocks, pull requests merged in 2021-03, with the labels that each got.

#3892 Add guards around monkey-patched `setNonce` function on apiFetch.
  assets/js/data/shared-controls.ts
Labels: status: ready to merge, type: cooldown, type: technical debt

#3893 Followups and improvements on TS implementation in the Cart data store.
  assets/js/data/cart/actions.ts
  assets/js/data/cart/index.ts
  assets/js/data/cart/reducers.ts
  assets/js/data/shared-controls.ts
  package-lock.json
  package.json
Labels: status: ready to merge, type: cooldown, type: technical debt

#3890 Improvements to payment methods integration docs
  docs/extensibility/payment-method-integration.md
Labels: priority: high, status: ready to merge, type: cooldown, type: documentation

#3905 Show cart item subtotal instead of total in Cart and Checkout blocks
  assets/js/base/components/cart-checkout/order-summary/order-summary-item.js
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/cart/test/block.js
Labels: status: ready to merge, type: bug, ◼️ block: cart, ◼️ block: checkout

#3898 Only set wp-edit-post style dependency if it has already been enqueued
  src/Assets.php
Labels: status: ready to merge, type: bug

#3907 Sync cart item quantity if its Implicitly changed.
  assets/js/base/hooks/cart/use-store-cart-item-quantity.js
Labels: status: ready to merge, type: bug, ◼️ block: cart

#3909 Add OrderSummary test for #3876
  assets/js/base/components/cart-checkout/order-summary/test/index.js
Labels: category: tests, skip-changelog, status: ready to merge, ◼️ block: checkout

#3878 Update Storybook and alias `wordpress-components`
  package-lock.json
  package.json
  storybook/webpack.config.js
Labels: skip-changelog, type: build

#3924 Update Single Product Test
  .github/workflows/php-js-e2e-tests.yml
  bin/.htaccess
  tests/e2e/specs/backend/single-product.test.js
Labels: status: ready to merge

#3897 Inherit line height in Cart item total
  assets/js/blocks/cart-checkout/cart/full-cart/style.scss
Labels: category: blocks, category: styles, status: ready to merge, type: bug, ◼️ block: cart

#3914 Add types to packages directory
  assets/js/base/components/formatted-monetary-amount/index.js
  assets/js/base/components/label/index.tsx
  assets/js/icons/icon/index.js
  assets/js/icons/icon/index.tsx
  assets/js/icons/tsconfig.json
  packages/checkout/panel/index.tsx
  packages/checkout/registry/index.ts
  packages/checkout/totals/fees/index.tsx
  packages/checkout/totals/item/index.js
  packages/checkout/totals/item/index.tsx
  packages/checkout/totals/subtotal/index.tsx
  packages/checkout/totals/taxes/index.tsx
  packages/checkout/utils/validation/index.ts
  packages/prices/index.js
  packages/prices/types.ts
  packages/prices/utils/price.ts
  packages/tsconfig.json
  tsconfig.base.json
  tsconfig.json
Labels: skip-changelog, status: ready to merge, type: technical debt

#3938 Fix Storybook after TypeScript changes
  storybook/webpack.config.js
  tsconfig.base.json
Labels: skip-changelog, status: ready to merge, type: technical debt

#3913 Add types to hooks
  .eslintrc.js
  assets/js/base/context/test/utils.js
  assets/js/base/hooks/cart/index.ts
  assets/js/base/hooks/cart/use-store-cart-coupons.ts
  assets/js/base/hooks/cart/use-store-cart-item-quantity.ts
  assets/js/base/hooks/cart/use-store-cart.ts
  assets/js/base/hooks/customer/index.ts
  assets/js/base/hooks/customer/use-customer-data.ts
  assets/js/base/hooks/customer/utils.ts
  assets/js/base/hooks/test/use-shallow-equal.js
  assets/js/base/hooks/tsconfig.json
  assets/js/base/hooks/use-container-queries.ts
  assets/js/base/hooks/use-previous.ts
  assets/js/base/hooks/use-shallow-equal.ts
  assets/js/base/hooks/use-store-add-to-cart.ts
  assets/js/base/hooks/use-throw-error.ts
  assets/js/base/hooks/use-trigger-fragment-refresh.ts
  assets/js/base/utils/derive-selected-shipping-rates.js
  assets/js/base/utils/from-entries-polyfill.ts
  assets/js/base/utils/index.js
  assets/js/data/cart/actions.ts
  assets/js/data/cart/index.ts
  assets/js/data/tsconfig.json
  assets/js/mapped-types.ts
  assets/js/previews/cart.ts
  assets/js/previews/shipping-rates.ts
  assets/js/type-defs/cart-response.ts
  assets/js/type-defs/hooks.ts
  assets/js/type-defs/index.ts
Labels: category: refactor, skip-changelog, status: ready to merge

#3945 Add docs on how to run e2e tests with a specific environment locally
  docs/contributors/javascript-testing.md
Labels: skip-changelog, status: ready to merge, type: documentation

#3950 Fix "save payment" checkbox not showing for payment methods
  assets/js/blocks/cart-checkout/payment-methods/payment-method-options.js
Labels: category: extensibility, priority: high, type: bug, ◼️ block: checkout

#3932 Only return a single handle for block styles
  src/BlockTypes/AbstractBlock.php
  src/BlockTypes/Cart.php
  src/BlockTypes/SingleProduct.php
Labels: status: ready to merge

#3952 Remove extra padding from payment methods with no description
  assets/js/blocks/cart-checkout/payment-methods/style.scss
  assets/js/payment-method-extensions/payment-methods/bacs/index.js
  assets/js/payment-method-extensions/payment-methods/cheque/index.js
  assets/js/payment-method-extensions/payment-methods/cod/index.js
  assets/js/payment-method-extensions/payment-methods/paypal/index.js
  docs/extensibility/payment-method-integration.md
Labels: category: styles, status: ready to merge, ◼️ block: checkout

#3957 Always set value in the fromEntries polyfill
  assets/js/base/utils/from-entries-polyfill.ts
Labels: status: ready to merge

#3961 Add new config property for payment method registration that allows for additional saved customer token handling.
  assets/js/blocks-registry/payment-methods/payment-method-config.js
  assets/js/blocks/cart-checkout/payment-methods/saved-payment-method-options.js
  docs/extensibility/payment-method-integration.md
Labels: priority: high, status: ready to merge, type: blocker, type: enhancement

#3958 Allow FormattedMonetaryAmount to deal with string based numbers
  assets/js/base/components/formatted-monetary-amount/index.tsx
Labels: skip-changelog, status: ready to merge

#3908 Update extensions types and fix inconsistent type from server.
  assets/js/data/default-states.ts
  assets/js/previews/cart.ts
  assets/js/type-defs/cart-response.ts
  assets/js/type-defs/cart.ts
  src/Domain/Services/ExtendRestApi.php
Labels: category: extensibility, status: ready to merge, type: bug

#3887 Fix block elements that don't play well with dark backgrounds
  assets/js/base/components/price-slider/style.scss
  assets/js/blocks/active-filters/style.scss
  assets/js/blocks/active-filters/utils.js
  assets/js/blocks/product-categories/style.scss
  assets/js/blocks/product-search/style.scss
Labels: status: ready to merge, type: enhancement, ◼️ block: product search, 🔹 block-type: filter blocks

#3953 Google Analytics Integration - Action Hooks and initial tracking events
  assets/js/atomic/blocks/product-elements/button/block.js
  assets/js/base/components/product-list/product-list.js
  assets/js/base/hooks/cart/use-store-cart-item-quantity.ts
  assets/js/base/hooks/index.js
  assets/js/base/hooks/use-store-add-to-cart.ts
  assets/js/base/hooks/use-store-events.ts
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/products/all-products/index.js
  assets/js/extensions/google-analytics/constants.ts
  assets/js/extensions/google-analytics/index.ts
  assets/js/extensions/google-analytics/tsconfig.json
  assets/js/extensions/google-analytics/utils.ts
  assets/js/type-defs/hooks.js
  assets/js/type-defs/hooks.ts
  assets/js/type-defs/index.ts
  assets/js/type-defs/product-response.ts
  bin/webpack-configs.js
  bin/webpack-entries.js
  package-lock.json
  package.json
  src/Assets.php
  tsconfig.json
  webpack.config.js
Labels: status: ready to merge

#3972 Update the `wp-env` package to latest
  .github/workflows/php-js-e2e-tests.yml
  .wp-env.json
  package-lock.json
  package.json
Labels: category: tests, skip-changelog, status: ready to merge, type: bug, type: build

#3937 Show compatibility notice when adding the Cart and Checkouts blocks in the editor
  assets/js/base/hooks/index.js
  assets/js/base/hooks/use-local-storage-state.ts
  assets/js/blocks/cart-checkout/cart/edit.js
  assets/js/blocks/cart-checkout/checkout/edit.js
  assets/js/editor-components/compatibility-notices/cart-checkout-compatibility-notice.tsx
  assets/js/editor-components/compatibility-notices/index.tsx
  assets/js/editor-components/compatibility-notices/use-compatibility-notice.ts
  assets/js/editor-components/compatibility-notices/woo-image.js
  tests/e2e/specs/backend/cart.test.js
  tests/e2e/specs/backend/checkout.test.js
  tests/e2e/utils.js
Labels: status: ready to merge, type: enhancement, ◼️ block: cart, ◼️ block: checkout

#3982 Refactor Payment Methods Integration API to fire `onPaymentProcessing` event with saved tokens.
  assets/js/base/context/cart-checkout/payment-methods/actions.ts
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.tsx
  assets/js/base/context/cart-checkout/payment-methods/reducer.ts
  assets/js/base/context/cart-checkout/payment-methods/types.ts
  assets/js/blocks/cart-checkout/payment-methods/express-payment-methods.js
  assets/js/blocks/cart-checkout/payment-methods/saved-payment-method-options.js
  assets/js/type-defs/contexts.js
Labels: category: extensibility, category: refactor, status: ready to merge, ◼️ block: checkout

#3991 Update data-controls and expect console logs from deprecated select control
  assets/js/base/context/cart-checkout/payment-methods/test/payment-method-data-context.js
  assets/js/blocks/cart-checkout/cart/test/block.js
  package-lock.json
  package.json
Labels: status: ready to merge

#3990 Expose the shouldSavePayment method value to registered payment methods
  assets/js/base/hooks/payment-methods/use-payment-method-interface.js
  assets/js/type-defs/registered-payment-method-props.js
  docs/extensibility/payment-method-integration.md
Labels: category: extensibility, status: ready to merge, type: enhancement, ◼️ block: checkout

#3989 Split unit tests up from e2e tests
  .github/workflows/php-js-e2e-tests.yml
  .github/workflows/unit-tests.yml
Labels: skip-changelog, status: ready to merge, type: build

#3992 Add scope to PluginArea
  assets/js/base/context/cart-checkout/checkout/index.js
Labels: category: extensibility, skip-changelog, ◼️ block: cart, ◼️ block: checkout

#3993 Remove checks for WP 5.4 from e2e tests
  docs/contributors/javascript-testing.md
  tests/e2e/specs/backend/cart.test.js
  tests/e2e/specs/backend/checkout.test.js
  tests/e2e/utils.js
Labels: category: tests, skip-changelog, status: ready to merge

#3960 Ensure cart changes remain after using back button to get back to the cart
  assets/js/data/cart/action-types.ts
  assets/js/data/cart/actions.ts
  assets/js/data/cart/constants.ts
  assets/js/data/cart/reducers.ts
  assets/js/data/cart/selectors.ts
  assets/js/data/default-states.ts
  assets/js/hocs/with-store-cart-api-hydration.js
  assets/js/middleware/cart-update.ts
  assets/js/middleware/index.js
  assets/js/type-defs/cart.ts
  package-lock.json
  package.json
  src/StoreApi/Schemas/CartSchema.php
  tests/e2e/specs/frontend/cart.test.js
  tests/utils/get-block-page-permalink.js
  tests/utils/get-normal-page-permalink.js
  tests/utils/index.js
  tests/utils/visit-block-page.js
Labels: category: blocks, status: ready to merge, type: bug, ◼️ block: cart

#4005 Strip tags from exceptions that are converted from notices
  src/StoreApi/Utilities/NoticeHandler.php
  tests/php/StoreApi/Utilities/NoticeHandler.php
Labels: category: blocks, category: rest-api, status: ready to merge, ◼️ block: cart, ◼️ block: checkout

#4013 Avoid get_billing and get_shipping method when updating the order
  src/StoreApi/Utilities/OrderController.php
Labels: status: ready to merge

#3996 Fix click on Proceed to checkout bug when Coupon error is visible.
  assets/js/base/components/cart-checkout/totals/coupon/style.scss
Labels: category: blocks, status: ready to merge, ◼️ block: cart

#3967 Add Google Analytics Product Block and Checkout Events
  assets/js/atomic/blocks/product-elements/add-to-cart/shared/add-to-cart-button.js
  assets/js/atomic/blocks/product-elements/button/block.js
  assets/js/atomic/blocks/product-elements/image/block.js
  assets/js/atomic/blocks/product-elements/title/block.js
  assets/js/base/components/product-list/product-list.js
  assets/js/base/context/cart-checkout/checkout-state/index.js
  assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.tsx
  assets/js/base/context/store-notices-context.js
  assets/js/base/hooks/cart/use-store-cart.ts
  assets/js/base/hooks/shipping/use-select-shipping-rate.ts
  assets/js/base/hooks/use-store-events.ts
  assets/js/blocks/cart-checkout/cart/full-cart/cart-line-item-row.js
  assets/js/blocks/cart-checkout/checkout/form/address-step.js
  assets/js/blocks/cart-checkout/checkout/form/index.js
  assets/js/blocks/single-product/block.js
  assets/js/extensions/google-analytics/index.ts
  assets/js/extensions/google-analytics/tsconfig.json
  assets/js/extensions/google-analytics/utils.ts
  src/Assets.php
  src/Assets/Api.php
  src/BlockTypes/AbstractProductGrid.php
  src/BlockTypes/ProductSearch.php
  src/Domain/Bootstrap.php
  src/Domain/Services/GoogleAnalytics.php
Labels: skip-changelog, status: ready to merge
