Repository woocommerce/woocommerce-blocks, pull requests merged in 2023-12, with the labels that each got.

#11982 [Product Collection] Fix: HTML Entity Decoding in Taxonomy Controls
  assets/js/blocks/product-collection/inspector-controls/taxonomy-controls/taxonomy-item.tsx
Labels: status: ready to merge, type: bug, focus: blocks, block: product collection

#11997 [Store Customization] Update the default content in patterns
  patterns/featured-category-focus.php
  patterns/hero-product-chessboard.php
  patterns/hero-product-split.php
  patterns/product-query-large-image-product-gallery.php
  patterns/social-follow-us-in-social-media.php
  patterns/store-info-alt-image-and-text.php
  patterns/testimonials-3-columns.php
  patterns/testimonials-single.php
  src/Patterns/dictionary.json
Labels: status: ready to merge, type: enhancement, focus: patterns

#11999 Update Feedback link on Cart and Checkout blocks
  assets/js/editor-components/feedback-prompt/index.tsx
Labels: status: ready to merge, type: enhancement, team: Rubik

#12006 Update Feedback link on Cart and Checkout blocks
  assets/js/editor-components/feedback-prompt/index.tsx
Labels: status: ready to merge, skip-changelog

#11787 Create add to custom fields documentation
  docs/third-party-developers/extensibility/rest-api/extend-rest-api-add-custom-fields.md
Labels: status: ready to merge, focus: documentation, category: extensibility, focus: rest api, skip-changelog

#11971 [Store Customization] Flush permalinks after updating all products
  src/Patterns/ProductUpdater.php
  src/StoreApi/Routes/V1/AI/Product.php
Labels: status: ready to merge, type: enhancement, skip-changelog, focus: ai

#12010 Remove page view tracking in favor of jetpack
  assets/js/extensions/jetpack/woocommerce-analytics/constants.ts
  assets/js/extensions/jetpack/woocommerce-analytics/index.ts
  assets/js/extensions/jetpack/woocommerce-analytics/test/index.ts
  bin/webpack-entries.js
  src/Domain/Bootstrap.php
  src/Domain/Services/JetpackWooCommerceAnalytics.php
  src/Shipping/ShippingController.php
  src/StoreApi/Routes/V1/Checkout.php
Labels: status: ready to merge, type: refactor, skip-changelog

#12003 Decrease modal width
  assets/js/editor-components/incompatible-extension-notice/editor.scss
Labels: status: ready to merge, type: enhancement, block: cart, block: checkout, team: Rubik, focus: checkout

#12007 Update product placeholders with products from design
  images/pattern-placeholders/watch-hand-brand-jewellery-strap-platinum.jpg
  images/pattern-placeholders/writing-typing-keyboard-technology-white-vintage.jpg
  src/Patterns/ProductUpdater.php
Labels: status: ready to merge, type: enhancement, skip-changelog, focus: patterns, focus: ai

#12005 Update patterns design
  images/pattern-placeholders/man-person-music-black-and-white-white-photography.jpg
  patterns/just-arrived-full-hero.php
  patterns/product-collection-3-columns.php
  patterns/product-query-product-gallery.php
  src/Patterns/PatternUpdater.php
  src/Patterns/dictionary.json
Labels: status: ready to merge, type: enhancement, skip-changelog, focus: patterns

#12016 [CYS] Fix regression and ensure AI-generated content is assigned to products after the third attempt
  src/Patterns/ProductUpdater.php
Labels: status: ready to merge, type: bug, status: blocker, focus: ai

#11877 Improve AI prompt for the header of the Hero Product 3 Split pattern
  src/Patterns/dictionary.json
Labels: status: ready to merge, type: enhancement, focus: ai

#12030 Fix Testimonials 3 Column pattern width
  patterns/testimonials-3-columns.php
Labels: status: ready to merge, type: enhancement

#11879 Improve AI prompt for the Featured Category Triple pattern
  src/Patterns/dictionary.json
Labels: status: ready to merge, type: enhancement, status: stale, focus: ai

#12033 Revert "Remove unused Add to Cart product element (#11948)"
  assets/js/atomic/blocks/component-init.js
  assets/js/atomic/blocks/index.js
  assets/js/atomic/blocks/product-elements/add-to-cart/attributes.ts
  assets/js/atomic/blocks/product-elements/add-to-cart/block.tsx
  assets/js/atomic/blocks/product-elements/add-to-cart/constants.tsx
  assets/js/atomic/blocks/product-elements/add-to-cart/edit.tsx
  assets/js/atomic/blocks/product-elements/add-to-cart/frontend.ts
  assets/js/atomic/blocks/product-elements/add-to-cart/index.ts
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/external.tsx
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/grouped.tsx
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/index.ts
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/simple.tsx
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/index.tsx
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/types.ts
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/attribute-picker.tsx
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/attribute-select-control.tsx
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/index.tsx
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/style.scss
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/test/index.ts
  assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/utils.ts
  assets/js/atomic/blocks/product-elements/add-to-cart/shared/add-to-cart-button.tsx
  assets/js/atomic/blocks/product-elements/add-to-cart/shared/index.ts
  assets/js/atomic/blocks/product-elements/add-to-cart/shared/product-unavailable.tsx
  assets/js/atomic/blocks/product-elements/add-to-cart/shared/quantity-input.tsx
  assets/js/atomic/blocks/product-elements/add-to-cart/style.scss
  assets/js/blocks/cart/inner-blocks/cart-cross-sells-products/editor.scss
  assets/js/blocks/cart/inner-blocks/cart-cross-sells-products/style.scss
  docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md
  docs/internal-developers/translations/translation-loading.md
  src/BlockTypes/ProductAddToCart.php
  src/BlockTypesController.php
Labels: status: ready to merge, type: bug, skip-changelog, block: all products, block: mini-cart

#12040 Add/11.6.2 testing instructions and changelog
  docs/internal-developers/testing/releases/1162.md
  docs/internal-developers/testing/releases/README.md
  readme.txt
Labels: status: ready to merge, skip-changelog, type: task

#11926 Upgrade TypeScript to 5.3.2
  package-lock.json
  package.json
  tsconfig.base.json
Labels: status: ready to merge, skip-changelog

#12049 Remove "shopper" from "review checkout" task copy
  src/Domain/Services/OnboardingTasks/ReviewCheckoutTask.php
Labels: status: ready to merge, type: enhancement, skip-changelog

#11995 Product gallery/fix/view all link
  assets/js/blocks/product-gallery/style.scss
Labels: status: ready to merge, type: bug, skip-changelog, block: product gallery

#12041 fix: Product Collection: Featured Products 5 Columns improve spacing
  assets/js/blocks/product-template/style.scss
  patterns/product-collection-featured-products-5-columns.php
Labels: status: ready to merge, type: enhancement

#11986 Add missing actions to data store documentation
  docs/third-party-developers/extensibility/data-store/cart.md
  docs/third-party-developers/extensibility/data-store/checkout.md
  docs/third-party-developers/extensibility/data-store/collections.md
  docs/third-party-developers/extensibility/data-store/validation.md
Labels: status: ready to merge, focus: documentation, skip-changelog

#12031 Fix performance issues with the extension incompatibility notice
  src/BlockTypes/Checkout.php
Labels: status: ready to merge, type: bug, focus: performance, team: Rubik

#12076 CYS: Add DELETE private/ai/products endpoint
  src/Patterns/ProductUpdater.php
  src/StoreApi/Routes/V1/AI/Products.php
Labels: type: enhancement, focus: rest api, skip-changelog, focus: ai, team: Kirigami & Origami

#12051 Fix font weight of cart totals title in site editor
  assets/js/base/components/cart-checkout/cart-line-items-table/style.scss
  assets/js/blocks/cart/style.scss
Labels: type: bug, block: cart, team: Rubik, focus: cart

#12072 Allow guests to view full order details on the order confirmation page
  src/BlockTypes/OrderConfirmation/AbstractOrderConfirmationBlock.php
  src/BlockTypes/OrderConfirmation/AdditionalInformation.php
  src/BlockTypes/OrderConfirmation/BillingAddress.php
  src/BlockTypes/OrderConfirmation/BillingWrapper.php
  src/BlockTypes/OrderConfirmation/Downloads.php
  src/BlockTypes/OrderConfirmation/DownloadsWrapper.php
  src/BlockTypes/OrderConfirmation/ShippingAddress.php
  src/BlockTypes/OrderConfirmation/ShippingWrapper.php
  src/BlockTypes/OrderConfirmation/Status.php
  src/BlockTypes/OrderConfirmation/Summary.php
  src/BlockTypes/OrderConfirmation/Totals.php
  src/BlockTypes/OrderConfirmation/TotalsWrapper.php
Labels: type: enhancement, block: checkout, team: Rubik

#12080 Social Follow Us Pattern: fix width image
  patterns/social-follow-us-in-social-media.php
Labels: type: enhancement, skip-changelog, focus: patterns

#12018 Update the checkout order endpoint allowed order statuses for payment complete
  src/StoreApi/Routes/V1/CheckoutOrder.php
Labels: type: bug, type: community contribution, team: Rubik

#12085 Products By Attribute: E2E tests - skip test
  tests/e2e-jest/specs/shopper/filter-products-by-attribute.test.ts
Labels: skip-changelog, block: filter by attribute, type: task

#11802 Fix casting error on Utils::wp_version_compare
  src/Utils/Utils.php
Labels: skip-changelog, type: community contribution, team: Rubik

#11853 Move merchant-side Checkout E2E tests to Playwright
  tests/e2e-jest/specs/backend/checkout.test.js
  tests/e2e/tests/checkout/checkout-block.merchant.block_theme.spec.ts
  tests/e2e/tests/checkout/checkout-block.merchant.classic_theme.spec.ts
  tests/e2e/utils/editor/editor-utils.page.ts
Labels: tools, skip-changelog, block: checkout, team: Rubik, focus: checkout, focus: e2e tests

#12086 Product Gallery: Migrate placeholder to Woo default placeholder
  src/Utils/ProductGalleryUtils.php
Labels: type: enhancement, block: product gallery

#12077 Remove styling from sale badge
  assets/js/atomic/blocks/product-elements/image/block.tsx
Labels: type: bug, block: single product

#12047 Update Features Flags and Experimental Interfaces doc with Collection Filters and its inner blocks
  docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md
Labels: skip-changelog, type: technical debt

#12063 Make Featured Category centered horizontally
  assets/js/blocks/featured-items/style.scss
Labels: type: bug, block: featured category

#11909 Update product category controls to use typescript
  assets/js/blocks/featured-items/with-edit-mode.tsx
  assets/js/editor-components/expandable-search-list-item/expandable-search-list-item.tsx
  assets/js/editor-components/product-attribute-term-control/index.tsx
  assets/js/editor-components/product-category-control/index.tsx
  assets/js/editor-components/product-control/index.tsx
  assets/js/editor-components/product-tag-control/product-tag-item.tsx
  assets/js/editor-components/search-list-control/item.tsx
  assets/js/editor-components/search-list-control/search-list-control.tsx
  assets/js/editor-components/search-list-control/types.ts
  assets/js/hocs/index.js
  assets/js/hocs/test/with-categories.jsx
  assets/js/hocs/test/with-searched-categories.jsx
  assets/js/hocs/with-categories.js
  assets/js/hocs/with-searched-categories.tsx
  assets/js/types/type-defs/hocs.ts
  assets/js/types/type-defs/index.ts
  assets/js/types/type-defs/product-category-response.ts
  assets/js/utils/products.ts
Labels: type: refactor, type: task

#11969 Add missing selectors to data store documentation
  docs/internal-developers/block-client-apis/checkout/checkout-api.md
  docs/third-party-developers/extensibility/data-store/checkout.md
  docs/third-party-developers/extensibility/data-store/collections.md
  docs/third-party-developers/extensibility/data-store/payment.md
  docs/third-party-developers/extensibility/data-store/schema.md
Labels: focus: documentation, skip-changelog, team: Rubik

#12088 Convert PaymentMethodErrorBoundary to Class component
  assets/js/blocks/cart-checkout-shared/payment-methods/payment-method-error-boundary.tsx
Labels: type: bug, team: Rubik, focus: checkout

#11998 Move shopper-side Checkout E2E tests to Playwright
  tests/e2e-jest/specs/shopper/cart-checkout/checkout.test.js
  tests/e2e/tests/checkout/checkout-block.block_theme.side_effects.spec.ts
  tests/e2e/tests/checkout/checkout-block.shopper.block_theme.side_effects.spec.ts
  tests/e2e/tests/checkout/checkout.page.ts
Labels: tools, skip-changelog, block: checkout, team: Rubik, focus: checkout, focus: e2e tests

#11933 Button: Update deprecated props
  assets/js/atomic/blocks/product-elements/shared/product-selector.tsx
  assets/js/atomic/blocks/product-elements/shared/with-product-selector.js
  assets/js/blocks/attribute-filter/edit.tsx
  assets/js/blocks/checkout/inner-blocks/checkout-shipping-methods-block/no-shipping-placeholder/index.js
  assets/js/blocks/classic-template/index.tsx
  assets/js/blocks/collection-filters/inner-blocks/attribute-filter/components/placeholder.tsx
  assets/js/blocks/collection-filters/inner-blocks/attribute-filter/edit.tsx
  assets/js/blocks/featured-items/with-edit-mode.tsx
  assets/js/blocks/handpicked-products/edit-mode.tsx
  assets/js/blocks/price-filter/edit.tsx
  assets/js/blocks/product-category/edit-mode.tsx
  assets/js/blocks/product-tag/block.tsx
  assets/js/blocks/products-by-attribute/edit-mode.tsx
  assets/js/blocks/products/all-products/edit.js
  assets/js/blocks/products/edit-utils.js
  assets/js/blocks/reviews/reviews-by-category/block.tsx
  assets/js/blocks/reviews/reviews-by-product/edit.tsx
  assets/js/blocks/single-product/edit/index.tsx
  assets/js/blocks/single-product/edit/layout-editor.tsx
  assets/js/editor-components/error-placeholder/index.tsx
  assets/js/editor-components/search-list-control/search-list-control.tsx
Labels: type: enhancement, type: community contribution, team: Kirigami & Origami

#12098 Remove placeholder image rendering and delegate it to Core's get_image function
  src/BlockTypes/ProductImage.php
Labels: type: bug, category: extensibility, block: product image gallery

#12101 Add Monorepo Merge Notice Workflow
  .github/workflows/monorepo-merge-notices.yml
Labels: type: task

#12137 Deactivate nightly builds
  .github/workflows/nightly-builds.yml
Labels: skip-changelog
